package se.deversity.vibetags.loadtest;

import org.openjdk.jmh.annotations.*;
import org.openjdk.jmh.infra.Blackhole;
import se.deversity.vibetags.processor.internal.GuardrailFileWriter;
import se.deversity.vibetags.processor.internal.WriteCache;

import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.concurrent.TimeUnit;

/**
 * JMH benchmark that proves the v0.7.1 {@link WriteCache} earns its keep.
 *
 * <h2>Why a separate class?</h2>
 *
 * The existing {@link ProcessorHotPathBenchmark} drives {@code processor.writeFileIfChanged(...)}
 * via a {@link se.deversity.vibetags.processor.AIGuardrailProcessor} constructed with
 * {@code new AIGuardrailProcessor()} — which never calls {@code init()} (no
 * {@code ProcessingEnvironment}), so the cache field stays {@code null}. Cache wins are
 * therefore invisible there.
 *
 * <p>This class wires the cache directly through {@link GuardrailFileWriter}'s 4-arg
 * constructor and compares two writers against the same on-disk content:
 *
 * <ul>
 *   <li>{@code writerWithCache} — cache populated during {@code @Setup}; subsequent
 *       benchmark iterations should hit the {@code isUnchanged} fast path and skip
 *       the read-and-compare cycle entirely.</li>
 *   <li>{@code writerNoCache} — null cache, so every iteration must read the file
 *       and compare byte-for-byte (marker variant) or stream (non-marker variant)
 *       to determine that no write is needed.</li>
 * </ul>
 *
 * <p>Two file types exercised:
 *
 * <ul>
 *   <li>{@code .md} (marker file): cache miss path goes through {@code Files.readString}
 *       on the full 64 KB and parses marker positions. This is where the cache delivers
 *       a dramatic win.</li>
 *   <li>{@code .cursorrules} (non-marker file): cache miss path goes through Phase 2's
 *       streaming byte-compare (also reads 64 KB but as a stream, no String allocation).
 *       The cache wins here are smaller because the streaming path is already efficient.</li>
 * </ul>
 *
 * <h2>Running</h2>
 * <pre>{@code
 *   cd load-tests
 *   mvn package -DskipTests
 *   java -jar target/benchmarks.jar WriteCacheHitBenchmark -wi 3 -i 5 -f 1 -tu us -bm avgt
 * }</pre>
 */
@BenchmarkMode(Mode.AverageTime)
@OutputTimeUnit(TimeUnit.MICROSECONDS)
@Warmup(iterations = 3, time = 1, timeUnit = TimeUnit.SECONDS)
@Measurement(iterations = 5, time = 2, timeUnit = TimeUnit.SECONDS)
@Fork(value = 1, jvmArgsPrepend = {"-Xms256m", "-Xmx512m"})
@State(Scope.Thread)
public class WriteCacheHitBenchmark {

    private static final String GENERATED_HEADER = "# Generated by VibeTags | https://github.com/PIsberg/vibetags\n";

    private GuardrailFileWriter writerWithCache;
    private GuardrailFileWriter writerNoCache;

    // Small workload (1 KB body — typical .cursorignore / .codyignore size).
    private Path smallMarkerFile;
    private Path smallNonMarkerFile;
    private String smallBody;

    // Medium workload (12 KB body — matches example/ generated CLAUDE.md, .cursorrules, llms-full.txt).
    private Path mediumMarkerFile;
    private Path mediumNonMarkerFile;
    private String mediumBody;

    // Large workload (1 MB body — what an llms-full.txt looks like on a big monorepo).
    private Path largeMarkerFile;
    private Path largeNonMarkerFile;
    private String largeBody;

    @Setup(Level.Trial)
    public void setup() throws IOException {
        Path tempDir = Files.createTempDirectory("jmh-cache-hit-");
        tempDir.toFile().deleteOnExit();

        smallBody  = repeatAlpha(1024);
        mediumBody = repeatAlpha(12 * 1024);
        largeBody  = repeatAlpha(1024 * 1024);

        smallMarkerFile     = tempDir.resolve("small.md");
        smallNonMarkerFile  = tempDir.resolve("small.cursorrules");
        mediumMarkerFile    = tempDir.resolve("medium.md");
        mediumNonMarkerFile = tempDir.resolve("medium.cursorrules");
        largeMarkerFile     = tempDir.resolve("large.md");
        largeNonMarkerFile  = tempDir.resolve("large.cursorrules");
        for (Path p : new Path[]{smallMarkerFile, smallNonMarkerFile, mediumMarkerFile, mediumNonMarkerFile,
                                 largeMarkerFile, largeNonMarkerFile}) {
            Files.writeString(p, "", StandardCharsets.UTF_8);
        }

        WriteCache cache = new WriteCache(tempDir.resolve(".vibetags-cache"));
        writerWithCache = new GuardrailFileWriter(GENERATED_HEADER, null, null, cache);
        writerNoCache   = new GuardrailFileWriter(GENERATED_HEADER, null, null, null);

        // Prime: first call writes canonical content + populates the cache. Subsequent benchmark
        // iterations see stable files and identical bodies, so they exercise the no-write fast path.
        primeFile(smallMarkerFile,     smallBody);
        primeFile(smallNonMarkerFile,  smallBody);
        primeFile(mediumMarkerFile,    mediumBody);
        primeFile(mediumNonMarkerFile, mediumBody);
        primeFile(largeMarkerFile,     largeBody);
        primeFile(largeNonMarkerFile,  largeBody);
    }

    private static String repeatAlpha(int chars) {
        StringBuilder sb = new StringBuilder(chars);
        for (int i = 0; i < chars; i++) sb.append((char) ('a' + (i % 26)));
        return sb.toString();
    }

    private void primeFile(Path file, String body) throws IOException {
        writerWithCache.writeFileIfChanged(file.toString(), body, true);
        // After priming, every subsequent call should return false (no write needed).
        if (writerWithCache.writeFileIfChanged(file.toString(), body, true))
            throw new IllegalStateException("primer did not converge for " + file);
        if (writerNoCache.writeFileIfChanged(file.toString(), body, true))
            throw new IllegalStateException("noCache writer disagrees on " + file);
    }

    /**
     * Each @Benchmark below issues 100 writeFileIfChanged calls per JMH invocation. JMH's
     * per-call floor on Windows hovers around 200 us regardless of workload — batching
     * 100 calls amortises that and exposes the actual per-call delta between cache-hit
     * and no-cache paths. Tag the methods with @OperationsPerInvocation so JMH divides
     * the measured time accordingly.
     */
    private static final int BATCH = 100;

    // ===== Small (1 KB) =====

    @Benchmark @OperationsPerInvocation(BATCH)
    public void small_marker_cacheHit(Blackhole bh) {
        for (int i = 0; i < BATCH; i++) bh.consume(writerWithCache.writeFileIfChanged(smallMarkerFile.toString(), smallBody, true));
    }
    @Benchmark @OperationsPerInvocation(BATCH)
    public void small_marker_noCache(Blackhole bh) {
        for (int i = 0; i < BATCH; i++) bh.consume(writerNoCache.writeFileIfChanged(smallMarkerFile.toString(), smallBody, true));
    }
    @Benchmark @OperationsPerInvocation(BATCH)
    public void small_nonMarker_cacheHit(Blackhole bh) {
        for (int i = 0; i < BATCH; i++) bh.consume(writerWithCache.writeFileIfChanged(smallNonMarkerFile.toString(), smallBody, true));
    }
    @Benchmark @OperationsPerInvocation(BATCH)
    public void small_nonMarker_noCache(Blackhole bh) {
        for (int i = 0; i < BATCH; i++) bh.consume(writerNoCache.writeFileIfChanged(smallNonMarkerFile.toString(), smallBody, true));
    }

    // ===== Medium (12 KB — realistic generated-file size) =====

    @Benchmark @OperationsPerInvocation(BATCH)
    public void medium_marker_cacheHit(Blackhole bh) {
        for (int i = 0; i < BATCH; i++) bh.consume(writerWithCache.writeFileIfChanged(mediumMarkerFile.toString(), mediumBody, true));
    }
    @Benchmark @OperationsPerInvocation(BATCH)
    public void medium_marker_noCache(Blackhole bh) {
        for (int i = 0; i < BATCH; i++) bh.consume(writerNoCache.writeFileIfChanged(mediumMarkerFile.toString(), mediumBody, true));
    }
    @Benchmark @OperationsPerInvocation(BATCH)
    public void medium_nonMarker_cacheHit(Blackhole bh) {
        for (int i = 0; i < BATCH; i++) bh.consume(writerWithCache.writeFileIfChanged(mediumNonMarkerFile.toString(), mediumBody, true));
    }
    @Benchmark @OperationsPerInvocation(BATCH)
    public void medium_nonMarker_noCache(Blackhole bh) {
        for (int i = 0; i < BATCH; i++) bh.consume(writerNoCache.writeFileIfChanged(mediumNonMarkerFile.toString(), mediumBody, true));
    }

    // ===== Large (1 MB — Files.readString cost dominates the no-cache path; cache wins clearly) =====

    @Benchmark @OperationsPerInvocation(BATCH)
    public void large_marker_cacheHit(Blackhole bh) {
        for (int i = 0; i < BATCH; i++) bh.consume(writerWithCache.writeFileIfChanged(largeMarkerFile.toString(), largeBody, true));
    }
    @Benchmark @OperationsPerInvocation(BATCH)
    public void large_marker_noCache(Blackhole bh) {
        for (int i = 0; i < BATCH; i++) bh.consume(writerNoCache.writeFileIfChanged(largeMarkerFile.toString(), largeBody, true));
    }
    @Benchmark @OperationsPerInvocation(BATCH)
    public void large_nonMarker_cacheHit(Blackhole bh) {
        for (int i = 0; i < BATCH; i++) bh.consume(writerWithCache.writeFileIfChanged(largeNonMarkerFile.toString(), largeBody, true));
    }
    @Benchmark @OperationsPerInvocation(BATCH)
    public void large_nonMarker_noCache(Blackhole bh) {
        for (int i = 0; i < BATCH; i++) bh.consume(writerNoCache.writeFileIfChanged(largeNonMarkerFile.toString(), largeBody, true));
    }
}
