package se.deversity.vibetags.processor.internal;

import org.jspecify.annotations.Nullable;
import se.deversity.vibetags.annotations.AIContract;
import se.deversity.vibetags.annotations.AICore;
import org.slf4j.Logger;

import javax.annotation.processing.Messager;
import javax.lang.model.element.AnnotationMirror;
import javax.lang.model.element.AnnotationValue;
import javax.lang.model.element.Element;
import javax.tools.Diagnostic;
import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.NoSuchFileException;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.nio.file.StandardCopyOption;
import java.util.ArrayList;
import java.util.Collections;
import java.util.List;
import java.util.Set;
import java.util.stream.Stream;

/**
 * Writes guardrail content to disk with marker-aware section updates, YAML front-matter
 * preservation, and atomic writes. Also strips legacy (pre-marker) VibeTags blocks and
 * cleans up orphaned granular rule files.
 *
 * <p>Lifecycle: stateless aside from injected {@link Messager} and {@link Logger}. Both are
 * nullable — callers who haven't initialised a processing environment (typical in unit tests)
 * get a no-op messager and quiet logging.
 */
@AICore(
    sensitivity = "high",
    note = "Atomic marker-aware file writer; invariant: hand-authored content outside VIBETAGS-START/END markers must never be overwritten or lost"
)
public final class GuardrailFileWriter {

    public static final String MARKER_START_MD = "<!-- VIBETAGS-START -->";
    public static final String MARKER_END_MD = "<!-- VIBETAGS-END -->";
    public static final String MARKER_START_HASH = "# VIBETAGS-START";
    public static final String MARKER_END_HASH = "# VIBETAGS-END";

    private final String generatedHeaderTrim;
    private final Messager messager;
    private final @Nullable Logger log;
    private final @Nullable WriteCache writeCache;
    private final boolean dryRun;
    private final List<String> dryRunChanges = Collections.synchronizedList(new ArrayList<>());

    /**
     * @param generatedHeader the canonical "Generated by VibeTags | ..." header used to detect
     *                        legacy (pre-marker) VibeTags blocks in existing files
     * @param messager        compiler messager (nullable — null becomes a no-op)
     * @param log             SLF4J logger (nullable)
     */
    public GuardrailFileWriter(String generatedHeader, @Nullable Messager messager, @Nullable Logger log) {
        this(generatedHeader, messager, log, null);
    }

    /**
     * @param writeCache      optional per-file content cache (nullable — null disables caching)
     */
    public GuardrailFileWriter(String generatedHeader, @Nullable Messager messager, @Nullable Logger log, @Nullable WriteCache writeCache) {
        this(generatedHeader, messager, log, writeCache, false);
    }

    /**
     * @param dryRun          when {@code true} the writer touches NOTHING on disk: every write,
     *                        scrub, or delete that a normal run would perform is recorded in
     *                        {@link #dryRunChanges()} instead. Used by check mode
     *                        ({@code -Avibetags.check=true}) for CI drift detection.
     */
    public GuardrailFileWriter(String generatedHeader, @Nullable Messager messager, @Nullable Logger log,
                               @Nullable WriteCache writeCache, boolean dryRun) {
        this.generatedHeaderTrim = generatedHeader.trim();
        this.messager = messager != null ? messager : noopMessager();
        this.log = log;
        this.writeCache = writeCache;
        this.dryRun = dryRun;
    }

    /** Paths a dry-run writer would have written, scrubbed, or deleted. Empty unless {@code dryRun}. */
    public List<String> dryRunChanges() {
        synchronized (dryRunChanges) {
            return new ArrayList<>(dryRunChanges);
        }
    }

    /**
     * Writes {@code content} to {@code path} only if the file's current content differs.
     * Honors marker-aware updates for .md/.mdc/llms*.txt, hash markers for rules/ignore files,
     * and full overwrite for .json/.toml.
     *
     * @return {@code true} if the file was actually written
     */
    @AIContract(reason = "Public API since v0.1; tests and the processor both bind to the (String path, String content, boolean hasNewRules) signature and return semantics")
    public boolean writeFileIfChanged(String path, String content, boolean hasNewRules) {
        try {
            Path filePath = Paths.get(path);

            // Fast-path: if our cache says we wrote this exact body to this file and the file
            // is byte-stable since (size + mtime unchanged), skip the read/diff/write entirely.
            if (writeCache != null && writeCache.isUnchanged(filePath, content)) {
                return false;
            }

            Path parent = filePath.getParent();
            if (parent != null && !dryRun) {
                Files.createDirectories(parent);
            }

            // Path.getFileName() returns null only for root paths (e.g. "/") — never for
            // the concrete file paths VibeTags constructs, but we guard for correctness.
            Path fileNamePath = filePath.getFileName();
            String fileName = fileNamePath != null ? fileNamePath.toString() : "";
            String[] markers = getMarkersFor(fileName);
            boolean supportsMarkers = (markers != null);

            // Pre-check size to allow non-marker overwrite branch to skip the full read
            long existingSize;
            boolean fileExists;
            try {
                existingSize = Files.size(filePath);
                fileExists = true;
            } catch (NoSuchFileException nsfe) {
                existingSize = 0L;
                fileExists = false;
            }
            byte[] contentBytes = content.getBytes(StandardCharsets.UTF_8);
            int contentByteLen = contentBytes.length;
            boolean nonMarkerSizeMismatch = !supportsMarkers && fileExists
                && Math.abs(existingSize - contentByteLen) > 64;

            // Phase-2 streaming fast path: for non-marker files where the on-disk size matches
            // the new content size exactly, stream-compare bytes with early-exit on first
            // mismatch. Skips materialising the entire file as a String just to call .equals().
            if (!supportsMarkers && fileExists && existingSize == contentByteLen) {
                if (fileBytesEqual(filePath, contentBytes)) {
                    // Byte-identical — nothing to do. Refresh the cache so subsequent calls hit
                    // the cheap WriteCache fast path even on the very first build.
                    if (writeCache != null) writeCache.recordWrite(filePath, content);
                    return false;
                }
                // Sizes match but bytes differ — write directly. No need for readString or
                // strip-tolerant compare: an exact-size byte mismatch is unambiguous.
                if (!hasNewRules && existingSize > 0) {
                    skipUpdateMsg(fileName);
                    return false;
                }
                writeAndCache(filePath, content, content);
                messager.printMessage(Diagnostic.Kind.NOTE, "VibeTags: Updated " + fileName);
                return true;
            }

            String existing = (fileExists && !nonMarkerSizeMismatch)
                ? Files.readString(filePath, StandardCharsets.UTF_8)
                : "";

            if (supportsMarkers) {
                return writeWithMarkers(filePath, fileName, path, content, existing, hasNewRules, markers);
            }
            return writeWithoutMarkers(filePath, fileName, content, existing, fileExists, existingSize, nonMarkerSizeMismatch, hasNewRules);
        } catch (IOException e) {
            messager.printMessage(Diagnostic.Kind.WARNING,
                "VibeTags: Failed to write AI rules file: " + path + " - " + e.getMessage());
            return false;
        }
    }

    /** Writes {@code finalContent} atomically and, if a write cache is wired, records the body we wrote. */
    private void writeAndCache(Path filePath, String finalContent, String bodyForCache) throws IOException {
        if (dryRun) {
            dryRunChanges.add(filePath.toString());
            return;
        }
        writeContentWithBackup(filePath, finalContent);
        if (writeCache != null) {
            writeCache.recordWrite(filePath, bodyForCache);
        }
    }

    private boolean writeWithMarkers(Path filePath, String fileName, String path, String content,
                                     String existing, boolean hasNewRules, String[] markers) throws IOException {
        String markerStart = markers[0];
        String markerEnd = markers[1];

        // Front-matter: markers MUST come after the YAML header
        String frontMatter = "";
        String body = content;
        if (content.startsWith("---")) {
            int secondTriple = content.indexOf("---", 3);
            if (secondTriple != -1) {
                frontMatter = content.substring(0, secondTriple + 3).trim();
                body = content.substring(secondTriple + 3).trim();
            }
        }

        String wrappedBody = markerStart + "\n" + neutraliseMarkers(body.trim(), markers) + "\n" + markerEnd;

        int start = indexOfMarkerLine(existing, markerStart, 0);
        if (start >= 0) {
            int end = indexOfMarkerLine(existing, markerEnd, start + markerStart.length());
            if (end == -1) {
                messager.printMessage(Diagnostic.Kind.WARNING,
                    "VibeTags: malformed markers in " + path + " (no end marker). Preserving content before start marker.");
                String before = stripLegacyVibeTagsBlock(existing.substring(0, start).stripTrailing());
                String finalContent = (!before.isEmpty() ? before + "\n\n" : "") + wrappedBody + "\n";
                if (existing.strip().equals(finalContent.strip())) return false;
                writeAndCache(filePath, finalContent, content);
                return true;
            }
            end += markerEnd.length();
            String before = stripLegacyVibeTagsBlock(existing.substring(0, start).stripTrailing());
            String after = existing.substring(end).stripLeading();

            StringBuilder sb = new StringBuilder();
            if (!before.isEmpty()) sb.append(before).append("\n\n");
            sb.append(wrappedBody);
            if (!after.isEmpty()) sb.append("\n\n").append(after);
            String finalContent = sb.toString().trim() + "\n";

            if (existing.strip().equals(finalContent.strip())) return false;

            if (!hasNewRules && !existing.isEmpty()) {
                skipUpdateMsg(fileName);
                return false;
            }

            writeAndCache(filePath, finalContent, content);
            messager.printMessage(Diagnostic.Kind.NOTE, "VibeTags: Updated " + fileName);
            return true;
        } else if (!existing.isEmpty() && existing.contains(generatedHeaderTrim)) {
            // Legacy file (no markers but has VibeTags header): upgrade to markers
            String finalContent = (frontMatter.isEmpty() ? "" : frontMatter + "\n\n") + wrappedBody + "\n";
            if (existing.strip().equals(finalContent.strip())) return false;

            if (!hasNewRules) {
                skipUpdateMsg(fileName);
                return false;
            }

            writeAndCache(filePath, finalContent, content);
            messager.printMessage(Diagnostic.Kind.NOTE, "VibeTags: Updated legacy file " + fileName);
            return true;
        } else {
            // Section missing or non-VibeTags file: append at end
            String updated = existing.isEmpty()
                ? (frontMatter.isEmpty() ? "" : frontMatter + "\n\n") + wrappedBody + "\n"
                : existing.stripTrailing() + "\n\n" + wrappedBody + "\n";
            if (existing.strip().equals(updated.strip())) return false;

            if (!hasNewRules && !existing.isEmpty()) {
                skipUpdateMsg(fileName);
                return false;
            }

            writeAndCache(filePath, updated, content);
            String action = existing.isEmpty() ? "wrote" : "appended";
            messager.printMessage(Diagnostic.Kind.NOTE, "VibeTags: " + action + " " + fileName);
            return true;
        }
    }

    private boolean writeWithoutMarkers(Path filePath, String fileName, String content, String existing,
                                        boolean fileExists, long existingSize, boolean nonMarkerSizeMismatch,
                                        boolean hasNewRules) throws IOException {
        if (!nonMarkerSizeMismatch && existing.strip().equals(content.strip())) return false;

        if (!hasNewRules && fileExists && existingSize > 0) {
            skipUpdateMsg(fileName);
            return false;
        }

        writeAndCache(filePath, content, content);
        messager.printMessage(Diagnostic.Kind.NOTE, "VibeTags: Updated " + fileName);
        return true;
    }

    /**
     * Returns the appropriate marker pair for a file based on its extension.
     * Returns {@code null} for JSON/TOML which are overwritten without markers.
     */
    public static @Nullable String[] getMarkersFor(String fileName) {
        if (fileName.endsWith(".md") || fileName.endsWith(".mdc")
            || "llms.txt".equals(fileName) || "llms-full.txt".equals(fileName)) {
            return new String[]{MARKER_START_MD, MARKER_END_MD};
        }
        if (fileName.endsWith(".json") || fileName.endsWith(".toml")) {
            return null;
        }
        return new String[]{MARKER_START_HASH, MARKER_END_HASH};
    }

    /**
     * Defuses any VibeTags delimiter that appears as a standalone line inside the generated body.
     *
     * <p>The body is assembled from annotation attribute values, and the markdown platforms emit
     * those verbatim (there is no XML/JSON structure to escape there). A {@code reason} containing
     * a marker on its own line would therefore close the managed region early: on the next compile
     * the true remainder of the block is mistaken for hand-authored content, kept, and re-appended,
     * so the file grows a stale duplicate of itself on every build.
     *
     * <p>A zero-width space after the {@code <!--} / {@code #} keeps the text readable while making
     * the line no longer equal to a delimiter.
     */
    private static String neutraliseMarkers(String body, String[] markers) {
        String out = body;
        for (String marker : markers) {
            if (indexOfMarkerLine(out, marker, 0) < 0) continue;
            String defused = marker.startsWith("<!--")
                ? "<!--​" + marker.substring(4)
                : "#​" + marker.substring(1);
            StringBuilder sb = new StringBuilder(out.length() + 8);
            int cursor = 0;
            while (cursor < out.length()) {
                int hit = indexOfMarkerLine(out, marker, cursor);
                if (hit < 0) {
                    sb.append(out, cursor, out.length());
                    break;
                }
                sb.append(out, cursor, hit).append(defused);
                cursor = hit + marker.length();
            }
            out = sb.toString();
        }
        return out;
    }

    /**
     * Finds a VibeTags marker only where it stands alone on its own line — the only form this
     * writer ever emits ({@code markerStart + "\n" + body + "\n" + markerEnd}).
     *
     * <p>A bare {@code indexOf} also matches a marker <em>mentioned</em> in hand-authored prose,
     * e.g. a CLAUDE.md documenting VibeTags itself:
     *
     * <pre>- **HTML comments**: `&lt;!-- VIBETAGS-START --&gt;` / `&lt;!-- VIBETAGS-END --&gt;`</pre>
     *
     * <p>Treating that as the managed region cuts the sentence in half and overwrites everything
     * after it — this repository's own CLAUDE.md was corrupted exactly that way. Requiring the
     * marker to own its line distinguishes a real delimiter from a citation of one.
     *
     * @param content   file content to search
     * @param marker    the marker literal
     * @param fromIndex index to start searching at
     * @return index of the first character of the marker, or {@code -1} if it appears nowhere as a
     *         standalone line at or after {@code fromIndex}
     */
    static int indexOfMarkerLine(String content, String marker, int fromIndex) {
        if (content == null || content.isEmpty() || marker == null || marker.isEmpty()) return -1;
        for (int i = content.indexOf(marker, Math.max(0, fromIndex)); i >= 0;
             i = content.indexOf(marker, i + 1)) {
            if (ownsItsLine(content, i, marker.length())) return i;
        }
        return -1;
    }

    /** True when only whitespace separates the match from the start and end of its line. */
    private static boolean ownsItsLine(String content, int start, int length) {
        for (int i = start - 1; i >= 0 && content.charAt(i) != '\n'; i--) {
            if (!Character.isWhitespace(content.charAt(i))) return false;
        }
        for (int i = start + length; i < content.length() && content.charAt(i) != '\n'; i++) {
            if (!Character.isWhitespace(content.charAt(i))) return false;
        }
        return true;
    }

    /**
     * Strips a legacy (pre-marker) VibeTags block, preserving genuine human content.
     */
    public String stripLegacyVibeTagsBlock(String before) {
        if (before == null || before.isEmpty()) return before;

        String commentedHeader = "<!-- " + generatedHeaderTrim + " -->";
        int legacyStart = before.indexOf(commentedHeader);
        if (legacyStart == -1) legacyStart = before.indexOf(generatedHeaderTrim);
        if (legacyStart == -1) return before;

        String rawPrefix = before.substring(0, legacyStart).stripTrailing();
        String rest = before.substring(legacyStart);

        boolean hasHumanPrefix = !rawPrefix.isEmpty()
            && rawPrefix.lines().anyMatch(l -> {
                String t = l.trim();
                return !t.isEmpty() && !t.startsWith("#") && !t.startsWith("*")
                    && !t.startsWith("-") && !t.startsWith("<!--");
            });
        String prefix = hasHumanPrefix ? rawPrefix : "";

        // For XML-structured files: find the last VibeTags closing tag within 2 000 chars
        String searchWindow = rest.length() > 2000 ? rest.substring(0, 2000) : rest;
        int blockEnd = -1;
        for (String closer : new String[]{"</rule>", "</project_guardrails>"}) {
            int idx = searchWindow.lastIndexOf(closer);
            if (idx >= 0) blockEnd = Math.max(blockEnd, idx + closer.length());
        }

        String humanContent;
        if (blockEnd > 0) {
            int nlAfter = rest.indexOf("\n", blockEnd);
            humanContent = nlAfter >= 0 ? rest.substring(nlAfter + 1).stripLeading() : "";
        } else {
            humanContent = hasHumanPrefix
                ? (rest.contains("\n\n") ? rest.substring(rest.indexOf("\n\n") + 2).stripLeading() : "")
                : "";
        }

        if (prefix.isEmpty()) return humanContent;
        if (humanContent.isEmpty()) return prefix;
        return prefix + "\n\n" + humanContent;
    }

    /**
     * Removes orphaned VibeTags sections from granular rule files in {@code dir}, deleting files
     * that become boilerplate-only.
     *
     * @param dir            directory to scan
     * @param extension      file extension filter (e.g. ".mdc" or ".md")
     * @param excludeQNames  qualified names (filename without extension) to skip — typically
     *                       files just written this round, to avoid delete-then-recreate cycles
     */
    public void cleanupGranularDirectory(Path dir, String extension, Set<String> excludeQNames) {
        if (dir == null || !Files.exists(dir) || !Files.isDirectory(dir)) return;
        try (Stream<Path> stream = Files.list(dir)) {
            stream.filter(Files::isRegularFile)
                  .filter(p -> p.toString().endsWith(extension))
                  .filter(p -> {
                      // Path.getFileName() returns null only for root paths — guard for correctness.
                      Path fn = p.getFileName();
                      String name = fn != null ? fn.toString() : "";
                      int dot = name.lastIndexOf('.');
                      return !excludeQNames.contains(dot >= 0 ? name.substring(0, dot) : name);
                  })
                  .forEach(this::scrubGranularFile);
        } catch (IOException ignored) {
            // Stay silent during compilation
        }
    }

    public void cleanupGranularDirectory(Path dir, String extension) {
        cleanupGranularDirectory(dir, extension, Collections.emptySet());
    }

    private void scrubGranularFile(Path p) {
        try {
            String content = Files.readString(p, StandardCharsets.UTF_8);
            boolean updated = false;

            int mdStart = indexOfMarkerLine(content, MARKER_START_MD, 0);
            if (mdStart >= 0) {
                int end = indexOfMarkerLine(content, MARKER_END_MD, mdStart + MARKER_START_MD.length());
                if (end != -1) {
                    String before = content.substring(0, mdStart).stripTrailing();
                    String after = content.substring(end + MARKER_END_MD.length()).stripLeading();
                    content = (!before.isEmpty() ? before + "\n\n" : "") + after;
                    updated = true;
                }
            } else {
                int hashStart = indexOfMarkerLine(content, MARKER_START_HASH, 0);
                if (hashStart >= 0) {
                    int end = indexOfMarkerLine(content, MARKER_END_HASH, hashStart + MARKER_START_HASH.length());
                    if (end != -1) {
                        String before = content.substring(0, hashStart).stripTrailing();
                        String after = content.substring(end + MARKER_END_HASH.length()).stripLeading();
                        content = (!before.isEmpty() ? before + "\n\n" : "") + after;
                        updated = true;
                    }
                }
            }

            if (updated) {
                content = content.trim();
                boolean isEmptyOrBoilerplate = content.isEmpty();
                if (!isEmptyOrBoilerplate && content.startsWith("---")) {
                    int secondTriple = content.indexOf("---", 3);
                    if (secondTriple != -1) {
                        String afterFrontMatter = content.substring(secondTriple + 3).trim();
                        isEmptyOrBoilerplate = afterFrontMatter.isEmpty();
                    }
                }

                if (dryRun) {
                    dryRunChanges.add(p.toString());
                    return;
                }

                if (isEmptyOrBoilerplate) {
                    Files.delete(p);
                    if (writeCache != null) writeCache.invalidate(p);
                } else {
                    Files.writeString(p, content + "\n", StandardCharsets.UTF_8);
                    if (writeCache != null) writeCache.invalidate(p);
                }
            }
        } catch (IOException ignored) {
            // Skip files we can't read
        }
    }

    /**
     * Streams {@code file} and compares byte-by-byte against {@code expected}. Returns true iff
     * the file is exactly the same bytes. Early-exits on first mismatch.
     *
     * <p>The caller must already have established that {@code Files.size(file) == expected.length}
     * — this method does not re-check.
     */
    public static boolean fileBytesEqual(Path file, byte[] expected) throws IOException {
        try (java.io.InputStream in = Files.newInputStream(file)) {
            byte[] buf = new byte[Math.min(8192, Math.max(1, expected.length))];
            int idx = 0;
            int n;
            while ((n = in.read(buf)) > 0) {
                if (idx + n > expected.length) return false; // file longer than expected
                for (int i = 0; i < n; i++) {
                    if (buf[i] != expected[idx + i]) return false;
                }
                idx += n;
            }
            return idx == expected.length;
        }
    }

    private void writeContentWithBackup(Path filePath, String finalContent) throws IOException {
        // Create the staging file with a fresh random name in the TARGET directory (so the atomic
        // move stays on the same filesystem). Files.createTempFile creates it atomically with
        // O_EXCL semantics, so it cannot follow or clobber a pre-planted symlink at a predictable
        // temp path — defeating a local symlink/TOCTOU write-redirect. The parent already exists
        // (the caller created it before any write).
        Path parent = filePath.getParent();
        Path tmp = (parent != null)
            ? Files.createTempFile(parent, ".vibetags-", ".tmp")
            : Files.createTempFile(".vibetags-", ".tmp");
        try {
            Files.writeString(tmp, finalContent, StandardCharsets.UTF_8);
            try {
                Files.move(tmp, filePath, StandardCopyOption.REPLACE_EXISTING, StandardCopyOption.ATOMIC_MOVE);
            } catch (java.nio.file.AtomicMoveNotSupportedException e) {
                Files.move(tmp, filePath, StandardCopyOption.REPLACE_EXISTING);
            }
        } finally {
            // A successful move consumes tmp; clean it up only if a failure left it behind.
            Files.deleteIfExists(tmp);
        }
    }

    private void skipUpdateMsg(String fileName) {
        String msg = "VibeTags: Skipping update of " + fileName + " (no annotations found in this module, preserving existing rules)";
        messager.printMessage(Diagnostic.Kind.NOTE, msg);
        if (log != null) log.info("Skipping update of {} — no annotations found", fileName);
    }

    /** Visible for testing — verifies the all-overloads no-op contract. */
    public static Messager noopMessager() {
        return new Messager() {
            @Override public void printMessage(Diagnostic.Kind kind, CharSequence msg) {}
            @Override public void printMessage(Diagnostic.Kind kind, CharSequence msg, Element e) {}
            @Override public void printMessage(Diagnostic.Kind kind, CharSequence msg, Element e, AnnotationMirror a) {}
            @Override public void printMessage(Diagnostic.Kind kind, CharSequence msg, Element e, AnnotationMirror a, AnnotationValue v) {}
        };
    }
}
