package se.deversity.vibetags.processor.internal;

import org.slf4j.Logger;

import javax.annotation.processing.Messager;
import javax.lang.model.element.AnnotationMirror;
import javax.lang.model.element.AnnotationValue;
import javax.lang.model.element.Element;
import javax.tools.Diagnostic;
import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.NoSuchFileException;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.nio.file.StandardCopyOption;
import java.util.Collections;
import java.util.Set;
import java.util.stream.Stream;

/**
 * Writes guardrail content to disk with marker-aware section updates, YAML front-matter
 * preservation, and atomic writes. Also strips legacy (pre-marker) VibeTags blocks and
 * cleans up orphaned granular rule files.
 *
 * <p>Lifecycle: stateless aside from injected {@link Messager} and {@link Logger}. Both are
 * nullable — callers who haven't initialised a processing environment (typical in unit tests)
 * get a no-op messager and quiet logging.
 */
public final class GuardrailFileWriter {

    public static final String MARKER_START_MD = "<!-- VIBETAGS-START -->";
    public static final String MARKER_END_MD = "<!-- VIBETAGS-END -->";
    public static final String MARKER_START_HASH = "# VIBETAGS-START";
    public static final String MARKER_END_HASH = "# VIBETAGS-END";

    private final String generatedHeaderTrim;
    private final Messager messager;
    private final Logger log;
    private final WriteCache writeCache;

    /**
     * @param generatedHeader the canonical "Generated by VibeTags | ..." header used to detect
     *                        legacy (pre-marker) VibeTags blocks in existing files
     * @param messager        compiler messager (nullable — null becomes a no-op)
     * @param log             SLF4J logger (nullable)
     */
    public GuardrailFileWriter(String generatedHeader, Messager messager, Logger log) {
        this(generatedHeader, messager, log, null);
    }

    /**
     * @param writeCache      optional per-file content cache (nullable — null disables caching)
     */
    public GuardrailFileWriter(String generatedHeader, Messager messager, Logger log, WriteCache writeCache) {
        this.generatedHeaderTrim = generatedHeader.trim();
        this.messager = messager != null ? messager : noopMessager();
        this.log = log;
        this.writeCache = writeCache;
    }

    /**
     * Writes {@code content} to {@code path} only if the file's current content differs.
     * Honors marker-aware updates for .md/.mdc/llms*.txt, hash markers for rules/ignore files,
     * and full overwrite for .json/.toml.
     *
     * @return {@code true} if the file was actually written
     */
    public boolean writeFileIfChanged(String path, String content, boolean hasNewRules) {
        try {
            Path filePath = Paths.get(path);

            // Fast-path: if our cache says we wrote this exact body to this file and the file
            // is byte-stable since (size + mtime unchanged), skip the read/diff/write entirely.
            if (writeCache != null && writeCache.isUnchanged(filePath, content)) {
                return false;
            }

            Path parent = filePath.getParent();
            if (parent != null) {
                Files.createDirectories(parent);
            }

            String fileName = filePath.getFileName().toString();
            String[] markers = getMarkersFor(fileName);
            boolean supportsMarkers = (markers != null);

            // Pre-check size to allow non-marker overwrite branch to skip the full read
            long existingSize;
            boolean fileExists;
            try {
                existingSize = Files.size(filePath);
                fileExists = true;
            } catch (NoSuchFileException nsfe) {
                existingSize = 0L;
                fileExists = false;
            }
            int contentByteLen = content.getBytes(StandardCharsets.UTF_8).length;
            boolean nonMarkerSizeMismatch = !supportsMarkers && fileExists
                && Math.abs(existingSize - contentByteLen) > 64;

            String existing = (fileExists && !nonMarkerSizeMismatch)
                ? Files.readString(filePath, StandardCharsets.UTF_8)
                : "";

            if (supportsMarkers) {
                return writeWithMarkers(filePath, fileName, path, content, existing, hasNewRules, markers);
            }
            return writeWithoutMarkers(filePath, fileName, content, existing, fileExists, existingSize, nonMarkerSizeMismatch, hasNewRules);
        } catch (IOException e) {
            messager.printMessage(Diagnostic.Kind.WARNING,
                "VibeTags: Failed to write AI rules file: " + path + " - " + e.getMessage());
            return false;
        }
    }

    /** Writes {@code finalContent} atomically and, if a write cache is wired, records the body we wrote. */
    private void writeAndCache(Path filePath, String finalContent, String bodyForCache) throws IOException {
        writeContentWithBackup(filePath, finalContent);
        if (writeCache != null) {
            writeCache.recordWrite(filePath, bodyForCache);
        }
    }

    private boolean writeWithMarkers(Path filePath, String fileName, String path, String content,
                                     String existing, boolean hasNewRules, String[] markers) throws IOException {
        String markerStart = markers[0];
        String markerEnd = markers[1];

        // Front-matter: markers MUST come after the YAML header
        String frontMatter = "";
        String body = content;
        if (content.startsWith("---")) {
            int secondTriple = content.indexOf("---", 3);
            if (secondTriple != -1) {
                frontMatter = content.substring(0, secondTriple + 3).trim();
                body = content.substring(secondTriple + 3).trim();
            }
        }

        String wrappedBody = markerStart + "\n" + body.trim() + "\n" + markerEnd;

        int start = existing.indexOf(markerStart);
        if (start >= 0) {
            int end = existing.indexOf(markerEnd);
            if (end == -1) {
                messager.printMessage(Diagnostic.Kind.WARNING,
                    "VibeTags: malformed markers in " + path + " (no end marker). Preserving content before start marker.");
                String before = stripLegacyVibeTagsBlock(existing.substring(0, start).stripTrailing());
                String finalContent = (!before.isEmpty() ? before + "\n\n" : "") + wrappedBody + "\n";
                if (existing.strip().equals(finalContent.strip())) return false;
                writeAndCache(filePath, finalContent, content);
                return true;
            }
            end += markerEnd.length();
            String before = stripLegacyVibeTagsBlock(existing.substring(0, start).stripTrailing());
            String after = existing.substring(end).stripLeading();

            StringBuilder sb = new StringBuilder();
            if (!before.isEmpty()) sb.append(before).append("\n\n");
            sb.append(wrappedBody);
            if (!after.isEmpty()) sb.append("\n\n").append(after);
            String finalContent = sb.toString().trim() + "\n";

            if (existing.strip().equals(finalContent.strip())) return false;

            if (!hasNewRules && !existing.isEmpty()) {
                skipUpdateMsg(fileName);
                return false;
            }

            writeAndCache(filePath, finalContent, content);
            messager.printMessage(Diagnostic.Kind.NOTE, "VibeTags: Updated " + fileName);
            return true;
        } else if (!existing.isEmpty() && existing.contains(generatedHeaderTrim)) {
            // Legacy file (no markers but has VibeTags header): upgrade to markers
            String finalContent = (frontMatter.isEmpty() ? "" : frontMatter + "\n\n") + wrappedBody + "\n";
            if (existing.strip().equals(finalContent.strip())) return false;

            if (!hasNewRules && !existing.isEmpty()) {
                skipUpdateMsg(fileName);
                return false;
            }

            writeAndCache(filePath, finalContent, content);
            messager.printMessage(Diagnostic.Kind.NOTE, "VibeTags: Updated legacy file " + fileName);
            return true;
        } else {
            // Section missing or non-VibeTags file: append at end
            String updated = existing.isEmpty()
                ? (frontMatter.isEmpty() ? "" : frontMatter + "\n\n") + wrappedBody + "\n"
                : existing.stripTrailing() + "\n\n" + wrappedBody + "\n";
            if (existing.strip().equals(updated.strip())) return false;

            if (!hasNewRules && !existing.isEmpty()) {
                skipUpdateMsg(fileName);
                return false;
            }

            writeAndCache(filePath, updated, content);
            String action = existing.isEmpty() ? "wrote" : "appended";
            messager.printMessage(Diagnostic.Kind.NOTE, "VibeTags: " + action + " " + fileName);
            return true;
        }
    }

    private boolean writeWithoutMarkers(Path filePath, String fileName, String content, String existing,
                                        boolean fileExists, long existingSize, boolean nonMarkerSizeMismatch,
                                        boolean hasNewRules) throws IOException {
        if (!nonMarkerSizeMismatch && existing.strip().equals(content.strip())) return false;

        if (!hasNewRules && fileExists && existingSize > 0) {
            skipUpdateMsg(fileName);
            return false;
        }

        writeAndCache(filePath, content, content);
        messager.printMessage(Diagnostic.Kind.NOTE, "VibeTags: Updated " + fileName);
        return true;
    }

    /**
     * Returns the appropriate marker pair for a file based on its extension.
     * Returns {@code null} for JSON/TOML which are overwritten without markers.
     */
    public static String[] getMarkersFor(String fileName) {
        if (fileName.endsWith(".md") || fileName.endsWith(".mdc")
            || fileName.equals("llms.txt") || fileName.equals("llms-full.txt")) {
            return new String[]{MARKER_START_MD, MARKER_END_MD};
        }
        if (fileName.endsWith(".json") || fileName.endsWith(".toml")) {
            return null;
        }
        return new String[]{MARKER_START_HASH, MARKER_END_HASH};
    }

    /**
     * Strips a legacy (pre-marker) VibeTags block, preserving genuine human content.
     */
    public String stripLegacyVibeTagsBlock(String before) {
        if (before == null || before.isEmpty()) return before;

        String commentedHeader = "<!-- " + generatedHeaderTrim + " -->";
        int legacyStart = before.indexOf(commentedHeader);
        if (legacyStart == -1) legacyStart = before.indexOf(generatedHeaderTrim);
        if (legacyStart == -1) return before;

        String rawPrefix = before.substring(0, legacyStart).stripTrailing();
        String rest = before.substring(legacyStart);

        boolean hasHumanPrefix = !rawPrefix.isEmpty()
            && rawPrefix.lines().anyMatch(l -> {
                String t = l.trim();
                return !t.isEmpty() && !t.startsWith("#") && !t.startsWith("*")
                    && !t.startsWith("-") && !t.startsWith("<!--");
            });
        String prefix = hasHumanPrefix ? rawPrefix : "";

        // For XML-structured files: find the last VibeTags closing tag within 2 000 chars
        String searchWindow = rest.length() > 2000 ? rest.substring(0, 2000) : rest;
        int blockEnd = -1;
        for (String closer : new String[]{"</rule>", "</project_guardrails>"}) {
            int idx = searchWindow.lastIndexOf(closer);
            if (idx >= 0) blockEnd = Math.max(blockEnd, idx + closer.length());
        }

        String humanContent;
        if (blockEnd > 0) {
            int nlAfter = rest.indexOf("\n", blockEnd);
            humanContent = nlAfter >= 0 ? rest.substring(nlAfter + 1).stripLeading() : "";
        } else {
            humanContent = hasHumanPrefix
                ? (rest.contains("\n\n") ? rest.substring(rest.indexOf("\n\n") + 2).stripLeading() : "")
                : "";
        }

        if (prefix.isEmpty()) return humanContent;
        if (humanContent.isEmpty()) return prefix;
        return prefix + "\n\n" + humanContent;
    }

    /**
     * Removes orphaned VibeTags sections from granular rule files in {@code dir}, deleting files
     * that become boilerplate-only.
     *
     * @param dir            directory to scan
     * @param extension      file extension filter (e.g. ".mdc" or ".md")
     * @param excludeQNames  qualified names (filename without extension) to skip — typically
     *                       files just written this round, to avoid delete-then-recreate cycles
     */
    public void cleanupGranularDirectory(Path dir, String extension, Set<String> excludeQNames) {
        if (dir == null || !Files.exists(dir) || !Files.isDirectory(dir)) return;
        try (Stream<Path> stream = Files.list(dir)) {
            stream.filter(Files::isRegularFile)
                  .filter(p -> p.toString().endsWith(extension))
                  .filter(p -> {
                      String name = p.getFileName().toString();
                      int dot = name.lastIndexOf('.');
                      return !excludeQNames.contains(dot >= 0 ? name.substring(0, dot) : name);
                  })
                  .forEach(this::scrubGranularFile);
        } catch (IOException ignored) {
            // Stay silent during compilation
        }
    }

    public void cleanupGranularDirectory(Path dir, String extension) {
        cleanupGranularDirectory(dir, extension, Collections.emptySet());
    }

    private void scrubGranularFile(Path p) {
        try {
            String content = Files.readString(p, StandardCharsets.UTF_8);
            boolean updated = false;

            int mdStart = content.indexOf(MARKER_START_MD);
            if (mdStart >= 0) {
                int end = content.indexOf(MARKER_END_MD);
                if (end != -1) {
                    String before = content.substring(0, mdStart).stripTrailing();
                    String after = content.substring(end + MARKER_END_MD.length()).stripLeading();
                    content = (!before.isEmpty() ? before + "\n\n" : "") + after;
                    updated = true;
                }
            } else {
                int hashStart = content.indexOf(MARKER_START_HASH);
                if (hashStart >= 0) {
                    int end = content.indexOf(MARKER_END_HASH);
                    if (end != -1) {
                        String before = content.substring(0, hashStart).stripTrailing();
                        String after = content.substring(end + MARKER_END_HASH.length()).stripLeading();
                        content = (!before.isEmpty() ? before + "\n\n" : "") + after;
                        updated = true;
                    }
                }
            }

            if (updated) {
                content = content.trim();
                boolean isEmptyOrBoilerplate = content.isEmpty();
                if (!isEmptyOrBoilerplate && content.startsWith("---")) {
                    int secondTriple = content.indexOf("---", 3);
                    if (secondTriple != -1) {
                        String afterFrontMatter = content.substring(secondTriple + 3).trim();
                        isEmptyOrBoilerplate = afterFrontMatter.isEmpty();
                    }
                }

                if (isEmptyOrBoilerplate) {
                    Files.delete(p);
                    if (writeCache != null) writeCache.invalidate(p);
                } else {
                    Files.writeString(p, content + "\n", StandardCharsets.UTF_8);
                    if (writeCache != null) writeCache.invalidate(p);
                }
            }
        } catch (IOException ignored) {
            // Skip files we can't read
        }
    }

    private void writeContentWithBackup(Path filePath, String finalContent) throws IOException {
        Path tmp = Paths.get(filePath.toString() + ".vibetags-tmp");
        Files.writeString(tmp, finalContent, StandardCharsets.UTF_8);
        try {
            Files.move(tmp, filePath, StandardCopyOption.REPLACE_EXISTING, StandardCopyOption.ATOMIC_MOVE);
        } catch (java.nio.file.AtomicMoveNotSupportedException e) {
            Files.move(tmp, filePath, StandardCopyOption.REPLACE_EXISTING);
        }
    }

    private void skipUpdateMsg(String fileName) {
        String msg = "VibeTags: Skipping update of " + fileName + " (no annotations found in this module, preserving existing rules)";
        messager.printMessage(Diagnostic.Kind.NOTE, msg);
        if (log != null) log.info("Skipping update of {} — no annotations found", fileName);
    }

    private static Messager noopMessager() {
        return new Messager() {
            @Override public void printMessage(Diagnostic.Kind kind, CharSequence msg) {}
            @Override public void printMessage(Diagnostic.Kind kind, CharSequence msg, Element e) {}
            @Override public void printMessage(Diagnostic.Kind kind, CharSequence msg, Element e, AnnotationMirror a) {}
            @Override public void printMessage(Diagnostic.Kind kind, CharSequence msg, Element e, AnnotationMirror a, AnnotationValue v) {}
        };
    }
}
