package se.deversity.vibetags.processor;

import org.junit.jupiter.api.Test;

import java.io.File;
import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;

import static org.junit.jupiter.api.Assertions.*;

/**
 * End-to-end tests that verify the annotation processor works correctly
 * when the example project is compiled.
 * 
 * These tests assume the example project has been compiled with `mvn clean compile`.
 */
class AnnotationProcessorEndToEndTest {

    private static final String EXAMPLE_DIR = "../example";

    @Test
    void testAllGeneratedFilesExist() {
        // These files should exist after compilation
        assertTrue(fileExists(".cursorrules"), ".cursorrules should exist");
        assertTrue(fileExists("CLAUDE.md"), "CLAUDE.md should exist");
        assertTrue(fileExists(".aiexclude"), ".aiexclude should exist");
        assertTrue(fileExists("chatgpt_instructions.md"), "chatgpt_instructions.md should exist");
        assertTrue(fileExists("gemini_instructions.md"), "gemini_instructions.md should exist");
        assertTrue(fileExists(".github/copilot-instructions.md"), ".github/copilot-instructions.md should exist");
    }

    @Test
    void testCursorRulesHasCorrectStructure() throws IOException {
        String content = readFile(".cursorrules");
        
        // Should have header
        assertTrue(content.contains("AUTO-GENERATED AI RULES"));
        assertTrue(content.contains("Do not edit manually"));
        
        // Should have locked files section
        assertTrue(content.contains("LOCKED FILES"));
        
        // Should have contextual rules section
        assertTrue(content.contains("CONTEXTUAL RULES"));
    }

    @Test
    void testCursorRulesHasMandatorySecurityAudits() throws IOException {
        String content = readFile(".cursorrules");
        
        // Should have security audit section from @AIAudit
        assertTrue(content.contains("MANDATORY SECURITY AUDITS"), 
            "Should contain mandatory security audits section");
        assertTrue(content.contains("DatabaseConnector"), 
            "Should mention DatabaseConnector class");
        assertTrue(content.contains("SQL Injection"), 
            "Should mention SQL Injection vulnerability");
        assertTrue(content.contains("Thread Safety"), 
            "Should mention Thread Safety vulnerability");
    }

    @Test
    void testClaudeMdHasCorrectXmlStructure() throws IOException {
        String content = readFile("CLAUDE.md");
        
        // Should have root element
        assertTrue(content.contains("<project_guardrails>"));
        assertTrue(content.contains("</project_guardrails>"));
        
        // Should have locked files section
        assertTrue(content.contains("<locked_files>"));
        assertTrue(content.contains("</locked_files>"));
        
        // Should have contextual instructions
        assertTrue(content.contains("<contextual_instructions>"));
        assertTrue(content.contains("</contextual_instructions>"));
    }

    @Test
    void testClaudeMdHasAuditRequirements() throws IOException {
        String content = readFile("CLAUDE.md");
        
        // Should have audit requirements from @AIAudit
        assertTrue(content.contains("<audit_requirements>"), 
            "Should contain audit requirements section");
        assertTrue(content.contains("DatabaseConnector"), 
            "Should mention DatabaseConnector");
        assertTrue(content.contains("<vulnerability_check>SQL Injection</vulnerability_check>"), 
            "Should have SQL Injection check");
        assertTrue(content.contains("<vulnerability_check>Thread Safety issues</vulnerability_check>"), 
            "Should have Thread Safety check");
        assertTrue(content.contains("<rule>"), 
            "Should have rule element");
    }

    @Test
    void testAiExcludeHasCorrectFormat() throws IOException {
        String content = readFile(".aiexclude");
        
        // Should have header
        assertTrue(content.contains("AUTO-GENERATED BY VIBETAGS"));
        
        // Should have glob patterns
        assertTrue(content.contains("**/"));
        assertTrue(content.contains(".java"));
    }

    @Test
    void testChatGptInstructionsHasSecurityGuardrails() throws IOException {
        String content = readFile("chatgpt_instructions.md");
        
        // Should have project knowledge section
        assertTrue(content.contains("Project Knowledge"));
        
        // Should have locked files
        assertTrue(content.contains("Locked Files"));
        
        // Should have security guardrails from @AIAudit
        assertTrue(content.contains("SECURITY GUARDRAILS"), 
            "Should contain security guardrails section");
        assertTrue(content.contains("DatabaseConnector"), 
            "Should mention DatabaseConnector");
        assertTrue(content.contains("SQL Injection"), 
            "Should mention SQL Injection");
        assertTrue(content.contains("Thread Safety"), 
            "Should mention Thread Safety");
    }

    @Test
    void testGeminiInstructionsHasContinuousAudit() throws IOException {
        String content = readFile("gemini_instructions.md");
        
        // Should have continuous audit requirements
        assertTrue(content.contains("CONTINUOUS AUDIT REQUIREMENTS"), 
            "Should contain continuous audit requirements header");
        assertTrue(content.contains("Senior Staff Engineer"), 
            "Should have Senior Staff Engineer persona");
        assertTrue(content.contains("DatabaseConnector"), 
            "Should mention DatabaseConnector");
        assertTrue(content.contains("SQL Injection"), 
            "Should mention SQL Injection");
        assertTrue(content.contains("Thread Safety"), 
            "Should mention Thread Safety");
    }

    @Test
    void testLockedFilesAppearInAllOutputs() throws IOException {
        // PaymentProcessor should be in all files
        String cursorRules = readFile(".cursorrules");
        String claudeMd = readFile("CLAUDE.md");
        String aiExclude = readFile(".aiexclude");
        String chatGpt = readFile("chatgpt_instructions.md");

        assertTrue(cursorRules.contains("PaymentProcessor"), 
            "Cursor rules should mention PaymentProcessor");
        assertTrue(claudeMd.contains("PaymentProcessor"), 
            "Claude.md should mention PaymentProcessor");
        assertTrue(chatGpt.contains("PaymentProcessor"), 
            "ChatGPT should mention PaymentProcessor");
    }

    @Test
    void testContextFilesHaveFocusAndAvoids() throws IOException {
        String cursorRules = readFile(".cursorrules");
        String claudeMd = readFile("CLAUDE.md");
        String chatGpt = readFile("chatgpt_instructions.md");

        // StringParser should have context rules
        assertTrue(cursorRules.contains("StringParser"));
        assertTrue(cursorRules.contains("memory usage"));
        
        assertTrue(claudeMd.contains("StringParser"));
        assertTrue(claudeMd.contains("<focus>"));
        assertTrue(claudeMd.contains("<avoids>"));
    }

    @Test
    void testSecurityConfigHasBothLockedAndContext() throws IOException {
        String cursorRules = readFile(".cursorrules");
        String claudeMd = readFile("CLAUDE.md");

        // SecurityConfig should appear in both sections
        assertTrue(cursorRules.contains("SecurityConfig"));
        assertTrue(claudeMd.contains("SecurityConfig"));
    }

    @Test
    void testFileContentIsNotEmpty() throws IOException {
        // All generated files should have content
        assertFalse(readFile(".cursorrules").isEmpty());
        assertFalse(readFile("CLAUDE.md").isEmpty());
        assertFalse(readFile(".aiexclude").isEmpty());
        assertFalse(readFile("chatgpt_instructions.md").isEmpty());
        assertFalse(readFile("gemini_instructions.md").isEmpty());
        assertFalse(readFile(".github/copilot-instructions.md").isEmpty());
    }

    @Test
    void testCopilotInstructionsHasCorrectStructure() throws IOException {
        String content = readFile(".github/copilot-instructions.md");

        assertTrue(content.contains("GitHub Copilot Instructions"),
            "Should have Copilot header");
        assertTrue(content.contains("AUTO-GENERATED BY VIBETAGS"),
            "Should have auto-generated marker");
        assertTrue(content.contains("Locked Files"),
            "Should have locked files section");
        assertTrue(content.contains("Contextual Guidelines"),
            "Should have contextual guidelines section");
    }

    @Test
    void testCopilotInstructionsHasLockedFiles() throws IOException {
        String content = readFile(".github/copilot-instructions.md");

        assertTrue(content.contains("PaymentProcessor"),
            "Should mention PaymentProcessor");
    }

    @Test
    void testCopilotInstructionsHasContextualGuidelines() throws IOException {
        String content = readFile(".github/copilot-instructions.md");

        assertTrue(content.contains("memory usage"),
            "Should mention focus from @AIContext");
        assertTrue(content.contains("java.util.regex"),
            "Should mention avoids from @AIContext");
    }

    @Test
    void testCopilotInstructionsHasSecurityAuditRequirements() throws IOException {
        String content = readFile(".github/copilot-instructions.md");

        assertTrue(content.contains("Security Audit Requirements"),
            "Should have security audit section");
        assertTrue(content.contains("DatabaseConnector"),
            "Should mention DatabaseConnector");
        assertTrue(content.contains("SQL Injection"),
            "Should mention SQL Injection");
        assertTrue(content.contains("Thread Safety"),
            "Should mention Thread Safety");
    }

    @Test
    void testCopilotInstructionsHasIgnoredElements() throws IOException {
        String content = readFile(".github/copilot-instructions.md");

        assertTrue(content.contains("Ignored Elements"),
            "Should have ignored elements section");
        assertTrue(content.contains("GeneratedMetadata"),
            "Should mention GeneratedMetadata");
    }

    @Test
    void testAuditChecklistFormatInChatGpt() throws IOException {
        String content = readFile("chatgpt_instructions.md");
        
        // Should have numbered checklist
        assertTrue(content.contains("1."));
        assertTrue(content.contains("Is this code vulnerable to"));
        assertTrue(content.contains("discard your draft and rewrite"));
    }

    @Test
    void testCursorRulesHasIgnoredElementsSection() throws IOException {
        String content = readFile(".cursorrules");
        assertTrue(content.contains("IGNORED ELEMENTS"),
            "Should contain ignored elements section");
        assertTrue(content.contains("GeneratedMetadata"),
            "Should mention GeneratedMetadata class");
    }

    @Test
    void testClaudeMdHasIgnoredElements() throws IOException {
        String content = readFile("CLAUDE.md");
        assertTrue(content.contains("<ignored_elements>"),
            "Should contain ignored_elements XML tag");
        assertTrue(content.contains("GeneratedMetadata"),
            "Should mention GeneratedMetadata");
        assertTrue(content.contains("Treat these as if they do not exist"),
            "Should have ignore rule");
    }

    @Test
    void testAiExcludeContainsIgnoredFile() throws IOException {
        String content = readFile(".aiexclude");
        assertTrue(content.contains("GeneratedMetadata"),
            "Should exclude GeneratedMetadata");
    }

    @Test
    void testChatGptInstructionsHasIgnoredFiles() throws IOException {
        String content = readFile("chatgpt_instructions.md");
        assertTrue(content.contains("Ignored Files"),
            "Should contain Ignored Files section");
        assertTrue(content.contains("GeneratedMetadata"),
            "Should mention GeneratedMetadata");
    }

    @Test
    void testGeminiInstructionsHasIgnoredElements() throws IOException {
        String content = readFile("gemini_instructions.md");
        assertTrue(content.contains("IGNORED ELEMENTS"),
            "Should contain IGNORED ELEMENTS section");
        assertTrue(content.contains("GeneratedMetadata"),
            "Should mention GeneratedMetadata");
    }

    private boolean fileExists(String filename) {
        return new File(EXAMPLE_DIR, filename).exists();
    }

    private String readFile(String filename) throws IOException {
        File file = new File(EXAMPLE_DIR, filename);
        if (!file.exists()) {
            return "";
        }
        return Files.readString(file.toPath(), StandardCharsets.UTF_8);
    }
}
