package se.deversity.vibetags.processor;

import org.junit.jupiter.api.AfterAll;
import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.io.TempDir;

import java.io.IOException;
import java.nio.file.Path;

import static org.junit.jupiter.api.Assertions.*;

/**
 * End-to-end tests that verify the annotation processor generates correct output files.
 * Self-contained: compiles annotated test sources into a {@code @TempDir} via
 * {@link ProcessorTestHarness} — no dependency on the example project.
 */
class AnnotationProcessorEndToEndTest {

    @TempDir
    static Path tempDir;

    private static ProcessorTestHarness harness;

    @BeforeAll
    static void setUp() throws IOException {
        harness = ProcessorTestHarness.withExampleSources(tempDir);
    }

    @AfterAll
    static void tearDown() {
        VibeTagsLogger.shutdown();
    }

    @Test
    void testAllGeneratedFilesExist() {
        assertTrue(harness.fileExists(".cursorrules"), ".cursorrules should exist");
        assertTrue(harness.fileExists("CLAUDE.md"), "CLAUDE.md should exist");
        assertTrue(harness.fileExists(".aiexclude"), ".aiexclude should exist");
        assertTrue(harness.fileExists("AGENTS.md"), "AGENTS.md should exist");
        assertTrue(harness.fileExists(".codex/config.toml"), ".codex/config.toml should exist");
        assertTrue(harness.fileExists(".codex/rules/vibetags.rules"), ".codex/rules/vibetags.rules should exist");
        assertTrue(harness.fileExists("gemini_instructions.md"), "gemini_instructions.md should exist");
        assertTrue(harness.fileExists(".github/copilot-instructions.md"), ".github/copilot-instructions.md should exist");
        assertTrue(harness.fileExists("QWEN.md"), "QWEN.md should exist");
        assertTrue(harness.fileExists(".qwen/settings.json"), ".qwen/settings.json should exist");
        assertTrue(harness.fileExists(".qwen/commands/refactor.md"), ".qwen/commands/refactor.md should exist");
        assertTrue(harness.fileExists(".aiexclude"), ".aiexclude should exist");
        assertTrue(harness.fileExists("llms.txt"), "llms.txt should exist");
        assertTrue(harness.fileExists("llms-full.txt"), "llms-full.txt should exist");
    }

    @Test
    void testCursorRulesHasCorrectStructure() throws IOException {
        String content = harness.readFile(".cursorrules");

        assertTrue(content.contains("AUTO-GENERATED AI RULES"));
        assertTrue(content.contains("Generated by VibeTags |"));
        assertTrue(content.contains("Do not edit manually"));
        assertTrue(content.contains("LOCKED FILES"));
        assertTrue(content.contains("CONTEXTUAL RULES"));
    }

    @Test
    void testCursorRulesHasMandatorySecurityAudits() throws IOException {
        String content = harness.readFile(".cursorrules");

        assertTrue(content.contains("MANDATORY SECURITY AUDITS"),
            "Should contain mandatory security audits section");
        assertTrue(content.contains("DatabaseConnector"),
            "Should mention DatabaseConnector class");
        assertTrue(content.contains("SQL Injection"),
            "Should mention SQL Injection vulnerability");
        assertTrue(content.contains("Thread Safety"),
            "Should mention Thread Safety vulnerability");
    }

    @Test
    void testClaudeMdHasCorrectXmlStructure() throws IOException {
        String content = harness.readFile("CLAUDE.md");

        assertTrue(content.contains("<project_guardrails>"));
        assertTrue(content.contains("</project_guardrails>"));
        assertTrue(content.contains("<locked_files>"));
        assertTrue(content.contains("</locked_files>"));
        assertTrue(content.contains("<contextual_instructions>"));
        assertTrue(content.contains("</contextual_instructions>"));
    }

    @Test
    void testClaudeMdHasAuditRequirements() throws IOException {
        String content = harness.readFile("CLAUDE.md");

        assertTrue(content.contains("<audit_requirements>"),
            "Should contain audit requirements section");
        assertTrue(content.contains("DatabaseConnector"),
            "Should mention DatabaseConnector");
        assertTrue(content.contains("<vulnerability_check>SQL Injection</vulnerability_check>"),
            "Should have SQL Injection check");
        assertTrue(content.contains("<vulnerability_check>Thread Safety issues</vulnerability_check>"),
            "Should have Thread Safety check");
        assertTrue(content.contains("<rule>"),
            "Should have rule element");
    }

    @Test
    void testAiExcludeHasCorrectFormat() throws IOException {
        String content = harness.readFile(".aiexclude");

        assertTrue(content.contains("AUTO-GENERATED BY VIBETAGS"));
        assertTrue(content.contains("**/"));
        assertTrue(content.contains(".java"));
    }

    @Test
    void testCodexAgentsHasSecurityAudits() throws IOException {
        String content = harness.readFile("AGENTS.md");

        assertTrue(content.contains("MANDATORY SECURITY AUDITS"),
            "Should contain mandatory security audits section");
        assertTrue(content.contains("DatabaseConnector"),
            "Should mention DatabaseConnector class");
        assertTrue(content.contains("SQL Injection"),
            "Should mention SQL Injection vulnerability");
        assertTrue(content.contains("Thread Safety"),
            "Should mention Thread Safety vulnerability");
    }

    @Test
    void testGeminiInstructionsHasContinuousAudit() throws IOException {
        String content = harness.readFile("gemini_instructions.md");

        assertTrue(content.contains("CONTINUOUS AUDIT REQUIREMENTS"),
            "Should contain continuous audit requirements header");
        assertTrue(content.contains("Senior Staff Engineer"),
            "Should have Senior Staff Engineer persona");
        assertTrue(content.contains("DatabaseConnector"),
            "Should mention DatabaseConnector");
        assertTrue(content.contains("SQL Injection"),
            "Should mention SQL Injection");
        assertTrue(content.contains("Thread Safety"),
            "Should mention Thread Safety");
    }

    @Test
    void testGeminiInstructionsHasLockedFiles() throws IOException {
        String content = harness.readFile("gemini_instructions.md");

        assertTrue(content.contains("LOCKED FILES"),
            "gemini_instructions.md should contain a LOCKED FILES section");
        assertTrue(content.contains("PaymentProcessor"),
            "gemini_instructions.md should mention @AILocked PaymentProcessor");
    }

    @Test
    void testGeminiInstructionsHasContextRules() throws IOException {
        String content = harness.readFile("gemini_instructions.md");

        assertTrue(content.contains("CONTEXTUAL RULES"),
            "gemini_instructions.md should contain a CONTEXTUAL RULES section");
        assertTrue(content.contains("StringParser"),
            "gemini_instructions.md should mention @AIContext StringParser");
    }

    @Test
    void testLockedFilesAppearInAllOutputs() throws IOException {
        String cursorRules = harness.readFile(".cursorrules");
        String claudeMd = harness.readFile("CLAUDE.md");
        String codexAgents = harness.readFile("AGENTS.md");

        assertTrue(cursorRules.contains("PaymentProcessor"),
            "Cursor rules should mention PaymentProcessor");
        assertTrue(claudeMd.contains("PaymentProcessor"),
            "Claude.md should mention PaymentProcessor");
        assertTrue(codexAgents.contains("PaymentProcessor"),
            "Codex AGENTS.md should mention PaymentProcessor");
    }

    @Test
    void testContextFilesHaveFocusAndAvoids() throws IOException {
        String cursorRules = harness.readFile(".cursorrules");
        String claudeMd = harness.readFile("CLAUDE.md");

        assertTrue(cursorRules.contains("StringParser"));
        assertTrue(cursorRules.contains("memory usage"));
        assertTrue(claudeMd.contains("StringParser"));
        assertTrue(claudeMd.contains("<focus>"));
        assertTrue(claudeMd.contains("<avoids>"));
    }

    @Test
    void testSecurityConfigHasBothLockedAndContext() throws IOException {
        String cursorRules = harness.readFile(".cursorrules");
        String claudeMd = harness.readFile("CLAUDE.md");

        assertTrue(cursorRules.contains("SecurityConfig"));
        assertTrue(claudeMd.contains("SecurityConfig"));
    }

    @Test
    void testFileContentIsNotEmpty() throws IOException {
        assertFalse(harness.readFile(".cursorrules").isEmpty());
        assertFalse(harness.readFile("CLAUDE.md").isEmpty());
        assertFalse(harness.readFile(".aiexclude").isEmpty());
        assertFalse(harness.readFile("AGENTS.md").isEmpty());
        assertFalse(harness.readFile(".codex/config.toml").isEmpty());
        assertFalse(harness.readFile(".codex/rules/vibetags.rules").isEmpty());
        assertFalse(harness.readFile("gemini_instructions.md").isEmpty());
        assertFalse(harness.readFile(".github/copilot-instructions.md").isEmpty());
    }

    @Test
    void testCopilotInstructionsHasCorrectStructure() throws IOException {
        String content = harness.readFile(".github/copilot-instructions.md");

        assertTrue(content.contains("GitHub Copilot Instructions"),
            "Should have Copilot header");
        assertTrue(content.contains("AUTO-GENERATED BY VIBETAGS"),
            "Should have auto-generated marker");
        assertTrue(content.contains("Locked Files"),
            "Should have locked files section");
        assertTrue(content.contains("Contextual Guidelines"),
            "Should have contextual guidelines section");
    }

    @Test
    void testCopilotInstructionsHasLockedFiles() throws IOException {
        String content = harness.readFile(".github/copilot-instructions.md");

        assertTrue(content.contains("PaymentProcessor"),
            "Should mention PaymentProcessor");
    }

    @Test
    void testCopilotInstructionsHasContextualGuidelines() throws IOException {
        String content = harness.readFile(".github/copilot-instructions.md");

        assertTrue(content.contains("memory usage"),
            "Should mention focus from @AIContext");
        assertTrue(content.contains("java.util.regex"),
            "Should mention avoids from @AIContext");
    }

    @Test
    void testCopilotInstructionsHasSecurityAuditRequirements() throws IOException {
        String content = harness.readFile(".github/copilot-instructions.md");

        assertTrue(content.contains("Security Audit Requirements"),
            "Should have security audit section");
        assertTrue(content.contains("DatabaseConnector"),
            "Should mention DatabaseConnector");
        assertTrue(content.contains("SQL Injection"),
            "Should mention SQL Injection");
        assertTrue(content.contains("Thread Safety"),
            "Should mention Thread Safety");
    }

    @Test
    void testCopilotInstructionsHasIgnoredElements() throws IOException {
        String content = harness.readFile(".github/copilot-instructions.md");

        assertTrue(content.contains("Ignored Elements"),
            "Should have ignored elements section");
        assertTrue(content.contains("GeneratedMetadata"),
            "Should mention GeneratedMetadata");
    }

    @Test
    void testCodexConfigHasCorrectSettings() throws IOException {
        String content = harness.readFile(".codex/config.toml");
        assertTrue(content.contains("model = \"o3-mini\""));
        assertTrue(content.contains("approval_policy = \"on-request\""));
    }

    @Test
    void testAIDraftImplementationTasksExist() throws IOException {
        String cursorRules = harness.readFile(".cursorrules");
        String claudeMd = harness.readFile("CLAUDE.md");

        assertTrue(cursorRules.contains("IMPLEMENTATION TASKS"), "Should have implementation tasks section");
        assertTrue(cursorRules.contains("NotificationService"), "Should mention NotificationService (Draft)");
        assertTrue(cursorRules.contains("Implement email sending"), "Should have instructions");

        assertTrue(claudeMd.contains("<implementation_tasks>"), "Should have implementation tasks XML");
        assertTrue(claudeMd.contains("NotificationService"), "Should mention NotificationService");
    }

    @Test
    void testVersionStampInLogFile() throws IOException {
        String logContent = harness.readFile("vibetags.log");
        assertTrue(logContent.contains(AIGuardrailProcessor.VERSION),
            "vibetags.log should contain the VibeTags version");
        assertTrue(logContent.contains("github.com/PIsberg/vibetags"),
            "vibetags.log should contain the GitHub URL");
    }

    @Test
    void testAttributionHeaderInAllFiles() throws IOException {
        String attribution = "Generated by VibeTags |";
        assertTrue(harness.readFile(".cursorrules").contains(attribution));
        assertTrue(harness.readFile("CLAUDE.md").contains(attribution));
        assertTrue(harness.readFile(".aiexclude").contains(attribution));
        assertTrue(harness.readFile("AGENTS.md").contains(attribution));
        assertTrue(harness.readFile("gemini_instructions.md").contains(attribution));
        assertTrue(harness.readFile(".github/copilot-instructions.md").contains(attribution));
    }

    @Test
    void testCodexRulesHasStarlarkContent() throws IOException {
        String content = harness.readFile(".codex/rules/vibetags.rules");
        assertTrue(content.contains("prefix_rule(\"mvn\", \"prompt\")"));
        assertTrue(content.contains("prefix_rule(\"ls\", \"allow\")"));
    }

    @Test
    void testCursorRulesHasIgnoredElementsSection() throws IOException {
        String content = harness.readFile(".cursorrules");
        assertTrue(content.contains("IGNORED ELEMENTS"),
            "Should contain ignored elements section");
        assertTrue(content.contains("GeneratedMetadata"),
            "Should mention GeneratedMetadata class");
    }

    @Test
    void testClaudeMdHasIgnoredElements() throws IOException {
        String content = harness.readFile("CLAUDE.md");
        assertTrue(content.contains("<ignored_elements>"),
            "Should contain ignored_elements XML tag");
        assertTrue(content.contains("GeneratedMetadata"),
            "Should mention GeneratedMetadata");
        assertTrue(content.contains("Treat these as if they do not exist"),
            "Should have ignore rule");
    }

    @Test
    void testAiExcludeContainsIgnoredFile() throws IOException {
        String content = harness.readFile(".aiexclude");
        assertTrue(content.contains("GeneratedMetadata"),
            "Should exclude GeneratedMetadata");
    }

    @Test
    void testCodexAgentsHasIgnoredFiles() throws IOException {
        String content = harness.readFile("AGENTS.md");
        assertTrue(content.contains("IGNORED ELEMENTS"),
            "Should contain Ignored Elements section");
        assertTrue(content.contains("GeneratedMetadata"),
            "Should mention GeneratedMetadata");
    }

    @Test
    void testGeminiInstructionsHasIgnoredElements() throws IOException {
        String content = harness.readFile("gemini_instructions.md");
        assertTrue(content.contains("IGNORED ELEMENTS"),
            "Should contain IGNORED ELEMENTS section");
        assertTrue(content.contains("GeneratedMetadata"),
            "Should mention GeneratedMetadata");
    }

    @Test
    void testQwenMdHasCorrectStructure() throws IOException {
        String content = harness.readFile("QWEN.md");
        assertTrue(content.contains("PROJECT CONTEXT"), "Should have Qwen header");
        assertTrue(content.contains("LOCKED FILES"), "Should have locked files section");
        assertTrue(content.contains("CONTEXTUAL RULES"), "Should have contextual rules section");
        assertTrue(content.contains("MANDATORY SECURITY AUDITS"), "Should have audit section");
        assertTrue(content.contains("IGNORED ELEMENTS"), "Should have ignored elements section");
    }

    @Test
    void testQwenSettingsHasCorrectFormat() throws IOException {
        String content = harness.readFile(".qwen/settings.json");
        assertTrue(content.contains("\"model\": \"qwen3-coder-plus\""), "Should specify Qwen model");
        assertTrue(content.contains("\"mcp\": {"), "Should have MCP settings");
    }

    // -----------------------------------------------------------------------
    // llms.txt tests
    // -----------------------------------------------------------------------

    @Test
    void testLlmsTxtHasCorrectStructure() throws IOException {
        String content = harness.readFile("llms.txt");

        assertTrue(content.contains("## Locked Files"),
            "llms.txt should have a Locked Files section");
        assertTrue(content.contains("## Contextual Rules"),
            "llms.txt should have a Contextual Rules section");
        assertTrue(content.contains("## Security Audit Requirements"),
            "llms.txt should have a Security Audit Requirements section");
        assertTrue(content.contains("## Ignored Elements"),
            "llms.txt should have an Ignored Elements section");
        assertTrue(content.contains("## Implementation Tasks"),
            "llms.txt should have an Implementation Tasks section");
        assertTrue(content.contains("## PII / Privacy Guardrails"),
            "llms.txt should have a PII / Privacy Guardrails section");
    }

    @Test
    void testLlmsTxtHasSummaryBlockquote() throws IOException {
        String content = harness.readFile("llms.txt");

        assertTrue(content.contains("> AI guardrail rules generated from source annotations by VibeTags."),
            "llms.txt should contain a summary blockquote");
    }

    @Test
    void testLlmsTxtHasLockedFilesAsLinks() throws IOException {
        String content = harness.readFile("llms.txt");

        assertTrue(content.contains("[PaymentProcessor]"),
            "llms.txt should list PaymentProcessor as a link");
        assertTrue(content.contains("[SecurityConfig]"),
            "llms.txt should list SecurityConfig as a link");
    }

    @Test
    void testLlmsTxtHasAuditEntries() throws IOException {
        String content = harness.readFile("llms.txt");

        assertTrue(content.contains("[DatabaseConnector]"),
            "llms.txt should reference DatabaseConnector in audit section");
        assertTrue(content.contains("SQL Injection"),
            "llms.txt should mention SQL Injection");
        assertTrue(content.contains("Thread Safety"),
            "llms.txt should mention Thread Safety");
    }

    @Test
    void testLlmsTxtHasIgnoredElements() throws IOException {
        String content = harness.readFile("llms.txt");

        assertTrue(content.contains("[GeneratedMetadata]"),
            "llms.txt should reference GeneratedMetadata in ignored elements");
        assertTrue(content.contains("excluded from AI context"),
            "llms.txt should state elements are excluded from AI context");
    }

    @Test
    void testLlmsTxtHasPrivacyEntries() throws IOException {
        String content = harness.readFile("llms.txt");

        assertTrue(content.contains("## PII / Privacy Guardrails"),
            "llms.txt should have a PII section");
    }

    @Test
    void testLlmsTxtHasImplementationTaskLinks() throws IOException {
        String content = harness.readFile("llms.txt");

        assertTrue(content.contains("[NotificationService]") || content.contains("NotificationService"),
            "llms.txt should reference NotificationService draft tasks");
    }

    // -----------------------------------------------------------------------
    // llms-full.txt tests
    // -----------------------------------------------------------------------

    @Test
    void testLlmsFullTxtHasCorrectStructure() throws IOException {
        String content = harness.readFile("llms-full.txt");

        assertTrue(content.contains("## Locked Files (Do Not Edit)"),
            "llms-full.txt should have expanded Locked Files header");
        assertTrue(content.contains("## Contextual Rules"),
            "llms-full.txt should have Contextual Rules section");
        assertTrue(content.contains("## Mandatory Security Audit Requirements"),
            "llms-full.txt should have Mandatory Security Audit Requirements");
        assertTrue(content.contains("## Ignored Elements"),
            "llms-full.txt should have Ignored Elements section");
        assertTrue(content.contains("## Implementation Tasks"),
            "llms-full.txt should have Implementation Tasks section");
        assertTrue(content.contains("## PII / Privacy Guardrails"),
            "llms-full.txt should have PII / Privacy Guardrails section");
    }

    @Test
    void testLlmsFullTxtHasSummaryBlockquote() throws IOException {
        String content = harness.readFile("llms-full.txt");

        assertTrue(content.contains("> Complete AI guardrail configuration generated from source annotations by VibeTags"),
            "llms-full.txt should contain a summary blockquote mentioning VibeTags");
        assertTrue(content.contains("Windsurf") || content.contains("Claude 4.6") || content.contains("Gemini"),
            "llms-full.txt should mention large-context LLMs");
    }

    @Test
    void testLlmsFullTxtHasNoVersionStamp() throws IOException {
        String content = harness.readFile("llms-full.txt");
        assertFalse(content.contains("v1.0.0-SNAPSHOT"),
            "llms-full.txt should NOT embed the version — check vibetags.log instead");
    }

    @Test
    void testLlmsFullTxtHasLockedFilesWithReasons() throws IOException {
        String content = harness.readFile("llms-full.txt");

        assertTrue(content.contains("PaymentProcessor"),
            "llms-full.txt should mention PaymentProcessor");
        assertTrue(content.contains("**Reason**"),
            "llms-full.txt should use bold Reason labels");
        assertTrue(content.contains("SecurityConfig"),
            "llms-full.txt should mention SecurityConfig");
    }

    @Test
    void testLlmsFullTxtHasAuditRequirements() throws IOException {
        String content = harness.readFile("llms-full.txt");

        assertTrue(content.contains("DatabaseConnector"),
            "llms-full.txt should mention DatabaseConnector");
        assertTrue(content.contains("**Required Checks**"),
            "llms-full.txt should use bold Required Checks labels");
        assertTrue(content.contains("SQL Injection"),
            "llms-full.txt should list SQL Injection");
        assertTrue(content.contains("Thread Safety"),
            "llms-full.txt should list Thread Safety");
    }

    @Test
    void testLlmsFullTxtHasIgnoredElementsWithDetail() throws IOException {
        String content = harness.readFile("llms-full.txt");

        assertTrue(content.contains("GeneratedMetadata"),
            "llms-full.txt should mention GeneratedMetadata in ignored elements");
        assertTrue(content.contains("Treat them as non-existent"),
            "llms-full.txt should explain the ignore semantics");
    }

    @Test
    void testLlmsFullTxtHasContextualRulesWithFocusAndAvoid() throws IOException {
        String content = harness.readFile("llms-full.txt");

        assertTrue(content.contains("**Focus**"),
            "llms-full.txt should use bold Focus labels");
        assertTrue(content.contains("**Avoid**"),
            "llms-full.txt should use bold Avoid labels");
        assertTrue(content.contains("memory usage"),
            "llms-full.txt should contain StringParser focus");
    }

    @Test
    void testLlmsFullTxtHasDraftInstructions() throws IOException {
        String content = harness.readFile("llms-full.txt");

        assertTrue(content.contains("**Instructions**"),
            "llms-full.txt should use bold Instructions labels");
        assertTrue(content.contains("NotificationService"),
            "llms-full.txt should mention NotificationService");
    }

    @Test
    void testLlmsTxtAppearInAllLockedOutputs() throws IOException {
        String llmsTxt = harness.readFile("llms.txt");
        String llmsFullTxt = harness.readFile("llms-full.txt");

        assertTrue(llmsTxt.contains("PaymentProcessor"),
            "llms.txt should mention PaymentProcessor");
        assertTrue(llmsFullTxt.contains("PaymentProcessor"),
            "llms-full.txt should mention PaymentProcessor");
    }

    // -----------------------------------------------------------------------
    // @AIDraft — Qwen coverage (was missing)
    // -----------------------------------------------------------------------

    @Test
    void testQwenGetsDraftInstructions() throws IOException {
        String content = harness.readFile("QWEN.md");
        assertTrue(content.contains("NotificationService"),
            "QWEN.md must include @AIDraft NotificationService");
        assertTrue(content.contains("IMPLEMENTATION TASKS"),
            "QWEN.md must have an IMPLEMENTATION TASKS section");
    }

    // -----------------------------------------------------------------------
    // @AICore — all platform coverage (was missing from all platform files)
    // -----------------------------------------------------------------------

    @Test
    void testAICoreAppearsInCursorRules() throws IOException {
        String content = harness.readFile(".cursorrules");
        assertTrue(content.contains("CriticalService"), ".cursorrules must mention @AICore CriticalService");
        assertTrue(content.contains("CORE FUNCTIONALITY"), ".cursorrules must have a CORE FUNCTIONALITY section");
    }

    @Test
    void testAICoreAppearsInClaudeMd() throws IOException {
        String content = harness.readFile("CLAUDE.md");
        assertTrue(content.contains("CriticalService"), "CLAUDE.md must mention @AICore CriticalService");
        assertTrue(content.contains("core_elements"), "CLAUDE.md must have <core_elements> XML block");
    }

    @Test
    void testAICoreAppearsInGemini() throws IOException {
        String content = harness.readFile("gemini_instructions.md");
        assertTrue(content.contains("CriticalService"), "gemini must mention @AICore CriticalService");
        assertTrue(content.contains("CORE FUNCTIONALITY"), "gemini must have CORE FUNCTIONALITY section");
    }

    @Test
    void testAICoreAppearsInQwen() throws IOException {
        String content = harness.readFile("QWEN.md");
        assertTrue(content.contains("CriticalService"), "QWEN.md must mention @AICore CriticalService");
        assertTrue(content.contains("CORE FUNCTIONALITY"), "QWEN.md must have a CORE FUNCTIONALITY section");
    }

    @Test
    void testAICoreAppearsInCodex() throws IOException {
        String content = harness.readFile("AGENTS.md");
        assertTrue(content.contains("CriticalService"), "AGENTS.md must mention @AICore CriticalService");
        assertTrue(content.contains("CORE FUNCTIONALITY"), "AGENTS.md must have a CORE FUNCTIONALITY section");
    }

    @Test
    void testAICoreAppearsInCopilot() throws IOException {
        String content = harness.readFile(".github/copilot-instructions.md");
        assertTrue(content.contains("CriticalService"), "copilot-instructions must mention @AICore CriticalService");
        assertTrue(content.contains("Core Functionality"), "copilot-instructions must have Core Functionality section");
    }

    // -----------------------------------------------------------------------
    // @AIPerformance — all platform coverage (was missing from all platform files)
    // -----------------------------------------------------------------------

    @Test
    void testAIPerformanceAppearsInCursorRules() throws IOException {
        String content = harness.readFile(".cursorrules");
        assertTrue(content.contains("HotPathRouter"), ".cursorrules must mention @AIPerformance HotPathRouter");
        assertTrue(content.contains("PERFORMANCE CONSTRAINTS"), ".cursorrules must have PERFORMANCE CONSTRAINTS section");
    }

    @Test
    void testAIPerformanceAppearsInClaudeMd() throws IOException {
        String content = harness.readFile("CLAUDE.md");
        assertTrue(content.contains("HotPathRouter"), "CLAUDE.md must mention @AIPerformance HotPathRouter");
        assertTrue(content.contains("performance_constraints"), "CLAUDE.md must have <performance_constraints> XML block");
    }

    @Test
    void testAIPerformanceAppearsInGemini() throws IOException {
        String content = harness.readFile("gemini_instructions.md");
        assertTrue(content.contains("HotPathRouter"), "gemini must mention @AIPerformance HotPathRouter");
        assertTrue(content.contains("PERFORMANCE CONSTRAINTS"), "gemini must have PERFORMANCE CONSTRAINTS section");
    }

    @Test
    void testAIPerformanceAppearsInQwen() throws IOException {
        String content = harness.readFile("QWEN.md");
        assertTrue(content.contains("HotPathRouter"), "QWEN.md must mention @AIPerformance HotPathRouter");
        assertTrue(content.contains("PERFORMANCE CONSTRAINTS"), "QWEN.md must have PERFORMANCE CONSTRAINTS section");
    }

    @Test
    void testAIPerformanceAppearsInCodex() throws IOException {
        String content = harness.readFile("AGENTS.md");
        assertTrue(content.contains("HotPathRouter"), "AGENTS.md must mention @AIPerformance HotPathRouter");
        assertTrue(content.contains("PERFORMANCE CONSTRAINTS"), "AGENTS.md must have PERFORMANCE CONSTRAINTS section");
    }

    @Test
    void testAIPerformanceAppearsInCopilot() throws IOException {
        String content = harness.readFile(".github/copilot-instructions.md");
        assertTrue(content.contains("HotPathRouter"), "copilot-instructions must mention @AIPerformance HotPathRouter");
        assertTrue(content.contains("Performance Constraints"), "copilot-instructions must have Performance Constraints section");
    }

    // -----------------------------------------------------------------------
    // @AICore — llms.txt / llms-full.txt coverage
    // -----------------------------------------------------------------------

    @Test
    void testLlmsTxtHasCoreSection() throws IOException {
        String content = harness.readFile("llms.txt");
        assertTrue(content.contains("## 🧠 Core Functionality"),
            "llms.txt must have a Core Functionality section for @AICore elements");
        assertTrue(content.contains("CriticalService"),
            "llms.txt must list the @AICore CriticalService");
    }

    @Test
    void testLlmsFullTxtHasCoreSection() throws IOException {
        String content = harness.readFile("llms-full.txt");
        assertTrue(content.contains("## 🧠 Core Functionality"),
            "llms-full.txt must have a Core Functionality section");
        assertTrue(content.contains("CriticalService"),
            "llms-full.txt must list the @AICore CriticalService");
        assertTrue(content.contains("**Sensitivity**"),
            "llms-full.txt must use bold Sensitivity label for @AICore");
        assertTrue(content.contains("**Note**"),
            "llms-full.txt must use bold Note label for @AICore");
    }

    // -----------------------------------------------------------------------
    // @AIPerformance — llms.txt / llms-full.txt coverage
    // -----------------------------------------------------------------------

    @Test
    void testLlmsTxtHasPerformanceSection() throws IOException {
        String content = harness.readFile("llms.txt");
        assertTrue(content.contains("## ⚡ Performance Constraints"),
            "llms.txt must have a Performance Constraints section for @AIPerformance elements");
        assertTrue(content.contains("HotPathRouter"),
            "llms.txt must list the @AIPerformance HotPathRouter");
    }

    @Test
    void testLlmsFullTxtHasPerformanceSection() throws IOException {
        String content = harness.readFile("llms-full.txt");
        assertTrue(content.contains("## ⚡ Performance Constraints"),
            "llms-full.txt must have a Performance Constraints section");
        assertTrue(content.contains("HotPathRouter"),
            "llms-full.txt must list the @AIPerformance HotPathRouter");
        assertTrue(content.contains("**Constraint**"),
            "llms-full.txt must use bold Constraint label for @AIPerformance");
    }

    // -----------------------------------------------------------------------
    // Aider (CONVENTIONS.md / .aiderignore) coverage
    // -----------------------------------------------------------------------

    @Test
    void testAiderFilesGenerated() {
        assertTrue(harness.fileExists("CONVENTIONS.md"), "CONVENTIONS.md should be generated");
        assertTrue(harness.fileExists(".aiderignore"), ".aiderignore should be generated");
    }

    @Test
    void testAiderConventionsHasLockedContent() throws IOException {
        String content = harness.readFile("CONVENTIONS.md");
        assertTrue(content.contains("PaymentProcessor"),
            "CONVENTIONS.md must include @AILocked PaymentProcessor");
        assertTrue(content.contains("LOCKED"),
            "CONVENTIONS.md must have a LOCKED section");
    }

    @Test
    void testAiderConventionsHasCoreContent() throws IOException {
        String content = harness.readFile("CONVENTIONS.md");
        assertTrue(content.contains("CriticalService"),
            "CONVENTIONS.md must include @AICore CriticalService");
        assertTrue(content.contains("CORE FUNCTIONALITY"),
            "CONVENTIONS.md must have a CORE FUNCTIONALITY section");
        assertTrue(content.contains("**Sensitivity**"),
            "CONVENTIONS.md must use bold Sensitivity label");
    }

    @Test
    void testAiderConventionsHasPerformanceContent() throws IOException {
        String content = harness.readFile("CONVENTIONS.md");
        assertTrue(content.contains("HotPathRouter"),
            "CONVENTIONS.md must include @AIPerformance HotPathRouter");
        assertTrue(content.contains("PERFORMANCE CONSTRAINTS"),
            "CONVENTIONS.md must have a PERFORMANCE CONSTRAINTS section");
        assertTrue(content.contains("**Constraint**"),
            "CONVENTIONS.md must use bold Constraint label");
    }

    @Test
    void testAiderIgnoreHasIgnoredPattern() throws IOException {
        String content = harness.readFile(".aiderignore");
        assertTrue(content.contains("GeneratedMetadata"),
            ".aiderignore must contain the @AIIgnore GeneratedMetadata glob pattern");
        assertTrue(content.contains(".java"),
            ".aiderignore patterns should be .java file globs");
    }

    @Test
    void testAiderConventionsHasAuditContent() throws IOException {
        String content = harness.readFile("CONVENTIONS.md");
        assertTrue(content.contains("DatabaseConnector"),
            "CONVENTIONS.md must include @AIAudit DatabaseConnector");
        assertTrue(content.contains("SECURITY AUDIT"),
            "CONVENTIONS.md must have a SECURITY AUDIT section");
    }

    // -----------------------------------------------------------------------
    // Multi-round accumulation
    // -----------------------------------------------------------------------

    @Test
    void testAllAnnotationTypesRepresentedInOutputs() throws IOException {
        // Verify every annotation type contributed content to at least one output
        String cursor = harness.readFile(".cursorrules");
        assertTrue(cursor.contains("PaymentProcessor"),  "@AILocked must appear");
        assertTrue(cursor.contains("memory usage"),      "@AIContext must appear");
        assertTrue(cursor.contains("IMPLEMENTATION TASKS"), "@AIDraft must appear");
        assertTrue(cursor.contains("SQL Injection"),     "@AIAudit must appear");
        assertTrue(cursor.contains("GeneratedMetadata"), "@AIIgnore must appear");
        assertTrue(cursor.contains("PII"),               "@AIPrivacy must appear");
        assertTrue(cursor.contains("CORE FUNCTIONALITY"), "@AICore must appear");
        assertTrue(cursor.contains("PERFORMANCE CONSTRAINTS"), "@AIPerformance must appear");
    }
}
