package se.deversity.vibetags.processor;

import org.junit.jupiter.api.Test;

import java.io.File;
import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;

import static org.junit.jupiter.api.Assertions.*;

/**
 * End-to-end tests that verify the annotation processor works correctly
 * when the example project is compiled.
 * 
 * These tests assume the example project has been compiled with `mvn clean compile`.
 */
class AnnotationProcessorEndToEndTest {

    private static final String EXAMPLE_DIR;
    
    static {
        // Find example dir relative to working directory
        // In Maven, working dir is usually vibetags/vibetags/
        // In IDE/Root, working dir is usually vibetags/
        File standard = new File("../example");
        File rootRelative = new File("example");
        
        if (standard.exists() && standard.isDirectory()) {
            EXAMPLE_DIR = "../example";
        } else if (rootRelative.exists() && rootRelative.isDirectory()) {
            EXAMPLE_DIR = "example";
        } else {
            // Fallback for CI or other environments
            EXAMPLE_DIR = "example"; 
        }
    }

    @Test
    void testAllGeneratedFilesExist() {
        // These files should exist after compilation
        assertTrue(fileExists(".cursorrules"), ".cursorrules should exist");
        assertTrue(fileExists("CLAUDE.md"), "CLAUDE.md should exist");
        assertTrue(fileExists(".aiexclude"), ".aiexclude should exist");
        assertTrue(fileExists("AGENTS.md"), "AGENTS.md should exist");
        assertTrue(fileExists(".codex/config.toml"), ".codex/config.toml should exist");
        assertTrue(fileExists(".codex/rules/vibetags.rules"), ".codex/rules/vibetags.rules should exist");
        assertTrue(fileExists("gemini_instructions.md"), "gemini_instructions.md should exist");
        assertTrue(fileExists(".github/copilot-instructions.md"), ".github/copilot-instructions.md should exist");
        assertTrue(fileExists("QWEN.md"), "QWEN.md should exist");
        assertTrue(fileExists(".qwen/settings.json"), ".qwen/settings.json should exist");
        assertTrue(fileExists(".qwen/commands/refactor.md"), ".qwen/commands/refactor.md should exist");
        // .cursorignore, .copilotignore, .claudeignore, .qwenignore are opt-in, so they might not exist unless created
        // But .aiexclude is now always generated (if gemini/codex active in test context)
        assertTrue(fileExists(".aiexclude"), ".aiexclude should exist");
    }

    @Test
    void testCursorRulesHasCorrectStructure() throws IOException {
        String content = readFile(".cursorrules");
        
        // Should have header
        assertTrue(content.contains("AUTO-GENERATED AI RULES"));
        assertTrue(content.contains("Generated by VibeTags v1.0.0-SNAPSHOT"));
        assertTrue(content.contains("Do not edit manually"));
        
        // Should have locked files section
        assertTrue(content.contains("LOCKED FILES"));
        
        // Should have contextual rules section
        assertTrue(content.contains("CONTEXTUAL RULES"));
    }

    @Test
    void testCursorRulesHasMandatorySecurityAudits() throws IOException {
        String content = readFile(".cursorrules");
        
        // Should have security audit section from @AIAudit
        assertTrue(content.contains("MANDATORY SECURITY AUDITS"), 
            "Should contain mandatory security audits section");
        assertTrue(content.contains("DatabaseConnector"), 
            "Should mention DatabaseConnector class");
        assertTrue(content.contains("SQL Injection"), 
            "Should mention SQL Injection vulnerability");
        assertTrue(content.contains("Thread Safety"), 
            "Should mention Thread Safety vulnerability");
    }

    @Test
    void testClaudeMdHasCorrectXmlStructure() throws IOException {
        String content = readFile("CLAUDE.md");
        
        // Should have root element
        assertTrue(content.contains("<project_guardrails>"));
        assertTrue(content.contains("</project_guardrails>"));
        
        // Should have locked files section
        assertTrue(content.contains("<locked_files>"));
        assertTrue(content.contains("</locked_files>"));
        
        // Should have contextual instructions
        assertTrue(content.contains("<contextual_instructions>"));
        assertTrue(content.contains("</contextual_instructions>"));
    }

    @Test
    void testClaudeMdHasAuditRequirements() throws IOException {
        String content = readFile("CLAUDE.md");
        
        // Should have audit requirements from @AIAudit
        assertTrue(content.contains("<audit_requirements>"), 
            "Should contain audit requirements section");
        assertTrue(content.contains("DatabaseConnector"), 
            "Should mention DatabaseConnector");
        assertTrue(content.contains("<vulnerability_check>SQL Injection</vulnerability_check>"), 
            "Should have SQL Injection check");
        assertTrue(content.contains("<vulnerability_check>Thread Safety issues</vulnerability_check>"), 
            "Should have Thread Safety check");
        assertTrue(content.contains("<rule>"), 
            "Should have rule element");
    }

    @Test
    void testAiExcludeHasCorrectFormat() throws IOException {
        String content = readFile(".aiexclude");
        
        // Should have header
        assertTrue(content.contains("AUTO-GENERATED BY VIBETAGS"));
        
        // Should have glob patterns
        assertTrue(content.contains("**/"));
        assertTrue(content.contains(".java"));
    }

    @Test
    void testCodexAgentsHasSecurityAudits() throws IOException {
        String content = readFile("AGENTS.md");
        
        // Should have security audit section from @AIAudit
        assertTrue(content.contains("MANDATORY SECURITY AUDITS"), 
            "Should contain mandatory security audits section");
        assertTrue(content.contains("DatabaseConnector"), 
            "Should mention DatabaseConnector class");
        assertTrue(content.contains("SQL Injection"), 
            "Should mention SQL Injection vulnerability");
        assertTrue(content.contains("Thread Safety"), 
            "Should mention Thread Safety vulnerability");
    }

    @Test
    void testGeminiInstructionsHasContinuousAudit() throws IOException {
        String content = readFile("gemini_instructions.md");
        
        // Should have continuous audit requirements
        assertTrue(content.contains("CONTINUOUS AUDIT REQUIREMENTS"), 
            "Should contain continuous audit requirements header");
        assertTrue(content.contains("Senior Staff Engineer"), 
            "Should have Senior Staff Engineer persona");
        assertTrue(content.contains("DatabaseConnector"), 
            "Should mention DatabaseConnector");
        assertTrue(content.contains("SQL Injection"), 
            "Should mention SQL Injection");
        assertTrue(content.contains("Thread Safety"), 
            "Should mention Thread Safety");
    }

    @Test
    void testLockedFilesAppearInAllOutputs() throws IOException {
        // PaymentProcessor should be in all files
        String cursorRules = readFile(".cursorrules");
        String claudeMd = readFile("CLAUDE.md");
        String codexAgents = readFile("AGENTS.md");

        assertTrue(cursorRules.contains("PaymentProcessor"), 
            "Cursor rules should mention PaymentProcessor");
        assertTrue(claudeMd.contains("PaymentProcessor"), 
            "Claude.md should mention PaymentProcessor");
        assertTrue(codexAgents.contains("PaymentProcessor"), 
            "Codex AGENTS.md should mention PaymentProcessor");
    }

    @Test
    void testContextFilesHaveFocusAndAvoids() throws IOException {
        String cursorRules = readFile(".cursorrules");
        String claudeMd = readFile("CLAUDE.md");
        String codexAgents = readFile("AGENTS.md");

        // StringParser should have context rules
        assertTrue(cursorRules.contains("StringParser"));
        assertTrue(cursorRules.contains("memory usage"));
        
        assertTrue(claudeMd.contains("StringParser"));
        assertTrue(claudeMd.contains("<focus>"));
        assertTrue(claudeMd.contains("<avoids>"));
    }

    @Test
    void testSecurityConfigHasBothLockedAndContext() throws IOException {
        String cursorRules = readFile(".cursorrules");
        String claudeMd = readFile("CLAUDE.md");

        // SecurityConfig should appear in both sections
        assertTrue(cursorRules.contains("SecurityConfig"));
        assertTrue(claudeMd.contains("SecurityConfig"));
    }

    @Test
    void testFileContentIsNotEmpty() throws IOException {
        // All generated files should have content
        assertFalse(readFile(".cursorrules").isEmpty());
        assertFalse(readFile("CLAUDE.md").isEmpty());
        assertFalse(readFile(".aiexclude").isEmpty());
        assertFalse(readFile("AGENTS.md").isEmpty());
        assertFalse(readFile(".codex/config.toml").isEmpty());
        assertFalse(readFile(".codex/rules/vibetags.rules").isEmpty());
        assertFalse(readFile("gemini_instructions.md").isEmpty());
        assertFalse(readFile(".github/copilot-instructions.md").isEmpty());
    }

    @Test
    void testCopilotInstructionsHasCorrectStructure() throws IOException {
        String content = readFile(".github/copilot-instructions.md");

        assertTrue(content.contains("GitHub Copilot Instructions"),
            "Should have Copilot header");
        assertTrue(content.contains("AUTO-GENERATED BY VIBETAGS"),
            "Should have auto-generated marker");
        assertTrue(content.contains("Locked Files"),
            "Should have locked files section");
        assertTrue(content.contains("Contextual Guidelines"),
            "Should have contextual guidelines section");
    }

    @Test
    void testCopilotInstructionsHasLockedFiles() throws IOException {
        String content = readFile(".github/copilot-instructions.md");

        assertTrue(content.contains("PaymentProcessor"),
            "Should mention PaymentProcessor");
    }

    @Test
    void testCopilotInstructionsHasContextualGuidelines() throws IOException {
        String content = readFile(".github/copilot-instructions.md");

        assertTrue(content.contains("memory usage"),
            "Should mention focus from @AIContext");
        assertTrue(content.contains("java.util.regex"),
            "Should mention avoids from @AIContext");
    }

    @Test
    void testCopilotInstructionsHasSecurityAuditRequirements() throws IOException {
        String content = readFile(".github/copilot-instructions.md");

        assertTrue(content.contains("Security Audit Requirements"),
            "Should have security audit section");
        assertTrue(content.contains("DatabaseConnector"),
            "Should mention DatabaseConnector");
        assertTrue(content.contains("SQL Injection"),
            "Should mention SQL Injection");
        assertTrue(content.contains("Thread Safety"),
            "Should mention Thread Safety");
    }

    @Test
    void testCopilotInstructionsHasIgnoredElements() throws IOException {
        String content = readFile(".github/copilot-instructions.md");

        assertTrue(content.contains("Ignored Elements"),
            "Should have ignored elements section");
        assertTrue(content.contains("GeneratedMetadata"),
            "Should mention GeneratedMetadata");
    }

    @Test
    void testCodexConfigHasCorrectSettings() throws IOException {
        String content = readFile(".codex/config.toml");
        assertTrue(content.contains("model = \"o3-mini\""));
        assertTrue(content.contains("approval_policy = \"on-request\""));
    }

    @Test
    void testAIDraftImplementationTasksExist() throws IOException {
        String cursorRules = readFile(".cursorrules");
        String claudeMd = readFile("CLAUDE.md");
        
        assertTrue(cursorRules.contains("IMPLEMENTATION TASKS"), "Should have implementation tasks section");
        assertTrue(cursorRules.contains("NotificationService"), "Should mention NotificationService (Draft)");
        assertTrue(cursorRules.contains("Implement email sending"), "Should have instructions");
        
        assertTrue(claudeMd.contains("<implementation_tasks>"), "Should have implementation tasks XML");
        assertTrue(claudeMd.contains("NotificationService"), "Should mention NotificationService");
    }

    @Test
    void testVersionStampInAllFiles() throws IOException {
        String version = "v1.0.0-SNAPSHOT";
        assertTrue(readFile(".cursorrules").contains(version));
        assertTrue(readFile("CLAUDE.md").contains(version));
        assertTrue(readFile(".aiexclude").contains(version));
        assertTrue(readFile("AGENTS.md").contains(version));
        assertTrue(readFile("gemini_instructions.md").contains(version));
        assertTrue(readFile(".github/copilot-instructions.md").contains(version));
    }

    @Test
    void testCodexRulesHasStarlarkContent() throws IOException {
        String content = readFile(".codex/rules/vibetags.rules");
        assertTrue(content.contains("prefix_rule(\"mvn\", \"prompt\")"));
        assertTrue(content.contains("prefix_rule(\"ls\", \"allow\")"));
    }

    @Test
    void testCursorRulesHasIgnoredElementsSection() throws IOException {
        String content = readFile(".cursorrules");
        assertTrue(content.contains("IGNORED ELEMENTS"),
            "Should contain ignored elements section");
        assertTrue(content.contains("GeneratedMetadata"),
            "Should mention GeneratedMetadata class");
    }

    @Test
    void testClaudeMdHasIgnoredElements() throws IOException {
        String content = readFile("CLAUDE.md");
        assertTrue(content.contains("<ignored_elements>"),
            "Should contain ignored_elements XML tag");
        assertTrue(content.contains("GeneratedMetadata"),
            "Should mention GeneratedMetadata");
        assertTrue(content.contains("Treat these as if they do not exist"),
            "Should have ignore rule");
    }

    @Test
    void testAiExcludeContainsIgnoredFile() throws IOException {
        String content = readFile(".aiexclude");
        assertTrue(content.contains("GeneratedMetadata"),
            "Should exclude GeneratedMetadata");
    }

    @Test
    void testCodexAgentsHasIgnoredFiles() throws IOException {
        String content = readFile("AGENTS.md");
        assertTrue(content.contains("IGNORED ELEMENTS"),
            "Should contain Ignored Elements section");
        assertTrue(content.contains("GeneratedMetadata"),
            "Should mention GeneratedMetadata");
    }

    @Test
    void testGeminiInstructionsHasIgnoredElements() throws IOException {
        String content = readFile("gemini_instructions.md");
        assertTrue(content.contains("IGNORED ELEMENTS"), 
            "Should contain IGNORED ELEMENTS section");
        assertTrue(content.contains("GeneratedMetadata"), 
            "Should mention GeneratedMetadata");
    }

    @Test
    void testQwenMdHasCorrectStructure() throws IOException {
        String content = readFile("QWEN.md");
        assertTrue(content.contains("PROJECT CONTEXT"), "Should have Qwen header");
        assertTrue(content.contains("LOCKED FILES"), "Should have locked files section");
        assertTrue(content.contains("CONTEXTUAL RULES"), "Should have contextual rules section");
        assertTrue(content.contains("MANDATORY SECURITY AUDITS"), "Should have audit section");
        assertTrue(content.contains("IGNORED ELEMENTS"), "Should have ignored elements section");
    }

    @Test
    void testQwenSettingsHasCorrectFormat() throws IOException {
        String content = readFile(".qwen/settings.json");
        assertTrue(content.contains("\"model\": \"qwen3-coder-plus\""), "Should specify Qwen model");
        assertTrue(content.contains("\"mcp\": {"), "Should have MCP settings");
    }

    private boolean fileExists(String filename) {
        Path p = Path.of(EXAMPLE_DIR, filename).toAbsolutePath().normalize();
        return Files.exists(p);
    }

    private String readFile(String filename) throws IOException {
        Path p = Path.of(EXAMPLE_DIR, filename).toAbsolutePath().normalize();
        if (!Files.exists(p)) {
            return "";
        }
        return Files.readString(p, StandardCharsets.UTF_8);
    }
}
