package se.deversity.vibetags.processor;

import org.junit.jupiter.api.AfterAll;
import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.io.TempDir;

import java.io.IOException;
import java.nio.file.Path;

import static org.junit.jupiter.api.Assertions.assertTrue;

/**
 * End-to-end tests for the Claude Code local-override platform (CLAUDE.local.md).
 *
 * Verifies that when CLAUDE.local.md exists on disk, the processor populates it with
 * the same guardrail content as CLAUDE.md (Claude Code loads both files for the same project).
 */
class ClaudeLocalEndToEndTest {

    @TempDir
    static Path tempDir;

    private static ProcessorTestHarness harness;

    @BeforeAll
    static void setUp() throws IOException {
        harness = ProcessorTestHarness.withExampleSources(tempDir);
    }

    @AfterAll
    static void tearDown() {
        VibeTagsLogger.shutdown();
    }

    @Test
    void claudeLocal_fileIsGenerated() throws IOException {
        assertTrue(harness.fileExists("CLAUDE.local.md"), "CLAUDE.local.md must be generated when the file exists on disk");
    }

    @Test
    void claudeLocal_containsLockedFilesSection() throws IOException {
        String content = harness.readFile("CLAUDE.local.md");
        assertTrue(content.contains("<locked_files>"), "CLAUDE.local.md must contain <locked_files> block");
        assertTrue(content.contains("</locked_files>"), "CLAUDE.local.md must close <locked_files> block");
    }

    @Test
    void claudeLocal_containsVibeTagsMarkers() throws IOException {
        String content = harness.readFile("CLAUDE.local.md");
        assertTrue(content.contains("VIBETAGS-START"), "CLAUDE.local.md must contain VIBETAGS-START marker");
        assertTrue(content.contains("VIBETAGS-END"), "CLAUDE.local.md must contain VIBETAGS-END marker");
    }

    @Test
    void claudeLocal_containsLockedEntry() throws IOException {
        String content = harness.readFile("CLAUDE.local.md");
        assertTrue(content.contains("com.example.payment.PaymentProcessor"), "CLAUDE.local.md must list the @AILocked class");
    }

    @Test
    void claudeLocal_contentMatchesClaudeMd() throws IOException {
        String local = harness.readFile("CLAUDE.local.md");
        String claude = harness.readFile("CLAUDE.md");
        // Both files should contain the same guardrail entries (CLAUDE.local.md reuses CLAUDE.md content).
        assertTrue(local.contains("com.example.security.SecurityConfig"),
            "CLAUDE.local.md must contain the security config entry present in CLAUDE.md");
        assertTrue(claude.contains("com.example.security.SecurityConfig"),
            "CLAUDE.md must also contain the security config entry");
    }

    @Test
    void claudeLocal_containsAutoGeneratedHeader() throws IOException {
        String content = harness.readFile("CLAUDE.local.md");
        assertTrue(content.contains("Generated by VibeTags |"), "CLAUDE.local.md must have a generated-by-VibeTags header");
    }
}
