package se.deversity.vibetags.processor;

import org.junit.jupiter.api.AfterAll;
import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.io.TempDir;

import java.io.IOException;
import java.nio.file.Path;

import static org.junit.jupiter.api.Assertions.assertTrue;

/**
 * End-to-end tests for the Claude Code Skill platform (.claude/skills/vibetags-guardrails/SKILL.md).
 *
 * Verifies that when the file exists on disk, the processor writes it with the required
 * Skill YAML frontmatter (name + description) followed by the same Markdown guardrail body
 * used for .cursorrules.
 */
class ClaudeSkillEndToEndTest {

    private static final String SKILL_FILE = ".claude/skills/vibetags-guardrails/SKILL.md";

    @TempDir
    static Path tempDir;

    private static ProcessorTestHarness harness;

    @BeforeAll
    static void setUp() throws IOException {
        harness = ProcessorTestHarness.withExampleSources(tempDir);
    }

    @AfterAll
    static void tearDown() {
        VibeTagsLogger.shutdown();
    }

    @Test
    void claudeSkill_fileIsGenerated() throws IOException {
        assertTrue(harness.fileExists(SKILL_FILE), "SKILL.md must be generated when the file exists on disk");
    }

    @Test
    void claudeSkill_containsRequiredFrontMatter() throws IOException {
        String content = harness.readFile(SKILL_FILE);
        assertTrue(content.startsWith("---\n"), "SKILL.md must start with YAML frontmatter");
        assertTrue(content.contains("name: vibetags-guardrails"), "SKILL.md frontmatter must declare a skill name");
        assertTrue(content.contains("description:"), "SKILL.md frontmatter must declare a description");
    }

    @Test
    void claudeSkill_markersComeAfterFrontMatter() throws IOException {
        String content = harness.readFile(SKILL_FILE);
        int secondTriple = content.indexOf("---", 3);
        int markerStart = content.indexOf("VIBETAGS-START");
        assertTrue(secondTriple > 0 && markerStart > secondTriple,
            "VIBETAGS-START marker must appear after the YAML frontmatter block");
    }

    @Test
    void claudeSkill_containsLockedEntry() throws IOException {
        String content = harness.readFile(SKILL_FILE);
        assertTrue(content.contains("com.example.payment.PaymentProcessor"), "SKILL.md must list the @AILocked class");
    }

    @Test
    void claudeSkill_containsAutoGeneratedHeader() throws IOException {
        String content = harness.readFile(SKILL_FILE);
        assertTrue(content.contains("AUTO-GENERATED"), "SKILL.md body must have an auto-generated header");
    }
}
