package se.deversity.vibetags.processor;

import org.junit.jupiter.api.AfterAll;
import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.io.TempDir;

import java.io.IOException;
import java.nio.file.Path;

import static org.junit.jupiter.api.Assertions.assertTrue;

/**
 * End-to-end tests for the Cline platform (.clinerules).
 *
 * Verifies that when .clinerules exists on disk, the processor populates it with
 * the same guardrail content as .cursorrules (Cline uses the same Markdown format).
 */
class ClineEndToEndTest {

    @TempDir
    static Path tempDir;

    private static ProcessorTestHarness harness;

    @BeforeAll
    static void setUp() throws IOException {
        harness = ProcessorTestHarness.withExampleSources(tempDir);
    }

    @AfterAll
    static void tearDown() {
        VibeTagsLogger.shutdown();
    }

    @Test
    void clinerules_fileIsGenerated() throws IOException {
        assertTrue(harness.fileExists(".clinerules"), ".clinerules must be generated when the file exists on disk");
    }

    @Test
    void clinerules_containsLockedFilesSection() throws IOException {
        String cline = harness.readFile(".clinerules");
        assertTrue(cline.contains("LOCKED FILES"), ".clinerules must contain LOCKED FILES section");
    }

    @Test
    void clinerules_containsVibeTagsMarkers() throws IOException {
        String cline = harness.readFile(".clinerules");
        assertTrue(cline.contains("VIBETAGS-START"), ".clinerules must contain VIBETAGS-START marker");
        assertTrue(cline.contains("VIBETAGS-END"), ".clinerules must contain VIBETAGS-END marker");
    }

    @Test
    void clinerules_containsLockedEntry() throws IOException {
        String cline = harness.readFile(".clinerules");
        assertTrue(cline.contains("com.example.payment.PaymentProcessor"), ".clinerules must list the @AILocked class");
    }

    @Test
    void clinerules_contentMatchesCursorRules() throws IOException {
        String cline = harness.readFile(".clinerules");
        String cursor = harness.readFile(".cursorrules");
        // Both files should contain the same guardrail entries (Cline reuses cursor content)
        assertTrue(cline.contains("com.example.security.SecurityConfig"),
            ".clinerules must contain the security config entry present in .cursorrules");
        assertTrue(cursor.contains("com.example.security.SecurityConfig"),
            ".cursorrules must also contain the security config entry");
    }

    @Test
    void clinerules_containsAutoGeneratedHeader() throws IOException {
        String cline = harness.readFile(".clinerules");
        assertTrue(cline.contains("AUTO-GENERATED"), ".clinerules must have an auto-generated header");
    }
}
