package se.deversity.vibetags.processor;

import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.io.TempDir;

import se.deversity.vibetags.processor.internal.ServiceRegistry;
import se.deversity.vibetags.processor.internal.content.Platform;

import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertNull;
import static org.junit.jupiter.api.Assertions.assertTrue;

/**
 * VibeTags no longer writes {@code .codex/config.toml} (#934).
 *
 * <p>It was written whenever {@code AGENTS.md} was managed, with fixed content that carried no
 * guardrail: {@code model = "o3-mini"} and {@code approval_policy = "on-request"} under a
 * {@code [project]} table. Codex reads {@code model} and {@code approval_policy} as top-level keys
 * and documents no {@code [project]} table (its configuration reference, read 2026-10-09), so the
 * file did nothing, while reading to any user as a model pin VibeTags imposed. The owner chose to
 * stop writing it outright: a deprecation cycle would protect behaviour nobody gets.
 *
 * <p>Removal means what it meant for the 1.4 removals: an existing file is left exactly as it is.
 * {@code .codex/rules/vibetags.rules}, the Codex sidecar that does carry the guardrails, stays.
 */
@Tag("e2e")
@DisplayName(".codex/config.toml is no longer written (#934)")
class CodexConfigRemovedTest {

    @Test
    @DisplayName("AGENTS.md as the sole config writes the rules sidecar but no .codex/config.toml")
    void managingAgentsMdNoLongerCreatesTheConfig(@TempDir Path root) throws IOException {
        ProcessorTestHarness h = new ProcessorTestHarness(root, false);
        h.touchOptIn("AGENTS.md");
        ProcessorTestHarness.addExampleSources(h);

        h.compile();

        assertTrue(h.readFile("AGENTS.md").contains("PaymentProcessor"),
            "the processor ran and managed AGENTS.md, which is what used to bring the config with it");
        assertTrue(Files.isRegularFile(root.resolve(".codex/rules/vibetags.rules")),
            "the Codex rules sidecar carries the guardrails and must still be written");
        assertFalse(Files.exists(root.resolve(".codex/config.toml")),
            ".codex/config.toml was created; it carried no guardrail and Codex ignored its [project] table");
    }

    @Test
    @DisplayName("a .codex/config.toml an earlier build wrote is left byte-identical")
    void anExistingConfigIsLeftAlone(@TempDir Path root) throws IOException {
        ProcessorTestHarness h = new ProcessorTestHarness(root, false);
        h.touchOptIn("AGENTS.md");
        Path config = Files.createDirectories(root.resolve(".codex")).resolve("config.toml");
        String lastBuild = "# # Generated by VibeTags | https://github.com/PIsberg/vibetags\n"
            + "[project]\nmodel = \"o3-mini\"\napproval_policy = \"on-request\"\n";
        Files.writeString(config, lastBuild, StandardCharsets.UTF_8);
        ProcessorTestHarness.addExampleSources(h);

        h.compile();

        assertTrue(h.readFile("AGENTS.md").contains("PaymentProcessor"), "the processor ran");
        assertEquals(lastBuild, Files.readString(config, StandardCharsets.UTF_8),
            ".codex/config.toml is no longer a VibeTags output, so the build must not touch it");
    }

    @Test
    @DisplayName("codex_config is gone from the service map and the platforms")
    void theServiceIsGoneFromEveryRegistry(@TempDir Path root) {
        assertFalse(ServiceRegistry.buildServiceFileMap(root).containsKey("codex_config"),
            "codex_config still maps to a path");
        assertFalse(ServiceRegistry.buildServiceFileMap(root).containsValue(root.resolve(".codex/config.toml")),
            ".codex/config.toml is still a service path");
        assertNull(Platform.fromServiceKey("codex_config"), "codex_config still names a Platform");
    }
}
