package se.deversity.vibetags.processor;

import org.junit.jupiter.api.AfterAll;
import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.io.TempDir;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;

import static org.junit.jupiter.api.Assertions.*;

class GranularRulesEndToEndTest {

    @TempDir
    static Path tempDir;

    private static ProcessorTestHarness harness;

    @BeforeAll
    static void setUp() throws IOException {
        harness = ProcessorTestHarness.withExampleSources(tempDir);
    }

    @AfterAll
    static void tearDown() {
        VibeTagsLogger.shutdown();
    }

    @Test
    void testAiderFilesGenerated() {
        assertTrue(harness.fileExists("CONVENTIONS.md"));
        assertTrue(harness.fileExists(".aiderignore"));
    }

    @Test
    void testAiderConventionsContent() throws IOException {
        String content = harness.readFile("CONVENTIONS.md");
        assertTrue(content.contains("CONVENTIONS"));
        assertTrue(content.contains("LOCKED: com.example.payment.PaymentProcessor"));
        assertTrue(content.contains("SECURITY AUDIT: com.example.database.DatabaseConnector"));
    }

    @Test
    void testCursorGranularRulesGenerated() {
        assertTrue(harness.fileExists(".cursor/rules/com-example-payment-PaymentProcessor.mdc"));
        assertTrue(harness.fileExists(".cursor/rules/com-example-database-DatabaseConnector.mdc"));
    }

    @Test
    void testCursorGranularRuleContent() throws IOException {
        String content = harness.readFile(".cursor/rules/com-example-payment-PaymentProcessor.mdc");
        assertTrue(content.startsWith("---"));
        assertTrue(content.contains("description: \"AI rules for com.example.payment.PaymentProcessor\""));
        assertTrue(content.contains("globs: [\"**/PaymentProcessor.java\"]"));
        assertTrue(content.contains("## Locked Status"));
        assertTrue(content.contains("VIBETAGS-START"));
    }

    @Test
    void testTraeGranularRulesGenerated() {
        assertTrue(harness.fileExists(".trae/rules/com-example-payment-PaymentProcessor.md"));
    }

    @Test
    void testTraeGranularRuleContent() throws IOException {
        String content = harness.readFile(".trae/rules/com-example-payment-PaymentProcessor.md");
        assertTrue(content.startsWith("---"));
        assertTrue(content.contains("alwaysApply: false"));
        assertTrue(content.contains("globs: [\"**/PaymentProcessor.java\"]"));
    }

    @Test
    void testRooRulesGenerated() {
        assertTrue(harness.fileExists(".roo/rules/com-example-payment-PaymentProcessor.md"));
    }

    @Test
    void testRooRuleContent() throws IOException {
        String content = harness.readFile(".roo/rules/com-example-payment-PaymentProcessor.md");
        assertFalse(content.contains("---")); // Roo uses plain Markdown
        assertTrue(content.contains("# Rules for PaymentProcessor"));
        assertTrue(content.contains("## Locked Status"));
    }

    @Test
    void testOrphanedFileCleanup(@TempDir Path cleanupDir) throws IOException {
        // 1. Create a dummy file that looks like it was generated by VibeTags
        Path rulesDir = cleanupDir.resolve(".cursor/rules");
        Files.createDirectories(rulesDir);
        Path orphanedFile = rulesDir.resolve("OrphanedRule.mdc");
        // Must contain markers and either .md or .mdc extension
        Files.writeString(orphanedFile, "<!-- VIBETAGS-START -->\nold rule\n<!-- VIBETAGS-END -->");
        assertTrue(Files.exists(orphanedFile));

        // 2. Run the processor in this directory
        ProcessorTestHarness h = new ProcessorTestHarness(cleanupDir);
        h.addSource("com.example.Legit", 
            "package com.example;\n" +
            "import se.deversity.vibetags.annotations.AILocked;\n" +
            "@AILocked(reason=\"ok\") public class Legit {}");
        h.compile();

        // 3. Verify that OrphanedRule.mdc is GONE
        assertFalse(Files.exists(orphanedFile), "Orphaned VibeTags rule should be deleted");
        // Verify that the new rule WAS generated
        assertTrue(Files.exists(rulesDir.resolve("com-example-Legit.mdc")));

        // 4. Shutdown logger to release file handle on Windows
        VibeTagsLogger.shutdown();
    }
}
