package se.deversity.vibetags.processor;

import org.junit.jupiter.api.AfterAll;
import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.io.TempDir;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;

import static org.junit.jupiter.api.Assertions.*;

class GranularRulesEndToEndTest {

    @TempDir
    static Path tempDir;

    private static ProcessorTestHarness harness;

    @BeforeAll
    static void setUp() throws IOException {
        harness = ProcessorTestHarness.withExampleSources(tempDir);
    }

    @AfterAll
    static void tearDown() {
        VibeTagsLogger.shutdown();
    }

    @Test
    void testAiderFilesGenerated() {
        assertTrue(harness.fileExists("CONVENTIONS.md"));
        assertTrue(harness.fileExists(".aiderignore"));
    }

    @Test
    void testAiderConventionsContent() throws IOException {
        String content = harness.readFile("CONVENTIONS.md");
        assertTrue(content.contains("CONVENTIONS"));
        assertTrue(content.contains("LOCKED: com.example.payment.PaymentProcessor"));
        assertTrue(content.contains("SECURITY AUDIT: com.example.database.DatabaseConnector"));
    }

    @Test
    void testCursorGranularRulesGenerated() {
        assertTrue(harness.fileExists(".cursor/rules/com-example-payment-PaymentProcessor.mdc"));
        assertTrue(harness.fileExists(".cursor/rules/com-example-database-DatabaseConnector.mdc"));
    }

    @Test
    void testCursorGranularRuleContent() throws IOException {
        String content = harness.readFile(".cursor/rules/com-example-payment-PaymentProcessor.mdc");
        assertTrue(content.startsWith("---"));
        assertTrue(content.contains("description: \"AI rules for com.example.payment.PaymentProcessor\""));
        assertTrue(content.contains("globs: [\"**/PaymentProcessor.java\"]"));
        assertTrue(content.contains("## Locked Status"));
        assertTrue(content.contains("VIBETAGS-START"));
    }

    @Test
    void testTraeGranularRulesGenerated() {
        assertTrue(harness.fileExists(".trae/rules/com-example-payment-PaymentProcessor.md"));
    }

    @Test
    void testTraeGranularRuleContent() throws IOException {
        String content = harness.readFile(".trae/rules/com-example-payment-PaymentProcessor.md");
        assertTrue(content.startsWith("---"));
        assertTrue(content.contains("alwaysApply: false"));
        assertTrue(content.contains("globs: [\"**/PaymentProcessor.java\"]"));
    }

    @Test
    void testRooRulesGenerated() {
        assertTrue(harness.fileExists(".roo/rules/com-example-payment-PaymentProcessor.md"));
    }

    @Test
    void testRooRuleContent() throws IOException {
        String content = harness.readFile(".roo/rules/com-example-payment-PaymentProcessor.md");
        assertFalse(content.contains("---")); // Roo uses plain Markdown
        assertTrue(content.contains("# Rules for PaymentProcessor"));
        assertTrue(content.contains("## Locked Status"));
    }

    @Test
    void testOrphanedFileCleanup(@TempDir Path cleanupDir) throws IOException {
        // 1. Create a dummy file that looks like it was generated by VibeTags but has NO manual content
        Path rulesDir = cleanupDir.resolve(".cursor/rules");
        Files.createDirectories(rulesDir);
        Path orphanedEmptyFile = rulesDir.resolve("OrphanedEmpty.mdc");
        Files.writeString(orphanedEmptyFile, "---\ndescription: ...\n---\n<!-- VIBETAGS-START -->\nold rule\n<!-- VIBETAGS-END -->");
        assertTrue(Files.exists(orphanedEmptyFile));

        // Create a dummy file that has a manual rule added
        Path orphanedManualFile = rulesDir.resolve("OrphanedManual.mdc");
        Files.writeString(orphanedManualFile, "---\ndescription: ...\n---\n<!-- VIBETAGS-START -->\nold rule\n<!-- VIBETAGS-END -->\n\n# Manual Rule\nsurvive!");
        assertTrue(Files.exists(orphanedManualFile));

        // 2. Run the processor in this directory
        ProcessorTestHarness h = new ProcessorTestHarness(cleanupDir);
        h.addSource("com.example.Legit", 
            "package com.example;\n" +
            "import se.deversity.vibetags.annotations.AILocked;\n" +
            "@AILocked(reason=\"ok\") public class Legit {}");
        h.compile();

        // 3. Verify that OrphanedEmpty.mdc is GONE because it was just boilerplate
        assertFalse(Files.exists(orphanedEmptyFile), "Orphaned empty VibeTags rule should be deleted");

        // Verify that OrphanedManual.mdc SURVIVED and the vibetags section was scrubbed
        assertTrue(Files.exists(orphanedManualFile), "Orphaned rule with manual edits should survive");
        String manualContent = Files.readString(orphanedManualFile);
        assertFalse(manualContent.contains("old rule"), "Auto-generated block should be scrubbed");
        assertFalse(manualContent.contains("VIBETAGS-START"), "Markers should be scrubbed");
        assertTrue(manualContent.contains("# Manual Rule\nsurvive!"), "Manual rule must survive");

        // Verify that the new rule WAS generated
        assertTrue(Files.exists(rulesDir.resolve("com-example-Legit.mdc")));

        // 4. Shutdown logger to release file handle on Windows
        VibeTagsLogger.shutdown();
    }
}
