package se.deversity.vibetags.processor;

import org.junit.jupiter.api.AfterAll;
import org.junit.jupiter.api.BeforeAll;
import se.deversity.asynctest.AsyncTest;
import se.deversity.vibetags.processor.internal.GuardrailFileWriter;
import se.deversity.vibetags.processor.internal.WriteCache;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.Comparator;
import java.util.stream.Stream;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertTrue;

/**
 * Concurrency stress test for the parallel write phase in
 * {@code AIGuardrailProcessor.generateFiles()}, which fans every active service out over a
 * bounded ForkJoinPool while sharing one {@link GuardrailFileWriter} and one {@link WriteCache}
 * across the workers.
 *
 * <p>This test mirrors that shape exactly — one file per task, a shared writer, a shared cache —
 * and asserts the invariant that phase must never break: hand-authored content outside the
 * {@code VIBETAGS-START} / {@code VIBETAGS-END} markers survives, and the file ends up with
 * exactly one marker pair. A torn or interleaved write shows up as lost preamble, lost epilogue,
 * or a duplicated marker, all of which are silent data loss in a consumer's repository.
 */
class GuardrailFileWriterAsyncTest {

    private static final String HEADER = "# Generated by VibeTags | https://github.com/PIsberg/vibetags\n";
    private static final String PREAMBLE_MARK = "hand-authored preamble";
    private static final String EPILOGUE_MARK = "hand-authored epilogue";
    private static final String GENERATED_MARK = "generated guardrail line";

    private static Path root;
    private static GuardrailFileWriter writer;

    @BeforeAll
    static void setUp() throws IOException {
        root = Files.createTempDirectory("vibetags-writer-async");
        writer = new GuardrailFileWriter(HEADER, null, null, new WriteCache(root.resolve(".vibetags-cache")));
    }

    @AfterAll
    static void tearDown() throws IOException {
        if (root == null) return;
        try (Stream<Path> paths = Files.walk(root)) {
            paths.sorted(Comparator.reverseOrder()).forEach(p -> {
                try {
                    Files.deleteIfExists(p);
                } catch (IOException ignored) {
                    // Best-effort cleanup of a temp directory; a leftover file must not fail the test.
                }
            });
        }
    }

    @AsyncTest(threads = 8, invocations = 20, timeoutMs = 60_000)
    void handAuthoredContentSurvivesTheParallelWritePhase() throws IOException {
        // One distinct file per worker, as in the real write phase: the concurrency is across
        // files, over shared writer and cache state.
        String name = "CLAUDE-" + Thread.currentThread().threadId() + ".md";
        Path file = root.resolve(name);

        if (!Files.exists(file)) {
            Files.writeString(file, "# " + PREAMBLE_MARK + "\n\n"
                + GuardrailFileWriter.MARKER_START_MD + "\n"
                + GuardrailFileWriter.MARKER_END_MD + "\n\n## " + EPILOGUE_MARK + "\n");
        }

        writer.writeFileIfChanged(file.toString(), "## Guardrails\n\n- " + GENERATED_MARK + "\n", true);

        String actual = Files.readString(file);
        int start = actual.indexOf(GuardrailFileWriter.MARKER_START_MD);
        int end = actual.indexOf(GuardrailFileWriter.MARKER_END_MD);
        assertTrue(start >= 0, () -> name + " lost its start marker: " + actual);
        assertTrue(end > start, () -> name + " lost or reordered its end marker: " + actual);

        assertEquals(1, occurrences(actual, GuardrailFileWriter.MARKER_START_MD),
            () -> name + " has a duplicated start marker: " + actual);
        assertEquals(1, occurrences(actual, GuardrailFileWriter.MARKER_END_MD),
            () -> name + " has a duplicated end marker: " + actual);

        int preamble = actual.indexOf(PREAMBLE_MARK);
        int epilogue = actual.indexOf(EPILOGUE_MARK);
        assertTrue(preamble >= 0 && preamble < start,
            () -> name + " lost the hand-authored preamble above the markers: " + actual);
        assertTrue(epilogue > end,
            () -> name + " lost the hand-authored epilogue below the markers: " + actual);

        int generated = actual.indexOf(GENERATED_MARK);
        assertTrue(generated > start && generated < end,
            () -> name + " did not render the generated body between the markers: " + actual);
    }

    private static int occurrences(String haystack, String needle) {
        int count = 0;
        for (int i = haystack.indexOf(needle); i >= 0; i = haystack.indexOf(needle, i + needle.length())) {
            count++;
        }
        return count;
    }
}
