package se.deversity.vibetags.processor;

import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.io.TempDir;
import se.deversity.vibetags.processor.internal.GuardrailFileWriter;
import se.deversity.vibetags.processor.internal.WriteCache;

import javax.annotation.processing.Messager;
import javax.tools.Diagnostic;
import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;

import static org.junit.jupiter.api.Assertions.*;

/**
 * Targets the streaming + cache integration branches of {@link GuardrailFileWriter} that the
 * existing end-to-end tests don't exercise:
 *
 * <ul>
 *   <li>The streaming fast-path's cache-record call (when bytes already match).</li>
 *   <li>The {@code !hasNewRules && existingSize > 0} skip-update branch in the streaming path
 *       (sizes match exactly but bytes differ + caller signalled "no new rules").</li>
 *   <li>The four no-op {@link Messager} overloads on {@link GuardrailFileWriter#noopMessager}.</li>
 * </ul>
 */
class GuardrailFileWriterCoverageTest {

    private static final String GENERATED_HEADER = "# Generated by VibeTags | https://example.invalid\n";

    @Test
    void streaming_byteEqualHit_recordsCacheEntry(@TempDir Path tmp) throws IOException {
        WriteCache cache = new WriteCache(tmp.resolve(".vibetags-cache"));
        GuardrailFileWriter writer = new GuardrailFileWriter(GENERATED_HEADER, null, null, cache);

        // Non-marker file pre-populated to match the body byte-for-byte. The streaming branch
        // sees existingSize == contentByteLen, runs fileBytesEqual → true, and must call
        // cache.recordWrite to populate the cache for subsequent calls.
        Path file = tmp.resolve("config.json");
        String body = "alpha-beta-gamma\n";
        Files.writeString(file, body, StandardCharsets.UTF_8);

        boolean wrote = writer.writeFileIfChanged(file.toString(), body, true);
        assertFalse(wrote, "byte-equal content should not trigger a write");
        assertTrue(cache.isUnchanged(file, body),
            "the streaming-hit path must populate the cache so subsequent isUnchanged calls hit");
    }

    @Test
    void streaming_byteMismatch_skipUpdate_whenNoNewRulesOnNonEmptyFile(@TempDir Path tmp) throws IOException {
        // The streaming branch fires when sizes match exactly. If bytes differ AND hasNewRules=false
        // AND existingSize > 0, the writer must take the skipUpdateMsg early-return — preserving
        // the existing file rather than overwriting unrelated content.
        GuardrailFileWriter writer = new GuardrailFileWriter(GENERATED_HEADER, null, null, null);

        Path file = tmp.resolve("config.json");
        String existing = "abc12345\n";
        String newSameLen = "abcXYZ45\n"; // same byte length, different bytes
        Files.writeString(file, existing, StandardCharsets.UTF_8);
        assertEquals(existing.getBytes(StandardCharsets.UTF_8).length,
                     newSameLen.getBytes(StandardCharsets.UTF_8).length,
                     "test setup invariant: lengths must match for the streaming branch to fire");

        boolean wrote = writer.writeFileIfChanged(file.toString(), newSameLen, /*hasNewRules*/ false);
        assertFalse(wrote, "no-new-rules + non-empty existing file must trigger skipUpdate");
        assertEquals(existing, Files.readString(file, StandardCharsets.UTF_8),
            "existing file content must be preserved when skipUpdate triggers");
    }

    @Test
    void streaming_byteMismatch_writes_whenHasNewRulesIsTrue(@TempDir Path tmp) throws IOException {
        // Mirror image of the test above: if hasNewRules=true, the streaming branch DOES
        // write the new content (covers the `writeAndCache` branch on line 119 of the writer).
        GuardrailFileWriter writer = new GuardrailFileWriter(GENERATED_HEADER, null, null, null);

        Path file = tmp.resolve("config.json");
        String existing = "abc12345\n";
        String newSameLen = "abcXYZ45\n";
        Files.writeString(file, existing, StandardCharsets.UTF_8);

        boolean wrote = writer.writeFileIfChanged(file.toString(), newSameLen, /*hasNewRules*/ true);
        assertTrue(wrote, "size match + byte mismatch + hasNewRules=true must write");
        assertEquals(newSameLen, Files.readString(file, StandardCharsets.UTF_8));
    }

    @Test
    void noopMessager_allFourOverloads_returnSilently() {
        Messager m = GuardrailFileWriter.noopMessager();
        // The Messager interface has four printMessage overloads; the no-op implementation
        // satisfies all of them by doing nothing. Calling each variant must not throw.
        assertDoesNotThrow(() -> m.printMessage(Diagnostic.Kind.NOTE, "two-arg"));
        assertDoesNotThrow(() -> m.printMessage(Diagnostic.Kind.NOTE, "three-arg", null));
        assertDoesNotThrow(() -> m.printMessage(Diagnostic.Kind.NOTE, "four-arg", null, null));
        assertDoesNotThrow(() -> m.printMessage(Diagnostic.Kind.NOTE, "five-arg", null, null, null));
    }
}
