package se.deversity.vibetags.processor;

import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.io.TempDir;

import se.deversity.vibetags.processor.internal.GuardrailFileWriter;

import javax.tools.Diagnostic;
import javax.tools.JavaFileObject;
import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.List;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertTrue;

/**
 * The other half of the file lifecycle: what happens when a generated file is still there but no
 * longer looks the way VibeTags left it.
 *
 * <p>{@code GuardrailLifecycleEndToEndTest} covers the file being <em>deleted</em> — the opt-out.
 * {@code WriteCacheProcessorIntegrationTest} covers an edit <em>outside</em> the markers being
 * preserved. Neither covers the cases a real repository produces constantly: a merge conflict
 * resolved by deleting the marker block, a half-applied patch that left a start marker with no end,
 * a file truncated by a bad script, an edit made <em>inside</em> the block by someone who did not
 * know it was generated, and a {@code .vibetags-cache} lost to {@code git clean}.
 *
 * <p>Each one is the same shape of failure as every multi-module defect so far: the build stays
 * green, the file still exists, and the guardrails are quietly wrong. The cache short-circuit makes
 * it worse — a run that decides nothing changed never looks at the damage, so these are tests of
 * {@code WriteCache.allCachedFilesStable()} as much as of the writer.
 */
@Tag("e2e")
class GuardrailFileRecoveryEndToEndTest {

    private static final String REASON = "Reconciliation is load-bearing";

    @AfterEach
    void releaseLogHandle() {
        VibeTagsLogger.shutdown();
    }

    /**
     * The merge-conflict case: a human resolves a conflict in {@code CLAUDE.md} by deleting the
     * whole marker block. The file still exists, so the platform is still opted in, and the block
     * has to come back — without taking the hand-written half of the file with it.
     */
    @Test
    void deletingTheMarkerBlock_reappendsIt_andKeepsTheHandWrittenContent(@TempDir Path dir) throws Exception {
        compileOnce(dir);

        Files.writeString(dir.resolve("CLAUDE.md"),
            "# My Project\n\nHand-written onboarding notes that predate VibeTags.\n",
            StandardCharsets.UTF_8);
        settle(dir);

        compileOnce(dir);

        String after = Files.readString(dir.resolve("CLAUDE.md"), StandardCharsets.UTF_8);
        assertTrue(after.contains("Hand-written onboarding notes that predate VibeTags."),
            "deleting the marker block must not cost the human half of the file:\n" + after);
        assertEquals(1, count(after, GuardrailFileWriter.MARKER_START_MD),
            "exactly one marker block must be re-appended, not zero and not two:\n" + after);
        assertTrue(after.contains(REASON),
            "the re-appended block must carry the current guardrails, not an empty shell:\n" + after);
    }

    /**
     * The half-applied-patch case: a start marker with no end. The writer documents this as
     * "preserve the content before the start marker" and warns — an unrepaired file would keep the
     * stale generated text forever, because nothing after a missing end marker can be replaced.
     */
    @Test
    void aStartMarkerWithNoEndMarker_isRepairedAndWarnedAbout(@TempDir Path dir) throws Exception {
        compileOnce(dir);
        // A real damaged block opens with the generated header; that line is what marks the text
        // after the orphaned START as the writer's own rather than the developer's.
        String header = Files.readString(dir.resolve("CLAUDE.md"), StandardCharsets.UTF_8).lines()
            .filter(l -> l.contains("Generated by VibeTags")).findFirst().orElseThrow();

        Files.writeString(dir.resolve("CLAUDE.md"),
            "# My Project\n\nHand-written preamble.\n\n"
                + GuardrailFileWriter.MARKER_START_MD + "\n"
                + header + "\n"
                + "Guardrails from three releases ago that nothing can replace.\n",
            StandardCharsets.UTF_8);
        settle(dir);

        List<Diagnostic<? extends JavaFileObject>> diagnostics = compileReturningDiagnostics(dir);

        String after = Files.readString(dir.resolve("CLAUDE.md"), StandardCharsets.UTF_8);
        assertTrue(after.contains("Hand-written preamble."),
            "content before the orphaned start marker is hand-authored and must survive:\n" + after);
        assertFalse(after.contains("Guardrails from three releases ago"),
            "content after an orphaned start marker is generated output that lost its end marker; "
                + "leaving it in place is how a stale guardrail outlives the annotation:\n" + after);
        assertEquals(1, count(after, GuardrailFileWriter.MARKER_START_MD),
            "the repair must leave exactly one start marker:\n" + after);
        assertEquals(1, count(after, GuardrailFileWriter.MARKER_END_MD),
            "the repair must restore the missing end marker:\n" + after);
        assertTrue(after.contains(REASON), "the repaired block must carry the current guardrails");

        assertTrue(diagnostics.stream()
                .anyMatch(d -> d.getMessage(null).contains("malformed markers")),
            "a repair that silently rewrites a file the developer edited must say so: "
                + "no 'malformed markers' diagnostic was emitted");
    }

    /**
     * A START line with no END whose following text is not a generated block: the developer
     * pasted the marker as an example, or kept a START line from an old experiment. The repair
     * above assumed everything after it was generated and deleted it, hand-written text included
     * (#865). Without the generated header there is no evidence the text is the writer's, so the
     * file is left exactly as it is and the build says how to fix it.
     */
    @Test
    void aStrayStartMarkerAboveHandWrittenText_leavesTheFileAndSaysSo(@TempDir Path dir) throws Exception {
        compileOnce(dir);
        String handWritten = "# My Project\n\nTo opt a file in, paste this line:\n\n"
            + GuardrailFileWriter.MARKER_START_MD + "\n\n## Build\n\nmvn verify\n";
        Files.writeString(dir.resolve("CLAUDE.md"), handWritten, StandardCharsets.UTF_8);
        settle(dir);

        List<Diagnostic<? extends JavaFileObject>> diagnostics = compileReturningDiagnostics(dir);

        assertEquals(handWritten, Files.readString(dir.resolve("CLAUDE.md"), StandardCharsets.UTF_8),
            "text after a stray START line is the developer's; nothing may be deleted");
        assertTrue(diagnostics.stream().anyMatch(d -> d.getKind() == Diagnostic.Kind.WARNING
                && d.getMessage(null).contains("left untouched")),
            "a file VibeTags declines to update must say why and how to fix it");
    }

    /** A file truncated to nothing is still an opt-in signal, so the next compile must refill it. */
    @Test
    void truncatingAGeneratedFileToEmpty_repopulatesIt(@TempDir Path dir) throws Exception {
        compileOnce(dir);

        Files.writeString(dir.resolve("CLAUDE.md"), "", StandardCharsets.UTF_8);
        settle(dir);

        compileOnce(dir);

        String after = Files.readString(dir.resolve("CLAUDE.md"), StandardCharsets.UTF_8);
        assertTrue(after.contains(REASON),
            "an emptied file is an empty opt-in signal, exactly like a freshly touched one — "
                + "the next compile must repopulate it:\n" + after);
        assertEquals(1, count(after, GuardrailFileWriter.MARKER_START_MD),
            "and must do so with one marker block:\n" + after);
    }

    /**
     * An edit <em>inside</em> the markers is not hand-authored content — it is a developer editing
     * generated output, usually without realising it. The next compile has to take it back, or the
     * generated file and the annotations disagree with no way to tell which is right.
     *
     * <p>This is the case the fingerprint short-circuit is most likely to swallow: the annotations
     * did not change, so the only thing standing between the tampered file and a skipped run is
     * {@code allCachedFilesStable()}.
     */
    @Test
    void anEditInsideTheMarkers_isRevertedOnTheNextCompile(@TempDir Path dir) throws Exception {
        compileOnce(dir);

        Path claude = dir.resolve("CLAUDE.md");
        String generated = Files.readString(claude, StandardCharsets.UTF_8);
        assertTrue(generated.contains(REASON), "precondition: the reason is generated in the first place");
        Files.writeString(claude, generated.replace(REASON, "TAMPERED BY HAND"), StandardCharsets.UTF_8);
        settle(dir);

        compileOnce(dir);

        String after = Files.readString(claude, StandardCharsets.UTF_8);
        assertTrue(after.contains(REASON),
            "the annotation is the source of truth; an in-block edit must be overwritten:\n" + after);
        assertFalse(after.contains("TAMPERED BY HAND"),
            "an unchanged annotation set must not let the fingerprint short-circuit skip past a "
                + "modified output file:\n" + after);
    }

    /**
     * A generated file whose block opens on line 1, saved again by an editor that writes a UTF-8
     * byte order mark. The START marker must still be found: U+FEFF is not whitespace to
     * {@code Character.isWhitespace}, so the marker no longer owned its line, the file was taken for
     * a legacy one, and the old block, END marker included, was kept as hand-written text above a
     * second, new block. Every guardrail the old block stated stayed outside the markers for good.
     */
    @Test
    void aByteOrderMarkBeforeTheStartMarker_stillFindsTheBlock(@TempDir Path dir) throws Exception {
        compileOnce(dir);
        Path claude = dir.resolve("CLAUDE.md");
        String generated = Files.readString(claude, StandardCharsets.UTF_8);
        assertTrue(generated.startsWith("<!-- VIBETAGS-START -->"),
            "precondition: the block opens the file:\n" + generated);
        Files.writeString(claude, "﻿" + generated.replace(REASON, "TAMPERED BY HAND")
            + "\nNotes kept by hand.\n", StandardCharsets.UTF_8);
        settle(dir);

        compileOnce(dir);

        String after = Files.readString(claude, StandardCharsets.UTF_8);
        assertEquals(1, count(after, "<!-- VIBETAGS-START -->"), "one block, not two:\n" + after);
        assertEquals(1, count(after, "<!-- VIBETAGS-END -->"), "one block, not two:\n" + after);
        assertFalse(after.contains("TAMPERED BY HAND"), "the old block must be replaced:\n" + after);
        assertTrue(after.contains(REASON), after);
        assertTrue(after.contains("Notes kept by hand."), "hand-written text must survive:\n" + after);
        assertTrue(after.startsWith("﻿<!-- VIBETAGS-START -->"),
            "the byte order mark is the editor's encoding choice and stays where it was");
    }

    /**
     * {@code .vibetags-cache} is a build artifact — {@code git clean}, a CI cold clone or a
     * {@code target/} wipe removes it routinely. Losing it must cost a rebuild, not a diff: if the
     * cache is what makes output stable, then every cold CI run rewrites files and every developer
     * with a warm cache disagrees with CI about what is committed.
     */
    @Test
    void deletingTheWriteCache_reproducesByteIdenticalOutput(@TempDir Path dir) throws Exception {
        compileOnce(dir);
        String before = Files.readString(dir.resolve("CLAUDE.md"), StandardCharsets.UTF_8);

        assertTrue(Files.deleteIfExists(dir.resolve(".vibetags-cache")),
            "precondition: the cache file must exist to be deleted");
        settle(dir);

        compileOnce(dir);

        assertEquals(before, Files.readString(dir.resolve("CLAUDE.md"), StandardCharsets.UTF_8),
            "output must be a function of the annotations, not of a surviving cache file");
        assertTrue(Files.exists(dir.resolve(".vibetags-cache")),
            "the cache must be rebuilt so the run after a cold one can short-circuit again");
    }


    /**
     * The ordinary case, and the only one of these that every project is in on every build: a
     * {@code CLAUDE.md} whose hand-written half sits around a <em>well-formed</em> marker block,
     * compiled again.
     *
     * <p>Every other case in this class reaches the writer through a damaged file: the block
     * deleted, a start marker with no end, the file truncated. Those take repair paths. The steady
     * state takes the ordinary replace path, which is the one that runs on every compile of every
     * project that has ever opted in, and it was reachable here only through
     * {@code MarkerInjectionTest}, a writer-level unit test framed around an injection attempt.
     * Measured: dropping the preamble in the replace path left all five tests in this class green
     * while the invariant this class is named for was broken.
     *
     * <p>Content on both sides of the block, because they are two substrings and two chances to
     * lose one.
     */
    @Test
    void handWrittenContentAroundAWellFormedBlock_survivesTheNextCompile(@TempDir Path dir) throws Exception {
        compileOnce(dir);

        String generated = Files.readString(dir.resolve("CLAUDE.md"), StandardCharsets.UTF_8);
        assertEquals(1, count(generated, GuardrailFileWriter.MARKER_START_MD),
            "precondition: the first compile leaves one well-formed block:\n" + generated);

        Files.writeString(dir.resolve("CLAUDE.md"),
            "# My Project\n\nOnboarding notes above the block.\n\n"
                + generated.strip()
                + "\n\n## Team conventions\n\nNotes below the block.\n",
            StandardCharsets.UTF_8);
        settle(dir);

        compileOnce(dir);

        String after = Files.readString(dir.resolve("CLAUDE.md"), StandardCharsets.UTF_8);
        assertTrue(after.contains("Onboarding notes above the block."),
            "hand-authored content before the block must survive the ordinary rewrite:\n" + after);
        assertTrue(after.contains("Notes below the block."),
            "and so must hand-authored content after it:\n" + after);
        assertEquals(1, count(after, GuardrailFileWriter.MARKER_START_MD),
            "still exactly one block, not a second one appended below the human text:\n" + after);
        assertTrue(after.contains(REASON),
            "and the block still carries the guardrails:\n" + after);
    }

    /**
     * A TOML output has nowhere to put a marker line, so VibeTags writes it whole. That is right
     * for a file VibeTags wrote and destructive for one a person did: a project that already
     * configures Codex in {@code .codex/config.toml} had it replaced the first time {@code AGENTS.md}
     * was managed, which writes that file implicitly.
     */
    @Test
    void aHandWrittenCodexConfig_isNotOverwritten(@TempDir Path dir) throws Exception {
        String config = "model = \"gpt-5-codex\"\n\n[mcp_servers.docs]\ncommand = \"docs-mcp\"\n";
        Files.createDirectories(dir.resolve(".codex"));
        Files.writeString(dir.resolve(".codex/config.toml"), config, StandardCharsets.UTF_8);
        ProcessorTestHarness h = new ProcessorTestHarness(dir, false);
        h.touchOptIn("AGENTS.md");
        addLedger(h);
        h.compile();
        VibeTagsLogger.shutdown();

        assertTrue(Files.readString(dir.resolve("AGENTS.md")).contains(REASON),
            "precondition: AGENTS.md is managed, which is what writes .codex/config.toml");
        assertEquals(config, Files.readString(dir.resolve(".codex/config.toml"), StandardCharsets.UTF_8),
            "a Codex configuration VibeTags did not write must be left exactly as it is");
    }

    /** The same for the PR-Agent configuration, whose presence is the opt-in. */
    @Test
    void aHandWrittenPrAgentConfig_isNotOverwritten(@TempDir Path dir) throws Exception {
        String config = "[pr_reviewer]\nnum_code_suggestions = 3\nrequire_tests_review = true\n";
        Files.writeString(dir.resolve(".pr_agent.toml"), config, StandardCharsets.UTF_8);
        ProcessorTestHarness h = new ProcessorTestHarness(dir, false);
        h.touchOptIn("CLAUDE.md");
        addLedger(h);
        List<Diagnostic<? extends JavaFileObject>> diagnostics = h.compileReturningDiagnostics();
        VibeTagsLogger.shutdown();

        assertTrue(Files.readString(dir.resolve("CLAUDE.md")).contains(REASON), "precondition: the round generated");
        assertEquals(config, Files.readString(dir.resolve(".pr_agent.toml"), StandardCharsets.UTF_8),
            "review settings VibeTags did not write must be left exactly as they are");
        assertTrue(diagnostics.stream().anyMatch(d -> d.getKind() == Diagnostic.Kind.WARNING
                && d.getMessage(java.util.Locale.ROOT).contains(".pr_agent.toml")),
            "and the build must say why the file carries no guardrails: " + diagnostics);
    }

    // -----------------------------------------------------------------------
    // Helpers
    // -----------------------------------------------------------------------

    private static void addLedger(ProcessorTestHarness h) {
        h.addSource("com.example.Ledger",
            "package com.example;\n"
                + "import se.deversity.vibetags.annotations.AILocked;\n"
                + "@AILocked(reason = \"" + REASON + "\")\n"
                + "public class Ledger {}\n");
    }

    private static void compileOnce(Path dir) throws IOException {
        harness(dir).compile();
        VibeTagsLogger.shutdown();
    }

    private static List<Diagnostic<? extends JavaFileObject>> compileReturningDiagnostics(Path dir)
            throws IOException {
        List<Diagnostic<? extends JavaFileObject>> diagnostics =
            harness(dir).compileReturningDiagnostics();
        VibeTagsLogger.shutdown();
        return diagnostics;
    }

    /** {@code CLAUDE.md} as the sole opt-in, so the assertions are about one file and one writer. */
    private static ProcessorTestHarness harness(Path dir) throws IOException {
        ProcessorTestHarness h = new ProcessorTestHarness(dir, false);
        h.touchOptIn("CLAUDE.md");
        h.addSource("com.example.Ledger",
            "package com.example;\n"
                + "import se.deversity.vibetags.annotations.AILocked;\n"
                + "@AILocked(reason = \"" + REASON + "\")\n"
                + "public class Ledger {}\n");
        return h;
    }

    private static void settle(Path dir) throws IOException, InterruptedException {
        ProcessorTestHarness.awaitFilesystemTick(dir);
        VibeTagsLogger.shutdown();
    }

    private static int count(String haystack, String needle) {
        int n = 0;
        for (int i = haystack.indexOf(needle); i >= 0; i = haystack.indexOf(needle, i + needle.length())) {
            n++;
        }
        return n;
    }
}
