package se.deversity.vibetags.processor;

import org.junit.jupiter.api.AfterAll;
import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.parallel.Isolated;
import se.deversity.asynctest.AsyncTest;
import se.deversity.asynctest.FailOn;
import se.deversity.asynctest.Preset;
import se.deversity.asynctest.diagnostics.TrustTier;
import se.deversity.vibetags.processor.internal.GuardrailFileWriter;
import se.deversity.vibetags.processor.internal.WriteCache;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.Comparator;
import java.util.concurrent.atomic.AtomicBoolean;
import java.util.concurrent.atomic.AtomicInteger;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import java.util.stream.Stream;

/**
 * Invariant 2 under the shape a parallel reactor actually has: many writers, one file.
 *
 * <p>Every module of a {@code mvn -T} or Gradle {@code --parallel} build writes the root
 * {@code CLAUDE.md} through its own {@link GuardrailFileWriter} and {@link WriteCache}, and each one
 * reads the file, splices its block between the markers and moves the result into place.
 * {@link GuardrailFileWriterAsyncTest} gives every worker a file of its own, so it never has two
 * writers reading and replacing the same bytes. Here they do, and every snapshot of the file must
 * still hold the developer's text above and below the block exactly once, exactly one marker pair,
 * and one writer's whole body between the markers: never two bodies, never a fragment, never a
 * block spliced into a copy of another writer's block.
 *
 * <p>Which writer's body wins is not asserted. With no lock across modules the last move wins,
 * and a stale body is a cache and merge question ({@code WriteCacheCrossInstanceAsyncTest}, #908),
 * not a lost-content one.
 */
// @Isolated: real platform threads plus detector instrumentation. Runs alone so that
// pressure does not reach the javac-based e2e tests beside it. See docs/TESTS.md.
@Isolated
class GuardrailFileWriterSharedFileAsyncTest {

    private static final String HEADER = "# Generated by VibeTags | https://github.com/PIsberg/vibetags\n";
    private static final String PREAMBLE = "# Project notes written by hand";
    private static final String EPILOGUE = "## Hand-written appendix";
    private static final Pattern BODY_LINE = Pattern.compile("- guardrail line from writer \\d+");
    private static final int CYCLES_PER_INVOCATION = 20;
    private static final AtomicInteger NEXT_WRITER = new AtomicInteger();
    private static final ThreadLocal<Integer> WRITER = ThreadLocal.withInitial(NEXT_WRITER::incrementAndGet);
    private static final AtomicBoolean ANY_WRITE = new AtomicBoolean();

    private static Path root;
    private static Path shared;

    @BeforeAll
    static void setUp() throws IOException {
        root = Files.createTempDirectory("vibetags-writer-shared-file");
        shared = root.resolve("CLAUDE.md");
        Files.writeString(shared, PREAMBLE + "\n\n"
            + GuardrailFileWriter.MARKER_START_MD + "\n"
            + GuardrailFileWriter.MARKER_END_MD + "\n\n"
            + EPILOGUE + "\n");
    }

    @AfterAll
    static void tearDown() throws IOException {
        if (root == null) return;
        try (Stream<Path> paths = Files.walk(root)) {
            paths.sorted(Comparator.reverseOrder()).forEach(p -> {
                try {
                    Files.deleteIfExists(p);
                } catch (IOException ignored) {
                    // Best-effort cleanup of a temp directory; a leftover file must not fail the test.
                }
            });
        }
    }

    @AsyncTest(threads = 8, invocations = 10, timeoutMs = 120_000,
        useVirtualThreads = false, preset = Preset.ALL,
        failOn = FailOn.HIGH, minTrust = TrustTier.FACT)
    void handAuthoredTextSurvivesWritersSharingOneFile() {
        String body = "- guardrail line from writer " + WRITER.get() + "\n";
        for (int cycle = 0; cycle < CYCLES_PER_INVOCATION; cycle++) {
            // One module per worker: a writer and a cache of its own over the shared cache path.
            WriteCache cache = new WriteCache(root.resolve(WriteCache.DEFAULT_FILE_NAME));
            if (new GuardrailFileWriter(HEADER, null, null, cache).writeFileIfChanged(shared.toString(), body, true)) {
                ANY_WRITE.set(true);
            }
            cache.flush();

            // One read is one version of the file: the move replaces it whole, so whatever this
            // read returns is a file some writer produced. Windows refuses the read while a rename
            // is replacing the file; that cycle has nothing to judge.
            // Read the flag before the file: once any write has completed, no later version of the
            // file can have an empty block, because no writer writes one.
            boolean written = ANY_WRITE.get();
            String snapshot;
            try {
                snapshot = Files.readString(shared);
            } catch (IOException replacedMeanwhile) {
                continue;
            }
            assertWellFormed(snapshot, written);
        }
    }

    private static void assertWellFormed(String snapshot, boolean written) {
        require(count(snapshot, PREAMBLE) == 1, "the hand-written preamble is not there exactly once", snapshot);
        require(count(snapshot, EPILOGUE) == 1, "the hand-written appendix is not there exactly once", snapshot);
        require(count(snapshot, GuardrailFileWriter.MARKER_START_MD) == 1, "not exactly one start marker", snapshot);
        require(count(snapshot, GuardrailFileWriter.MARKER_END_MD) == 1, "not exactly one end marker", snapshot);
        int start = snapshot.indexOf(GuardrailFileWriter.MARKER_START_MD);
        int end = snapshot.indexOf(GuardrailFileWriter.MARKER_END_MD);
        require(snapshot.indexOf(PREAMBLE) < start, "the preamble moved inside or below the block", snapshot);
        require(snapshot.indexOf(EPILOGUE) > end, "the appendix moved inside or above the block", snapshot);
        String block = snapshot.substring(start, end);
        Matcher lines = BODY_LINE.matcher(block);
        int bodies = 0;
        while (lines.find()) {
            bodies++;
        }
        require(bodies == 1 || (bodies == 0 && !written),
            "the block holds " + bodies + " writers' bodies instead of one", snapshot);
    }

    private static void require(boolean condition, String problem, String snapshot) {
        if (!condition) {
            throw new AssertionError(problem + ". The file was:\n" + snapshot);
        }
    }

    private static int count(String haystack, String needle) {
        int n = 0;
        for (int i = haystack.indexOf(needle); i >= 0; i = haystack.indexOf(needle, i + needle.length())) {
            n++;
        }
        return n;
    }
}
