package se.deversity.vibetags.processor;

import org.junit.jupiter.api.Test;
import se.deversity.vibetags.processor.internal.AnnotationCollector;
import se.deversity.vibetags.processor.internal.GuardrailContentBuilder;

import java.lang.reflect.Field;
import java.util.LinkedHashSet;
import java.util.Set;

import static org.junit.jupiter.api.Assertions.assertNotNull;
import static org.junit.jupiter.api.Assertions.assertNull;

/**
 * Verifies that {@link GuardrailContentBuilder} skips per-platform StringBuilder allocations when
 * the consumer hasn't opted into that platform. Exercises {@code initBuilders()} via {@code build()}
 * (the only public entry point) and checks the internal field state with reflection.
 *
 * <p>The contract: every call site that touches one of these gated builders is itself guarded by
 * the matching {@code *Active} flag, so the field staying {@code null} for an inactive service is
 * a load-bearing assumption — not just a memory optimisation. Regressions here would show up as
 * NPEs during {@code build()}, which we also catch by running {@link GuardrailContentBuilder#build()}.
 */
class GuardrailContentBuilderLazyAllocationTest {

    private static final String GENERATED_HEADER = "# Generated by VibeTags | https://example.test\n";

    @Test
    void onlyCursorActive_leavesEveryOtherPlatformBuilderNull() throws Exception {
        AnnotationCollector empty = new AnnotationCollector();
        Set<String> active = setOf("cursor"); // Only cursor opted in.
        GuardrailContentBuilder b = new GuardrailContentBuilder(empty, active, "TestProject", GENERATED_HEADER);
        b.build(); // populates internal state via initBuilders()

        // Always-allocated baseline (cursor / claude / codex / copilot / qwen / aiExclude stay eager).
        assertFieldNotNull(b, "cursorRules");

        // Lazy fields — must stay null when their service isn't active.
        for (String name : new String[]{
            "windsurfRules", "windsurfIgnoreSection", "windsurfDraftSection",
            "windsurfPrivacySection", "windsurfCoreSection", "windsurfPerfSection", "windsurfContractSection",
            "zedRules", "zedIgnoreSection", "zedDraftSection",
            "zedPrivacySection", "zedCoreSection", "zedPerfSection", "zedContractSection",
            "codyIgnoreFile", "supermavenIgnoreFile",
            "llmsTxt", "llmsTxtContext", "llmsTxtAudit", "llmsTxtIgnore", "llmsTxtDraft",
            "llmsTxtPrivacy", "llmsTxtCore", "llmsTxtPerformance", "llmsTxtContract",
            "llmsFullTxt", "llmsFullTxtContext", "llmsFullTxtAudit", "llmsFullTxtIgnore",
            "llmsFullTxtDraft", "llmsFullTxtPrivacy", "llmsFullTxtCore",
            "llmsFullTxtPerformance", "llmsFullTxtContract",
            "cursorIgnoreFile", "claudeIgnoreFile", "copilotIgnoreFile", "qwenIgnoreFile",
            "aiderConventions", "aiderIgnore"
        }) {
            assertFieldNull(b, name);
        }
    }

    @Test
    void llmsActive_allocatesLlmsTxtAndItsSubsections() throws Exception {
        AnnotationCollector empty = new AnnotationCollector();
        Set<String> active = setOf("cursor", "llms");
        GuardrailContentBuilder b = new GuardrailContentBuilder(empty, active, "TestProject", GENERATED_HEADER);
        b.build();

        assertFieldNotNull(b, "llmsTxt");
        assertFieldNotNull(b, "llmsTxtContext");
        assertFieldNotNull(b, "llmsTxtAudit");
        assertFieldNotNull(b, "llmsTxtContract");
        // llms_full was NOT activated → its bucket stays null.
        assertFieldNull(b, "llmsFullTxt");
        assertFieldNull(b, "llmsFullTxtContext");
    }

    @Test
    void windsurfActive_allocatesWindsurfBuildersOnly() throws Exception {
        AnnotationCollector empty = new AnnotationCollector();
        Set<String> active = setOf("cursor", "windsurf");
        GuardrailContentBuilder b = new GuardrailContentBuilder(empty, active, "TestProject", GENERATED_HEADER);
        b.build();

        assertFieldNotNull(b, "windsurfRules");
        assertFieldNotNull(b, "windsurfPerfSection");
        assertFieldNull(b, "zedRules");
        assertFieldNull(b, "zedPerfSection");
    }

    @Test
    void aiderConvActive_allocatesAiderConventionsOnly() throws Exception {
        AnnotationCollector empty = new AnnotationCollector();
        Set<String> active = setOf("cursor", "aider_conventions");
        GuardrailContentBuilder b = new GuardrailContentBuilder(empty, active, "TestProject", GENERATED_HEADER);
        b.build();

        assertFieldNotNull(b, "aiderConventions");
        assertFieldNull(b, "aiderIgnore");
    }

    @Test
    void everyPerPlatformIgnoreActive_allocatesIts(@org.junit.jupiter.api.io.TempDir java.nio.file.Path tmp) throws Exception {
        AnnotationCollector empty = new AnnotationCollector();
        Set<String> active = setOf("cursor", "cursor_ignore", "claude_ignore", "copilot_ignore", "qwen_ignore");
        GuardrailContentBuilder b = new GuardrailContentBuilder(empty, active, "TestProject", GENERATED_HEADER);
        b.build();

        assertFieldNotNull(b, "cursorIgnoreFile");
        assertFieldNotNull(b, "claudeIgnoreFile");
        assertFieldNotNull(b, "copilotIgnoreFile");
        assertFieldNotNull(b, "qwenIgnoreFile");
    }

    private static Set<String> setOf(String... values) {
        Set<String> s = new LinkedHashSet<>();
        for (String v : values) s.add(v);
        return s;
    }

    private static void assertFieldNotNull(Object target, String fieldName) throws Exception {
        Field f = target.getClass().getDeclaredField(fieldName);
        f.setAccessible(true);
        assertNotNull(f.get(target),
            "Expected " + fieldName + " to be allocated for the active service set");
    }

    private static void assertFieldNull(Object target, String fieldName) throws Exception {
        Field f = target.getClass().getDeclaredField(fieldName);
        f.setAccessible(true);
        assertNull(f.get(target),
            "Expected " + fieldName + " to remain null when its service is inactive");
    }
}
