package se.deversity.vibetags.processor;

import org.junit.jupiter.api.AfterAll;
import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.io.TempDir;

import java.io.IOException;
import java.nio.file.Path;

import static org.junit.jupiter.api.Assertions.assertTrue;

/**
 * End-to-end tests for the JetBrains Junie platform (.junie/guidelines.md).
 *
 * Verifies that when .junie/guidelines.md exists on disk, the processor populates it with
 * guardrail content derived from .cursorrules but using Junie-specific headings.
 */
class JunieEndToEndTest {

    @TempDir
    static Path tempDir;

    private static ProcessorTestHarness harness;

    @BeforeAll
    static void setUp() throws IOException {
        harness = ProcessorTestHarness.withExampleSources(tempDir);
    }

    @AfterAll
    static void tearDown() {
        VibeTagsLogger.shutdown();
    }

    @Test
    void junieGuidelines_fileIsGenerated() throws IOException {
        assertTrue(harness.fileExists(".junie/guidelines.md"),
            ".junie/guidelines.md must be generated when the file exists on disk");
    }

    @Test
    void junieGuidelines_containsJunieHeading() throws IOException {
        String junie = harness.readFile(".junie/guidelines.md");
        assertTrue(junie.contains("JetBrains Junie Guidelines"),
            ".junie/guidelines.md must contain the Junie-specific heading");
    }

    @Test
    void junieGuidelines_containsVibeTagsMarkers() throws IOException {
        String junie = harness.readFile(".junie/guidelines.md");
        assertTrue(junie.contains("VIBETAGS-START"), ".junie/guidelines.md must contain VIBETAGS-START marker");
        assertTrue(junie.contains("VIBETAGS-END"), ".junie/guidelines.md must contain VIBETAGS-END marker");
    }

    @Test
    void junieGuidelines_containsLockedEntry() throws IOException {
        String junie = harness.readFile(".junie/guidelines.md");
        assertTrue(junie.contains("com.example.payment.PaymentProcessor"),
            ".junie/guidelines.md must list the @AILocked class");
    }

    @Test
    void junieGuidelines_containsLockedFilesSection() throws IOException {
        String junie = harness.readFile(".junie/guidelines.md");
        assertTrue(junie.contains("Locked Files"),
            ".junie/guidelines.md must contain a Locked Files section");
    }

    @Test
    void junieGuidelines_containsAutoGeneratedHeader() throws IOException {
        String junie = harness.readFile(".junie/guidelines.md");
        assertTrue(junie.contains("AUTO-GENERATED BY VIBETAGS"),
            ".junie/guidelines.md must have an auto-generated header");
    }
}
