package se.deversity.vibetags.processor;

import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.io.TempDir;
import se.deversity.vibetags.processor.internal.GuardrailFileWriter;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;

import static org.junit.jupiter.api.Assertions.*;

/**
 * Regression tests for marker detection when hand-authored prose *mentions* the markers.
 *
 * <p>A file may legitimately document VibeTags itself — this repository's own {@code CLAUDE.md}
 * does exactly that, in a line reading:
 *
 * <pre>- **HTML comments** (CLAUDE.md, ...): `&lt;!-- VIBETAGS-START --&gt;` / `&lt;!-- VIBETAGS-END --&gt;`</pre>
 *
 * <p>Locating the managed block with a bare {@code indexOf} matches those in-prose mentions, so the
 * writer treated the middle of a human sentence as the start of its region and overwrote the rest
 * of it — the sentence was cut in half and the generated block was injected into the wound. The
 * markers are only delimiters when the writer emitted them: alone on their own line.
 */
class MarkerInProseTest {

    private static final String HEADER = "# Generated by VibeTags\n";

    /** The exact shape of the corruption seen in this repository's own CLAUDE.md. */
    @Test
    void proseMentioningMarkersIsNotTreatedAsTheBlock(@TempDir Path tmp) throws IOException {
        GuardrailFileWriter writer = new GuardrailFileWriter(HEADER, null, null, null);
        Path file = tmp.resolve("CLAUDE.md");

        String human = """
            # CLAUDE.md

            ## Marker-based updates

            - **HTML comments** (CLAUDE.md, llms.txt): `<!-- VIBETAGS-START -->` / `<!-- VIBETAGS-END -->`
            - **Hash comments** (.cursorrules): `# VIBETAGS-START` / `# VIBETAGS-END`

            That is all.
            """;
        Files.writeString(file, human);

        writer.writeFileIfChanged(file.toString(), "GENERATED RULES", true);
        String after = Files.readString(file);

        assertTrue(after.contains(
                "- **HTML comments** (CLAUDE.md, llms.txt): `<!-- VIBETAGS-START -->` / `<!-- VIBETAGS-END -->`"),
            "the documentation sentence must survive intact, not be cut in half:\n" + after);
        assertTrue(after.contains("- **Hash comments** (.cursorrules): `# VIBETAGS-START` / `# VIBETAGS-END`"),
            "the second documentation line must survive too:\n" + after);
        assertTrue(after.contains("That is all."), "human content after the prose must not be lost:\n" + after);
        assertTrue(after.contains("GENERATED RULES"), "generated content must still be written:\n" + after);
    }

    /** A real block must still be found and replaced, even when prose above it mentions the markers. */
    @Test
    void realBlockIsStillReplacedWhenProseMentionsMarkers(@TempDir Path tmp) throws IOException {
        GuardrailFileWriter writer = new GuardrailFileWriter(HEADER, null, null, null);
        Path file = tmp.resolve("CLAUDE.md");

        String existing = """
            # Docs

            We wrap output in `<!-- VIBETAGS-START -->` and `<!-- VIBETAGS-END -->`.

            <!-- VIBETAGS-START -->
            OLD RULES
            <!-- VIBETAGS-END -->

            Trailing human notes.
            """;
        Files.writeString(file, existing);

        writer.writeFileIfChanged(file.toString(), "NEW RULES", true);
        String after = Files.readString(file);

        assertTrue(after.contains("We wrap output in `<!-- VIBETAGS-START -->` and `<!-- VIBETAGS-END -->`."),
            "prose above the block must be preserved verbatim:\n" + after);
        assertTrue(after.contains("NEW RULES"), "the block must be updated:\n" + after);
        assertFalse(after.contains("OLD RULES"), "the old block must be replaced, not duplicated:\n" + after);
        assertTrue(after.contains("Trailing human notes."), "content after the block must survive:\n" + after);
        assertEquals(1, countOccurrences(after, "<!-- VIBETAGS-START -->\n"),
            "exactly one real start marker line must exist:\n" + after);
    }

    /** Hash-marker platforms (.cursorrules and friends) have the same exposure. */
    @Test
    void hashMarkerProseIsNotTreatedAsTheBlock(@TempDir Path tmp) throws IOException {
        GuardrailFileWriter writer = new GuardrailFileWriter(HEADER, null, null, null);
        Path file = tmp.resolve(".cursorrules");

        String human = """
            Project rules.
            Our generator writes between # VIBETAGS-START and # VIBETAGS-END lines.
            Keep this note.
            """;
        Files.writeString(file, human);

        writer.writeFileIfChanged(file.toString(), "GENERATED", true);
        String after = Files.readString(file);

        assertTrue(after.contains("Our generator writes between # VIBETAGS-START and # VIBETAGS-END lines."),
            "the inline mention must survive:\n" + after);
        assertTrue(after.contains("Keep this note."), "human content must not be eaten:\n" + after);
        assertTrue(after.contains("GENERATED"), "generated content must be written:\n" + after);
    }

    /**
     * The header-citation twin of the marker-citation bug above: {@code stripLegacyVibeTagsBlock}
     * used to match the generated header anywhere in the text, so prose quoting the full header
     * line was treated as the start of a legacy block and eaten. Like the markers, the header is
     * only a delimiter when it stands on its own line.
     */
    private static final String FULL_HEADER =
        "# Generated by VibeTags | https://github.com/PIsberg/vibetags\n";

    @Test
    void headerCitationInProse_survivesAMarkerRewrite(@TempDir Path tmp) throws IOException {
        GuardrailFileWriter writer = new GuardrailFileWriter(FULL_HEADER, null, null, null);
        Path file = tmp.resolve("CLAUDE.md");

        String existing = """
            # Docs

            Every generated file starts with `# Generated by VibeTags | https://github.com/PIsberg/vibetags` as its first line.

            Keep this paragraph too.

            <!-- VIBETAGS-START -->
            OLD RULES
            <!-- VIBETAGS-END -->
            """;
        Files.writeString(file, existing);

        writer.writeFileIfChanged(file.toString(), "NEW RULES", true);
        String after = Files.readString(file);

        assertTrue(after.contains(
                "Every generated file starts with `# Generated by VibeTags | https://github.com/PIsberg/vibetags` as its first line."),
            "prose quoting the header must survive intact, not be treated as a legacy block:\n" + after);
        assertTrue(after.contains("Keep this paragraph too."),
            "content between the citation and the block must survive:\n" + after);
        assertTrue(after.contains("NEW RULES"), "the block must still be updated:\n" + after);
    }

    @Test
    void headerCitationInProse_doesNotTriggerTheLegacyOverwrite(@TempDir Path tmp) throws IOException {
        // No markers at all: a hand-authored file whose only sin is quoting the header inline.
        // The legacy-upgrade branch replaces the whole file with the generated block, so a false
        // header match here loses every hand-written line, not just a slice.
        GuardrailFileWriter writer = new GuardrailFileWriter(FULL_HEADER, null, null, null);
        Path file = tmp.resolve("CLAUDE.md");

        String human = """
            # My project notes

            VibeTags output is recognisable by the `# Generated by VibeTags | https://github.com/PIsberg/vibetags` line.

            Everything here is hand-written.
            """;
        Files.writeString(file, human);

        writer.writeFileIfChanged(file.toString(), "GENERATED RULES", true);
        String after = Files.readString(file);

        assertTrue(after.contains("# My project notes"),
            "a citation must not flip the file into legacy-overwrite mode:\n" + after);
        assertTrue(after.contains("Everything here is hand-written."),
            "hand-written content must survive:\n" + after);
        assertTrue(after.contains("GENERATED RULES"),
            "the generated block must be appended as for any hand-authored file:\n" + after);
    }

    private static int countOccurrences(String haystack, String needle) {
        int count = 0;
        for (int i = haystack.indexOf(needle); i >= 0; i = haystack.indexOf(needle, i + 1)) {
            count++;
        }
        return count;
    }
}
