package se.deversity.vibetags.processor;

import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.io.TempDir;
import se.deversity.vibetags.processor.internal.GuardrailFileWriter;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;

import static org.junit.jupiter.api.Assertions.*;

/**
 * The generated body is built from annotation attribute values, and the markdown platforms
 * (llms.txt, .clinerules, GEMINI.md, …) deliberately emit those values raw — there is no XML/JSON
 * structure to escape. But the file <em>does</em> have structure: the VibeTags markers themselves.
 *
 * <p>So a reason string that happens to contain a marker on its own line, e.g.
 *
 * <pre>{@code @AILocked(reason = "see the block:\n<!-- VIBETAGS-END -->\nnotes")}</pre>
 *
 * <p>closes the managed region early. On the next compile everything after that forged marker —
 * the true remainder of the generated block — is mistaken for hand-authored content, preserved,
 * and re-appended, so the file grows a duplicated, stale copy of itself on every build.
 *
 * <p>The writer must therefore never emit a body that contains its own delimiters.
 */
class MarkerInjectionTest {

    private static final String HEADER = "# Generated by VibeTags\n";

    @Test
    void endMarkerInsideGeneratedBodyDoesNotBreakTheBlock(@TempDir Path tmp) throws IOException {
        GuardrailFileWriter writer = new GuardrailFileWriter(HEADER, null, null, null);
        Path file = tmp.resolve("llms.txt");
        Files.writeString(file, "");

        // A reason string carrying a marker on its own line.
        String hostile = "RULE A\n<!-- VIBETAGS-END -->\nTRAILING PART OF THE RULE";
        writer.writeFileIfChanged(file.toString(), hostile, true);

        // Second compile with different content — this is where corruption surfaces.
        writer.writeFileIfChanged(file.toString(), "RULE B", true);
        String after = Files.readString(file);

        assertEquals(1, count(after, "<!-- VIBETAGS-START -->"),
            "exactly one start marker must remain:\n" + after);
        assertEquals(1, count(after, "<!-- VIBETAGS-END -->"),
            "the forged end marker must not survive as a second delimiter:\n" + after);
        assertTrue(after.contains("RULE B"), "the new content must be written:\n" + after);
        assertFalse(after.contains("TRAILING PART OF THE RULE"),
            "stale generated text must not be resurrected as 'human' content:\n" + after);
        assertFalse(after.contains("RULE A"),
            "the previous generated body must be fully replaced:\n" + after);
    }

    @Test
    void startMarkerInsideGeneratedBodyIsAlsoNeutralised(@TempDir Path tmp) throws IOException {
        GuardrailFileWriter writer = new GuardrailFileWriter(HEADER, null, null, null);
        Path file = tmp.resolve(".cursorrules");
        Files.writeString(file, "");

        writer.writeFileIfChanged(file.toString(), "A\n# VIBETAGS-START\nB", true);
        writer.writeFileIfChanged(file.toString(), "C", true);
        String after = Files.readString(file);

        assertEquals(1, count(after, "# VIBETAGS-START"), "one start delimiter only:\n" + after);
        assertEquals(1, count(after, "# VIBETAGS-END"), "one end delimiter only:\n" + after);
        assertTrue(after.contains("C"), "new content written:\n" + after);
    }

    /** Genuine human content outside the block must still survive an injection attempt. */
    @Test
    void humanContentSurvivesAnInjectionAttempt(@TempDir Path tmp) throws IOException {
        GuardrailFileWriter writer = new GuardrailFileWriter(HEADER, null, null, null);
        Path file = tmp.resolve("GEMINI.md");
        Files.writeString(file, "# My notes\n\nKeep me.\n");

        writer.writeFileIfChanged(file.toString(), "X\n<!-- VIBETAGS-END -->\nY", true);
        writer.writeFileIfChanged(file.toString(), "Z", true);
        String after = Files.readString(file);

        assertTrue(after.contains("Keep me."), "hand-authored content must survive:\n" + after);
        assertEquals(1, count(after, "<!-- VIBETAGS-END -->"), "one end delimiter only:\n" + after);
        assertTrue(after.contains("Z"), "new content written:\n" + after);
    }

    private static int count(String haystack, String needle) {
        int n = 0;
        for (int i = haystack.indexOf(needle); i >= 0; i = haystack.indexOf(needle, i + 1)) n++;
        return n;
    }
}
