package se.deversity.vibetags.processor;

import org.junit.jupiter.api.AfterAll;
import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.io.TempDir;

import java.io.IOException;
import java.nio.file.Path;

import static org.junit.jupiter.api.Assertions.*;

/**
 * End-to-end tests for platforms added in v0.9.6:
 * GEMINI.md (Google Gemini official markdown) and .antigravityignore (Antigravity AI).
 */
class NewPlatformsV3EndToEndTest {

    @TempDir
    static Path tempDir;

    private static ProcessorTestHarness harness;

    @BeforeAll
    static void setUp() throws IOException {
        harness = ProcessorTestHarness.withExampleSources(tempDir);
    }

    @AfterAll
    static void tearDown() {
        VibeTagsLogger.shutdown();
    }

    // -----------------------------------------------------------------------
    // File existence
    // -----------------------------------------------------------------------

    @Test
    void testGeminiMdExists() {
        assertTrue(harness.fileExists("GEMINI.md"), "GEMINI.md should exist");
    }

    @Test
    void testAntigravityIgnoreExists() {
        assertTrue(harness.fileExists(".antigravityignore"), ".antigravityignore should exist");
    }

    // -----------------------------------------------------------------------
    // GEMINI.md — content mirrors gemini_instructions.md
    // -----------------------------------------------------------------------

    @Test
    void testGeminiMdHasHeader() throws IOException {
        String content = harness.readFile("GEMINI.md");

        assertTrue(content.contains("# GEMINI AI INSTRUCTIONS"),
            "GEMINI.md should have the GEMINI AI INSTRUCTIONS header");
        assertTrue(content.contains("Generated by VibeTags"),
            "GEMINI.md should contain the generated-by header");
    }

    @Test
    void testGeminiMdHasLockedFilesSection() throws IOException {
        String content = harness.readFile("GEMINI.md");

        assertTrue(content.contains("LOCKED FILES"),
            "GEMINI.md should have locked files section");
        assertTrue(content.contains("PaymentProcessor"),
            "GEMINI.md should mention @AILocked PaymentProcessor");
    }

    @Test
    void testGeminiMdHasContextualRules() throws IOException {
        String content = harness.readFile("GEMINI.md");

        assertTrue(content.contains("CONTEXTUAL RULES"),
            "GEMINI.md should have contextual rules section");
        assertTrue(content.contains("authentication flow"),
            "GEMINI.md should contain @AIContext focus value");
    }

    @Test
    void testGeminiMdHasAuditSection() throws IOException {
        String content = harness.readFile("GEMINI.md");

        assertTrue(content.contains("CONTINUOUS AUDIT REQUIREMENTS"),
            "GEMINI.md should have continuous audit requirements section");
        assertTrue(content.contains("DatabaseConnector"),
            "GEMINI.md should mention @AIAudit DatabaseConnector");
        assertTrue(content.contains("SQL Injection"),
            "GEMINI.md should include SQL Injection check");
    }

    @Test
    void testGeminiMdHasIgnoredElements() throws IOException {
        String content = harness.readFile("GEMINI.md");

        assertTrue(content.contains("IGNORED ELEMENTS"),
            "GEMINI.md should have ignored elements section");
        assertTrue(content.contains("GeneratedMetadata"),
            "GEMINI.md should mention @AIIgnore GeneratedMetadata");
    }

    @Test
    void testGeminiMdHasVibeTagsMarkers() throws IOException {
        String content = harness.readFile("GEMINI.md");

        assertTrue(content.contains("<!-- VIBETAGS-START -->"),
            "GEMINI.md should use HTML comment start marker");
        assertTrue(content.contains("<!-- VIBETAGS-END -->"),
            "GEMINI.md should use HTML comment end marker");
    }

    @Test
    void testGeminiMdContentMatchesGeminiInstructionsMd() throws IOException {
        String geminiMd       = harness.readFile("GEMINI.md");
        String geminiInstr    = harness.readFile("gemini_instructions.md");

        // Both files should contain identical guardrail content (between markers)
        assertTrue(geminiMd.contains("LOCKED FILES"),    "GEMINI.md should have locked section");
        assertTrue(geminiInstr.contains("LOCKED FILES"), "gemini_instructions.md should have locked section");
        assertTrue(geminiMd.contains("PaymentProcessor"),    "GEMINI.md should mention PaymentProcessor");
        assertTrue(geminiInstr.contains("PaymentProcessor"), "gemini_instructions.md should mention PaymentProcessor");
    }

    // -----------------------------------------------------------------------
    // .antigravityignore — glob-pattern ignore file
    // -----------------------------------------------------------------------

    @Test
    void testAntigravityIgnoreHasHeader() throws IOException {
        String content = harness.readFile(".antigravityignore");

        assertTrue(content.contains("AUTO-GENERATED BY VIBETAGS"),
            ".antigravityignore should have auto-generated header");
        assertTrue(content.contains("Antigravity"),
            ".antigravityignore should identify the target platform");
    }

    @Test
    void testAntigravityIgnoreHasIgnoredPattern() throws IOException {
        String content = harness.readFile(".antigravityignore");

        assertTrue(content.contains("GeneratedMetadata"),
            ".antigravityignore should have @AIIgnore GeneratedMetadata glob");
        assertTrue(content.contains(".java"),
            ".antigravityignore should use .java glob patterns");
    }

    @Test
    void testAntigravityIgnoreHasVibeTagsMarkers() throws IOException {
        String content = harness.readFile(".antigravityignore");

        assertTrue(content.contains("# VIBETAGS-START"),
            ".antigravityignore should use hash-comment start marker");
        assertTrue(content.contains("# VIBETAGS-END"),
            ".antigravityignore should use hash-comment end marker");
    }

    @Test
    void testAntigravityIgnoreMatchesOtherIgnoreFiles() throws IOException {
        String antigravity = harness.readFile(".antigravityignore");
        String codeium     = harness.readFile(".codeiumignore");
        String dbl         = harness.readFile(".doubleignore");

        // All three ignore files should list the same @AIIgnore glob patterns
        assertTrue(antigravity.contains("GeneratedMetadata"),
            ".antigravityignore should list @AIIgnore elements");
        assertTrue(codeium.contains("GeneratedMetadata"),
            ".codeiumignore should list @AIIgnore elements");
        assertTrue(dbl.contains("GeneratedMetadata"),
            ".doubleignore should list @AIIgnore elements");
    }
}
