package se.deversity.vibetags.processor;

import org.junit.jupiter.api.AfterAll;
import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.io.TempDir;

import java.io.IOException;
import java.nio.file.Path;

import static org.junit.jupiter.api.Assertions.*;

/**
 * End-to-end tests for the platforms added for the AI PR-reviewer, context-packer, and
 * editor expansion:
 * <ul>
 *   <li>Context-packer ignore files: {@code .repomixignore}, {@code .gitingestignore},
 *       {@code .gptignore}, {@code .ghostcoderignore}, {@code .piecesignore}</li>
 *   <li>AI PR reviewers: {@code .coderabbit.yaml}, {@code .pr_agent.toml}, {@code ellipsis.yaml}</li>
 *   <li>Editors &amp; modes: {@code .void/rules.md}, {@code .roomodes}</li>
 * </ul>
 */
class NewPlatformsV4EndToEndTest {

    @TempDir
    static Path tempDir;

    private static ProcessorTestHarness harness;

    @BeforeAll
    static void setUp() throws IOException {
        harness = ProcessorTestHarness.withExampleSources(tempDir);
    }

    @AfterAll
    static void tearDown() {
        VibeTagsLogger.shutdown();
    }

    // -----------------------------------------------------------------------
    // File existence
    // -----------------------------------------------------------------------

    @Test
    void testAllNewFilesExist() {
        assertTrue(harness.fileExists(".repomixignore"), ".repomixignore should exist");
        assertTrue(harness.fileExists(".gitingestignore"), ".gitingestignore should exist");
        assertTrue(harness.fileExists(".gptignore"), ".gptignore should exist");
        assertTrue(harness.fileExists(".ghostcoderignore"), ".ghostcoderignore should exist");
        assertTrue(harness.fileExists(".piecesignore"), ".piecesignore should exist");
        assertTrue(harness.fileExists(".coderabbit.yaml"), ".coderabbit.yaml should exist");
        assertTrue(harness.fileExists(".pr_agent.toml"), ".pr_agent.toml should exist");
        assertTrue(harness.fileExists("ellipsis.yaml"), "ellipsis.yaml should exist");
        assertTrue(harness.fileExists(".void/rules.md"), ".void/rules.md should exist");
        assertTrue(harness.fileExists(".roomodes"), ".roomodes should exist");
    }

    // -----------------------------------------------------------------------
    // Context-packer ignore files
    // -----------------------------------------------------------------------

    @Test
    void testRepomixIgnoreContent() throws IOException {
        String content = harness.readFile(".repomixignore");
        assertTrue(content.contains("AUTO-GENERATED BY VIBETAGS"), "should have generated header");
        assertTrue(content.contains("Repomix"), "should identify Repomix");
        assertTrue(content.contains("GeneratedMetadata"), "should list @AIIgnore element");
        assertTrue(content.contains(".java"), "should use .java globs");
        assertTrue(content.contains("# VIBETAGS-START"), "should use hash markers");
        assertTrue(content.contains("# VIBETAGS-END"), "should close hash markers");
    }

    @Test
    void testContextPackerIgnoreFilesShareContent() throws IOException {
        for (String f : new String[]{".gitingestignore", ".gptignore", ".ghostcoderignore", ".piecesignore"}) {
            String content = harness.readFile(f);
            assertTrue(content.contains("GeneratedMetadata"), f + " should list @AIIgnore elements");
            assertTrue(content.contains("# VIBETAGS-START"), f + " should use hash markers");
        }
    }

    @Test
    void testGptIgnoreIdentifiesPlatform() throws IOException {
        assertTrue(harness.readFile(".gptignore").contains("GPT context packer"),
            ".gptignore should identify the GPT context packer");
        assertTrue(harness.readFile(".ghostcoderignore").contains("Ghostcoder"),
            ".ghostcoderignore should identify Ghostcoder");
        assertTrue(harness.readFile(".piecesignore").contains("Pieces"),
            ".piecesignore should identify Pieces");
    }

    // -----------------------------------------------------------------------
    // CodeRabbit
    // -----------------------------------------------------------------------

    @Test
    void testCodeRabbitYaml() throws IOException {
        String content = harness.readFile(".coderabbit.yaml");
        assertTrue(content.contains("reviews:"), "should declare reviews block");
        assertTrue(content.contains("path_instructions:"), "should declare path_instructions");
        assertTrue(content.contains("**/*.java"), "should target Java sources");
        assertTrue(content.contains("PaymentProcessor"), "should mention @AILocked element");
        assertTrue(content.contains("# VIBETAGS-START"), "yaml should use hash markers");
    }

    // -----------------------------------------------------------------------
    // Ellipsis
    // -----------------------------------------------------------------------

    @Test
    void testEllipsisYaml() throws IOException {
        String content = harness.readFile("ellipsis.yaml");
        assertTrue(content.contains("version: 1.3"), "should declare Ellipsis version");
        assertTrue(content.contains("pr_review:"), "should declare pr_review block");
        assertTrue(content.contains("rules:"), "should declare rules list");
        assertTrue(content.contains("PaymentProcessor"), "should list @AILocked element as a rule");
        assertTrue(content.contains("# VIBETAGS-START"), "yaml should use hash markers");
    }

    // -----------------------------------------------------------------------
    // PR-Agent (TOML — full overwrite, no markers)
    // -----------------------------------------------------------------------

    @Test
    void testPrAgentToml() throws IOException {
        String content = harness.readFile(".pr_agent.toml");
        assertTrue(content.contains("[pr_reviewer]"), "should declare pr_reviewer section");
        assertTrue(content.contains("extra_instructions"), "should set extra_instructions");
        assertTrue(content.contains("PaymentProcessor"), "should mention @AILocked element");
        assertFalse(content.contains("# VIBETAGS-START"), "toml is overwritten without markers");
    }

    // -----------------------------------------------------------------------
    // Void editor
    // -----------------------------------------------------------------------

    @Test
    void testVoidRulesMd() throws IOException {
        String content = harness.readFile(".void/rules.md");
        assertTrue(content.contains("LOCKED FILES"), "should mirror Cursor markdown layout");
        assertTrue(content.contains("PaymentProcessor"), "should mention @AILocked element");
        assertTrue(content.contains("<!-- VIBETAGS-START -->"), "md should use HTML markers");
    }

    // -----------------------------------------------------------------------
    // Roo modes
    // -----------------------------------------------------------------------

    @Test
    void testRooModes() throws IOException {
        String content = harness.readFile(".roomodes");
        assertTrue(content.contains("customModes:"), "should declare customModes list");
        assertTrue(content.contains("vibetags-architect"), "should define the VibeTags Architect mode");
        assertTrue(content.contains("customInstructions:"), "should carry custom instructions");
        assertTrue(content.contains("PaymentProcessor"), "should embed guardrails in instructions");
        assertTrue(content.contains("# VIBETAGS-START"), "roomodes should use hash markers");
    }
}
