package se.deversity.vibetags.processor;

import org.junit.jupiter.api.AfterAll;
import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.io.TempDir;

import java.io.IOException;
import java.nio.file.Path;

import static org.junit.jupiter.api.Assertions.*;

/**
 * End-to-end tests for platforms added in v0.9.6: GEMINI.md (Google Gemini official markdown).
 * .antigravityignore (Antigravity AI) was removed in 1.4 (#720).
 */
class NewPlatformsV3EndToEndTest {

    @TempDir
    static Path tempDir;

    private static ProcessorTestHarness harness;

    @BeforeAll
    static void setUp() throws IOException {
        harness = ProcessorTestHarness.withExampleSources(tempDir);
    }

    @AfterAll
    static void tearDown() {
        VibeTagsLogger.shutdown();
    }

    // -----------------------------------------------------------------------
    // File existence
    // -----------------------------------------------------------------------

    @Test
    void testGeminiMdExists() {
        assertTrue(harness.fileExists("GEMINI.md"), "GEMINI.md should exist");
    }

    // -----------------------------------------------------------------------
    // GEMINI.md
    // -----------------------------------------------------------------------

    @Test
    void testGeminiMdHasHeader() throws IOException {
        String content = harness.readFile("GEMINI.md");

        assertTrue(content.contains("# GEMINI AI INSTRUCTIONS"),
            "GEMINI.md should have the GEMINI AI INSTRUCTIONS header");
        assertTrue(content.contains("Generated by VibeTags"),
            "GEMINI.md should contain the generated-by header");
    }

    @Test
    void testGeminiMdHasLockedFilesSection() throws IOException {
        String content = harness.readFile("GEMINI.md");

        assertTrue(content.contains("LOCKED FILES"),
            "GEMINI.md should have locked files section");
        assertTrue(content.contains("PaymentProcessor"),
            "GEMINI.md should mention @AILocked PaymentProcessor");
    }

    @Test
    void testGeminiMdHasContextualRules() throws IOException {
        String content = harness.readFile("GEMINI.md");

        assertTrue(content.contains("CONTEXTUAL RULES"),
            "GEMINI.md should have contextual rules section");
        assertTrue(content.contains("authentication flow"),
            "GEMINI.md should contain @AIContext focus value");
    }

    @Test
    void testGeminiMdHasAuditSection() throws IOException {
        String content = harness.readFile("GEMINI.md");

        assertTrue(content.contains("CONTINUOUS AUDIT REQUIREMENTS"),
            "GEMINI.md should have continuous audit requirements section");
        assertTrue(content.contains("DatabaseConnector"),
            "GEMINI.md should mention @AIAudit DatabaseConnector");
        assertTrue(content.contains("SQL Injection"),
            "GEMINI.md should include SQL Injection check");
    }

    @Test
    void testGeminiMdHasIgnoredElements() throws IOException {
        String content = harness.readFile("GEMINI.md");

        assertTrue(content.contains("IGNORED ELEMENTS"),
            "GEMINI.md should have ignored elements section");
        assertTrue(content.contains("GeneratedMetadata"),
            "GEMINI.md should mention @AIIgnore GeneratedMetadata");
    }

    @Test
    void testGeminiMdHasVibeTagsMarkers() throws IOException {
        String content = harness.readFile("GEMINI.md");

        assertTrue(content.contains("<!-- VIBETAGS-START -->"),
            "GEMINI.md should use HTML comment start marker");
        assertTrue(content.contains("<!-- VIBETAGS-END -->"),
            "GEMINI.md should use HTML comment end marker");
    }

    @Test
    void testGeminiMdCarriesTheGuardrails() throws IOException {
        String geminiMd = harness.readFile("GEMINI.md");

        assertTrue(geminiMd.contains("LOCKED FILES"), "GEMINI.md should have locked section");
        assertTrue(geminiMd.contains("PaymentProcessor"), "GEMINI.md should mention PaymentProcessor");
        // Gemini's own wording, from SectionCatalog's Gemini overrides (#645 moved them to GEMINI_MD)
        assertTrue(geminiMd.contains("CONTINUOUS AUDIT REQUIREMENTS"), "GEMINI.md should use Gemini's audit heading");
    }
}
