package se.deversity.vibetags.processor;

import org.junit.jupiter.api.AfterAll;
import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.io.TempDir;

import java.io.IOException;
import java.nio.file.Path;

import static org.junit.jupiter.api.Assertions.*;

/**
 * End-to-end tests for the platforms added in v0.8.0 that 1.4 still writes: Codeium. PearAI,
 * Mentat, Sweep, Plandex, Double.bot and Open Interpreter were removed in 1.4 (#720).
 */
@Tag("e2e")
class NewPlatformsV2EndToEndTest {

    @TempDir
    static Path tempDir;

    private static ProcessorTestHarness harness;

    @BeforeAll
    static void setUp() throws IOException {
        harness = ProcessorTestHarness.withExampleSources(tempDir);
    }

    @AfterAll
    static void tearDown() {
        VibeTagsLogger.shutdown();
    }

    // -----------------------------------------------------------------------
    // Codeium .codeiumignore
    // -----------------------------------------------------------------------

    @Test
    void testCodeiumIgnoreHasIgnoredPattern() throws IOException {
        String content = harness.readFile(".codeiumignore");

        assertTrue(content.contains("AUTO-GENERATED BY VIBETAGS"), "Should have auto-generated header");
        assertTrue(content.contains("GeneratedMetadata"), "Should have @AIIgnore GeneratedMetadata glob");
        assertTrue(content.contains(".java"), "Should use .java glob patterns");
    }

    @Test
    void testCodeiumIgnoreHasVibeTagsMarkers() throws IOException {
        String content = harness.readFile(".codeiumignore");

        assertTrue(content.contains("# VIBETAGS-START"), "Should have hash-comment start marker");
        assertTrue(content.contains("# VIBETAGS-END"), "Should have hash-comment end marker");
    }
}
