package se.deversity.vibetags.processor;

import org.junit.jupiter.api.AfterAll;
import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.io.TempDir;

import java.io.IOException;
import java.nio.file.Path;

import static org.junit.jupiter.api.Assertions.*;

/**
 * End-to-end tests for platforms added in v0.7.0:
 * Windsurf, Zed, Sourcegraph Cody, Supermaven, and the granular rule directories
 * for Windsurf, Continue, Tabnine, Amazon Q, and the universal .ai/rules/ standard.
 */
class NewPlatformsEndToEndTest {

    @TempDir
    static Path tempDir;

    private static ProcessorTestHarness harness;

    @BeforeAll
    static void setUp() throws IOException {
        harness = ProcessorTestHarness.withExampleSources(tempDir);
    }

    @AfterAll
    static void tearDown() {
        VibeTagsLogger.shutdown();
    }

    // -----------------------------------------------------------------------
    // File existence
    // -----------------------------------------------------------------------

    @Test
    void testNewFlatFilesExist() {
        assertTrue(harness.fileExists(".windsurfrules"), ".windsurfrules should exist");
        assertTrue(harness.fileExists(".rules"), ".rules should exist");
        assertTrue(harness.fileExists(".cody/config.json"), ".cody/config.json should exist");
        assertTrue(harness.fileExists(".codyignore"), ".codyignore should exist");
        assertTrue(harness.fileExists(".supermavenignore"), ".supermavenignore should exist");
    }

    @Test
    void testNewGranularDirectoriesExist() {
        assertTrue(harness.fileExists(".windsurf/rules/com-example-payment-PaymentProcessor.md"),
            ".windsurf/rules should have PaymentProcessor rule");
        assertTrue(harness.fileExists(".continue/rules/com-example-payment-PaymentProcessor.md"),
            ".continue/rules should have PaymentProcessor rule");
        assertTrue(harness.fileExists(".tabnine/guidelines/com-example-payment-PaymentProcessor.md"),
            ".tabnine/guidelines should have PaymentProcessor rule");
        assertTrue(harness.fileExists(".amazonq/rules/com-example-payment-PaymentProcessor.md"),
            ".amazonq/rules should have PaymentProcessor rule");
        assertTrue(harness.fileExists(".ai/rules/com-example-payment-PaymentProcessor.md"),
            ".ai/rules should have PaymentProcessor rule");
    }

    // -----------------------------------------------------------------------
    // Windsurf .windsurfrules
    // -----------------------------------------------------------------------

    @Test
    void testWindsurfRulesHasCorrectStructure() throws IOException {
        String content = harness.readFile(".windsurfrules");

        assertTrue(content.contains("AUTO-GENERATED AI RULES"), "Should have auto-generated header");
        assertTrue(content.contains("Generated by VibeTags |"), "Should have attribution");
        assertTrue(content.contains("Do not edit manually"), "Should have edit warning");
        assertTrue(content.contains("LOCKED FILES"), "Should have locked files section");
        assertTrue(content.contains("CONTEXTUAL RULES"), "Should have contextual rules section");
    }

    @Test
    void testWindsurfRulesHasLockedFiles() throws IOException {
        String content = harness.readFile(".windsurfrules");

        assertTrue(content.contains("PaymentProcessor"), "Should mention @AILocked PaymentProcessor");
        assertTrue(content.contains("SecurityConfig"), "Should mention @AILocked SecurityConfig");
    }

    @Test
    void testWindsurfRulesHasContextRules() throws IOException {
        String content = harness.readFile(".windsurfrules");

        assertTrue(content.contains("StringParser"), "Should mention @AIContext StringParser");
        assertTrue(content.contains("memory usage"), "Should include focus from @AIContext");
        assertTrue(content.contains("java.util.regex"), "Should include avoids from @AIContext");
    }

    @Test
    void testWindsurfRulesHasSecurityAudits() throws IOException {
        String content = harness.readFile(".windsurfrules");

        assertTrue(content.contains("MANDATORY SECURITY AUDITS"), "Should have security audits section");
        assertTrue(content.contains("DatabaseConnector"), "Should mention @AIAudit DatabaseConnector");
        assertTrue(content.contains("SQL Injection"), "Should mention SQL Injection");
        assertTrue(content.contains("Thread Safety"), "Should mention Thread Safety");
    }

    @Test
    void testWindsurfRulesHasIgnoredElements() throws IOException {
        String content = harness.readFile(".windsurfrules");

        assertTrue(content.contains("IGNORED ELEMENTS"), "Should have ignored elements section");
        assertTrue(content.contains("GeneratedMetadata"), "Should mention @AIIgnore GeneratedMetadata");
    }

    @Test
    void testWindsurfRulesHasImplementationTasks() throws IOException {
        String content = harness.readFile(".windsurfrules");

        assertTrue(content.contains("IMPLEMENTATION TASKS"), "Should have implementation tasks section");
        assertTrue(content.contains("NotificationService"), "Should mention @AIDraft NotificationService");
    }

    @Test
    void testWindsurfRulesHasPrivacyGuardrails() throws IOException {
        String content = harness.readFile(".windsurfrules");

        assertTrue(content.contains("PII"), "Should have PII / privacy guardrails section");
    }

    @Test
    void testWindsurfRulesHasCoreAndPerformance() throws IOException {
        String content = harness.readFile(".windsurfrules");

        assertTrue(content.contains("CORE FUNCTIONALITY"), "Should have core functionality section");
        assertTrue(content.contains("CriticalService"), "Should mention @AICore CriticalService");
        assertTrue(content.contains("PERFORMANCE CONSTRAINTS"), "Should have performance constraints section");
        assertTrue(content.contains("HotPathRouter"), "Should mention @AIPerformance HotPathRouter");
    }

    // -----------------------------------------------------------------------
    // Zed .rules
    // -----------------------------------------------------------------------

    @Test
    void testZedRulesHasCorrectStructure() throws IOException {
        String content = harness.readFile(".rules");

        assertTrue(content.contains("AUTO-GENERATED AI RULES"), "Should have auto-generated header");
        assertTrue(content.contains("Generated by VibeTags |"), "Should have attribution");
        assertTrue(content.contains("Locked Files"), "Should have locked files section");
        assertTrue(content.contains("Context Guidelines"), "Should have context guidelines section");
    }

    @Test
    void testZedRulesHasLockedFiles() throws IOException {
        String content = harness.readFile(".rules");

        assertTrue(content.contains("PaymentProcessor"), "Should mention @AILocked PaymentProcessor");
        assertTrue(content.contains("SecurityConfig"), "Should mention @AILocked SecurityConfig");
    }

    @Test
    void testZedRulesHasSecurityAudits() throws IOException {
        String content = harness.readFile(".rules");

        assertTrue(content.contains("Security Audits"), "Should have security audits section");
        assertTrue(content.contains("DatabaseConnector"), "Should mention DatabaseConnector");
        assertTrue(content.contains("SQL Injection"), "Should mention SQL Injection");
    }

    @Test
    void testZedRulesHasCoreAndPerformance() throws IOException {
        String content = harness.readFile(".rules");

        assertTrue(content.contains("Core Functionality"), "Should have Core Functionality section");
        assertTrue(content.contains("CriticalService"), "Should mention @AICore CriticalService");
        assertTrue(content.contains("Performance Constraints"), "Should have Performance Constraints section");
        assertTrue(content.contains("HotPathRouter"), "Should mention @AIPerformance HotPathRouter");
    }

    @Test
    void testZedRulesHasIgnoredElements() throws IOException {
        String content = harness.readFile(".rules");

        assertTrue(content.contains("Ignored Elements"), "Should have ignored elements section");
        assertTrue(content.contains("GeneratedMetadata"), "Should mention @AIIgnore GeneratedMetadata");
    }

    // -----------------------------------------------------------------------
    // Cody .cody/config.json
    // -----------------------------------------------------------------------

    @Test
    void testCodyConfigHasCorrectFormat() throws IOException {
        String content = harness.readFile(".cody/config.json");

        assertTrue(content.contains("customCommands"), "Should have customCommands array");
        assertTrue(content.contains("vibetags-review"), "Should have vibetags-review command");
        assertTrue(content.contains("vibetags-audit"), "Should have vibetags-audit command");
    }

    @Test
    void testCodyConfigIsValidJsonStructure() throws IOException {
        String content = harness.readFile(".cody/config.json");

        assertTrue(content.startsWith("{"), "Should start with {");
        assertTrue(content.trim().endsWith("}"), "Should end with }");
        assertTrue(content.contains("\"description\""), "Should have description field");
        assertTrue(content.contains("\"prompt\""), "Should have prompt field");
    }

    // -----------------------------------------------------------------------
    // Ignore files — .codyignore and .supermavenignore
    // -----------------------------------------------------------------------

    @Test
    void testCodyIgnoreHasIgnoredPattern() throws IOException {
        String content = harness.readFile(".codyignore");

        assertTrue(content.contains("AUTO-GENERATED BY VIBETAGS"), "Should have auto-generated header");
        assertTrue(content.contains("GeneratedMetadata"), "Should have @AIIgnore GeneratedMetadata glob");
        assertTrue(content.contains(".java"), "Should use .java glob patterns");
    }

    @Test
    void testSupermavenIgnoreHasIgnoredPattern() throws IOException {
        String content = harness.readFile(".supermavenignore");

        assertTrue(content.contains("AUTO-GENERATED BY VIBETAGS"), "Should have auto-generated header");
        assertTrue(content.contains("GeneratedMetadata"), "Should have @AIIgnore GeneratedMetadata glob");
        assertTrue(content.contains(".java"), "Should use .java glob patterns");
    }

    // -----------------------------------------------------------------------
    // Windsurf granular .windsurf/rules/*.md
    // -----------------------------------------------------------------------

    @Test
    void testWindsurfGranularRulesHaveYamlFrontMatter() throws IOException {
        String content = harness.readFile(".windsurf/rules/com-example-payment-PaymentProcessor.md");

        assertTrue(content.startsWith("---"), "Should start with YAML front-matter");
        assertTrue(content.contains("description: \"AI rules for com.example.payment.PaymentProcessor\""),
            "Should have description in front-matter");
        assertTrue(content.contains("globs: [\"**/PaymentProcessor.java\"]"),
            "Should have globs in front-matter");
        assertTrue(content.contains("alwaysApply: false"), "Should have alwaysApply field");
    }

    @Test
    void testWindsurfGranularRulesHaveContent() throws IOException {
        String content = harness.readFile(".windsurf/rules/com-example-payment-PaymentProcessor.md");

        assertTrue(content.contains("# Rules for PaymentProcessor"), "Should have rules heading");
        assertTrue(content.contains("Locked Status"), "Should have locked status section");
        assertTrue(content.contains("VIBETAGS-START"), "Should have VibeTags markers");
    }

    // -----------------------------------------------------------------------
    // Continue granular .continue/rules/*.md
    // -----------------------------------------------------------------------

    @Test
    void testContinueGranularRulesHaveYamlFrontMatter() throws IOException {
        String content = harness.readFile(".continue/rules/com-example-payment-PaymentProcessor.md");

        assertTrue(content.startsWith("---"), "Should start with YAML front-matter");
        assertTrue(content.contains("globs: [\"**/PaymentProcessor.java\"]"),
            "Should have globs in front-matter");
        assertTrue(content.contains("alwaysApply: false"), "Should have alwaysApply field");
    }

    @Test
    void testContinueGranularRulesHaveContent() throws IOException {
        String content = harness.readFile(".continue/rules/com-example-payment-PaymentProcessor.md");

        assertTrue(content.contains("# Rules for PaymentProcessor"), "Should have rules heading");
        assertTrue(content.contains("VIBETAGS-START"), "Should have VibeTags markers");
    }

    // -----------------------------------------------------------------------
    // Tabnine granular .tabnine/guidelines/*.md
    // -----------------------------------------------------------------------

    @Test
    void testTabnineGranularRulesHaveContent() throws IOException {
        String content = harness.readFile(".tabnine/guidelines/com-example-payment-PaymentProcessor.md");

        assertTrue(content.contains("AI Guidelines for PaymentProcessor"), "Should have guidelines heading");
        assertTrue(content.contains("Locked Status"), "Should have locked status content");
        assertFalse(content.startsWith("---"), "Tabnine uses plain Markdown, no front-matter");
    }

    // -----------------------------------------------------------------------
    // Amazon Q granular .amazonq/rules/*.md
    // -----------------------------------------------------------------------

    @Test
    void testAmazonQGranularRulesHaveContent() throws IOException {
        String content = harness.readFile(".amazonq/rules/com-example-payment-PaymentProcessor.md");

        assertTrue(content.contains("Amazon Q Rules for PaymentProcessor"), "Should have Amazon Q heading");
        assertTrue(content.contains("Locked Status"), "Should have locked status content");
        assertFalse(content.startsWith("---"), "Amazon Q uses plain Markdown, no front-matter");
    }

    // -----------------------------------------------------------------------
    // Universal .ai/rules/*.md
    // -----------------------------------------------------------------------

    @Test
    void testAiRulesGranularHaveContent() throws IOException {
        String content = harness.readFile(".ai/rules/com-example-payment-PaymentProcessor.md");

        assertTrue(content.contains("# Rules for PaymentProcessor"), "Should have rules heading");
        assertTrue(content.contains("Locked Status"), "Should have locked status content");
        assertTrue(content.contains("VIBETAGS-START"), "Should have VibeTags markers");
    }

    // -----------------------------------------------------------------------
    // All annotation types appear in windsurf
    // -----------------------------------------------------------------------

    @Test
    void testAllAnnotationTypesRepresentedInWindsurfRules() throws IOException {
        String content = harness.readFile(".windsurfrules");

        assertTrue(content.contains("PaymentProcessor"),   "@AILocked must appear");
        assertTrue(content.contains("memory usage"),       "@AIContext must appear");
        assertTrue(content.contains("IMPLEMENTATION TASKS"), "@AIDraft must appear");
        assertTrue(content.contains("SQL Injection"),      "@AIAudit must appear");
        assertTrue(content.contains("GeneratedMetadata"),  "@AIIgnore must appear");
        assertTrue(content.contains("PII"),                "@AIPrivacy must appear");
        assertTrue(content.contains("CORE FUNCTIONALITY"), "@AICore must appear");
        assertTrue(content.contains("PERFORMANCE CONSTRAINTS"), "@AIPerformance must appear");
    }

    // -----------------------------------------------------------------------
    // Marker-based updates work for windsurf/zed
    // -----------------------------------------------------------------------

    @Test
    void testWindsurfRulesHasVibeTagsMarkers() throws IOException {
        String content = harness.readFile(".windsurfrules");

        assertTrue(content.contains("# VIBETAGS-START"), "Should have hash-comment start marker");
        assertTrue(content.contains("# VIBETAGS-END"), "Should have hash-comment end marker");
    }

    @Test
    void testZedRulesHasVibeTagsMarkers() throws IOException {
        String content = harness.readFile(".rules");

        assertTrue(content.contains("# VIBETAGS-START"), "Should have hash-comment start marker");
        assertTrue(content.contains("# VIBETAGS-END"), "Should have hash-comment end marker");
    }
}
