package se.deversity.vibetags.processor;

import org.junit.jupiter.api.AfterAll;
import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.io.TempDir;

import java.io.IOException;
import java.nio.file.Path;

import static org.junit.jupiter.api.Assertions.*;

/**
 * End-to-end tests specifically for Qwen-generated files.
 * Self-contained: compiles annotated test sources into a {@code @TempDir} via
 * {@link ProcessorTestHarness} — no dependency on the example project.
 */
class QwenEndToEndTest {

    @TempDir
    static Path tempDir;

    private static ProcessorTestHarness harness;

    @BeforeAll
    static void setUp() throws IOException {
        harness = ProcessorTestHarness.withExampleSources(tempDir);
    }

    @AfterAll
    static void tearDown() {
        VibeTagsLogger.shutdown();
    }

    @Test
    void testQwenFilesExist() {
        assertTrue(harness.fileExists("QWEN.md"), "QWEN.md should exist");
        assertTrue(harness.fileExists(".qwenignore"), ".qwenignore should exist");
        assertTrue(harness.fileExists(".qwen/settings.json"), ".qwen/settings.json should exist");
        assertTrue(harness.fileExists(".qwen/commands/refactor.md"), ".qwen/commands/refactor.md should exist");
    }

    @Test
    void testQwenMdHasCorrectHeader() throws IOException {
        String content = harness.readFile("QWEN.md");

        assertTrue(content.contains("# PROJECT CONTEXT"), "Should have PROJECT CONTEXT header");
        assertTrue(content.contains("AUTO-GENERATED BY VIBETAGS"), "Should have auto-generated marker");
        assertTrue(content.contains("Generated by VibeTags |"), "Should have VibeTags attribution");
    }

    @Test
    void testQwenMdHasLockedFilesSection() throws IOException {
        String content = harness.readFile("QWEN.md");

        assertTrue(content.contains("## LOCKED FILES (DO NOT EDIT)"),
            "Should have locked files section");
        assertTrue(content.contains("PaymentProcessor"),
            "Should mention PaymentProcessor (locked class)");
        assertTrue(content.contains("SecurityConfig"),
            "Should mention SecurityConfig (locked class)");
    }

    @Test
    void testQwenMdHasContextualRulesSection() throws IOException {
        String content = harness.readFile("QWEN.md");

        assertTrue(content.contains("## CONTEXTUAL RULES"),
            "Should have contextual rules section");
        assertTrue(content.contains("SecurityConfig"),
            "Should mention SecurityConfig");
        assertTrue(content.contains("Focus:"),
            "Should have focus directives");
        assertTrue(content.contains("Avoid:"),
            "Should have avoid directives");
    }

    @Test
    void testQwenMdHasSecurityAuditsSection() throws IOException {
        String content = harness.readFile("QWEN.md");

        assertTrue(content.contains("## \uD83D\uDEE1\uFE0F MANDATORY SECURITY AUDITS"),
            "Should have security audits section with emoji");
        assertTrue(content.contains("DatabaseConnector"),
            "Should mention DatabaseConnector (audited class)");
        assertTrue(content.contains("Required Checks:"),
            "Should have required checks list");
        assertTrue(content.contains("SQL Injection"),
            "Should mention SQL Injection vulnerability");
        assertTrue(content.contains("Thread Safety"),
            "Should mention Thread Safety vulnerability");
    }

    @Test
    void testQwenMdHasIgnoredElementsSection() throws IOException {
        String content = harness.readFile("QWEN.md");

        assertTrue(content.contains("## IGNORED ELEMENTS"),
            "Should have ignored elements section");
        assertTrue(content.contains("GeneratedMetadata"),
            "Should mention GeneratedMetadata (ignored class)");
    }

    @Test
    void testQwenSettingsJsonIsValid() throws IOException {
        String content = harness.readFile(".qwen/settings.json");

        assertFalse(content.isEmpty(), "Settings file should not be empty");
        assertTrue(content.contains("\"model\""), "Should specify model");
        assertTrue(content.contains("qwen3-coder-plus"), "Should use qwen3-coder-plus model");
        assertTrue(content.contains("\"mcp\""), "Should have MCP configuration");
        assertTrue(content.contains("\"enabled\": true"), "Should have MCP enabled");
    }

    @Test
    void testQwenIgnoreHasCorrectFormat() throws IOException {
        String content = harness.readFile(".qwenignore");

        assertTrue(content.contains("# AUTO-GENERATED BY VIBETAGS"),
            "Should have auto-generated header");
        assertTrue(content.contains("Qwen-specific exclusion list"),
            "Should have Qwen-specific description");
        assertTrue(content.contains("**/"),
            "Should contain glob patterns");
        assertTrue(content.contains(".java"),
            "Should reference .java files");
        assertTrue(content.contains("GeneratedMetadata"),
            "Should exclude GeneratedMetadata");
    }

    @Test
    void testQwenRefactorCommandExists() throws IOException {
        String content = harness.readFile(".qwen/commands/refactor.md");

        assertTrue(content.contains("# /refactor command"),
            "Should have refactor command header");
        assertTrue(content.contains("AUTO-GENERATED BY VIBETAGS"),
            "Should have auto-generated marker");
        assertTrue(content.contains("Refactor"),
            "Should contain refactor instructions");
        assertTrue(content.contains("QWEN.md"),
            "Should reference QWEN.md for context");
    }

    @Test
    void testQwenMdContainsAllAnnotationTypes() throws IOException {
        String content = harness.readFile("QWEN.md");

        assertTrue(content.contains("LOCKED FILES"), "Should have @AILocked content");
        assertTrue(content.contains("CONTEXTUAL RULES"), "Should have @AIContext content");
        assertTrue(content.contains("MANDATORY SECURITY AUDITS"), "Should have @AIAudit content");
        assertTrue(content.contains("IGNORED ELEMENTS"), "Should have @AIIgnore content");
    }

    @Test
    void testQwenMdLockedFilesHaveReasons() throws IOException {
        String content = harness.readFile("QWEN.md");

        assertTrue(content.contains("PaymentProcessor") && content.contains(" - "),
            "PaymentProcessor should have a reason (hyphen separator)");
        assertTrue(content.contains("SecurityConfig") && content.contains(" - "),
            "SecurityConfig should have a reason");
    }

    @Test
    void testQwenMdContextFilesHaveFocusAndAvoids() throws IOException {
        String content = harness.readFile("QWEN.md");

        assertTrue(content.contains("StringParser"),
            "Should mention StringParser (context class)");
        assertTrue(content.contains("memory usage"),
            "Should have focus on memory usage");
        assertTrue(content.contains("java.util.regex"),
            "Should avoid java.util.regex");
    }

    @Test
    void testQwenAttributionHeaders() throws IOException {
        String qwenMd = harness.readFile("QWEN.md");
        String qwenIgnore = harness.readFile(".qwenignore");
        String qwenRefactor = harness.readFile(".qwen/commands/refactor.md");

        assertTrue(qwenMd.contains("Generated by VibeTags |"), "QWEN.md should have VibeTags attribution");
        assertTrue(qwenIgnore.contains("Generated by VibeTags |"), ".qwenignore should have VibeTags attribution");
        assertTrue(qwenRefactor.contains("AUTO-GENERATED BY VIBETAGS"), "refactor.md should have auto-generated marker");
    }

    @Test
    void testQwenMdContentIsNotEmpty() throws IOException {
        String content = harness.readFile("QWEN.md");
        assertFalse(content.isEmpty(), "QWEN.md should not be empty");
        assertTrue(content.length() > 100, "QWEN.md should have substantial content");
    }

    @Test
    void testQwenSettingsContentIsNotEmpty() throws IOException {
        String content = harness.readFile(".qwen/settings.json");
        assertFalse(content.isEmpty(), ".qwen/settings.json should not be empty");
        assertTrue(content.length() > 50, "Settings file should have meaningful content");
    }

    @Test
    void testQwenIgnoreContentIsNotEmpty() throws IOException {
        String content = harness.readFile(".qwenignore");
        assertFalse(content.isEmpty(), ".qwenignore should not be empty");
        assertTrue(content.contains("GeneratedMetadata"),
            "Should contain at least one ignored pattern");
    }

    @Test
    void testQwenMdStructure() throws IOException {
        String content = harness.readFile("QWEN.md");

        String[] expectedSections = {
            "# PROJECT CONTEXT",
            "## LOCKED FILES (DO NOT EDIT)",
            "## CONTEXTUAL RULES",
            "## \uD83D\uDEE1\uFE0F MANDATORY SECURITY AUDITS",
            "## IGNORED ELEMENTS"
        };

        for (String section : expectedSections) {
            assertTrue(content.contains(section),
                "QWEN.md should contain section: " + section);
        }
    }

    @Test
    void testQwenHandlesMultipleLockedFiles() throws IOException {
        String content = harness.readFile("QWEN.md");

        int lockedCount = countOccurrences(content, "`com.example.");
        assertTrue(lockedCount >= 5,
            "Should have at least 5 locked/context elements, found: " + lockedCount);
    }

    @Test
    void testQwenMdAuditSectionHasAllVulnerabilities() throws IOException {
        String content = harness.readFile("QWEN.md");

        assertTrue(content.contains("SQL Injection"),
            "Should list SQL Injection");
        assertTrue(content.contains("Thread Safety"),
            "Should list Thread Safety");
    }

    private int countOccurrences(String text, String pattern) {
        int count = 0;
        int index = 0;
        while ((index = text.indexOf(pattern, index)) != -1) {
            count++;
            index += pattern.length();
        }
        return count;
    }
}
