package se.deversity.vibetags.processor;

import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.*;

/**
 * Edge cases for {@code stripLegacyVibeTagsBlock}. The basic happy paths are covered in
 * {@link AIGuardrailProcessorUnitTest}; this class pins the trickier branches that the
 * GuardrailFileWriter extraction could easily break (XML-closer search window, the
 * Math.max picking the LATER closer, multi-paragraph human content via the nlAfter logic,
 * the bare-header detection path).
 */
class StripLegacyVibeTagsBlockEdgeCasesTest {

    private final AIGuardrailProcessor p = new AIGuardrailProcessor();

    @Test
    void picksLatestXmlCloser_whenBothPresent() {
        // Both </rule> and </project_guardrails> are searched. Whichever comes LATER wins,
        // so everything up to and including that closer is treated as legacy.
        String legacy =
            "<!-- # Generated by VibeTags | https://github.com/PIsberg/vibetags -->\n" +
            "<project_guardrails>\n" +
            "  <locked_files></locked_files>\n" +
            "</project_guardrails>\n" +
            "<rule>extra trailing rule</rule>\n";
        String human = "# CLAUDE.md\n\nMy guidance.\n";

        String result = p.stripLegacyVibeTagsBlock(legacy + human);

        assertFalse(result.contains("<rule>"), "Both XML closers must be stripped");
        assertFalse(result.contains("</project_guardrails>"), "project_guardrails closer must be stripped");
        assertTrue(result.contains("# CLAUDE.md"), "Human content after the latest closer must remain");
        assertTrue(result.contains("My guidance"));
    }

    @Test
    void picksRuleCloser_whenItIsTheOnlyOne() {
        String legacy =
            "<!-- # Generated by VibeTags | https://github.com/PIsberg/vibetags -->\n" +
            "<rule>some inline rule</rule>\n";
        String human = "# Project notes\n\nHand-written.\n";

        String result = p.stripLegacyVibeTagsBlock(legacy + human);

        assertFalse(result.contains("<rule>"), "Solo </rule> closer must still strip the legacy block");
        assertTrue(result.contains("# Project notes"));
        assertTrue(result.contains("Hand-written"));
    }

    @Test
    void preservesMultipleParagraphsAfterCloser() {
        String legacy =
            "<!-- # Generated by VibeTags | https://github.com/PIsberg/vibetags -->\n" +
            "<project_guardrails>x</project_guardrails>\n";
        String human =
            "# CLAUDE.md\n\n" +
            "Paragraph one.\n\n" +
            "Paragraph two.\n\n" +
            "Paragraph three.\n";

        String result = p.stripLegacyVibeTagsBlock(legacy + human);

        assertTrue(result.contains("Paragraph one."));
        assertTrue(result.contains("Paragraph two."));
        assertTrue(result.contains("Paragraph three."));
    }

    @Test
    void detectsBareHeader_notHtmlCommented() {
        // Some legacy files have the bare "# Generated by VibeTags | ..." line without HTML comment wrapping
        // (typical for .cursorrules, .aiexclude). The detection must still find it.
        String legacy =
            "# AUTO-GENERATED AI RULES\n" +
            "# Generated by VibeTags | https://github.com/PIsberg/vibetags\n" +
            "## LOCKED FILES\n" +
            "* `Foo` - reason\n";

        String result = p.stripLegacyVibeTagsBlock(legacy);

        assertEquals("", result, "Fully auto-generated content with bare header must be wiped");
    }

    @Test
    void preservesPrefix_humanContentBeforeLegacyHeader() {
        // If the user has hand-written prose ABOVE the legacy header, that prefix is kept.
        String prefix = "Here is my hand-written intro.\n\nIt has prose.\n\n";
        String legacy =
            "<!-- # Generated by VibeTags | https://github.com/PIsberg/vibetags -->\n" +
            "<project_guardrails></project_guardrails>\n" +
            "<rule>x</rule>\n";

        String result = p.stripLegacyVibeTagsBlock(prefix + legacy);

        assertTrue(result.contains("hand-written intro"), "Human prefix must survive");
        assertTrue(result.contains("It has prose"), "Multi-paragraph human prefix must survive");
        assertFalse(result.contains("<project_guardrails>"), "Legacy block must be stripped");
        assertFalse(result.contains("<rule>"), "Legacy </rule> must be stripped");
    }

    @Test
    void treatsBoilerplatePrefix_asNonHuman() {
        // Lines that are only hash-comments / bullets / blank are classified as boilerplate (not human),
        // so the prefix is dropped.
        String boilerplatePrefix =
            "# AUTO-GENERATED AI RULES\n" +
            "# Do not edit manually.\n" +
            "* old bullet\n";
        String legacy =
            "# Generated by VibeTags | https://github.com/PIsberg/vibetags\n" +
            "## LOCKED FILES\n" +
            "* `Foo` - reason\n";

        String result = p.stripLegacyVibeTagsBlock(boilerplatePrefix + legacy);

        assertEquals("", result,
            "Hash/bullet/blank-only prefix must be classified as boilerplate and dropped along with the legacy block");
    }

    @Test
    void noXmlClosers_noHumanPrefix_stripsEverything() {
        // .cursorrules style: all generated, no XML, no human prefix. rest = all legacy.
        String legacy =
            "# Generated by VibeTags | https://github.com/PIsberg/vibetags\n" +
            "## LOCKED FILES\n" +
            "* `Foo`\n" +
            "* `Bar`\n";

        String result = p.stripLegacyVibeTagsBlock(legacy);

        assertEquals("", result);
    }
}
