package se.deversity.vibetags.processor;

import org.junit.jupiter.api.AfterAll;
import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.parallel.Isolated;
import se.deversity.asynctest.AsyncTest;
import se.deversity.asynctest.FailOn;
import se.deversity.asynctest.Preset;
import se.deversity.asynctest.diagnostics.TrustTier;
import se.deversity.vibetags.processor.internal.GuardrailFileWriter;
import se.deversity.vibetags.processor.internal.WriteCache;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.attribute.BasicFileAttributes;
import java.util.Comparator;
import java.util.Objects;
import java.util.concurrent.atomic.AtomicInteger;
import java.util.stream.Stream;

import static org.junit.jupiter.api.Assertions.assertTrue;

/**
 * A parallel reactor's modules share one {@code .vibetags-cache}, each through its own
 * {@link WriteCache}, and all of them write the same root files.
 *
 * <p>{@code vibetags.root} is the reactor root for every module, so {@code mvn -T} or Gradle's
 * {@code --parallel} runs one processor per module against one cache path and one
 * {@code CLAUDE.md}. {@link WriteCacheAsyncTest} drives one instance from many threads and
 * {@link GuardrailFileWriterAsyncTest} gives every worker its own file; neither has two instances
 * writing one file, which is the shape the reactor actually has.
 *
 * <p>The property is the one a false positive breaks: when an instance says the file is
 * unchanged since it wrote {@code body}, the file really holds {@code body}. A wrong "unchanged"
 * makes the writer skip a file that holds another module's content, and nothing reports it.
 * Workers share a body in pairs and every body has a length of its own, so two different writes
 * in the same millisecond still differ in size; a failure here can only be an entry that pairs
 * one writer's hash with another writer's file attributes.
 */
// @Isolated: real platform threads plus detector instrumentation. Runs alone so that
// pressure does not reach the javac-based e2e tests beside it. See docs/TESTS.md.
@Isolated
class WriteCacheCrossInstanceAsyncTest {

    private static final String HEADER = "# Generated by VibeTags | https://github.com/PIsberg/vibetags\n";
    private static final int CYCLES_PER_INVOCATION = 25;
    private static final int GROUPS = 4;
    private static final AtomicInteger NEXT_WORKER = new AtomicInteger();
    private static final ThreadLocal<Integer> WORKER = ThreadLocal.withInitial(NEXT_WORKER::incrementAndGet);

    private static Path root;
    private static Path shared;

    @BeforeAll
    static void setUp() throws IOException {
        root = Files.createTempDirectory("vibetags-cache-cross-instance");
        shared = root.resolve("CLAUDE.md");
        Files.writeString(shared, GuardrailFileWriter.MARKER_START_MD + "\n" + GuardrailFileWriter.MARKER_END_MD + "\n");
    }

    @AfterAll
    static void tearDown() throws IOException {
        if (root == null) return;
        try (Stream<Path> paths = Files.walk(root)) {
            paths.sorted(Comparator.reverseOrder()).forEach(p -> {
                try {
                    Files.deleteIfExists(p);
                } catch (IOException ignored) {
                    // Best-effort cleanup of a temp directory; a leftover file must not fail the test.
                }
            });
        }
    }

    @AsyncTest(threads = 8, invocations = 10, timeoutMs = 120_000,
        useVirtualThreads = false, preset = Preset.ALL,
        failOn = FailOn.HIGH, minTrust = TrustTier.FACT)
    void anUnchangedVerdictAlwaysMatchesTheBytesOnDisk() throws IOException {
        // One worker is one module: its own cache instance over the shared cache path, its own
        // writer, the same root file as every other module.
        // Two workers per body: a worker that finds its partner's write already on disk takes the
        // "file is current" path and records without writing, the other way an entry is made.
        int group = WORKER.get() % GROUPS + 1; // from 1: an empty run of x leaves a trailing space the writer strips
        String body = "- guardrail from module group " + group + " " + "x".repeat(group) + "\n";
        for (int cycle = 0; cycle < CYCLES_PER_INVOCATION; cycle++) {
            WriteCache cache = new WriteCache(root.resolve(WriteCache.DEFAULT_FILE_NAME));
            GuardrailFileWriter writer = new GuardrailFileWriter(HEADER, null, null, cache);
            writer.writeFileIfChanged(shared.toString(), body, true);

            // The verdict and the bytes must describe one file. A stat on each side of them is the
            // snapshot: when the two agree on size, full mtime and file key, nothing replaced the
            // file in between, so the verdict was about the bytes read. When they differ another
            // module wrote meanwhile and this cycle proves nothing either way. Checking the verdict
            // again after the read instead was the test's own race: macOS CI wrote a same-size
            // file in the same millisecond between the read and the second verdict, which made a
            // correct verdict look like a wrong one.
            // Windows refuses a stat or read while another worker's rename is replacing the file
            // (AccessDeniedException on windows-latest CI); that cycle is inconclusive too.
            BasicFileAttributes before;
            boolean unchanged;
            String onDisk;
            BasicFileAttributes after;
            try {
                before = Files.readAttributes(shared, BasicFileAttributes.class);
                unchanged = cache.isUnchanged(shared, body);
                onDisk = Files.readString(shared);
                after = Files.readAttributes(shared, BasicFileAttributes.class);
            } catch (IOException replacedMeanwhile) {
                cache.flush();
                continue;
            }
            if (unchanged && sameFile(before, after) && !onDisk.contains(body)) {
                throw new AssertionError("the cache vouched for a body the file does not hold.\n"
                    + "expected: " + body + "on disk:\n" + onDisk);
            }
            cache.flush();
        }
        assertTrue(Files.exists(shared), "the shared file must survive the contention");
    }

    private static boolean sameFile(BasicFileAttributes a, BasicFileAttributes b) {
        return a.size() == b.size()
            && a.lastModifiedTime().equals(b.lastModifiedTime())
            && Objects.equals(a.fileKey(), b.fileKey());
    }
}
