package se.deversity.vibetags.loadtest;

import com.sun.management.ThreadMXBean;
import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.io.TempDir;
import se.deversity.vibetags.processor.VibeTagsLogger;

import javax.tools.DiagnosticCollector;
import javax.tools.JavaCompiler;
import javax.tools.JavaFileObject;
import javax.tools.SimpleJavaFileObject;
import javax.tools.StandardJavaFileManager;
import javax.tools.ToolProvider;
import java.io.IOException;
import java.io.PrintWriter;
import java.io.UncheckedIOException;
import java.lang.annotation.Annotation;
import java.lang.management.ManagementFactory;
import java.net.URI;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.StandardOpenOption;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.Comparator;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Locale;
import java.util.Map;
import java.util.stream.Collectors;
import java.util.stream.Stream;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertTrue;
import static org.junit.jupiter.api.Assumptions.assumeTrue;

/**
 * What each of the 44 annotations costs, and what the six-annotation fixture was not measuring.
 *
 * <h2>Why this is not part of {@link AnnotationVolumeStressTest}</h2>
 *
 * <p>{@link SyntheticClassGenerator} rotates six annotations and has since 0.5.4:
 * {@code @AIContext}, {@code @AILocked}, {@code @AIAudit}, {@code @AIIgnore}, {@code @AIPrivacy}
 * and {@code @AIDraft}. The project has 44, so 38 formatters never ran in any sweep here and no
 * committed baseline said anything about their cost (issue #835). That matters more since #765
 * replaced 44 hand-written arms in each of five classes with one table walked per annotation: the
 * eleven-release sweep measured that refactor flat, which is the right result about six
 * annotations and says nothing about the other 38.
 *
 * <p>Widening the six-annotation fixture in place would be the wrong fix, for the reason
 * {@code PlatformBreadthStressTest} gives about opt-in breadth: its output is what every folder
 * under {@code load-tests/results/} measured, and changing the mix silently makes the release
 * trend incomparable with everything captured after. So this measures the missing dimension
 * beside it, at one fixed N, carrying the six-annotation mix as an anchor column.
 *
 * <h2>What it measures</h2>
 *
 * <ul>
 *   <li><b>The two fixtures at one N.</b> Overhead allocation, wall-clock and generated bytes for
 *       the six-annotation mix and for one carrying all 44, with a per-annotated-reference column
 *       so the two are comparable despite holding different numbers of annotations.</li>
 *   <li><b>Per-annotation marginal cost.</b> One compile per annotation, N classes carrying only
 *       that one, against a control of the same N classes carrying none. This is the number
 *       nothing in this harness has ever reported, and it is what says whether a formatter is
 *       expensive rather than whether the set of them is.</li>
 * </ul>
 *
 * <h2>What it gates on</h2>
 *
 * <p>Not on a threshold. Run-to-run allocation here moves by more than the difference between
 * most annotations, and a threshold on that is a flake waiting for a Friday. It gates on the
 * coverage claim instead, which is the thing #835 is about: every annotation in the processor's
 * own table was placed, compiled and rendered something. A fixture that quietly stopped covering
 * an annotation would otherwise report a smaller number and look like an improvement.
 *
 * <pre>
 *   cd load-tests
 *   mvn test -Dtest=AnnotationBreadthStressTest
 * </pre>
 *
 * Results are written to {@code target/annotation-breadth-&lt;timestamp&gt;.txt}.
 */
class AnnotationBreadthStressTest {

    private static final Path RESULTS_FILE = Path.of("target",
        "annotation-breadth-"
            + LocalDateTime.now().format(DateTimeFormatter.ofPattern("yyyy-MM-dd_HH-mm-ss")) + ".txt");

    private static final String PROCESSOR_CLASS = "se.deversity.vibetags.processor.AIGuardrailProcessor";

    /** The six opt-in files every committed baseline's sweep creates, so the anchor column matches. */
    private static final String[] OPT_IN_FILES = {
        ".cursorrules", "CLAUDE.md", ".aiexclude", "AGENTS.md",
        "gemini_instructions.md", "QWEN.md"
    };

    /** The two-fixture comparison. Matches the sweeps' mid N so the anchor column is recognisable. */
    private static final int COMPARISON_CLASSES = 500;

    /**
     * The per-annotation table. Smaller because it is 45 compiles rather than two, and because a
     * per-annotation difference that only shows above 100 classes is not a per-element cost.
     */
    private static final int PER_ANNOTATION_CLASSES = 100;

    private static ThreadMXBean threadBean;

    @BeforeAll
    static void prepare() throws IOException {
        java.lang.management.ThreadMXBean platformBean = ManagementFactory.getThreadMXBean();
        assumeTrue(platformBean instanceof ThreadMXBean,
            "com.sun.management.ThreadMXBean not available on this JVM - skipping.");
        threadBean = (ThreadMXBean) platformBean;
        assumeTrue(threadBean.isThreadAllocatedMemorySupported(),
            "Per-thread allocation tracking not supported on this JVM.");
        if (!threadBean.isThreadAllocatedMemoryEnabled()) {
            threadBean.setThreadAllocatedMemoryEnabled(true);
        }
        Files.createDirectories(RESULTS_FILE.getParent());
        try (PrintWriter pw = new PrintWriter(Files.newBufferedWriter(RESULTS_FILE,
                StandardCharsets.UTF_8, StandardOpenOption.CREATE, StandardOpenOption.TRUNCATE_EXISTING))) {
            pw.println("VibeTags Annotation-Breadth Stress Test Results");
            pw.println("=".repeat(96));
        }
    }

    @AfterEach
    void releaseProcessorLogHandle() {
        VibeTagsLogger.shutdown();
    }

    @Test
    @DisplayName("the six-annotation fixture against one carrying all 44, at the same N")
    void costOfTheAnnotationsTheSweepsDoNotEmit(@TempDir Path tempDir) throws Exception {
        List<Class<? extends Annotation>> all = WideAnnotationClassGenerator.annotations();
        assumeTrue(!all.isEmpty(),
            "the processor jar under test predates GuardrailAnnotations.ALL, or names an annotation"
                + " this classpath's annotations jar does not have - skipping the breadth table");

        int n = Math.min(COMPARISON_CLASSES, maxClasses());
        List<String[]> narrowText = SyntheticClassGenerator.generate(n);
        List<String[]> wideText = WideAnnotationClassGenerator.generate(n, all);
        List<JavaFileObject> narrow = sources(narrowText);
        List<JavaFileObject> wide = sources(wideText);

        // The first compile in a JVM carries a one-off class-loading tail larger than the
        // difference between the two fixtures, so it is spent before anything is recorded.
        measure(narrow, root(tempDir, "warmup"), tempDir, "classes-warmup");

        Fixture narrowResult = run(narrow, tempDir, "narrow", countAnnotations(narrowText), n);
        Fixture wideResult = run(wide, tempDir, "wide", countAnnotations(wideText), n);

        append("");
        append(String.format(Locale.ROOT, "%-10s %-10s %-12s %-18s %-13s %-15s %-14s",
            "Fixture", "Classes", "Annotations", "OverheadAlloc(KB)", "Elapsed(ms)", "OutputSize(B)",
            "Alloc/ann(B)"));
        append("-".repeat(96));
        for (Fixture fixture : List.of(narrowResult, wideResult)) {
            String line = String.format(Locale.ROOT, "%-10s %-10d %-12d %-18d %-13d %-15d %-14d",
                fixture.name, n, fixture.annotations, fixture.overheadAllocKb, fixture.elapsedMillis,
                fixture.outputBytes, fixture.allocPerAnnotation());
            System.out.println(line);
            append(line);
        }

        assertTrue(narrowResult.outputBytes > 0, "the six-annotation fixture rendered nothing");
        assertTrue(wideResult.outputBytes > narrowResult.outputBytes,
            "a fixture carrying all " + all.size() + " annotations must render more than one"
                + " carrying six; it rendered " + wideResult.outputBytes + " against "
                + narrowResult.outputBytes + ", so the wide fixture is measuring something other"
                + " than what it claims to");
    }

    @Test
    @DisplayName("what each of the 44 costs on its own, against a round that renders nothing")
    void perAnnotationMarginalCost(@TempDir Path tempDir) throws Exception {
        List<Class<? extends Annotation>> all = WideAnnotationClassGenerator.annotations();
        assumeTrue(!all.isEmpty(),
            "the processor jar under test predates GuardrailAnnotations.ALL - skipping");

        int n = Math.min(PER_ANNOTATION_CLASSES, maxClasses());

        List<String> unplaceable = all.stream()
            .filter(a -> WideAnnotationClassGenerator.placementOf(a) == null)
            .map(Class::getSimpleName)
            .collect(Collectors.toList());
        assertEquals(List.of(), unplaceable,
            "this fixture could not place these annotations anywhere, so they would go unmeasured"
                + " exactly as they did before #835; give the generated class a site they accept");

        List<JavaFileObject> control = sources(WideAnnotationClassGenerator.generateUnannotated(n));
        measure(control, root(tempDir, "warmup"), tempDir, "classes-warmup");
        Fixture empty = run(control, tempDir, "control", 0, n);

        Map<String, Fixture> byAnnotation = new LinkedHashMap<>();
        for (Class<? extends Annotation> annotation : all) {
            String name = annotation.getSimpleName();
            List<JavaFileObject> only = sources(
                WideAnnotationClassGenerator.generate(n, List.of(annotation)));
            byAnnotation.put(name, run(only, tempDir, name, n, n));
        }

        append("");
        append("Per-annotation marginal cost, N=" + n + " classes each carrying that one annotation.");
        append("Marginal = this fixture's overhead minus the control row below, which is the same"
            + " N classes carrying no VibeTags annotation, with the processor still active.");
        append(String.format(Locale.ROOT, "%-24s %-18s %-18s %-15s",
            "Annotation", "OverheadAlloc(KB)", "Marginal(KB)", "OutputSize(B)"));
        append("-".repeat(96));
        append(String.format(Locale.ROOT, "%-24s %-18d %-18s %-15d",
            "(control: none)", empty.overheadAllocKb, "-", empty.outputBytes));
        byAnnotation.entrySet().stream()
            .sorted(Comparator.comparingLong(e -> -e.getValue().overheadAllocKb))
            .forEach(entry -> {
                Fixture f = entry.getValue();
                String line = String.format(Locale.ROOT, "%-24s %-18d %-18d %-15d",
                    entry.getKey(), f.overheadAllocKb, f.overheadAllocKb - empty.overheadAllocKb,
                    f.outputBytes);
                System.out.println(line);
                appendQuietly(line);
            });

        // The gate, and the only one here: every annotation in the processor's own table rendered
        // something of its own. A fixture that stopped covering one would report a smaller number
        // and read as an improvement, which is the shape of the gap this test was opened for.
        List<String> renderedNothing = byAnnotation.entrySet().stream()
            .filter(entry -> entry.getValue().outputBytes <= empty.outputBytes)
            .map(Map.Entry::getKey)
            .collect(Collectors.toList());
        assertEquals(List.of(), renderedNothing,
            "these annotations produced no more output than a round with none of them, so this"
                + " table measured nothing for them: either the fixture is not reaching the"
                + " formatter, or the formatter writes nothing. Control wrote "
                + empty.outputBytes + " bytes");
        assertEquals(all.size(), byAnnotation.size(),
            "one measurement per annotation in GuardrailAnnotations.ALL, or the table has a"
                + " duplicate simple name and one row overwrote another");
    }

    // -------------------------------------------------------------------------

    /** One fixture, measured once against the shared {@code -proc:none} baseline. */
    private static final class Fixture {
        final String name;
        final int annotations;
        final long overheadAllocKb;
        final long elapsedMillis;
        final long outputBytes;

        Fixture(String name, int annotations, long overheadAllocKb, long elapsedMillis,
                long outputBytes) {
            this.name = name;
            this.annotations = annotations;
            this.overheadAllocKb = overheadAllocKb;
            this.elapsedMillis = elapsedMillis;
            this.outputBytes = outputBytes;
        }

        long allocPerAnnotation() {
            return annotations == 0 ? 0 : overheadAllocKb * 1024 / annotations;
        }
    }

    private Fixture run(List<JavaFileObject> sources, Path tempDir, String name, int annotations,
                        int classes) throws IOException {
        long baseline = measureWithoutProcessor(sources, tempDir, "baseline-" + name);
        Path projectRoot = root(tempDir, name);
        Measurement m = measure(sources, projectRoot, tempDir, "classes-" + name);
        assertTrue(classes > 0, "a fixture of no classes measures nothing");
        return new Fixture(name, annotations, (m.allocatedBytes - baseline) / 1024, m.elapsedMillis,
            writtenBytes(projectRoot));
    }

    /**
     * A fresh project root opted into the sweeps' six files.
     *
     * <p>The same six on purpose. This test varies the annotations and nothing else, so the opt-in
     * set has to be the one the historical sweeps used or the anchor column stops anchoring.
     */
    private static Path root(Path tempDir, String name) throws IOException {
        Path projectRoot = tempDir.resolve(name);
        Files.createDirectories(projectRoot);
        for (String file : OPT_IN_FILES) {
            Path target = projectRoot.resolve(file);
            if (!Files.exists(target)) {
                Files.createFile(target);
            }
        }
        return projectRoot;
    }

    /** Bytes allocated and milliseconds elapsed for one processor-on compile. */
    private static final class Measurement {
        final long allocatedBytes;
        final long elapsedMillis;

        Measurement(long allocatedBytes, long elapsedMillis) {
            this.allocatedBytes = allocatedBytes;
            this.elapsedMillis = elapsedMillis;
        }
    }

    private static Measurement measure(List<JavaFileObject> sources, Path projectRoot, Path tempDir,
                                       String classesDirName) throws IOException {
        JavaCompiler compiler = systemCompiler();
        Path classesDir = tempDir.resolve(classesDirName);
        Files.createDirectories(classesDir);
        List<String> options = List.of(
            "-source", "17",
            "-target", "17",
            "-d", classesDir.toString(),
            "-classpath", System.getProperty("java.class.path"),
            "-processor", PROCESSOR_CLASS,
            "-Avibetags.root=" + projectRoot.toAbsolutePath());

        DiagnosticCollector<JavaFileObject> diagnostics = new DiagnosticCollector<>();
        System.gc();
        long tid = Thread.currentThread().getId();
        long before = threadBean.getThreadAllocatedBytes(tid);
        long start = System.currentTimeMillis();
        try (StandardJavaFileManager fm = compiler.getStandardFileManager(diagnostics, Locale.ROOT,
                StandardCharsets.UTF_8)) {
            compiler.getTask(null, fm, diagnostics, options, null, sources).call();
        }
        long elapsed = System.currentTimeMillis() - start;
        assertCompiled(diagnostics, classesDirName);
        return new Measurement(threadBean.getThreadAllocatedBytes(tid) - before, elapsed);
    }

    /** The same compile with no annotation processing: javac's own share, subtracted per fixture. */
    private static long measureWithoutProcessor(List<JavaFileObject> sources, Path tempDir,
                                                String classesDirName) throws IOException {
        JavaCompiler compiler = systemCompiler();
        Path classesDir = tempDir.resolve(classesDirName);
        Files.createDirectories(classesDir);
        List<String> options = List.of(
            "-source", "17",
            "-target", "17",
            "-d", classesDir.toString(),
            "-classpath", System.getProperty("java.class.path"),
            "-proc:none");
        DiagnosticCollector<JavaFileObject> diagnostics = new DiagnosticCollector<>();
        System.gc();
        long tid = Thread.currentThread().getId();
        long before = threadBean.getThreadAllocatedBytes(tid);
        try (StandardJavaFileManager fm = compiler.getStandardFileManager(diagnostics, Locale.ROOT,
                StandardCharsets.UTF_8)) {
            compiler.getTask(null, fm, diagnostics, options, null, sources).call();
        }
        long allocated = threadBean.getThreadAllocatedBytes(tid) - before;
        assertCompiled(diagnostics, classesDirName);
        return allocated;
    }

    /**
     * A generated source that does not compile is the failure this fixture is most exposed to,
     * because every usage in it is synthesised from an annotation's reflected shape rather than
     * written out. Without this the run still produces a table, of a compile that stopped early.
     */
    private static void assertCompiled(DiagnosticCollector<JavaFileObject> diagnostics, String what) {
        List<String> errors = diagnostics.getDiagnostics().stream()
            .filter(d -> d.getKind() == javax.tools.Diagnostic.Kind.ERROR)
            .map(d -> d.getMessage(Locale.ROOT))
            .collect(Collectors.toList());
        assertEquals(List.of(), errors, "the " + what + " fixture did not compile");
    }

    private static JavaCompiler systemCompiler() {
        JavaCompiler compiler = ToolProvider.getSystemJavaCompiler();
        if (compiler == null) {
            throw new IllegalStateException(
                "javax.tools.JavaCompiler not available - run with a JDK, not a JRE.");
        }
        return compiler;
    }

    private static long writtenBytes(Path projectRoot) throws IOException {
        try (Stream<Path> walk = Files.walk(projectRoot)) {
            return walk.filter(Files::isRegularFile)
                .filter(AnnotationBreadthStressTest::isGuardrailOutput)
                .mapToLong(AnnotationBreadthStressTest::sizeOf).sum();
        }
    }

    /** True for a file an AI tool reads, false for the processor's own bookkeeping. */
    private static boolean isGuardrailOutput(Path path) {
        Path name = path.getFileName();
        if (name == null) {
            return false;
        }
        String fileName = name.toString();
        return !fileName.startsWith(".vibetags-") && !"vibetags.log".equals(fileName);
    }

    private static long sizeOf(Path path) {
        try {
            return Files.size(path);
        } catch (IOException e) {
            throw new UncheckedIOException(e);
        }
    }

    /**
     * Annotated references in a fixture, counted in its text rather than worked out from the rule
     * that produced it.
     *
     * <p>The per-annotation column divides by this, so a formula here is a wrong number in a
     * table that looks right. The six-annotation mix is a rotation - every class, every 2nd, 3rd,
     * 4th, 5th and 7th - and the arithmetic answer for N=500 is 1214, not the 1500 that "six
     * annotations, half the classes each" gives. Counting is cheap and cannot drift when the
     * rotation does.
     */
    private static int countAnnotations(List<String[]> generated) {
        int count = 0;
        for (String[] pair : generated) {
            for (String line : pair[1].split("\n", -1)) {
                if (line.stripLeading().startsWith("@")) {
                    count++;
                }
            }
        }
        return count;
    }

    private static List<JavaFileObject> sources(List<String[]> generated) {
        List<JavaFileObject> files = new ArrayList<>(generated.size());
        for (String[] pair : generated) {
            files.add(source(pair[0], pair[1]));
        }
        return files;
    }

    private static JavaFileObject source(String simpleName, String code) {
        URI uri = URI.create("string:///com/example/generated/" + simpleName + ".java");
        return new SimpleJavaFileObject(uri, JavaFileObject.Kind.SOURCE) {
            @Override
            public CharSequence getCharContent(boolean ignoreEncodingErrors) {
                return code;
            }
        };
    }

    private static int maxClasses() {
        String prop = System.getProperty("stress.max.classes");
        if (prop == null || prop.isBlank() || prop.contains("${")) {
            return Integer.MAX_VALUE;
        }
        try {
            return Integer.parseInt(prop.trim());
        } catch (NumberFormatException e) {
            return Integer.MAX_VALUE;
        }
    }

    private static void append(String line) throws IOException {
        try (PrintWriter pw = new PrintWriter(Files.newBufferedWriter(RESULTS_FILE,
                StandardCharsets.UTF_8, StandardOpenOption.CREATE, StandardOpenOption.APPEND))) {
            pw.println(line);
        }
    }

    private static void appendQuietly(String line) {
        try {
            append(line);
        } catch (IOException e) {
            throw new UncheckedIOException(e);
        }
    }
}
