package se.deversity.vibetags.loadtest;

import com.sun.management.ThreadMXBean;
import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.io.TempDir;
import se.deversity.vibetags.processor.VibeTagsLogger;

import javax.tools.DiagnosticCollector;
import javax.tools.JavaCompiler;
import javax.tools.JavaFileObject;
import javax.tools.SimpleJavaFileObject;
import javax.tools.StandardJavaFileManager;
import javax.tools.ToolProvider;
import java.io.IOException;
import java.io.PrintWriter;
import java.io.UncheckedIOException;
import java.lang.management.ManagementFactory;
import java.lang.reflect.Method;
import java.net.URI;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.StandardOpenOption;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.Collection;
import java.util.LinkedHashMap;
import java.util.LinkedHashSet;
import java.util.List;
import java.util.Locale;
import java.util.Map;
import java.util.Set;
import java.util.stream.Collectors;
import java.util.stream.Stream;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertTrue;
import static org.junit.jupiter.api.Assumptions.assumeTrue;

/**
 * What a project pays for each platform it has opted into, and what opting a scoped-rules
 * directory in takes back out of the always-loaded file.
 *
 * <h2>Why this is not part of {@link AnnotationVolumeStressTest}</h2>
 *
 * <p>That sweep creates six opt-in files, and has done since 0.5.4. The project now writes 65
 * config files across 45 platforms, so the sweep renders a small and shrinking fraction of the
 * work a well-equipped project asks for, and its overhead column is not the number such a project
 * feels. The gap was recorded once before, in the 0.8.0 entry ("the stress test does not opt in to
 * any of the 7 new platforms, so new-platform overhead cannot be measured here"), and it has grown
 * with every platform added since.
 *
 * <p>Widening that sweep's fixture in place would have been the wrong fix: every baseline under
 * {@code load-tests/results/} measured the six-file shape, and changing it silently makes the whole
 * release trend incomparable. So this measures the missing dimension beside it, at one fixed N, and
 * carries the six-file level as a column on purpose — that column is the anchor tying this table
 * back to the historical sweep.
 *
 * <h2>What it measures</h2>
 *
 * <p>Allocation, wall-clock, generated bytes and always-loaded bytes at five opt-in levels, each in
 * its own project root:
 *
 * <ul>
 *   <li><b>minimal</b> — {@code .cursorrules} alone: one rendered aggregate, the floor.</li>
 *   <li><b>sweep</b> — the six files {@link AnnotationVolumeStressTest} uses.</li>
 *   <li><b>sweep+granular</b> — those six plus {@code .claude/rules/}. Invariant 6 says the
 *       aggregate collapses to a scoped-rules index while the safety buckets stay inline, so this
 *       level is what that costs and, in the {@code ClaudeMd(B)} column, what it saves.</li>
 *   <li><b>all-files</b> — every opt-in that writes a single file.</li>
 *   <li><b>all+granular</b> — the above plus every scoped-rules directory: the most a project can
 *       ask VibeTags for.</li>
 * </ul>
 *
 * <h2>Why the opt-in list is read out of the processor jar, reflectively</h2>
 *
 * <p>Membership is derived from {@code ServiceRegistry}, not from a list written here, so a
 * platform added tomorrow is measured tomorrow — a hand-kept copy of that list is the defect issue
 * #762 was opened for and this test is not going to keep another one. It is read through reflection
 * because {@code load-tests} is deliberately compiled against <em>older</em> processor jars to
 * compare releases ({@code -Dprocessor.version=1.2.5}), and a direct call to a method those jars do
 * not have fails the whole module's {@code testCompile} — taking the volume sweeps down with it,
 * which is exactly what happened the first time this test was written against
 * {@code ServiceRegistry.writesDirectory}. Against a jar too old to answer, this test skips and
 * says so; the sweeps beside it still run.
 *
 * <pre>
 *   cd load-tests
 *   mvn test -Dtest=PlatformBreadthStressTest
 * </pre>
 *
 * Results are appended to {@code target/platform-breadth-<timestamp>.txt}.
 */
class PlatformBreadthStressTest {

    private static final Path RESULTS_FILE = Path.of("target",
        "platform-breadth-"
            + LocalDateTime.now().format(DateTimeFormatter.ofPattern("yyyy-MM-dd_HH-mm-ss")) + ".txt");

    private static final String PROCESSOR_CLASS = "se.deversity.vibetags.processor.AIGuardrailProcessor";

    private static final String REGISTRY_CLASS = "se.deversity.vibetags.processor.internal.ServiceRegistry";

    /** The always-loaded file whose collapse the granular levels are measured against. */
    private static final String ALWAYS_LOADED = "CLAUDE.md";

    /** Claude's scoped-rules directory: the granular opt-in this test switches on by itself. */
    private static final String CLAUDE_RULES_DIR = ".claude/rules";

    /**
     * The six files every committed baseline's sweep opts into. Kept so this table has an anchor.
     *
     * <p>Root-relative paths rather than file names, because a name does not identify a service:
     * {@code AGENTS.md} is Codex's output and {@code .junie/AGENTS.md} is Junie's, so matching on
     * the name alone picked up seven services for the six-file level.
     */
    private static final Set<String> SWEEP_PATHS = Set.of(
        ".cursorrules", ALWAYS_LOADED, ".aiexclude", "AGENTS.md", "gemini_instructions.md", "QWEN.md");

    /**
     * Opt-ins whose file is a switch rather than a rendered output, left out of the all-files level
     * because creating one changes what the other levels mean instead of adding to them.
     *
     * <p>{@code .vibetags-root-index} flips how a reactor root merges its aggregates,
     * {@code TESTING.md} routes a test round's guardrails out of the always-loaded files, and
     * {@code .vibetags-locks} is a JSON Lines report for a CI guard that no agent loads. Routing is
     * measured in {@link TestingMdRoutingStressTest}; the other two are measured nowhere yet, and
     * saying so is the point of listing them here.
     */
    private static final Set<String> SWITCH_PATHS = Set.of(
        ".vibetags-root-index", "TESTING.md", ".vibetags-locks");

    /** Big enough for rendering to dominate, small enough that five levels stay inside a minute. */
    private static final int DEFAULT_CLASSES = 500;

    private static ThreadMXBean threadBean;

    @BeforeAll
    static void prepare() throws IOException {
        java.lang.management.ThreadMXBean platformBean = ManagementFactory.getThreadMXBean();
        assumeTrue(platformBean instanceof ThreadMXBean,
            "com.sun.management.ThreadMXBean not available on this JVM — skipping.");
        threadBean = (ThreadMXBean) platformBean;
        assumeTrue(threadBean.isThreadAllocatedMemorySupported(),
            "Per-thread allocation tracking not supported on this JVM.");
        if (!threadBean.isThreadAllocatedMemoryEnabled()) {
            threadBean.setThreadAllocatedMemoryEnabled(true);
        }
        Files.createDirectories(RESULTS_FILE.getParent());
        try (PrintWriter pw = new PrintWriter(Files.newBufferedWriter(RESULTS_FILE,
                StandardCharsets.UTF_8, StandardOpenOption.CREATE, StandardOpenOption.TRUNCATE_EXISTING))) {
            pw.println("VibeTags Platform-Breadth Stress Test Results");
            pw.println("=".repeat(104));
            pw.printf("%-16s %-8s %-18s %-13s %-15s %-14s %-12s%n",
                "Level", "OptIns", "OverheadAlloc(KB)", "Elapsed(ms)", "OutputSize(B)",
                "FilesWritten", "ClaudeMd(B)");
            pw.println("-".repeat(104));
        }
    }

    @AfterEach
    void releaseProcessorLogHandle() {
        VibeTagsLogger.shutdown();
    }

    @Test
    void costGrowsWithTheNumberOfPlatformsOptedIn(@TempDir Path tempDir) throws Exception {
        Registry registry = Registry.of();
        assumeTrue(registry != null,
            "the processor jar under test predates ServiceRegistry.optInKeys/buildServiceFileMap — "
                + "skipping the breadth levels, which need it to know what can be opted into");

        int n = Math.min(DEFAULT_CLASSES, maxClasses());
        List<JavaFileObject> sources = SyntheticClassGenerator.generate(n).stream()
            .map(pair -> source(pair[0], pair[1]))
            .collect(Collectors.toList());

        Map<String, Path> serviceFiles = registry.serviceFiles();

        List<String> fileKeys = registry.optInKeys().stream()
            .filter(key -> !registry.writesDirectory(key))
            .filter(key -> !SWITCH_PATHS.contains(relativePath(serviceFiles.get(key))))
            .sorted()
            .collect(Collectors.toList());
        List<String> directoryKeys = registry.optInKeys().stream()
            .filter(registry::writesDirectory)
            .sorted()
            .collect(Collectors.toList());
        List<String> sweepKeys = fileKeys.stream()
            .filter(key -> SWEEP_PATHS.contains(relativePath(serviceFiles.get(key))))
            .collect(Collectors.toList());
        List<String> minimalKeys = fileKeys.stream()
            .filter(key -> ".cursorrules".equals(relativePath(serviceFiles.get(key))))
            .collect(Collectors.toList());
        List<String> claudeRulesKeys = directoryKeys.stream()
            .filter(key -> CLAUDE_RULES_DIR.equals(relativePath(serviceFiles.get(key))))
            .collect(Collectors.toList());

        assertEquals(1, minimalKeys.size(),
            "expected exactly one service to own .cursorrules, found " + minimalKeys);
        assertEquals(SWEEP_PATHS.size(), sweepKeys.size(),
            "the sweep's six anchor files no longer all resolve to an opt-in service: " + sweepKeys);
        assertEquals(1, claudeRulesKeys.size(),
            "expected exactly one service to own " + CLAUDE_RULES_DIR + ", found " + claudeRulesKeys);

        // The first compile in a JVM carries a one-off class-loading tail larger than the
        // differences between levels, so it is spent before anything is recorded.
        measure(sources, root(tempDir, "warmup", sweepKeys, serviceFiles, registry), tempDir,
            "classes-warmup");

        long baseline = measureWithoutProcessor(sources, tempDir);

        Map<String, Level> levels = new LinkedHashMap<>();
        levels.put("minimal",
            run(sources, tempDir, "minimal", minimalKeys, serviceFiles, registry, baseline));
        levels.put("sweep",
            run(sources, tempDir, "sweep", sweepKeys, serviceFiles, registry, baseline));
        levels.put("sweep+granular", run(sources, tempDir, "sweep-granular",
            concat(sweepKeys, claudeRulesKeys), serviceFiles, registry, baseline));
        levels.put("all-files",
            run(sources, tempDir, "all-files", fileKeys, serviceFiles, registry, baseline));
        levels.put("all+granular", run(sources, tempDir, "all-granular",
            concat(fileKeys, directoryKeys), serviceFiles, registry, baseline));

        for (Map.Entry<String, Level> entry : levels.entrySet()) {
            Level level = entry.getValue();
            String line = String.format(Locale.ROOT, "%-16s %-8d %-18d %-13d %-15d %-14d %-12d",
                entry.getKey(), level.optIns, level.overheadAllocKb, level.elapsedMillis,
                level.outputBytes, level.filesWritten, level.alwaysLoadedBytes);
            System.out.println(line);
            append(line);
        }
        System.out.printf(Locale.ROOT,
            "  N=%d classes, %d single-file opt-ins and %d scoped-rules directories available%n",
            n, fileKeys.size(), directoryKeys.size());

        assertLevelsRendered(levels);
        assertGranularEngaged(levels);
    }

    /**
     * Every level must actually have rendered what it opted into.
     *
     * <p>Without this the whole table can be five measurements of a processor that wrote nothing —
     * which is what a fixture creating paths the processor does not write produces, and it passes
     * any assertion made on timings alone.
     */
    private static void assertLevelsRendered(Map<String, Level> levels) {
        for (Map.Entry<String, Level> entry : levels.entrySet()) {
            assertTrue(entry.getValue().outputBytes > 0,
                entry.getKey() + " wrote no output at all: its opt-in entries were created at paths "
                    + "the processor does not write, so this level measured nothing");
        }
        assertTrue(levels.get("all-files").outputBytes > levels.get("sweep").outputBytes,
            "opting into every single-file platform must render more than the sweep's six: "
                + levels.get("all-files").outputBytes + " vs " + levels.get("sweep").outputBytes);
        assertTrue(levels.get("sweep").outputBytes > levels.get("minimal").outputBytes,
            "six files must render more than one: " + levels.get("sweep").outputBytes
                + " vs " + levels.get("minimal").outputBytes);
    }

    /**
     * The granular level must have collapsed the aggregate, which is invariant 6 and the only
     * reason its extra cost is worth paying. Asserted rather than assumed for the reason
     * {@link TestingMdRoutingStressTest} gives: a fixture can leave the feature switched off and
     * still go green, having measured the other path twice.
     */
    private static void assertGranularEngaged(Map<String, Level> levels) {
        long plain = levels.get("sweep").alwaysLoadedBytes;
        long granular = levels.get("sweep+granular").alwaysLoadedBytes;
        assertTrue(plain > 0, ALWAYS_LOADED + " is empty at the sweep level: nothing was rendered");
        assertTrue(granular < plain,
            "opting " + CLAUDE_RULES_DIR + " in must collapse " + ALWAYS_LOADED
                + " to its index and safety buckets, but it went from " + plain + " to " + granular
                + " bytes — the granular directory was not treated as an opt-in");
        assertTrue(levels.get("sweep+granular").filesWritten > levels.get("sweep").filesWritten,
            "the granular level must write per-element rule files beside the aggregates: "
                + levels.get("sweep+granular").filesWritten + " vs "
                + levels.get("sweep").filesWritten);
    }

    // -------------------------------------------------------------------------

    /**
     * {@code ServiceRegistry} reached reflectively, so that pointing this module at an older
     * processor jar skips this test instead of failing the module's compilation. See the class
     * javadoc for why that matters.
     */
    private static final class Registry {
        private final Method buildServiceFileMap;
        private final Method optInKeys;
        private final Method writesDirectory;

        private Registry(Method buildServiceFileMap, Method optInKeys, Method writesDirectory) {
            this.buildServiceFileMap = buildServiceFileMap;
            this.optInKeys = optInKeys;
            this.writesDirectory = writesDirectory;
        }

        /** The registry of the processor on the classpath, or {@code null} when it is too old. */
        static Registry of() {
            try {
                Class<?> type = Class.forName(REGISTRY_CLASS);
                Method map = type.getMethod("buildServiceFileMap", Path.class);
                Method keys = type.getMethod("optInKeys");
                Method dir;
                try {
                    dir = type.getMethod("writesDirectory", String.class);
                } catch (NoSuchMethodException e) {
                    // Older than issue #762, which turned the `_granular` naming convention into a
                    // declared descriptor kind. The convention below is what that release replaced.
                    dir = null;
                }
                return new Registry(map, keys, dir);
            } catch (ClassNotFoundException | NoSuchMethodException e) {
                return null;
            }
        }

        /** Service key to root-relative output path. */
        @SuppressWarnings("unchecked")
        Map<String, Path> serviceFiles() {
            return (Map<String, Path>) invoke(buildServiceFileMap, Path.of(""));
        }

        /** The keys whose entry's presence on disk is the opt-in. */
        @SuppressWarnings("unchecked")
        Collection<String> optInKeys() {
            return (Collection<String>) invoke(optInKeys);
        }

        /** True when the service writes a directory of per-element rule files rather than one file. */
        boolean writesDirectory(String key) {
            if (writesDirectory == null) {
                return key.endsWith("_granular");
            }
            return Boolean.TRUE.equals(invoke(writesDirectory, key));
        }

        private Object invoke(Method method, Object... args) {
            try {
                return method.invoke(null, args);
            } catch (ReflectiveOperationException e) {
                throw new IllegalStateException(
                    "could not read " + REGISTRY_CLASS + "." + method.getName(), e);
            }
        }
    }

    /** One opt-in level, measured once. */
    private static final class Level {
        final int optIns;
        final long overheadAllocKb;
        final long elapsedMillis;
        final long outputBytes;
        final long filesWritten;
        final long alwaysLoadedBytes;

        Level(int optIns, long overheadAllocKb, long elapsedMillis, long outputBytes,
              long filesWritten, long alwaysLoadedBytes) {
            this.optIns = optIns;
            this.overheadAllocKb = overheadAllocKb;
            this.elapsedMillis = elapsedMillis;
            this.outputBytes = outputBytes;
            this.filesWritten = filesWritten;
            this.alwaysLoadedBytes = alwaysLoadedBytes;
        }
    }

    private Level run(List<JavaFileObject> sources, Path tempDir, String name, List<String> keys,
                      Map<String, Path> serviceFiles, Registry registry, long baseline)
            throws IOException {
        Path projectRoot = root(tempDir, name, keys, serviceFiles, registry);
        Measurement m = measure(sources, projectRoot, tempDir, "classes-" + name);
        Path alwaysLoaded = projectRoot.resolve(ALWAYS_LOADED);
        long alwaysLoadedBytes = Files.exists(alwaysLoaded) ? Files.size(alwaysLoaded) : 0L;
        return new Level(keys.size(), (m.allocatedBytes - baseline) / 1024, m.elapsedMillis,
            writtenBytes(projectRoot), writtenFiles(projectRoot), alwaysLoadedBytes);
    }

    /**
     * Creates the opt-in entries for {@code keys} under a fresh project root: an empty file for a
     * single-file service, an empty directory for a scoped-rules one. An empty entry is the opt-in
     * the processor documents, and the same signal every other test here uses.
     *
     * <p>The directories go first, and a file whose path is already one of them is skipped, because
     * one path can be both: {@code .clinerules} is Cline's aggregate file <em>and</em> its
     * scoped-rules directory, and a project has one or the other, never both. At a level that opts
     * into everything the directory form wins, since that is the shape a project asking for scoped
     * rules would have.
     */
    private static Path root(Path tempDir, String name, List<String> keys,
                             Map<String, Path> serviceFiles, Registry registry) throws IOException {
        Path projectRoot = tempDir.resolve(name);
        Files.createDirectories(projectRoot);
        for (String key : keys) {
            Path relative = serviceFiles.get(key);
            if (relative != null && registry.writesDirectory(key)) {
                Files.createDirectories(projectRoot.resolve(relative.toString()));
            }
        }
        for (String key : keys) {
            Path relative = serviceFiles.get(key);
            if (relative == null || registry.writesDirectory(key)) {
                continue;
            }
            Path target = projectRoot.resolve(relative.toString());
            if (Files.isDirectory(target)) {
                continue;
            }
            Path parent = target.getParent();
            if (parent != null) {
                Files.createDirectories(parent);
            }
            if (!Files.exists(target)) {
                Files.createFile(target);
            }
        }
        return projectRoot;
    }

    /** Bytes allocated and milliseconds elapsed for one processor-on compile. */
    private static final class Measurement {
        final long allocatedBytes;
        final long elapsedMillis;

        Measurement(long allocatedBytes, long elapsedMillis) {
            this.allocatedBytes = allocatedBytes;
            this.elapsedMillis = elapsedMillis;
        }
    }

    private static Measurement measure(List<JavaFileObject> sources, Path projectRoot, Path tempDir,
                                       String classesDirName) throws IOException {
        JavaCompiler compiler = ToolProvider.getSystemJavaCompiler();
        if (compiler == null) {
            throw new IllegalStateException(
                "javax.tools.JavaCompiler not available — run with a JDK, not a JRE.");
        }
        // Class files land outside the project root so the output walk sees generated guardrail
        // files and nothing else.
        Path classesDir = tempDir.resolve(classesDirName);
        Files.createDirectories(classesDir);

        List<String> options = List.of(
            "-source", "17",
            "-target", "17",
            "-d", classesDir.toString(),
            "-classpath", System.getProperty("java.class.path"),
            "-processor", PROCESSOR_CLASS,
            "-Avibetags.root=" + projectRoot.toAbsolutePath());

        DiagnosticCollector<JavaFileObject> diagnostics = new DiagnosticCollector<>();
        System.gc();
        long tid = Thread.currentThread().getId();
        long before = threadBean.getThreadAllocatedBytes(tid);
        long start = System.currentTimeMillis();
        try (StandardJavaFileManager fm = compiler.getStandardFileManager(diagnostics, Locale.ROOT,
                StandardCharsets.UTF_8)) {
            compiler.getTask(null, fm, diagnostics, options, null, sources).call();
        }
        long elapsed = System.currentTimeMillis() - start;
        return new Measurement(threadBean.getThreadAllocatedBytes(tid) - before, elapsed);
    }

    /** The same compile with no annotation processing: javac's own share, subtracted from every level. */
    private static long measureWithoutProcessor(List<JavaFileObject> sources, Path tempDir)
            throws IOException {
        JavaCompiler compiler = ToolProvider.getSystemJavaCompiler();
        Path classesDir = tempDir.resolve("classes-baseline");
        Files.createDirectories(classesDir);
        List<String> options = List.of(
            "-source", "17",
            "-target", "17",
            "-d", classesDir.toString(),
            "-classpath", System.getProperty("java.class.path"),
            "-proc:none");
        DiagnosticCollector<JavaFileObject> diagnostics = new DiagnosticCollector<>();
        System.gc();
        long tid = Thread.currentThread().getId();
        long before = threadBean.getThreadAllocatedBytes(tid);
        try (StandardJavaFileManager fm = compiler.getStandardFileManager(diagnostics, Locale.ROOT,
                StandardCharsets.UTF_8)) {
            compiler.getTask(null, fm, diagnostics, options, null, sources).call();
        }
        return threadBean.getThreadAllocatedBytes(tid) - before;
    }

    private static long writtenBytes(Path projectRoot) throws IOException {
        try (Stream<Path> walk = Files.walk(projectRoot)) {
            return walk.filter(Files::isRegularFile).filter(PlatformBreadthStressTest::isGuardrailOutput)
                .mapToLong(PlatformBreadthStressTest::sizeOf).sum();
        }
    }

    private static long writtenFiles(Path projectRoot) throws IOException {
        try (Stream<Path> walk = Files.walk(projectRoot)) {
            return walk.filter(Files::isRegularFile).filter(PlatformBreadthStressTest::isGuardrailOutput)
                .filter(p -> sizeOf(p) > 0).count();
        }
    }

    /**
     * True for a file an AI tool reads, false for the processor's own bookkeeping.
     *
     * <p>{@code .vibetags-cache} and {@code vibetags.log} are written into the project root beside
     * the guardrail files, and counting them puts three files and a few hundred KB of the
     * processor's own housekeeping into a column named {@code OutputSize} — which at the minimal
     * level was most of what the column reported.
     */
    private static boolean isGuardrailOutput(Path path) {
        Path name = path.getFileName();
        if (name == null) {
            return false;
        }
        String fileName = name.toString();
        return !fileName.startsWith(".vibetags-") && !"vibetags.log".equals(fileName);
    }

    private static long sizeOf(Path path) {
        try {
            return Files.size(path);
        } catch (IOException e) {
            throw new UncheckedIOException(e);
        }
    }

    private static List<String> concat(List<String> first, List<String> second) {
        Set<String> all = new LinkedHashSet<>(first);
        all.addAll(second);
        return new ArrayList<>(all);
    }

    /** The service's root-relative path with forward slashes, so a literal compares on every OS. */
    private static String relativePath(Path path) {
        return path == null ? "" : path.toString().replace('\\', '/');
    }

    private static JavaFileObject source(String simpleName, String code) {
        URI uri = URI.create("string:///com/example/generated/" + simpleName + ".java");
        return new SimpleJavaFileObject(uri, JavaFileObject.Kind.SOURCE) {
            @Override
            public CharSequence getCharContent(boolean ignoreEncodingErrors) {
                return code;
            }
        };
    }

    private static int maxClasses() {
        String prop = System.getProperty("stress.max.classes");
        if (prop == null || prop.isBlank() || prop.contains("${")) {
            return Integer.MAX_VALUE;
        }
        try {
            return Integer.parseInt(prop.trim());
        } catch (NumberFormatException e) {
            return Integer.MAX_VALUE;
        }
    }

    private static void append(String line) throws IOException {
        try (PrintWriter pw = new PrintWriter(Files.newBufferedWriter(RESULTS_FILE,
                StandardCharsets.UTF_8, StandardOpenOption.CREATE, StandardOpenOption.APPEND))) {
            pw.println(line);
        }
    }
}
