package se.deversity.vibetags.processor.internal.content;

import org.jspecify.annotations.Nullable;

/**
 * Represents all supported AI platforms and configuration services generated by VibeTags.
 */
public enum Platform {
    CURSOR("cursor"),
    CLAUDE("claude"),
    AI_EXCLUDE("aiexclude"),
    CODEX("codex"),
    COPILOT("copilot"),
    QWEN("qwen"),
    GEMINI("gemini"),
    LLMS("llms"),
    LLMS_FULL("llms_full"),
    AIDER_CONVENTIONS("aider_conventions"),
    AIDER_IGNORE("aider_ignore"),
    CURSOR_IGNORE("cursor_ignore"),
    CLAUDE_IGNORE("claude_ignore"),
    COPILOT_IGNORE("copilot_ignore"),
    QWEN_IGNORE("qwen_ignore"),
    WINDSURF("windsurf"),
    ZED("zed"),
    CODY_IGNORE("cody_ignore"),
    SUPERMAVEN_IGNORE("supermaven_ignore"),
    MENTAT("mentat"),
    SWEEP("sweep"),
    PLANDEX("plandex"),
    DOUBLE_IGNORE("double_ignore"),
    INTERPRETER("interpreter"),
    CODEIUM_IGNORE("codeium_ignore"),
    GEMINI_MD("gemini_md"),
    ANTIGRAVITY_IGNORE("antigravity_ignore"),
    CLINE("cline"),
    JUNIE("junie"),
    FIREBASE("firebase"),
    // Context-packer ignore files
    REPOMIX_IGNORE("repomix_ignore"),
    GITINGEST_IGNORE("gitingest_ignore"),
    GPT_IGNORE("gpt_ignore"),
    GHOSTCODER_IGNORE("ghostcoder_ignore"),
    PIECES_IGNORE("pieces_ignore"),
    // AI pull-request reviewers
    CODERABBIT("coderabbit"),
    PR_AGENT("pr_agent"),
    ELLIPSIS("ellipsis"),
    // Editors & modes
    VOID("void"),
    ROO_MODES("roo_modes"),
    CODEX_CONFIG("codex_config"),
    CODEX_RULES("codex_rules"),
    QWEN_SETTINGS("qwen_settings"),
    QWEN_REFACTOR("qwen_refactor"),
    CODY("cody"),
    LOCKS_REPORT("locks_report"),

    // Granular rule platforms
    CURSOR_GRANULAR("cursor_granular"),
    TRAE_GRANULAR("trae_granular"),
    ROO_GRANULAR("roo_granular"),
    WINDSURF_GRANULAR("windsurf_granular"),
    CONTINUE_GRANULAR("continue_granular"),
    TABNINE_GRANULAR("tabnine_granular"),
    AMAZONQ_GRANULAR("amazonq_granular"),
    AI_RULES_GRANULAR("ai_rules_granular"),
    PEARAI_GRANULAR("pearai_granular"),
    KIRO_GRANULAR("kiro_granular");

    private final String serviceKey;

    Platform(String serviceKey) {
        this.serviceKey = serviceKey;
    }

    public String getServiceKey() {
        return serviceKey;
    }

    public static @Nullable Platform fromServiceKey(String serviceKey) {
        for (Platform p : values()) {
            if (p.serviceKey.equals(serviceKey)) {
                return p;
            }
        }
        return null;
    }
}
