package se.deversity.vibetags.processor;

import se.deversity.vibetags.annotations.AIContext;
import se.deversity.vibetags.annotations.AIAudit;
import se.deversity.vibetags.annotations.AIDraft;
import se.deversity.vibetags.annotations.AIIgnore;
import se.deversity.vibetags.annotations.AILocked;
import se.deversity.vibetags.annotations.AIPrivacy;

import org.slf4j.Logger;

import javax.annotation.processing.*;
import javax.tools.Diagnostic;
import javax.lang.model.SourceVersion;
import javax.lang.model.element.Element;
import javax.lang.model.element.ElementKind;
import javax.lang.model.element.TypeElement;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.stream.Collectors;

/**
 * The core annotation processor for VibeTags.
 * Scans for VibeTags annotations and generates AI platform-specific configuration files
 * (Cursor, Claude, Gemini, Codex, Copilot, Windsurf) to act as guardrails for AI-assisted development.
 * Also generates {@code llms.txt} (concise map) and {@code llms-full.txt} (full reference)
 * following the llms.txt standard for LLM agent discovery.
 */
@SupportedAnnotationTypes("*")
@SupportedSourceVersion(SourceVersion.RELEASE_11)
@SupportedOptions({"vibetags.root", "vibetags.project", "vibetags.log.path", "vibetags.log.level"})
public class AIGuardrailProcessor extends AbstractProcessor {
    
    /** Public constructor for the service loader. */
    public AIGuardrailProcessor() {}

    
    static final String VERSION = "0.5.1";
    private static final String GITHUB_URL = "https://github.com/PIsberg/vibetags";

    /** Header written into every generated file — no version so bumping the dep never creates spurious diffs. */
    private static final String GENERATED_HEADER = "# Generated by VibeTags | " + GITHUB_URL + "\n";

    private static final String MARKER_START_MD = "<!-- VIBETAGS-START -->";
    private static final String MARKER_END_MD = "<!-- VIBETAGS-END -->";
    private static final String MARKER_START_HASH = "# VIBETAGS-START";
    private static final String MARKER_END_HASH = "# VIBETAGS-END";

    // Ensures we process exactly once per compilation run (the actual generation).
    private boolean processed = false;

    /** SLF4J logger backed by a Logback FileAppender writing to {@code vibetags.log} in the project root. */
    private Logger log = null;

    private Path root;
    private String projectName;

    private final Set<Element> lockedElements  = new java.util.LinkedHashSet<>();
    private final Set<Element> contextElements = new java.util.LinkedHashSet<>();
    private final Set<Element> ignoreElements  = new java.util.LinkedHashSet<>();
    private final Set<Element> auditElements   = new java.util.LinkedHashSet<>();
    private final Set<Element> draftElements   = new java.util.LinkedHashSet<>();
    private final Set<Element> privacyElements = new java.util.LinkedHashSet<>();

    // Builders for various AI platforms
    private StringBuilder cursorRules;
    private StringBuilder claudeMd;
    private StringBuilder aiExclude;
    private StringBuilder codexAgents;
    private StringBuilder copilot;
    private StringBuilder llmsTxt;
    private StringBuilder llmsTxtContext;
    private StringBuilder llmsTxtAudit;
    private StringBuilder llmsTxtIgnore;
    private StringBuilder llmsTxtDraft;
    private StringBuilder llmsTxtPrivacy;
    private StringBuilder llmsFullTxt;
    private StringBuilder llmsFullTxtContext;
    private StringBuilder llmsFullTxtAudit;
    private StringBuilder llmsFullTxtIgnore;
    private StringBuilder llmsFullTxtDraft;
    private StringBuilder llmsFullTxtPrivacy;
    private StringBuilder cursorIgnore;
    private StringBuilder qwenMd;
    private StringBuilder aiderConventions;
    private StringBuilder aiderIgnore;
    private StringBuilder cursorIgnoreFile;
    private StringBuilder claudeIgnoreFile;
    private StringBuilder copilotIgnoreFile;
    private StringBuilder qwenIgnoreFile;
    private final Map<Element, StringBuilder> elementRules = new java.util.LinkedHashMap<>();

    @Override
    public synchronized void init(ProcessingEnvironment processingEnv) {
        super.init(processingEnv);
        Map<String, String> options = processingEnv.getOptions();
        
        String rootOverride = options.get("vibetags.root");
        this.root = Paths.get((rootOverride != null && !rootOverride.isBlank())
                ? rootOverride
                : Paths.get("").toAbsolutePath().toString()).toAbsolutePath().normalize();
        
        this.projectName = options.getOrDefault("vibetags.project", "This Project");
        
        String logPath = options.get("vibetags.log.path");
        String logLevel = options.get("vibetags.log.level");
        log = VibeTagsLogger.forRoot(this.root, logPath, logLevel);

        // Reset state for potential reuse (especially in tests)
        this.processed = false;
        this.lockedElements.clear();
        this.contextElements.clear();
        this.ignoreElements.clear();
        this.auditElements.clear();
        this.draftElements.clear();
        this.privacyElements.clear();
        this.elementRules.clear();

        initBuilders();
    }

    private void initBuilders() {
        cursorRules = new StringBuilder("# AUTO-GENERATED AI RULES\n" + GENERATED_HEADER + "# Do not edit manually.\n\n## LOCKED FILES (DO NOT EDIT)\n");
        claudeMd = new StringBuilder("<!-- " + GENERATED_HEADER.trim() + " -->\n<project_guardrails>\n  <locked_files>\n");
        aiExclude = new StringBuilder("# AUTO-GENERATED BY VIBETAGS\n" + GENERATED_HEADER + "# The following files are strictly excluded from AI context.\n");
        codexAgents = new StringBuilder("# AUTO-GENERATED AI RULES\n" + GENERATED_HEADER + "# Do not edit manually.\n\n## LOCKED FILES (DO NOT EDIT)\n");
        copilot = new StringBuilder("# GitHub Copilot Instructions\n" + GENERATED_HEADER + "# AUTO-GENERATED BY VIBETAGS. Do not edit manually.\n\n## Locked Files — DO NOT MODIFY\nDo not suggest changes to the following files:\n\n");
        qwenMd = new StringBuilder("# PROJECT CONTEXT\n" + GENERATED_HEADER + "# AUTO-GENERATED BY VIBETAGS\n\n## LOCKED FILES (DO NOT EDIT)\n");

        llmsTxt = new StringBuilder("# " + projectName + "\n\n" +
            "> AI guardrail rules generated from source annotations by VibeTags.\n\n" +
            "AI tools reading this file should respect the guardrails defined below. " +
            "These rules were extracted from Java source annotations at compile time " +
            "and apply to all AI assistants including Windsurf Cascade, Cursor, Claude, " +
            "GitHub Copilot, and Gemini.\n\n" +
            "## Locked Files\n");
        llmsTxtContext  = new StringBuilder("\n## Contextual Rules\n");
        llmsTxtAudit    = new StringBuilder("\n## Security Audit Requirements\n");
        llmsTxtIgnore   = new StringBuilder("\n## Ignored Elements\n");
        llmsTxtDraft    = new StringBuilder("\n## Implementation Tasks\n");
        llmsTxtPrivacy  = new StringBuilder("\n## PII / Privacy Guardrails\n");

        llmsFullTxt = new StringBuilder("# " + projectName + " — AI Guardrail Rules\n" +
            "> Complete AI guardrail configuration generated from source annotations by VibeTags.\n\n" +
            "This document contains the full set of AI guardrail rules for this project. " +
            "AI tools with large context windows (such as Windsurf Cascade, Claude 4.6, or Gemini 1.5 Pro) " +
            "may load this file directly instead of fetching individual documentation pages.\n\n" +
            "## Locked Files (Do Not Edit)\n" +
            "The following files are locked. AI tools MUST NOT propose modifications to them.\n\n");
        llmsFullTxtContext  = new StringBuilder("\n## Contextual Rules\n" +
            "These files have specific context and focus areas for AI assistance.\n\n");
        llmsFullTxtAudit    = new StringBuilder("\n## Mandatory Security Audit Requirements\n" +
            "When writing or modifying the following files, perform a security audit for the listed vulnerabilities " +
            "before displaying any code to the user.\n\n");
        llmsFullTxtIgnore   = new StringBuilder("\n## Ignored Elements\n" +
            "The following elements must be completely excluded from AI context. Treat them as non-existent.\n\n");
        llmsFullTxtDraft    = new StringBuilder("\n## Implementation Tasks\n" +
            "The following elements are in draft mode and need implementation.\n\n");
        llmsFullTxtPrivacy  = new StringBuilder("\n## PII / Privacy Guardrails\n" +
            "Never include runtime values of the following elements in logs, console output, " +
            "external API calls, test fixtures, or mock data.\n\n");

        cursorIgnoreFile = new StringBuilder("# AUTO-GENERATED BY VIBETAGS\n" + GENERATED_HEADER + "# Cursor-specific exclusion list.\n");
        claudeIgnoreFile = new StringBuilder("# AUTO-GENERATED BY VIBETAGS\n" + GENERATED_HEADER + "# Claude-specific exclusion list.\n");
        copilotIgnoreFile = new StringBuilder("# AUTO-GENERATED BY VIBETAGS\n" + GENERATED_HEADER + "# Copilot-specific exclusion list.\n");
        qwenIgnoreFile = new StringBuilder("# AUTO-GENERATED BY VIBETAGS\n" + GENERATED_HEADER + "# Qwen-specific exclusion list.\n");

        aiderConventions = new StringBuilder("# " + projectName + " CONVENTIONS\n" + GENERATED_HEADER + "# AUTO-GENERATED BY VIBETAGS\n\nThis file contains project-specific coding conventions and AI guardrails extracted from source annotations.\n\n");
        aiderIgnore = new StringBuilder("# AUTO-GENERATED BY VIBETAGS\n" + GENERATED_HEADER + "# Aider-specific exclusion list.\n");

        cursorIgnore = new StringBuilder("\n## \uD83D\uDEAB IGNORED ELEMENTS (EXCLUDE FROM CONTEXT)\nDo not reference, suggest changes to, or include the following in completions or answers.\n\n");
    }

    @Override
    public boolean process(Set<? extends TypeElement> annotations, RoundEnvironment roundEnv) {
        if (roundEnv.processingOver()) {
            if (!processed) {
                generateFiles();
                processed = true;
            }
            return false;
        }

        // Aggregate elements from the current round
        lockedElements.addAll(roundEnv.getElementsAnnotatedWith(AILocked.class));
        contextElements.addAll(roundEnv.getElementsAnnotatedWith(AIContext.class));
        ignoreElements.addAll(roundEnv.getElementsAnnotatedWith(AIIgnore.class));
        auditElements.addAll(roundEnv.getElementsAnnotatedWith(AIAudit.class));
        draftElements.addAll(roundEnv.getElementsAnnotatedWith(AIDraft.class));
        privacyElements.addAll(roundEnv.getElementsAnnotatedWith(AIPrivacy.class));

        // Validation in each round for early feedback
        validateAnnotations(processingEnv.getMessager(), roundEnv);

        return false; // allow others to see the annotations
    }

    private void generateFiles() {
        if (log != null) {
            log.info("VibeTags v{} | {}", VERSION, GITHUB_URL);
            log.info("Root: {}", root.toAbsolutePath());
        }

        // Collect element names for logging
        List<String> lockedNames  = lockedElements.stream().map(e -> e.getSimpleName().toString()).collect(Collectors.toList());
        List<String> contextNames = contextElements.stream().map(e -> e.getSimpleName().toString()).collect(Collectors.toList());
        List<String> ignoreNames  = ignoreElements.stream().map(e -> e.getSimpleName().toString()).collect(Collectors.toList());
        List<String> auditNames   = auditElements.stream().map(e -> e.getSimpleName().toString()).collect(Collectors.toList());
        List<String> draftNames   = draftElements.stream().map(e -> e.getSimpleName().toString()).collect(Collectors.toList());
        List<String> privacyNames = privacyElements.stream().map(e -> e.getSimpleName().toString()).collect(Collectors.toList());

        // Signal directories for granular rules
        Map<String, Path> serviceFiles = buildServiceFileMap(root);
        Set<String> activeServices = resolveActiveServices(processingEnv.getMessager(), serviceFiles);
        if (activeServices.contains("cursor_granular")) cleanupGranularDirectory(serviceFiles.get("cursor_granular"), ".mdc");
        if (activeServices.contains("trae_granular"))   cleanupGranularDirectory(serviceFiles.get("trae_granular"), ".md");
        if (activeServices.contains("roo_granular"))    cleanupGranularDirectory(serviceFiles.get("roo_granular"), ".md");

        // Process @AILocked
        for (Element element : lockedElements) {
            AILocked locked = element.getAnnotation(AILocked.class);
            String className = element.toString();
            String reason = locked.reason();

            cursorRules.append("* `").append(className).append("` - Reason: ").append(reason).append("\n");
            claudeMd.append("    <file path=\"").append(className).append("\">\n")
                    .append("      <reason>").append(reason).append("</reason>\n")
                    .append("    </file>\n");
            aiExclude.append("**/").append(element.getSimpleName()).append(".java\n");
            codexAgents.append("- **").append(className).append("**: ").append(reason).append("\n");
            copilot.append("- `").append(className).append("` - ").append(reason).append("\n");
            qwenMd.append("* `").append(className).append("` - ").append(reason).append("\n");

            llmsTxt.append("- [").append(element.getSimpleName()).append("](").append(className).append("): ").append(reason).append("\n");
            llmsFullTxt.append("### ").append(className).append("\n")
                       .append("- **Reason**: ").append(reason).append("\n\n");

            aiderConventions.append("#### LOCKED: ").append(className).append("\n")
                            .append("- **Status**: Locked (Do Not Edit)\n")
                            .append("- **Reason**: ").append(reason).append("\n\n");
            appendToGranular(element, "Locked Status", "- **Reason**: " + reason);
        }

        claudeMd.append("  </locked_files>\n  <contextual_instructions>\n");
        cursorRules.append("\n## CONTEXTUAL RULES\n");
        codexAgents.append("\n## CONTEXTUAL RULES\n");
        copilot.append("\n## Contextual Guidelines\n");
        qwenMd.append("\n## CONTEXTUAL RULES\n");

        // Process @AIContext
        for (Element element : contextElements) {
            AIContext context = element.getAnnotation(AIContext.class);
            String className = element.toString();

            cursorRules.append("* `").append(className).append("`\n  * Focus: ").append(context.focus())
                       .append("\n  * Avoid: ").append(context.avoids()).append("\n");
            claudeMd.append("    <file path=\"").append(className).append("\">\n")
                    .append("      <focus>").append(context.focus()).append("</focus>\n")
                    .append("      <avoids>").append(context.avoids()).append("</avoids>\n")
                    .append("    </file>\n");
            codexAgents.append("- `").append(className).append("`: Focus on ").append(context.focus())
                       .append(". Avoid ").append(context.avoids()).append(".\n");
            copilot.append("- `").append(className).append("` \n")
                   .append("  - Focus: ").append(context.focus()).append("\n")
                   .append("  - Avoid: ").append(context.avoids()).append("\n");
            qwenMd.append("* `").append(className).append("` \n")
                  .append("  * Focus: ").append(context.focus()).append("\n")
                  .append("  * Avoid: ").append(context.avoids()).append("\n");

            llmsTxtContext.append("- [").append(element.getSimpleName()).append("](").append(className)
                          .append("): Focus - ").append(context.focus())
                          .append(". Avoid - ").append(context.avoids()).append("\n");
            llmsFullTxtContext.append("### ").append(className).append("\n")
                              .append("- **Focus**: ").append(context.focus()).append("\n")
                              .append("- **Avoid**: ").append(context.avoids()).append("\n\n");

            aiderConventions.append("#### CONTEXT: ").append(className).append("\n")
                            .append("- **Focus**: ").append(context.focus()).append("\n")
                            .append("- **Avoid**: ").append(context.avoids()).append("\n\n");
            appendToGranular(element, "Context & Focus", "- **Focus**: " + context.focus() + "\n- **Avoid**: " + context.avoids());
        }
        claudeMd.append("  </contextual_instructions>\n");

        // Builders for ignored elements
        StringBuilder claudeIgnore = new StringBuilder("  <ignored_elements>\n");
        StringBuilder codexIgnore = new StringBuilder("\n## IGNORED ELEMENTS\nThe following elements must be completely excluded from AI context and completions:\n\n");
        StringBuilder geminiIgnore = new StringBuilder("## IGNORED ELEMENTS\nThe following elements must be completely excluded from AI context and completions:\n\n");
        StringBuilder copilotIgnore = new StringBuilder("\n## Ignored Elements\nDo not reference or suggest changes to the following:\n\n");
        StringBuilder qwenIgnore = new StringBuilder("\n## IGNORED ELEMENTS\nThe following elements must be completely excluded from AI's memory and context:\n\n");

        // Process @AIIgnore
        for (Element element : ignoreElements) {
            String className = element.toString();
            cursorIgnore.append("* `").append(className).append("` \n");
            claudeIgnore.append("    <file path=\"").append(className).append("\"/>\n");
            aiExclude.append("**/").append(element.getSimpleName()).append(".java\n");
            codexIgnore.append("- `").append(className).append("` \n");
            geminiIgnore.append("- `").append(className).append("` \n");
            copilotIgnore.append("- `").append(className).append("` \n");

            String globPattern = "**/"+ element.getSimpleName() + ".java\n";
            cursorIgnoreFile.append(globPattern);
            claudeIgnoreFile.append(globPattern);
            copilotIgnoreFile.append(globPattern);
            qwenIgnoreFile.append(globPattern);
            qwenIgnore.append("* `").append(className).append("` \n");

            llmsTxtIgnore.append("- [").append(element.getSimpleName()).append("](").append(className)
                         .append("): excluded from AI context\n");
            llmsFullTxtIgnore.append("### ").append(className).append("\n")
                             .append("- Excluded from AI context entirely - treat as non-existent\n\n");

            aiderIgnore.append(globPattern);
            aiderConventions.append("#### IGNORE: ").append(className).append("\n")
                            .append("- **Instruction**: This element is strictly excluded from AI context. Do not reference it.\n\n");
            appendToGranular(element, "Exclusion Rule", "This element is strictly excluded from AI context. Do not reference it.");
        }

        // Builders for audit sections
        StringBuilder cursorAudit = new StringBuilder("\n## 🛡️ MANDATORY SECURITY AUDITS\nWhen proposing edits or writing code for the following files, you MUST perform a security review before outputting the final code. You must explicitly state in your response that you have audited the changes for the required vulnerabilities.\n\n");
        StringBuilder claudeAudit = new StringBuilder("\n  <audit_requirements>\n");
        StringBuilder geminiMd = new StringBuilder("# GEMINI AI INSTRUCTIONS\n" + GENERATED_HEADER + "\n## CONTINUOUS AUDIT REQUIREMENTS\n" +
            "You are acting as a Senior Staff Engineer. Whenever you write code for the files listed below, you must ensure your completions and chat responses strictly prevent the listed vulnerabilities:\n\n");
        StringBuilder codexAudit = new StringBuilder("\n## 🛡️ MANDATORY SECURITY AUDITS\nWhen proposing edits or writing code for the following files, you MUST perform a security review before outputting the final code. You must explicitly state in your response that you have audited the changes for the required vulnerabilities.\n\n");
        StringBuilder copilotAudit = new StringBuilder("\n## Security Audit Requirements\nBefore suggesting changes to the following files, audit for the listed vulnerabilities:\n\n");
        StringBuilder qwenAudit = new StringBuilder("\n## 🛡️ MANDATORY SECURITY AUDITS\nWhen proposing edits or writing code for the following files, you MUST perform a security review. Explicitly state that you have audited the changes for the listed vulnerabilities.\n\n");

        // Process @AIAudit
        for (Element element : auditElements) {
            AIAudit audit = element.getAnnotation(AIAudit.class);
            if (audit == null) continue;
            String className = element.toString();
            String[] checkFor = audit.checkFor();
            if (checkFor.length == 0) continue;

            cursorAudit.append("* `").append(className).append("` \n");
            cursorAudit.append("  - Required Checks: ").append(String.join(", ", checkFor)).append("\n");
            claudeAudit.append("    <file path=\"").append(className).append("\">\n");
            for (String vulnerability : checkFor) {
                claudeAudit.append("      <vulnerability_check>").append(vulnerability).append("</vulnerability_check>\n");
            }
            claudeAudit.append("    </file>\n");
            geminiMd.append("File: `").append(className).append("` ")
                    .append("\nCritical Vulnerabilities to Prevent: ");
            for (String vulnerability : checkFor) {
                geminiMd.append("\n- ").append(vulnerability);
            }
            geminiMd.append("\n\n");
            codexAudit.append("* `").append(className).append("` \n")
                      .append("  - Required Checks: ").append(String.join(", ", checkFor)).append("\n");
            copilotAudit.append("- `").append(className).append("` \n")
                        .append("  - Required Checks: ").append(String.join(", ", checkFor)).append("\n");
            qwenAudit.append("* `").append(className).append("` \n")
                     .append("  - Required Checks: ").append(String.join(", ", checkFor)).append("\n");

            llmsTxtAudit.append("- [").append(element.getSimpleName()).append("](").append(className)
                        .append("): check for ").append(String.join(", ", checkFor)).append("\n");
            llmsFullTxtAudit.append("### ").append(className).append("\n")
                            .append("- **Required Checks**: ").append(String.join(", ", checkFor)).append("\n\n");

            aiderConventions.append("#### SECURITY AUDIT: ").append(className).append("\n")
                            .append("- **Required Checks**: ").append(String.join(", ", checkFor)).append("\n\n");
            appendToGranular(element, "Security Audit Requirements", "When modifying this element, audit for:\n- " + String.join("\n- ", checkFor));
        }

        // Builders for draft elements
        StringBuilder cursorDraft = new StringBuilder("\n## 📝 IMPLEMENTATION TASKS (TODO)\n" +
            "The following elements are currently in DRAFT mode. Follow the instructions to implement them:\n\n");
        StringBuilder claudeDraft = new StringBuilder("  <implementation_tasks>\n");
        StringBuilder codexDraft = new StringBuilder("\n## IMPLEMENTATION TASKS\nThe following elements are drafts that need implementation:\n\n");
        StringBuilder geminiDraft = new StringBuilder("## IMPLEMENTATION TASKS\nThe following elements are drafts that need implementation:\n\n");
        StringBuilder copilotDraft = new StringBuilder("\n## Implementation Tasks\nFollow these instructions to implement the drafts:\n\n");

        // Process @AIDraft
        for (Element element : draftElements) {
            AIDraft draft = element.getAnnotation(AIDraft.class);
            if (draft == null) continue;
            String className = element.toString();
            String instructions = draft.instructions();
            
            cursorDraft.append("* `").append(className).append("` - Task: ").append(instructions).append("\n");
            claudeDraft.append("    <task path=\"").append(className).append("\">\n")
                       .append("      <instructions>").append(instructions).append("</instructions>\n")
                       .append("    </task>\n");
            codexDraft.append("- **").append(className).append("**: ").append(instructions).append("\n");
            geminiDraft.append("- `").append(className).append("`: ").append(instructions).append("\n");
            copilotDraft.append("- `").append(className).append("`: ").append(instructions).append("\n");

            llmsTxtDraft.append("- [").append(element.getSimpleName()).append("](").append(className)
                        .append("): ").append(instructions).append("\n");
            llmsFullTxtDraft.append("### ").append(className).append("\n")
                            .append("- **Instructions**: ").append(instructions).append("\n\n");

            aiderConventions.append("#### DRAFT/TODO: ").append(className).append("\n")
                            .append("- **Instruction**: ").append(instructions).append("\n\n");
            appendToGranular(element, "Implementation Tasks", "- **Instruction**: " + instructions);
        }

        // Builders for privacy elements
        StringBuilder cursorPrivacy = new StringBuilder("\n## \uD83D\uDD12 PII / PRIVACY GUARDRAILS\n" +
            "The following elements handle Personally Identifiable Information (PII).\n" +
            "NEVER include their runtime values in logs, console output, external API calls,\n" +
            "test fixtures, mock data, or code suggestions.\n\n");
        StringBuilder claudePrivacy = new StringBuilder("  <pii_guardrails>\n");
        StringBuilder codexPrivacy = new StringBuilder("\n## \uD83D\uDD12 PII / PRIVACY GUARDRAILS\n" +
            "The following elements handle PII. Never include their runtime values in logs,\n" +
            "console output, external API calls, test fixtures, or mock data.\n\n");
        StringBuilder geminiPrivacy = new StringBuilder("## PII / PRIVACY GUARDRAILS\n" +
            "The following elements handle Personally Identifiable Information (PII).\n" +
            "Never include their runtime values in logs, console output, external API calls,\n" +
            "test fixtures, mock data, or code suggestions.\n\n");
        StringBuilder copilotPrivacy = new StringBuilder("\n## PII / Privacy Guardrails\n" +
            "Never log, expose, or suggest code that outputs the runtime values of these elements:\n\n");
        StringBuilder qwenPrivacy = new StringBuilder("\n## \uD83D\uDD12 PII / PRIVACY GUARDRAILS\n" +
            "The following elements handle PII. Never include their runtime values in logs,\n" +
            "console output, external API calls, test fixtures, or mock data.\n\n");

        // Process @AIPrivacy
        for (Element element : privacyElements) {
            AIPrivacy privacy = element.getAnnotation(AIPrivacy.class);
            if (privacy == null) continue;
            String className = element.toString();
            String reason = privacy.reason();

            cursorPrivacy.append("* `").append(className).append("` - ").append(reason).append("\n");
            claudePrivacy.append("    <element path=\"").append(className).append("\">\n")
                         .append("      <reason>").append(reason).append("</reason>\n")
                         .append("    </element>\n");
            codexPrivacy.append("- `").append(className).append("`: ").append(reason).append("\n");
            geminiPrivacy.append("- `").append(className).append("`: ").append(reason).append("\n");
            copilotPrivacy.append("- `").append(className).append("` - ").append(reason).append("\n");
            qwenPrivacy.append("* `").append(className).append("` - ").append(reason).append("\n");

            llmsTxtPrivacy.append("- [").append(element.getSimpleName()).append("](").append(className)
                          .append("): ").append(reason).append("\n");
            llmsFullTxtPrivacy.append("### ").append(className).append("\n")
                              .append("- **Reason**: ").append(reason).append("\n\n");

            aiderConventions.append("#### PRIVACY/PII: ").append(className).append("\n")
                            .append("- **Safety Rule**: Never log or expose runtime values of this element.\n")
                            .append("- **Reason**: ").append(reason).append("\n\n");
            appendToGranular(element, "PII / Privacy Guardrails", "- **Rule**: Never log or expose runtime values of this element.\n- **Reason**: " + reason);
        }

        // Finalize sections
        if (!auditElements.isEmpty()) {
            cursorRules.append(cursorAudit);
            claudeAudit.append("  </audit_requirements>\n");
            claudeMd.append(claudeAudit);
            claudeMd.append("\n<rule>\n  If you are asked to modify any file listed in <audit_requirements>, you must first silently analyze your proposed code for the listed <vulnerability_check> items. If your code introduces these vulnerabilities, you must rewrite it before displaying it to the user.\n</rule>\n");
            codexAgents.append(codexAudit);
            copilot.append(copilotAudit);
            qwenMd.append(qwenAudit);
        }

        if (!ignoreElements.isEmpty()) {
            cursorRules.append(cursorIgnore);
            claudeIgnore.append("  </ignored_elements>\n");
            claudeMd.append(claudeIgnore);
            claudeMd.append("\n<rule>Never reference or suggest changes to any element listed in <ignored_elements>. Treat these as if they do not exist.</rule>\n");
            codexAgents.append(codexIgnore);
            geminiMd.append(geminiIgnore);
            copilot.append(copilotIgnore);
            qwenMd.append(qwenIgnore);
        }

        if (!draftElements.isEmpty()) {
            cursorRules.append(cursorDraft);
            claudeDraft.append("  </implementation_tasks>\n");
            claudeMd.append(claudeDraft);
            codexAgents.append(codexDraft);
            geminiMd.append(geminiDraft);
            copilot.append(copilotDraft);
        }

        if (!privacyElements.isEmpty()) {
            cursorRules.append(cursorPrivacy);
            claudePrivacy.append("  </pii_guardrails>\n");
            claudeMd.append(claudePrivacy);
            claudeMd.append("\n<rule>\n  Never include runtime values of elements listed in <pii_guardrails> in logs, console output, external API calls, test fixtures, mock data, or code suggestions. Treat their values as strictly confidential.\n</rule>\n");
            codexAgents.append(codexPrivacy);
            geminiMd.append(geminiPrivacy);
            copilot.append(copilotPrivacy);
            qwenMd.append(qwenPrivacy);
        }

        claudeMd.append("</project_guardrails>\n");
        claudeMd.append("\n<rule>Never propose edits to files listed in <locked_files>.</rule>\n");

        // Assemble llms.txt and llms-full.txt
        llmsTxt.append(llmsTxtContext);
        llmsFullTxt.append(llmsFullTxtContext);
        if (!auditElements.isEmpty()) { llmsTxt.append(llmsTxtAudit); llmsFullTxt.append(llmsFullTxtAudit); }
        if (!ignoreElements.isEmpty()) { llmsTxt.append(llmsTxtIgnore); llmsFullTxt.append(llmsFullTxtIgnore); }
        if (!draftElements.isEmpty()) { llmsTxt.append(llmsTxtDraft); llmsFullTxt.append(llmsFullTxtDraft); }
        if (!privacyElements.isEmpty()) { llmsTxt.append(llmsTxtPrivacy); llmsFullTxt.append(llmsFullTxtPrivacy); }

        if (log != null) {
            log.info("Active services ({}): {}", activeServices.size(),
                activeServices.stream().sorted().collect(Collectors.joining(", ")));
            if (!lockedNames.isEmpty())  log.info("@AILocked:  {} — {}", lockedNames.size(),  String.join(", ", lockedNames));
            if (!contextNames.isEmpty()) log.info("@AIContext: {} — {}", contextNames.size(), String.join(", ", contextNames));
            if (!ignoreNames.isEmpty())  log.info("@AIIgnore:  {} — {}", ignoreNames.size(),  String.join(", ", ignoreNames));
            if (!auditNames.isEmpty())   log.info("@AIAudit:   {} — {}", auditNames.size(),   String.join(", ", auditNames));
            if (!draftNames.isEmpty())   log.info("@AIDraft:   {} — {}", draftNames.size(),   String.join(", ", draftNames));
            if (!privacyElements.isEmpty()) log.info("@AIPrivacy: {} — {}", privacyNames.size(), String.join(", ", privacyNames));
        }

        Map<String, String> contentByService = new LinkedHashMap<>();
        if (activeServices.contains("cursor"))    contentByService.put("cursor",    cursorRules.toString());
        if (activeServices.contains("qwen"))      contentByService.put("qwen",      qwenMd.toString());
        if (activeServices.contains("claude"))    contentByService.put("claude",    claudeMd.toString());
        if (activeServices.contains("gemini"))    contentByService.put("gemini",    geminiMd.toString());
        if (activeServices.contains("codex"))     contentByService.put("codex",     codexAgents.toString());
        if (activeServices.contains("copilot"))   contentByService.put("copilot",   copilot.toString());
        if (activeServices.contains("llms"))      contentByService.put("llms",      llmsTxt.toString());
        if (activeServices.contains("llms_full")) contentByService.put("llms_full", llmsFullTxt.toString());

        if (activeServices.contains("aiexclude") && (activeServices.contains("gemini") || activeServices.contains("codex"))) {
            contentByService.put("aiexclude", aiExclude.toString());
        }

        if (activeServices.contains("cursor_ignore"))  contentByService.put("cursor_ignore",  cursorIgnoreFile.toString());
        if (activeServices.contains("claude_ignore"))  contentByService.put("claude_ignore",  claudeIgnoreFile.toString());
        if (activeServices.contains("copilot_ignore")) contentByService.put("copilot_ignore", copilotIgnoreFile.toString());
        if (activeServices.contains("qwen_ignore"))    contentByService.put("qwen_ignore",    qwenIgnoreFile.toString());

        if (activeServices.contains("codex")) {
            contentByService.put("codex_config", "# " + GENERATED_HEADER.trim() + "\n[project]\nmodel = \"o3-mini\"\napproval_policy = \"on-request\"\n");
            contentByService.put("codex_rules", 
                "# " + GENERATED_HEADER.trim() + "\n# VibeTags: Starlark Command Permissions\n\n" +
                "prefix_rule(\"ls\", \"allow\")\n" +
                "prefix_rule(\"cat\", \"allow\")\n" +
                "prefix_rule(\"grep\", \"allow\")\n" +
                "prefix_rule(\"mvn\", \"prompt\")\n" +
                "prefix_rule(\"npm\", \"prompt\")\n" +
                "prefix_rule(\"git\", \"prompt\")\n" +
                "prefix_rule(\"rm\", \"prompt\")\n");
        }
        if (activeServices.contains("qwen")) {
            contentByService.put("qwen_settings", "{\n  \"project\": {\n    \"model\": \"qwen3-coder-plus\",\n    \"mcp\": {\n      \"enabled\": true\n    }\n  }\n}\n");
            contentByService.put("qwen_refactor", "# /refactor command\n# AUTO-GENERATED BY VIBETAGS\n\nRefactor the current selection to improve maintainability and performance while strictly following the project's contextual rules in QWEN.md.\n");
        }

        if (activeServices.contains("aider_conventions")) contentByService.put("aider_conventions", aiderConventions.toString());
        if (activeServices.contains("aider_ignore"))      contentByService.put("aider_ignore",      aiderIgnore.toString());

        Messager messager = processingEnv.getMessager();
        contentByService.forEach((service, content) -> {
            Path filePath = serviceFiles.get(service);
            boolean changed = writeFileIfChanged(filePath.toString(), content);
            String relPath = root.relativize(filePath).toString().replace('\\', '/');
            String status = changed ? "updated" : "no changes";
            messager.printMessage(Diagnostic.Kind.NOTE, "VibeTags: " + status + " - " + relPath);
            if (log != null) {
                if (changed) log.info("{} — updated", relPath);
                else         log.info("{} — no changes", relPath);
            }
        });

        // Granular Rules Writing
        elementRules.forEach((element, builder) -> {
            String qName = element.toString().replace('.', '-').replaceAll("[^a-zA-Z0-9-]", "-");
            String simpleName = element.getSimpleName().toString();
            String rulesContent = builder.toString().trim();
            String glob = javax.lang.model.element.ElementKind.PACKAGE.equals(element.getKind())
                ? "**/"+ simpleName + "/**/*.java"
                : "**/"+ simpleName + ".java";

            if (activeServices.contains("cursor_granular")) {
                String mdc = "---\n" +
                    "description: \"AI rules for " + element + "\"\n" +
                    "globs: [\"" + glob + "\"]\n" +
                    "alwaysApply: false\n" +
                    "---\n\n" +
                    "# Rules for " + simpleName + "\n\n" +
                    rulesContent;
                Path path = serviceFiles.get("cursor_granular").resolve(qName + ".mdc");
                writeFileIfChanged(path.toString(), mdc);
            }

            if (activeServices.contains("trae_granular")) {
                String md = "---\n" +
                    "alwaysApply: false\n" +
                    "globs: [\"" + glob + "\"]\n" +
                    "description: \"AI rules for " + element + "\"\n" +
                    "---\n\n" +
                    "# Rules for " + simpleName + "\n\n" +
                    rulesContent;
                Path path = serviceFiles.get("trae_granular").resolve(qName + ".md");
                writeFileIfChanged(path.toString(), md);
            }

            if (activeServices.contains("roo_granular")) {
                String md = "# Rules for " + simpleName + "\n\n" + rulesContent;
                Path path = serviceFiles.get("roo_granular").resolve(qName + ".md");
                writeFileIfChanged(path.toString(), md);
            }
        });
        
        checkOrphanedAnnotations(messager, activeServices, 
            !lockedElements.isEmpty(),
            !ignoreElements.isEmpty(), 
            !auditElements.isEmpty());
    }

    void validateAnnotations(Messager messager, RoundEnvironment roundEnv) {
        // Contradiction Check: AIDraft + AILocked
        for (Element element : roundEnv.getElementsAnnotatedWith(AILocked.class)) {
            if (element.getAnnotation(AIDraft.class) != null) {
                messager.printMessage(Diagnostic.Kind.WARNING,
                    "VibeTags: " + element.toString() + " is annotated with both @AIDraft and @AILocked. This is contradictory.", element);
            }
        }

        // Empty Audit Check
        for (Element element : roundEnv.getElementsAnnotatedWith(AIAudit.class)) {
            AIAudit audit = element.getAnnotation(AIAudit.class);
            if (audit.checkFor().length == 0) {
                messager.printMessage(Diagnostic.Kind.WARNING,
                    "VibeTags: @AIAudit on " + element.toString() + " has no 'checkFor' items list. It will be ignored.", element);
            }
        }

        // Redundancy Check: AIPrivacy + AIIgnore
        for (Element element : roundEnv.getElementsAnnotatedWith(AIPrivacy.class)) {
            if (element.getAnnotation(AIIgnore.class) != null) {
                messager.printMessage(Diagnostic.Kind.WARNING,
                    "VibeTags: " + element.toString() + " is annotated with both @AIPrivacy and @AIIgnore. "
                    + "@AIIgnore already excludes the element from AI context; @AIPrivacy is redundant.", element);
            }
        }
    }

    void checkOrphanedAnnotations(Messager messager, Set<String> active, boolean hasLocked, boolean hasIgnore, boolean hasAudit) {
        if (hasIgnore) {
            warn(messager, active.contains("cursor") && !active.contains("cursor_ignore"),
                "VibeTags: @AIIgnore used but .cursorignore is missing for Cursor support. Consider creating it.");
            warn(messager, active.contains("claude") && !active.contains("claude_ignore"),
                "VibeTags: @AIIgnore used but .claudeignore is missing for Claude support. Consider creating it.");
            warn(messager, active.contains("copilot") && !active.contains("copilot_ignore"),
                "VibeTags: @AIIgnore used but .copilotignore is missing for Copilot support. Consider creating it.");
            warn(messager, active.contains("qwen") && !active.contains("qwen_ignore"),
                "VibeTags: @AIIgnore used but .qwenignore is missing for Qwen support. Consider creating it.");
            warn(messager, (active.contains("gemini") || active.contains("codex")) && !active.contains("aiexclude"),
                "VibeTags: @AIIgnore used but .aiexclude is missing for Gemini/Codex support. Consider creating it.");
        }

        if (hasLocked) {
            warn(messager, (active.contains("gemini") || active.contains("codex")) && !active.contains("aiexclude"),
                "VibeTags: @AILocked used but .aiexclude (hard guardrail) is missing for Gemini/Codex support. Consider creating it.");
        }
    }

    /** Emits a compiler WARNING via {@code messager} and mirrors it to the log file when the condition is true. */
    private void warn(Messager messager, boolean condition, String message) {
        if (!condition) return;
        messager.printMessage(Diagnostic.Kind.WARNING, message);
        if (log != null) log.warn(message);
    }

    private void cleanupGranularDirectory(Path dir, String extension) {
        if (dir == null || !Files.exists(dir) || !Files.isDirectory(dir)) return;
        try (java.util.stream.Stream<Path> stream = Files.list(dir)) {
            stream.filter(Files::isRegularFile)
                  .filter(p -> p.toString().endsWith(extension))
                  .forEach(p -> {
                      try {
                          String content = Files.readString(p);
                          if (content.contains(MARKER_START_MD) || content.contains(MARKER_START_HASH)) {
                              Files.delete(p);
                          }
                      } catch (IOException ignored) {}
                  });
        } catch (IOException e) {
            // Log if useful, but stay silent during compilation
        }
    }

    /**
     * Walks up the element hierarchy to find the nearest TypeElement (class/interface)
     * or PackageElement. This ensures granular rules are consolidated at the file or package level.
     */
    private Element getOwningElement(Element e) {
        Element current = e;
        while (current != null) {
            ElementKind kind = current.getKind();
            if (current instanceof TypeElement || (kind != null && kind.equals(javax.lang.model.element.ElementKind.PACKAGE))) {
                return current;
            }
            current = current.getEnclosingElement();
        }
        return e;
    }

    private void appendToGranular(Element element, String title, String content) {
        Element owner = getOwningElement(element);
        StringBuilder sb = elementRules.computeIfAbsent(owner, k -> new StringBuilder());
        if (sb.length() > 0) sb.append("\n");
        
        // Add a sub-header if the annotation is on a member (method/field) of the owning class
        if (!owner.equals(element)) {
            ElementKind kind = element.getKind();
            String kindStr = (kind != null) ? kind.toString().toLowerCase() : "element";
            sb.append("### Rules for ").append(kindStr)
              .append(" ").append(element.getSimpleName()).append("\n");
        } else {
            sb.append("## ").append(title).append("\n");
        }
        sb.append(content).append("\n");
    }

    /**
     * Returns the canonical map of service key → output file path for a given project root.
     *
     * @param root the project root directory
     * @return a map of logical service names to their expected file paths
     */
    public static Map<String, Path> buildServiceFileMap(Path root) {
        Map<String, Path> map = new LinkedHashMap<>();
        map.put("cursor",    root.resolve(".cursorrules"));
        map.put("claude",    root.resolve("CLAUDE.md"));
        map.put("aiexclude", root.resolve(".aiexclude"));
        map.put("codex",     root.resolve("AGENTS.md"));
        map.put("gemini",    root.resolve("gemini_instructions.md"));
        map.put("copilot",   root.resolve(".github/copilot-instructions.md"));
        map.put("qwen",      root.resolve("QWEN.md"));
        map.put("cursor_ignore",  root.resolve(".cursorignore"));
        map.put("claude_ignore",  root.resolve(".claudeignore"));
        map.put("copilot_ignore", root.resolve(".copilotignore"));
        map.put("qwen_ignore",    root.resolve(".qwenignore"));
        map.put("codex_config",   root.resolve(".codex/config.toml"));
        map.put("codex_rules",    root.resolve(".codex/rules/vibetags.rules"));
        map.put("qwen_settings",  root.resolve(".qwen/settings.json"));
        map.put("qwen_refactor",  root.resolve(".qwen/commands/refactor.md"));
        map.put("llms",           root.resolve("llms.txt"));
        map.put("llms_full",      root.resolve("llms-full.txt"));
        map.put("aider_conventions", root.resolve("CONVENTIONS.md"));
        map.put("aider_ignore",      root.resolve(".aiderignore"));
        map.put("cursor_granular",   root.resolve(".cursor/rules/"));
        map.put("roo_granular",      root.resolve(".roo/rules/"));
        map.put("trae_granular",     root.resolve(".trae/rules/"));
        return map;
    }

    /**
     * Resolves which primary services should have their files written.
     * Only "signal" files (like QWEN.md or .cursorrules) are checked — their presence acts as the opt-in.
     *
     * @param messager        the compiler messager for printing notes
     * @param allServiceFiles the map of all possible service files
     * @return the set of active service keys based on existing files
     */
    public static Set<String> resolveActiveServices(Messager messager, Map<String, Path> allServiceFiles) {
        // Only these primary files define an "active" service
        Set<String> optInKeys = Set.of(
            "cursor", "claude", "aiexclude", "codex", "gemini", "copilot", "qwen",
            "cursor_ignore", "claude_ignore", "copilot_ignore", "qwen_ignore",
            "llms", "llms_full", "aider_conventions", "aider_ignore",
            "cursor_granular", "roo_granular", "trae_granular"
        );

        Set<String> active = allServiceFiles.entrySet().stream()
            .filter(e -> optInKeys.contains(e.getKey()))
            .filter(e -> {
                Path p = e.getValue();
                return Files.exists(p);
            })
            .map(Map.Entry::getKey)
            .collect(java.util.stream.Collectors.toSet());

        if (active.isEmpty()) {
            StringBuilder msg = new StringBuilder(
                "VibeTags: No AI config files found - nothing will be generated.\n" +
                "Create one or more of the following files in your project root to opt in:\n");
            allServiceFiles.entrySet().stream()
                .filter(e -> optInKeys.contains(e.getKey()))
                .forEach(e -> msg.append("  ").append(e.getValue().getFileName()).append("\n"));
            messager.printMessage(javax.tools.Diagnostic.Kind.NOTE, msg.toString());
        }

        return active;
    }

    /**
     * Determines the appropriate VibeTags markers for a given file.
     *
     * @param fileName the name of the file
     * @return an array containing [startMarker, endMarker], or {@code null} if markers are not supported
     */
    private String[] getMarkersFor(String fileName) {
        if (fileName.endsWith(".md") || fileName.endsWith(".mdc") || fileName.equals("llms.txt") || fileName.equals("llms-full.txt")) {
            return new String[]{MARKER_START_MD, MARKER_END_MD};
        }
        if (fileName.endsWith(".json") || fileName.endsWith(".toml")) {
            return null; // No markers for JSON/TOML, overwrite only
        }
        // Default to hash comments for rules/ignore files (.cursorrules, .aiexclude, etc.)
        return new String[]{MARKER_START_HASH, MARKER_END_HASH};
    }

    /**
     * Writes {@code content} to {@code path} only if the file's current content differs.
     *
     * @param path    the destination file path
     * @param content the content to write
     * @return {@code true} if the file was written (content changed or file was empty),
     *         {@code false} if the existing content was already up-to-date.
     */
    public boolean writeFileIfChanged(String path, String content) {
        try {
            Path filePath = Paths.get(path);
            String fileName = filePath.getFileName().toString();
            String[] markers = getMarkersFor(fileName);

            // Special handling for YAML front-matter: markers MUST come after it
            String frontMatter = "";
            String body = content;
            if (content.startsWith("---")) {
                int secondTriple = content.indexOf("---", 3);
                if (secondTriple != -1) {
                    frontMatter = content.substring(0, secondTriple + 3).trim();
                    body = content.substring(secondTriple + 3).trim();
                }
            }

            // Wrap body in markers if supported
            String wrappedBody = (markers != null)
                ? markers[0] + "\n" + body.trim() + "\n" + markers[1]
                : body;

            String finalContent = frontMatter.isEmpty() ? wrappedBody : frontMatter + "\n\n" + wrappedBody;

            if (Files.exists(filePath)) {
                String existing = Files.readString(filePath, java.nio.charset.StandardCharsets.UTF_8);

                if (markers != null) {
                    int startIdx = existing.indexOf(markers[0]);
                    int endIdx = existing.indexOf(markers[1]);

                    if (startIdx != -1 && endIdx != -1 && startIdx < endIdx) {
                        // Section exists: replace it
                        String before = existing.substring(0, startIdx).stripTrailing();
                        String after = existing.substring(endIdx + markers[1].length()).stripLeading();

                        StringBuilder sb = new StringBuilder();
                        if (!before.isEmpty()) sb.append(before).append("\n\n");
                        sb.append(wrappedBody);
                        if (!after.isEmpty()) sb.append("\n\n").append(after);
                        String updated = sb.toString();

                        if (existing.strip().equals(updated.strip())) {
                            return false;
                        }
                        Files.writeString(filePath, updated, java.nio.charset.StandardCharsets.UTF_8);
                        return true;
                    } else if (existing.contains(GENERATED_HEADER.trim())) {
                        // Legacy VibeTags file found (no markers but has header): upgrade to markers
                        if (existing.strip().equals(finalContent.strip())) {
                            return false;
                        }
                        Files.writeString(filePath, finalContent, java.nio.charset.StandardCharsets.UTF_8);
                        return true;
                    } else {
                        // Section missing and not a legacy VibeTags file: append to the end
                        // If file is empty, don't add extra leading newlines
                        String updated = existing.isEmpty()
                            ? wrappedBody + "\n"
                            : existing.stripTrailing() + "\n\n" + wrappedBody + "\n";
                        Files.writeString(filePath, updated, java.nio.charset.StandardCharsets.UTF_8);
                        return true;
                    }
                } else {
                    // Markers not supported (JSON/TOML): standard overwrite-if-changed logic
                    if (existing.strip().equals(content.strip())) {
                        return false;
                    }
                }
            }

            // File doesn't exist or doesn't support markers: create with final content
            Path parent = filePath.getParent();
            if (parent != null && !Files.exists(parent)) {
                Files.createDirectories(parent);
            }
            try (PrintWriter out = new PrintWriter(new FileWriter(path, java.nio.charset.StandardCharsets.UTF_8))) {
                out.println(finalContent.trim());
            }
            return true;
        } catch (IOException e) {
            processingEnv.getMessager().printMessage(
                javax.tools.Diagnostic.Kind.WARNING, "VibeTags: Failed to write AI rules file: " + path
            );
            return false;
        }
    }

}
