package se.deversity.vibetags.processor;

import se.deversity.vibetags.processor.internal.AnnotationCollector;
import se.deversity.vibetags.processor.internal.AnnotationValidator;
import se.deversity.vibetags.processor.internal.BuildFingerprint;
import se.deversity.vibetags.processor.internal.GranularRulesWriter;
import se.deversity.vibetags.processor.internal.GuardrailContentBuilder;
import se.deversity.vibetags.processor.internal.GuardrailFileWriter;
import se.deversity.vibetags.processor.internal.OrphanWarner;
import se.deversity.vibetags.processor.internal.ServiceRegistry;
import se.deversity.vibetags.processor.internal.WriteCache;
import org.slf4j.Logger;

import javax.annotation.processing.*;
import javax.tools.Diagnostic;
import javax.lang.model.SourceVersion;
import javax.lang.model.element.Element;
import javax.lang.model.element.TypeElement;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.Map;
import java.util.Set;
import java.util.stream.Collectors;

/**
 * The core annotation processor for VibeTags.
 *
 * <p>Orchestrates the work — discovering annotated elements, validating, generating per-platform
 * guardrail content, and writing to disk. The actual work is delegated to focused helpers in the
 * {@link se.deversity.vibetags.processor.internal} package; this class is mostly the
 * {@link AbstractProcessor} adaptor plus a small set of package-private delegates kept in place
 * so the existing test suite continues to compile against the same surface.
 */
@SupportedAnnotationTypes("*")
@SupportedSourceVersion(SourceVersion.RELEASE_11)
@SupportedOptions({"vibetags.root", "vibetags.project", "vibetags.log.path", "vibetags.log.level"})
public class AIGuardrailProcessor extends AbstractProcessor {

    /** Public constructor for the service loader. */
    public AIGuardrailProcessor() {}

    static final String VERSION = "0.7.1";
    private static final String GITHUB_URL = "https://github.com/PIsberg/vibetags";

    /** Header written into every generated file — no version so bumping the dep never creates spurious diffs. */
    private static final String GENERATED_HEADER = "# Generated by VibeTags | " + GITHUB_URL + "\n";

    /** Ensures we generate files exactly once per compilation run. */
    private boolean processed = false;

    /** SLF4J logger backed by a Logback FileAppender writing to {@code vibetags.log} in the project root. */
    private Logger log = null;

    /** Lazily constructed file writer; recreated on init() with the live messager + log. */
    private GuardrailFileWriter fileWriter = new GuardrailFileWriter(GENERATED_HEADER, null, null);

    /** Granular rules writer; recreated on init() to share the live fileWriter. */
    private GranularRulesWriter granularWriter = new GranularRulesWriter(fileWriter);

    /** Per-output-file content cache; created on init() pointing at {@code <root>/.vibetags-cache}. */
    private WriteCache writeCache = null;

    private Path root;
    private String projectName;

    private final AnnotationCollector collector = new AnnotationCollector();
    private final Set<Element> lockedElements      = collector.locked();
    private final Set<Element> contextElements     = collector.context();
    private final Set<Element> ignoreElements      = collector.ignore();
    private final Set<Element> auditElements       = collector.audit();
    private final Set<Element> draftElements       = collector.draft();
    private final Set<Element> privacyElements     = collector.privacy();
    private final Set<Element> coreElements        = collector.core();
    private final Set<Element> performanceElements = collector.performance();

    /** Per-element granular rule sections, populated by GuardrailContentBuilder.build(). */
    private Map<Element, StringBuilder> elementRules = new java.util.LinkedHashMap<>();

    @Override
    public synchronized void init(ProcessingEnvironment processingEnv) {
        super.init(processingEnv);
        Map<String, String> options = processingEnv.getOptions();

        String rootOverride = options.get("vibetags.root");
        this.root = Paths.get((rootOverride != null && !rootOverride.isBlank())
                ? rootOverride
                : Paths.get("").toAbsolutePath().toString()).toAbsolutePath().normalize();

        Messager messager = getSafeMessager();
        messager.printMessage(Diagnostic.Kind.NOTE, "VibeTags: Root resolved: " + this.root);
        messager.printMessage(Diagnostic.Kind.NOTE, "VibeTags: user.dir:      " + System.getProperty("user.dir"));

        this.projectName = options.getOrDefault("vibetags.project", "This Project");

        String logPath = options.get("vibetags.log.path");
        String logLevel = options.get("vibetags.log.level");
        log = VibeTagsLogger.forRoot(this.root, logPath, logLevel);

        this.writeCache = new WriteCache(this.root.resolve(".vibetags-cache"));
        this.fileWriter = new GuardrailFileWriter(GENERATED_HEADER, processingEnv.getMessager(), log, this.writeCache);
        this.granularWriter = new GranularRulesWriter(this.fileWriter);

        // Reset for potential reuse (tests reuse the processor instance via init).
        this.processed = false;
        collector.reset();
        this.elementRules = new java.util.LinkedHashMap<>();
    }

    @Override
    public boolean process(Set<? extends TypeElement> annotations, RoundEnvironment roundEnv) {
        if (processed || roundEnv.processingOver()) {
            if (roundEnv.processingOver() && !processed) {
                generateFiles();
                processed = true;
            }
            return false;
        }

        collector.collect(roundEnv);
        validateAnnotations(processingEnv.getMessager(), roundEnv);

        return false; // allow other processors to see the same annotations
    }

    private void generateFiles() {
        if (log != null) {
            log.info("VibeTags v{} | {}", VERSION, GITHUB_URL);
            log.info("Root: {}", root.toAbsolutePath());
        }

        Map<String, Path> serviceFiles = ServiceRegistry.buildServiceFileMap(root);
        Set<String> activeServices = ServiceRegistry.resolveActiveServices(processingEnv.getMessager(), serviceFiles);

        // Top-level fingerprint short-circuit: if neither the annotation set nor the active
        // service set has changed since the last successful run, AND every file we wrote then is
        // still byte-stable on disk, skip the entire build + per-file-compare phase. The two-part
        // guard (input fingerprint AND output stability) means a manually deleted granular file
        // still triggers regeneration.
        String fingerprint = BuildFingerprint.compute(collector, activeServices);
        if (writeCache != null
                && fingerprint.equals(writeCache.getBuildFingerprint())
                && writeCache.allCachedFilesStable()) {
            Messager m = getSafeMessager();
            m.printMessage(Diagnostic.Kind.NOTE,
                "VibeTags: inputs unchanged since last run (fingerprint " + fingerprint
                    + "), skipping content build and writes.");
            if (log != null) log.info("Inputs unchanged (fingerprint {}). Skipping generate phase.", fingerprint);
            return;
        }

        // Build all per-platform content in one pass.
        GuardrailContentBuilder.Result built =
            new GuardrailContentBuilder(collector, activeServices, projectName, GENERATED_HEADER).build();
        Map<String, String> contentByService = built.contentByService;
        this.elementRules = built.elementRules;

        logSummary(activeServices);

        Messager messager = getSafeMessager();
        messager.printMessage(Diagnostic.Kind.NOTE,
            "VibeTags: Generating files (v" + VERSION + ") for " + contentByService.size()
                + " active services: " + String.join(", ", contentByService.keySet()));

        // Write the per-platform content files.
        contentByService.forEach((service, content) -> {
            Path filePath = serviceFiles.get(service);
            boolean isIgnoreFile = service.endsWith("_ignore") || service.equals("aider_ignore") || service.equals("aiexclude");
            boolean changed = writeFileIfChanged(filePath.toString(), content, collector.anyAnnotationsFound() || isIgnoreFile);
            String relPath = root.relativize(filePath).toString().replace('\\', '/');
            String status = changed ? "updated" : "no changes";
            messager.printMessage(Diagnostic.Kind.NOTE, "VibeTags: " + status + " - " + relPath);
            if (log != null) log.info("{} — {}", relPath, status);
        });

        // Per-class granular rule files (Cursor / Trae / Roo) + cleanup of orphans.
        Set<String> writtenQNames = granularWriter.writeAll(elementRules, serviceFiles, activeServices);
        granularWriter.cleanupAll(serviceFiles, activeServices, writtenQNames);

        checkOrphanedAnnotations(messager, activeServices,
            !lockedElements.isEmpty(),
            !ignoreElements.isEmpty(),
            !auditElements.isEmpty());

        if (writeCache != null) {
            writeCache.setBuildFingerprint(fingerprint);
            writeCache.flush();
        }
    }

    private void logSummary(Set<String> activeServices) {
        if (log == null) return;
        log.info("Active services ({}): {}", activeServices.size(),
            activeServices.stream().sorted().collect(Collectors.joining(", ")));
        logSet("@AILocked",      collector.locked());
        logSet("@AIContext",     collector.context());
        logSet("@AIIgnore",      collector.ignore());
        logSet("@AIAudit",       collector.audit());
        logSet("@AIDraft",       collector.draft());
        logSet("@AIPrivacy",     collector.privacy());
        logSet("@AICore",        collector.core());
        logSet("@AIPerformance", collector.performance());
    }

    private void logSet(String label, Set<Element> elements) {
        if (elements.isEmpty()) return;
        String names = elements.stream()
            .map(e -> e.getSimpleName().toString())
            .collect(Collectors.joining(", "));
        log.info("{}: {} — {}", label, elements.size(), names);
    }

    // ---------------------------------------------------------------------------------------
    // Test-facing delegates (kept on this class so the existing test surface still compiles).
    // ---------------------------------------------------------------------------------------

    void validateAnnotations(Messager messager, RoundEnvironment roundEnv) {
        AnnotationValidator.validate(messager, roundEnv);
    }

    void checkOrphanedAnnotations(Messager messager, Set<String> active, boolean hasLocked, boolean hasIgnore, boolean hasAudit) {
        OrphanWarner.warnAboutOrphans(messager, log, active, hasLocked, hasIgnore, hasAudit);
    }

    void cleanupGranularDirectory(Path dir, String extension) {
        fileWriter.cleanupGranularDirectory(dir, extension);
    }

    void cleanupGranularDirectory(Path dir, String extension, Set<String> excludeQNames) {
        fileWriter.cleanupGranularDirectory(dir, extension, excludeQNames);
    }

    public static Map<String, Path> buildServiceFileMap(Path root) {
        return ServiceRegistry.buildServiceFileMap(root);
    }

    public static Set<String> resolveActiveServices(Messager messager, Map<String, Path> allServiceFiles) {
        return ServiceRegistry.resolveActiveServices(messager, allServiceFiles);
    }

    public boolean writeFileIfChanged(String path, String content, boolean hasNewRules) {
        return fileWriter.writeFileIfChanged(path, content, hasNewRules);
    }

    String stripLegacyVibeTagsBlock(String before) {
        return fileWriter.stripLegacyVibeTagsBlock(before);
    }

    /**
     * Returns the messager from {@code processingEnv}. Both call sites run after
     * {@link #init(javax.annotation.processing.ProcessingEnvironment)} has populated
     * {@code processingEnv} via {@code super.init(...)}, so the field is non-null here.
     */
    private Messager getSafeMessager() {
        return processingEnv.getMessager();
    }
}
