package se.deversity.vibetags.processor;

import se.deversity.vibetags.annotations.AIContext;
import se.deversity.vibetags.annotations.AIAudit;
import se.deversity.vibetags.annotations.AIDraft;
import se.deversity.vibetags.annotations.AIIgnore;
import se.deversity.vibetags.annotations.AILocked;
import se.deversity.vibetags.annotations.AIPrivacy;
import se.deversity.vibetags.annotations.AICore;
import se.deversity.vibetags.annotations.AIPerformance;
import org.slf4j.Logger;

import javax.annotation.processing.*;
import javax.tools.Diagnostic;
import javax.lang.model.SourceVersion;
import javax.lang.model.element.Element;
import javax.lang.model.element.ElementKind;
import javax.lang.model.element.TypeElement;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.stream.Collectors;

/**
 * The core annotation processor for VibeTags.
 * Scans for VibeTags annotations and generates AI platform-specific configuration files
 * (Cursor, Claude, Gemini, Codex, Copilot, Windsurf) to act as guardrails for AI-assisted development.
 * Also generates {@code llms.txt} (concise map) and {@code llms-full.txt} (full reference)
 * following the llms.txt standard for LLM agent discovery.
 */
@SupportedAnnotationTypes("*")
@SupportedSourceVersion(SourceVersion.RELEASE_11)
@SupportedOptions({"vibetags.root", "vibetags.project", "vibetags.log.path", "vibetags.log.level"})
public class AIGuardrailProcessor extends AbstractProcessor {
    
    /** Public constructor for the service loader. */
    public AIGuardrailProcessor() {}

    
    static final String VERSION = "0.5.6";
    private static final String GITHUB_URL = "https://github.com/PIsberg/vibetags";

    /** Header written into every generated file — no version so bumping the dep never creates spurious diffs. */
    private static final String GENERATED_HEADER = "# Generated by VibeTags | " + GITHUB_URL + "\n";

    private static final String MARKER_START_MD = "<!-- VIBETAGS-START -->";
    private static final String MARKER_END_MD = "<!-- VIBETAGS-END -->";
    private static final String MARKER_START_HASH = "# VIBETAGS-START";
    private static final String MARKER_END_HASH = "# VIBETAGS-END";

    // Ensures we process exactly once per compilation run (the actual generation).
    private boolean processed = false;

    /** SLF4J logger backed by a Logback FileAppender writing to {@code vibetags.log} in the project root. */
    private Logger log = null;

    private boolean anyAnnotationsFound = false;
    private Path root;
    private String projectName;

    private final Set<Element> lockedElements  = new java.util.LinkedHashSet<>();
    private final Set<Element> contextElements = new java.util.LinkedHashSet<>();
    private final Set<Element> ignoreElements  = new java.util.LinkedHashSet<>();
    private final Set<Element> auditElements   = new java.util.LinkedHashSet<>();
    private final Set<Element> draftElements   = new java.util.LinkedHashSet<>();
    private final Set<Element> privacyElements = new java.util.LinkedHashSet<>();
    private final Set<Element> coreElements    = new java.util.LinkedHashSet<>();
    private final Set<Element> performanceElements = new java.util.LinkedHashSet<>();

    // Builders for various AI platforms
    private StringBuilder cursorRules;
    private StringBuilder claudeMd;
    private StringBuilder aiExclude;
    private StringBuilder codexAgents;
    private StringBuilder copilot;
    private StringBuilder llmsTxt;
    private StringBuilder llmsTxtContext;
    private StringBuilder llmsTxtAudit;
    private StringBuilder llmsTxtIgnore;
    private StringBuilder llmsTxtDraft;
    private StringBuilder llmsTxtPrivacy;
    private StringBuilder llmsFullTxt;
    private StringBuilder llmsFullTxtContext;
    private StringBuilder llmsFullTxtAudit;
    private StringBuilder llmsFullTxtIgnore;
    private StringBuilder llmsFullTxtDraft;
    private StringBuilder llmsFullTxtPrivacy;
    private StringBuilder llmsTxtCore;
    private StringBuilder llmsFullTxtCore;
    private StringBuilder llmsTxtPerformance;
    private StringBuilder llmsFullTxtPerformance;
    private StringBuilder cursorIgnore;
    private StringBuilder qwenMd;
    private StringBuilder aiderConventions;
    private StringBuilder aiderIgnore;
    private StringBuilder cursorIgnoreFile;
    private StringBuilder claudeIgnoreFile;
    private StringBuilder copilotIgnoreFile;
    private StringBuilder qwenIgnoreFile;
    private final Map<Element, StringBuilder> elementRules = new java.util.LinkedHashMap<>();

    @Override
    public synchronized void init(ProcessingEnvironment processingEnv) {
        super.init(processingEnv);
        Map<String, String> options = processingEnv.getOptions();
        
        String rootOverride = options.get("vibetags.root");
        this.root = Paths.get((rootOverride != null && !rootOverride.isBlank())
                ? rootOverride
                : Paths.get("").toAbsolutePath().toString()).toAbsolutePath().normalize();
        
        Messager messager = getSafeMessager();
        String rootMsg = "VibeTags: Root resolved: " + this.root;
        String dirMsg  = "VibeTags: user.dir:      " + System.getProperty("user.dir");
        messager.printMessage(Diagnostic.Kind.NOTE, rootMsg);
        messager.printMessage(Diagnostic.Kind.NOTE, dirMsg);
        
        this.projectName = options.getOrDefault("vibetags.project", "This Project");
        
        String logPath = options.get("vibetags.log.path");
        String logLevel = options.get("vibetags.log.level");
        log = VibeTagsLogger.forRoot(this.root, logPath, logLevel);

        // Reset state for potential reuse (especially in tests)
        this.processed = false;
        this.lockedElements.clear();
        this.contextElements.clear();
        this.ignoreElements.clear();
        this.auditElements.clear();
        this.draftElements.clear();
        this.privacyElements.clear();
        this.coreElements.clear();
        this.performanceElements.clear();
        this.elementRules.clear();
        this.anyAnnotationsFound = false;

        initBuilders();
    }

    private void initBuilders() {
        cursorRules = new StringBuilder("# AUTO-GENERATED AI RULES\n" + GENERATED_HEADER + "# Do not edit manually.\n\n## LOCKED FILES (DO NOT EDIT)\n");
        claudeMd = new StringBuilder("<!-- " + GENERATED_HEADER.trim() + " -->\n<project_guardrails>\n  <locked_files>\n");
        aiExclude = new StringBuilder("# AUTO-GENERATED BY VIBETAGS\n" + GENERATED_HEADER + "# The following files are strictly excluded from AI context.\n");
        codexAgents = new StringBuilder("# AUTO-GENERATED AI RULES\n" + GENERATED_HEADER + "# Do not edit manually.\n\n## LOCKED FILES (DO NOT EDIT)\n");
        copilot = new StringBuilder("# GitHub Copilot Instructions\n" + GENERATED_HEADER + "# AUTO-GENERATED BY VIBETAGS. Do not edit manually.\n\n## Locked Files — DO NOT MODIFY\nDo not suggest changes to the following files:\n\n");
        qwenMd = new StringBuilder("# PROJECT CONTEXT\n" + GENERATED_HEADER + "# AUTO-GENERATED BY VIBETAGS\n\n## LOCKED FILES (DO NOT EDIT)\n");

        llmsTxt = new StringBuilder("# " + projectName + "\n\n" +
            "> AI guardrail rules generated from source annotations by VibeTags.\n\n" +
            "AI tools reading this file should respect the guardrails defined below. " +
            "These rules were extracted from Java source annotations at compile time " +
            "and apply to all AI assistants including Windsurf Cascade, Cursor, Claude, " +
            "GitHub Copilot, and Gemini.\n\n" +
            "## Locked Files\n");
        llmsTxtContext  = new StringBuilder("\n## Contextual Rules\n");
        llmsTxtAudit    = new StringBuilder("\n## Security Audit Requirements\n");
        llmsTxtIgnore   = new StringBuilder("\n## Ignored Elements\n");
        llmsTxtDraft    = new StringBuilder("\n## Implementation Tasks\n");
        llmsTxtPrivacy  = new StringBuilder("\n## PII / Privacy Guardrails\n");
        llmsTxtCore     = new StringBuilder("\n## 🧠 Core Functionality\n");
        llmsTxtPerformance = new StringBuilder("\n## ⚡ Performance Constraints\n");

        llmsFullTxt = new StringBuilder("# " + projectName + " — AI Guardrail Rules\n" +
            "> Complete AI guardrail configuration generated from source annotations by VibeTags.\n\n" +
            "This document contains the full set of AI guardrail rules for this project. " +
            "AI tools with large context windows (such as Windsurf Cascade, Claude 4.6, or Gemini 1.5 Pro) " +
            "may load this file directly instead of fetching individual documentation pages.\n\n" +
            "## Locked Files (Do Not Edit)\n" +
            "The following files are locked. AI tools MUST NOT propose modifications to them.\n\n");
        llmsFullTxtContext  = new StringBuilder("\n## Contextual Rules\n" +
            "These files have specific context and focus areas for AI assistance.\n\n");
        llmsFullTxtAudit    = new StringBuilder("\n## Mandatory Security Audit Requirements\n" +
            "When writing or modifying the following files, perform a security audit for the listed vulnerabilities " +
            "before displaying any code to the user.\n\n");
        llmsFullTxtIgnore   = new StringBuilder("\n## Ignored Elements\n" +
            "The following elements must be completely excluded from AI context. Treat them as non-existent.\n\n");
        llmsFullTxtDraft    = new StringBuilder("\n## Implementation Tasks\n" +
            "The following elements are in draft mode and need implementation.\n\n");
        llmsFullTxtPrivacy  = new StringBuilder("\n## PII / Privacy Guardrails\n" +
            "Never include runtime values of the following elements in logs, console output, " +
            "external API calls, test fixtures, or mock data.\n\n");
        llmsFullTxtCore     = new StringBuilder("\n## 🧠 Core Functionality\n" +
            "The following elements are well-tested core functionality. Make changes with extreme caution.\n\n");
        llmsFullTxtPerformance = new StringBuilder("\n## ⚡ Performance Constraints\n" +
            "The following elements are on a hot-path and have strict time/space complexity constraints.\n\n");

        cursorIgnoreFile = new StringBuilder("# AUTO-GENERATED BY VIBETAGS\n" + GENERATED_HEADER + "# Cursor-specific exclusion list.\n");
        claudeIgnoreFile = new StringBuilder("# AUTO-GENERATED BY VIBETAGS\n" + GENERATED_HEADER + "# Claude-specific exclusion list.\n");
        copilotIgnoreFile = new StringBuilder("# AUTO-GENERATED BY VIBETAGS\n" + GENERATED_HEADER + "# Copilot-specific exclusion list.\n");
        qwenIgnoreFile = new StringBuilder("# AUTO-GENERATED BY VIBETAGS\n" + GENERATED_HEADER + "# Qwen-specific exclusion list.\n");

        aiderConventions = new StringBuilder("# " + projectName + " CONVENTIONS\n" + GENERATED_HEADER + "# AUTO-GENERATED BY VIBETAGS\n\nThis file contains project-specific coding conventions and AI guardrails extracted from source annotations.\n\n");
        aiderIgnore = new StringBuilder("# AUTO-GENERATED BY VIBETAGS\n" + GENERATED_HEADER + "# Aider-specific exclusion list.\n");

        cursorIgnore = new StringBuilder("\n## \uD83D\uDEAB IGNORED ELEMENTS (EXCLUDE FROM CONTEXT)\nDo not reference, suggest changes to, or include the following in completions or answers.\n\n");
    }

    @Override
    public boolean process(Set<? extends TypeElement> annotations, RoundEnvironment roundEnv) {
        if (processed || roundEnv.processingOver()) {
            if (roundEnv.processingOver() && !processed) {
                generateFiles();
                processed = true;
            }
            return false;
        }

        // Aggregate elements from the current round
        lockedElements.addAll(roundEnv.getElementsAnnotatedWith(AILocked.class));
        contextElements.addAll(roundEnv.getElementsAnnotatedWith(AIContext.class));
        ignoreElements.addAll(roundEnv.getElementsAnnotatedWith(AIIgnore.class));
        auditElements.addAll(roundEnv.getElementsAnnotatedWith(AIAudit.class));
        draftElements.addAll(roundEnv.getElementsAnnotatedWith(AIDraft.class));
        privacyElements.addAll(roundEnv.getElementsAnnotatedWith(AIPrivacy.class));
        coreElements.addAll(roundEnv.getElementsAnnotatedWith(AICore.class));
        performanceElements.addAll(roundEnv.getElementsAnnotatedWith(AIPerformance.class));

        if (!lockedElements.isEmpty() || !contextElements.isEmpty() || !ignoreElements.isEmpty() ||
            !auditElements.isEmpty() || !draftElements.isEmpty() || !privacyElements.isEmpty() ||
            !coreElements.isEmpty() || !performanceElements.isEmpty()) {
            anyAnnotationsFound = true;
        }

        // Validation in each round for early feedback
        validateAnnotations(processingEnv.getMessager(), roundEnv);

        return false; // allow others to see the annotations
    }

    private void generateFiles() {
        if (log != null) {
            log.info("VibeTags v{} | {}", VERSION, GITHUB_URL);
            log.info("Root: {}", root.toAbsolutePath());
        }

        // Collect element names for logging
        List<String> lockedNames  = lockedElements.stream().map(e -> e.getSimpleName().toString()).collect(Collectors.toList());
        List<String> contextNames = contextElements.stream().map(e -> e.getSimpleName().toString()).collect(Collectors.toList());
        List<String> ignoreNames  = ignoreElements.stream().map(e -> e.getSimpleName().toString()).collect(Collectors.toList());
        List<String> auditNames   = auditElements.stream().map(e -> e.getSimpleName().toString()).collect(Collectors.toList());
        List<String> draftNames   = draftElements.stream().map(e -> e.getSimpleName().toString()).collect(Collectors.toList());
        List<String> privacyNames = privacyElements.stream().map(e -> e.getSimpleName().toString()).collect(Collectors.toList());
        List<String> coreNames    = coreElements.stream().map(e -> e.getSimpleName().toString()).collect(Collectors.toList());
        List<String> performanceNames = performanceElements.stream().map(e -> e.getSimpleName().toString()).collect(Collectors.toList());

        // Signal directories for granular rules
        Map<String, Path> serviceFiles = buildServiceFileMap(root);
        Set<String> activeServices = resolveActiveServices(processingEnv.getMessager(), serviceFiles);

        // Cache active-service flags so per-element loops can skip building strings
        // for platforms that won't have a file written. Per-element appends dominate
        // generateFiles cost at high N, so this is the main load-test lever.
        boolean cursorActive   = activeServices.contains("cursor");
        boolean claudeActive   = activeServices.contains("claude");
        boolean aiexcludeActive = activeServices.contains("aiexclude");
        boolean codexActive    = activeServices.contains("codex");
        boolean copilotActive  = activeServices.contains("copilot");
        boolean qwenActive     = activeServices.contains("qwen");
        boolean geminiActive   = activeServices.contains("gemini");
        boolean llmsActive     = activeServices.contains("llms");
        boolean llmsFullActive = activeServices.contains("llms_full");
        boolean aiderConvActive   = activeServices.contains("aider_conventions");
        boolean aiderIgnoreActive = activeServices.contains("aider_ignore");
        boolean cursorIgnoreFileActive  = activeServices.contains("cursor_ignore");
        boolean claudeIgnoreFileActive  = activeServices.contains("claude_ignore");
        boolean copilotIgnoreFileActive = activeServices.contains("copilot_ignore");
        boolean qwenIgnoreFileActive    = activeServices.contains("qwen_ignore");
        boolean granularActive = activeServices.contains("cursor_granular")
            || activeServices.contains("trae_granular") || activeServices.contains("roo_granular");

        // Per-platform section builders for Gemini (assembled in the finalize section below)
        StringBuilder geminiLocked = new StringBuilder();
        StringBuilder geminiContext = new StringBuilder();

        // Process @AILocked
        for (Element element : lockedElements) {
            AILocked locked = element.getAnnotation(AILocked.class);
            String className = elementPath(element);
            String reason = locked.reason();

            if (cursorActive) cursorRules.append("* `").append(className).append("` - Reason: ").append(reason).append("\n");
            if (claudeActive) claudeMd.append("    <file path=\"").append(className).append("\">\n")
                    .append("      <reason>").append(reason).append("</reason>\n")
                    .append("    </file>\n");
            if (aiexcludeActive) aiExclude.append("**/").append(element.getSimpleName()).append(".java\n");
            if (codexActive) codexAgents.append("- **").append(className).append("**: ").append(reason).append("\n");
            if (copilotActive) copilot.append("- `").append(className).append("` - ").append(reason).append("\n");
            if (qwenActive) qwenMd.append("* `").append(className).append("` - ").append(reason).append("\n");
            if (geminiActive) geminiLocked.append("- `").append(className).append("`: ").append(reason).append("\n");

            if (llmsActive) llmsTxt.append("- [").append(elementDisplayName(element)).append("](").append(className).append("): ").append(reason).append("\n");
            if (llmsFullActive) llmsFullTxt.append("### ").append(className).append("\n")
                       .append("- **Reason**: ").append(reason).append("\n\n");

            if (aiderConvActive) aiderConventions.append("#### LOCKED: ").append(className).append("\n")
                            .append("- **Status**: Locked (Do Not Edit)\n")
                            .append("- **Reason**: ").append(reason).append("\n\n");
            if (granularActive) appendToGranular(element, "Locked Status", "- **Reason**: " + reason);
        }

        claudeMd.append("  </locked_files>\n  <contextual_instructions>\n");
        cursorRules.append("\n## CONTEXTUAL RULES\n");
        codexAgents.append("\n## CONTEXTUAL RULES\n");
        copilot.append("\n## Contextual Guidelines\n");
        qwenMd.append("\n## CONTEXTUAL RULES\n");

        // Process @AIContext
        for (Element element : contextElements) {
            AIContext context = element.getAnnotation(AIContext.class);
            String className = elementPath(element);

            if (cursorActive) cursorRules.append("* `").append(className).append("`\n  * Focus: ").append(context.focus())
                       .append("\n  * Avoid: ").append(context.avoids()).append("\n");
            if (claudeActive) claudeMd.append("    <file path=\"").append(className).append("\">\n")
                    .append("      <focus>").append(context.focus()).append("</focus>\n")
                    .append("      <avoids>").append(context.avoids()).append("</avoids>\n")
                    .append("    </file>\n");
            if (codexActive) codexAgents.append("- `").append(className).append("`: Focus on ").append(context.focus())
                       .append(". Avoid ").append(context.avoids()).append(".\n");
            if (copilotActive) copilot.append("- `").append(className).append("` \n")
                   .append("  - Focus: ").append(context.focus()).append("\n")
                   .append("  - Avoid: ").append(context.avoids()).append("\n");
            if (qwenActive) qwenMd.append("* `").append(className).append("` \n")
                  .append("  * Focus: ").append(context.focus()).append("\n")
                  .append("  * Avoid: ").append(context.avoids()).append("\n");

            if (llmsActive) llmsTxtContext.append("- [").append(elementDisplayName(element)).append("](").append(className)
                          .append("): Focus - ").append(context.focus())
                          .append(". Avoid - ").append(context.avoids()).append("\n");
            if (llmsFullActive) llmsFullTxtContext.append("### ").append(className).append("\n")
                              .append("- **Focus**: ").append(context.focus()).append("\n")
                              .append("- **Avoid**: ").append(context.avoids()).append("\n\n");

            if (aiderConvActive) aiderConventions.append("#### CONTEXT: ").append(className).append("\n")
                            .append("- **Focus**: ").append(context.focus()).append("\n")
                            .append("- **Avoid**: ").append(context.avoids()).append("\n\n");
            if (granularActive) appendToGranular(element, "Context & Focus", "- **Focus**: " + context.focus() + "\n- **Avoid**: " + context.avoids());
            if (geminiActive) geminiContext.append("- `").append(className).append("`: Focus - ").append(context.focus())
                         .append(". Avoid - ").append(context.avoids()).append("\n");
        }
        claudeMd.append("  </contextual_instructions>\n");

        // Builders for ignored elements
        StringBuilder claudeIgnore = new StringBuilder("  <ignored_elements>\n");
        StringBuilder codexIgnore = new StringBuilder("\n## IGNORED ELEMENTS\nThe following elements must be completely excluded from AI context and completions:\n\n");
        StringBuilder geminiIgnore = new StringBuilder("## IGNORED ELEMENTS\nThe following elements must be completely excluded from AI context and completions:\n\n");
        StringBuilder copilotIgnore = new StringBuilder("\n## Ignored Elements\nDo not reference or suggest changes to the following:\n\n");
        StringBuilder qwenIgnore = new StringBuilder("\n## IGNORED ELEMENTS\nThe following elements must be completely excluded from AI's memory and context:\n\n");

        // Process @AIIgnore
        for (Element element : ignoreElements) {
            String className = elementPath(element);
            if (cursorActive) cursorIgnore.append("* `").append(className).append("` \n");
            if (claudeActive) claudeIgnore.append("    <file path=\"").append(className).append("\"/>\n");
            if (aiexcludeActive) aiExclude.append("**/").append(element.getSimpleName()).append(".java\n");
            if (codexActive) codexIgnore.append("- `").append(className).append("` \n");
            if (geminiActive) geminiIgnore.append("- `").append(className).append("` \n");
            if (copilotActive) copilotIgnore.append("- `").append(className).append("` \n");

            String globPattern = "**/"+ element.getSimpleName() + ".java\n";
            if (cursorIgnoreFileActive)  cursorIgnoreFile.append(globPattern);
            if (claudeIgnoreFileActive)  claudeIgnoreFile.append(globPattern);
            if (copilotIgnoreFileActive) copilotIgnoreFile.append(globPattern);
            if (qwenIgnoreFileActive)    qwenIgnoreFile.append(globPattern);
            if (qwenActive) qwenIgnore.append("* `").append(className).append("` \n");

            if (llmsActive) llmsTxtIgnore.append("- [").append(elementDisplayName(element)).append("](").append(className)
                         .append("): excluded from AI context\n");
            if (llmsFullActive) llmsFullTxtIgnore.append("### ").append(className).append("\n")
                             .append("- Excluded from AI context entirely - treat as non-existent\n\n");

            if (aiderIgnoreActive) aiderIgnore.append(globPattern);
            if (aiderConvActive) aiderConventions.append("#### IGNORE: ").append(className).append("\n")
                            .append("- **Instruction**: This element is strictly excluded from AI context. Do not reference it.\n\n");
            if (granularActive) appendToGranular(element, "Exclusion Rule", "This element is strictly excluded from AI context. Do not reference it.");
        }

        // Builders for audit sections
        StringBuilder cursorAudit = new StringBuilder("\n## 🛡️ MANDATORY SECURITY AUDITS\nWhen proposing edits or writing code for the following files, you MUST perform a security review before outputting the final code. You must explicitly state in your response that you have audited the changes for the required vulnerabilities.\n\n");
        StringBuilder claudeAudit = new StringBuilder("\n  <audit_requirements>\n");
        // geminiMd assembled lazily from geminiLocked/geminiContext/geminiAudit in the finalize section
        StringBuilder geminiMd = new StringBuilder("# GEMINI AI INSTRUCTIONS\n" + GENERATED_HEADER + "\n");
        StringBuilder geminiAudit = new StringBuilder();
        StringBuilder codexAudit = new StringBuilder("\n## 🛡️ MANDATORY SECURITY AUDITS\nWhen proposing edits or writing code for the following files, you MUST perform a security review before outputting the final code. You must explicitly state in your response that you have audited the changes for the required vulnerabilities.\n\n");
        StringBuilder copilotAudit = new StringBuilder("\n## Security Audit Requirements\nBefore suggesting changes to the following files, audit for the listed vulnerabilities:\n\n");
        StringBuilder qwenAudit = new StringBuilder("\n## 🛡️ MANDATORY SECURITY AUDITS\nWhen proposing edits or writing code for the following files, you MUST perform a security review. Explicitly state that you have audited the changes for the listed vulnerabilities.\n\n");

        // Process @AIAudit
        for (Element element : auditElements) {
            AIAudit audit = element.getAnnotation(AIAudit.class);
            if (audit == null) continue;
            String className = elementPath(element);
            String[] checkFor = audit.checkFor();
            if (checkFor.length == 0) continue;
            String checkForJoined = String.join(", ", checkFor);

            if (cursorActive) {
                cursorAudit.append("* `").append(className).append("` \n");
                cursorAudit.append("  - Required Checks: ").append(checkForJoined).append("\n");
            }
            if (claudeActive) {
                claudeAudit.append("    <file path=\"").append(className).append("\">\n");
                for (String vulnerability : checkFor) {
                    claudeAudit.append("      <vulnerability_check>").append(vulnerability).append("</vulnerability_check>\n");
                }
                claudeAudit.append("    </file>\n");
            }
            if (geminiActive) {
                geminiAudit.append("File: `").append(className).append("` ")
                           .append("\nCritical Vulnerabilities to Prevent: ");
                for (String vulnerability : checkFor) {
                    geminiAudit.append("\n- ").append(vulnerability);
                }
                geminiAudit.append("\n\n");
            }
            if (codexActive) codexAudit.append("* `").append(className).append("` \n")
                      .append("  - Required Checks: ").append(checkForJoined).append("\n");
            if (copilotActive) copilotAudit.append("- `").append(className).append("` \n")
                        .append("  - Required Checks: ").append(checkForJoined).append("\n");
            if (qwenActive) qwenAudit.append("* `").append(className).append("` \n")
                     .append("  - Required Checks: ").append(checkForJoined).append("\n");

            if (llmsActive) llmsTxtAudit.append("- [").append(elementDisplayName(element)).append("](").append(className)
                        .append("): check for ").append(checkForJoined).append("\n");
            if (llmsFullActive) llmsFullTxtAudit.append("### ").append(className).append("\n")
                            .append("- **Required Checks**: ").append(checkForJoined).append("\n\n");

            if (aiderConvActive) aiderConventions.append("#### SECURITY AUDIT: ").append(className).append("\n")
                            .append("- **Required Checks**: ").append(checkForJoined).append("\n\n");
            if (granularActive) appendToGranular(element, "Security Audit Requirements", "When modifying this element, audit for:\n- " + String.join("\n- ", checkFor));
        }

        // Builders for draft elements
        StringBuilder cursorDraft = new StringBuilder("\n## 📝 IMPLEMENTATION TASKS (TODO)\n" +
            "The following elements are currently in DRAFT mode. Follow the instructions to implement them:\n\n");
        StringBuilder claudeDraft = new StringBuilder("  <implementation_tasks>\n");
        StringBuilder codexDraft = new StringBuilder("\n## IMPLEMENTATION TASKS\nThe following elements are drafts that need implementation:\n\n");
        StringBuilder geminiDraft = new StringBuilder("## IMPLEMENTATION TASKS\nThe following elements are drafts that need implementation:\n\n");
        StringBuilder copilotDraft = new StringBuilder("\n## Implementation Tasks\nFollow these instructions to implement the drafts:\n\n");
        StringBuilder qwenDraft = new StringBuilder("\n## IMPLEMENTATION TASKS\nThe following elements are drafts that need implementation:\n\n");

        // Process @AIDraft
        for (Element element : draftElements) {
            AIDraft draft = element.getAnnotation(AIDraft.class);
            if (draft == null) continue;
            String className = elementPath(element);
            String instructions = draft.instructions();

            if (cursorActive) cursorDraft.append("* `").append(className).append("` - Task: ").append(instructions).append("\n");
            if (claudeActive) claudeDraft.append("    <task path=\"").append(className).append("\">\n")
                       .append("      <instructions>").append(instructions).append("</instructions>\n")
                       .append("    </task>\n");
            if (codexActive) codexDraft.append("- **").append(className).append("**: ").append(instructions).append("\n");
            if (geminiActive) geminiDraft.append("- `").append(className).append("`: ").append(instructions).append("\n");
            if (copilotActive) copilotDraft.append("- `").append(className).append("`: ").append(instructions).append("\n");
            if (qwenActive) qwenDraft.append("* `").append(className).append("` - Task: ").append(instructions).append("\n");

            if (llmsActive) llmsTxtDraft.append("- [").append(elementDisplayName(element)).append("](").append(className)
                        .append("): ").append(instructions).append("\n");
            if (llmsFullActive) llmsFullTxtDraft.append("### ").append(className).append("\n")
                            .append("- **Instructions**: ").append(instructions).append("\n\n");

            if (aiderConvActive) aiderConventions.append("#### DRAFT/TODO: ").append(className).append("\n")
                            .append("- **Instruction**: ").append(instructions).append("\n\n");
            if (granularActive) appendToGranular(element, "Implementation Tasks", "- **Instruction**: " + instructions);
        }

        // Builders for privacy elements
        StringBuilder cursorPrivacy = new StringBuilder("\n## \uD83D\uDD12 PII / PRIVACY GUARDRAILS\n" +
            "The following elements handle Personally Identifiable Information (PII).\n" +
            "NEVER include their runtime values in logs, console output, external API calls,\n" +
            "test fixtures, mock data, or code suggestions.\n\n");
        StringBuilder claudePrivacy = new StringBuilder("  <pii_guardrails>\n");
        StringBuilder codexPrivacy = new StringBuilder("\n## \uD83D\uDD12 PII / PRIVACY GUARDRAILS\n" +
            "The following elements handle PII. Never include their runtime values in logs,\n" +
            "console output, external API calls, test fixtures, or mock data.\n\n");
        StringBuilder geminiPrivacy = new StringBuilder("## PII / PRIVACY GUARDRAILS\n" +
            "The following elements handle Personally Identifiable Information (PII).\n" +
            "Never include their runtime values in logs, console output, external API calls,\n" +
            "test fixtures, mock data, or code suggestions.\n\n");
        StringBuilder copilotPrivacy = new StringBuilder("\n## PII / Privacy Guardrails\n" +
            "Never log, expose, or suggest code that outputs the runtime values of these elements:\n\n");
        StringBuilder qwenPrivacy = new StringBuilder("\n## \uD83D\uDD12 PII / PRIVACY GUARDRAILS\n" +
            "The following elements handle PII. Never include their runtime values in logs,\n" +
            "console output, external API calls, test fixtures, or mock data.\n\n");

        // Process @AIPrivacy
        for (Element element : privacyElements) {
            AIPrivacy privacy = element.getAnnotation(AIPrivacy.class);
            if (privacy == null) continue;
            String className = elementPath(element);
            String reason = privacy.reason();

            if (cursorActive) cursorPrivacy.append("* `").append(className).append("` - ").append(reason).append("\n");
            if (claudeActive) claudePrivacy.append("    <element path=\"").append(className).append("\">\n")
                         .append("      <reason>").append(reason).append("</reason>\n")
                         .append("    </element>\n");
            if (codexActive) codexPrivacy.append("- `").append(className).append("`: ").append(reason).append("\n");
            if (geminiActive) geminiPrivacy.append("- `").append(className).append("`: ").append(reason).append("\n");
            if (copilotActive) copilotPrivacy.append("- `").append(className).append("` - ").append(reason).append("\n");
            if (qwenActive) qwenPrivacy.append("* `").append(className).append("` - ").append(reason).append("\n");

            if (llmsActive) llmsTxtPrivacy.append("- [").append(elementDisplayName(element)).append("](").append(className)
                          .append("): ").append(reason).append("\n");
            if (llmsFullActive) llmsFullTxtPrivacy.append("### ").append(className).append("\n")
                              .append("- **Reason**: ").append(reason).append("\n\n");

            if (aiderConvActive) aiderConventions.append("#### PRIVACY/PII: ").append(className).append("\n")
                            .append("- **Safety Rule**: Never log or expose runtime values of this element.\n")
                            .append("- **Reason**: ").append(reason).append("\n\n");
            if (granularActive) appendToGranular(element, "PII / Privacy Guardrails", "- **Rule**: Never log or expose runtime values of this element.\n- **Reason**: " + reason);
        }

        // Platform-specific builders for @AICore
        StringBuilder cursorCore = new StringBuilder("\n## \uD83E\uDDE0 CORE FUNCTIONALITY (CHANGE WITH EXTREME CAUTION)\n" +
            "The following elements are well-tested core components. Make changes with extreme caution.\n\n");
        StringBuilder claudeCore = new StringBuilder("  <core_elements>\n");
        StringBuilder codexCore  = new StringBuilder("\n## \uD83E\uDDE0 CORE FUNCTIONALITY\nThe following elements are well-tested core components. Make changes with extreme caution.\n\n");
        StringBuilder copilotCore = new StringBuilder("\n## Core Functionality (Extreme Caution)\nThe following elements are well-tested core components — change with extreme caution:\n\n");
        StringBuilder qwenCore   = new StringBuilder("\n## \uD83E\uDDE0 CORE FUNCTIONALITY\nThe following elements are well-tested core components. Make changes with extreme caution.\n\n");
        StringBuilder geminiCore = new StringBuilder();

        // Platform-specific builders for @AIPerformance
        StringBuilder cursorPerf = new StringBuilder("\n## \u26A1 PERFORMANCE CONSTRAINTS (HOT PATH)\n" +
            "The following elements are on a hot path. Never introduce O(n\u00B2) complexity. Always reason about time/space before proposing changes.\n\n");
        StringBuilder claudePerf = new StringBuilder("  <performance_constraints>\n");
        StringBuilder codexPerf  = new StringBuilder("\n## \u26A1 PERFORMANCE CONSTRAINTS\nHot-path elements — never introduce O(n\u00B2) or worse. Always reason about complexity before proposing changes.\n\n");
        StringBuilder copilotPerf = new StringBuilder("\n## Performance Constraints\nThe following elements are on a hot path — always reason about time and space complexity:\n\n");
        StringBuilder qwenPerf   = new StringBuilder("\n## \u26A1 PERFORMANCE CONSTRAINTS\nHot-path elements — O(n\u00B2) complexity is forbidden. Reason about complexity before proposing changes.\n\n");
        StringBuilder geminiPerf = new StringBuilder();

        // Process @AICore
        for (Element element : coreElements) {
            AICore core = element.getAnnotation(AICore.class);
            if (core == null) continue;
            String className = elementPath(element);
            String sensitivity = core.sensitivity();
            String note = core.note();

            if (cursorActive) cursorCore.append("* `").append(className).append("` - Sensitivity: ").append(sensitivity)
                      .append(". Note: ").append(note).append("\n");
            if (claudeActive) claudeCore.append("    <element path=\"").append(className).append("\">\n")
                      .append("      <sensitivity>").append(sensitivity).append("</sensitivity>\n")
                      .append("      <note>").append(note).append("</note>\n")
                      .append("    </element>\n");
            if (codexActive) codexCore.append("- **").append(className).append("** (sensitivity: ").append(sensitivity)
                     .append("): ").append(note).append("\n");
            if (copilotActive) copilotCore.append("- `").append(className).append("` — sensitivity: ").append(sensitivity)
                       .append(". ").append(note).append("\n");
            if (qwenActive) qwenCore.append("* `").append(className).append("` - Sensitivity: ").append(sensitivity)
                    .append(". Note: ").append(note).append("\n");
            if (geminiActive) geminiCore.append("- `").append(className).append("`: Sensitivity: ").append(sensitivity)
                      .append(". Note: ").append(note).append("\n");

            if (llmsActive) llmsTxtCore.append("- [").append(elementDisplayName(element)).append("](").append(className)
                       .append("): Sensitivity: ").append(sensitivity).append(". Note: ").append(note).append("\n");
            if (llmsFullActive) llmsFullTxtCore.append("### ").append(className).append("\n")
                           .append("- **Sensitivity**: ").append(sensitivity).append("\n")
                           .append("- **Note**: ").append(note).append("\n\n");

            if (aiderConvActive) aiderConventions.append("#### CORE FUNCTIONALITY: ").append(className).append("\n")
                            .append("- **Sensitivity**: ").append(sensitivity).append("\n")
                            .append("- **Note**: ").append(note).append("\n\n");
            if (granularActive) appendToGranular(element, "Core Functionality", "- **Sensitivity**: " + sensitivity + "\n- **Note**: " + note);
        }

        // Process @AIPerformance
        for (Element element : performanceElements) {
            AIPerformance perf = element.getAnnotation(AIPerformance.class);
            if (perf == null) continue;
            String className = elementPath(element);
            String constraint = perf.constraint();

            if (cursorActive) cursorPerf.append("* `").append(className).append("` - ").append(constraint).append("\n");
            if (claudeActive) claudePerf.append("    <element path=\"").append(className).append("\">\n")
                      .append("      <constraint>").append(constraint).append("</constraint>\n")
                      .append("    </element>\n");
            if (codexActive) codexPerf.append("- **").append(className).append("**: ").append(constraint).append("\n");
            if (copilotActive) copilotPerf.append("- `").append(className).append("`: ").append(constraint).append("\n");
            if (qwenActive) qwenPerf.append("* `").append(className).append("` - ").append(constraint).append("\n");
            if (geminiActive) geminiPerf.append("- `").append(className).append("`: ").append(constraint).append("\n");

            if (llmsActive) llmsTxtPerformance.append("- [").append(elementDisplayName(element)).append("](").append(className)
                              .append("): ").append(constraint).append("\n");
            if (llmsFullActive) llmsFullTxtPerformance.append("### ").append(className).append("\n")
                                  .append("- **Constraint**: ").append(constraint).append("\n\n");

            if (aiderConvActive) aiderConventions.append("#### PERFORMANCE CONSTRAINTS: ").append(className).append("\n")
                            .append("- **Rule**: Optimal complexity required. O(n^2) is forbidden on hot paths.\n")
                            .append("- **Constraint**: ").append(constraint).append("\n\n");
            if (granularActive) appendToGranular(element, "Performance Constraints", "- **Rule**: Optimal complexity required. O(n^2) is forbidden on hot paths.\n- **Constraint**: " + constraint);
        }

        // Assemble Gemini content from per-annotation section builders
        if (!lockedElements.isEmpty()) {
            geminiMd.append("\n## LOCKED FILES (DO NOT MODIFY)\n")
                    .append("Do not suggest modifications to the following files:\n\n")
                    .append(geminiLocked);
        }
        if (!contextElements.isEmpty()) {
            geminiMd.append("\n## CONTEXTUAL RULES\n")
                    .append("Apply the following context when assisting with these files:\n\n")
                    .append(geminiContext);
        }
        if (!auditElements.isEmpty()) {
            geminiMd.append("\n## CONTINUOUS AUDIT REQUIREMENTS\n")
                    .append("You are acting as a Senior Staff Engineer. Whenever you write code for the files listed below, you must ensure your completions and chat responses strictly prevent the listed vulnerabilities:\n\n")
                    .append(geminiAudit);
        }

        // Finalize sections
        if (!auditElements.isEmpty()) {
            cursorRules.append(cursorAudit);
            claudeAudit.append("  </audit_requirements>\n");
            claudeMd.append(claudeAudit);
            claudeMd.append("\n<rule>\n  If you are asked to modify any file listed in <audit_requirements>, you must first silently analyze your proposed code for the listed <vulnerability_check> items. If your code introduces these vulnerabilities, you must rewrite it before displaying it to the user.\n</rule>\n");
            codexAgents.append(codexAudit);
            copilot.append(copilotAudit);
            qwenMd.append(qwenAudit);
        }

        if (!ignoreElements.isEmpty()) {
            cursorRules.append(cursorIgnore);
            claudeIgnore.append("  </ignored_elements>\n");
            claudeMd.append(claudeIgnore);
            claudeMd.append("\n<rule>Never reference or suggest changes to any element listed in <ignored_elements>. Treat these as if they do not exist.</rule>\n");
            codexAgents.append(codexIgnore);
            geminiMd.append(geminiIgnore);
            copilot.append(copilotIgnore);
            qwenMd.append(qwenIgnore);
        }

        if (!draftElements.isEmpty()) {
            cursorRules.append(cursorDraft);
            claudeDraft.append("  </implementation_tasks>\n");
            claudeMd.append(claudeDraft);
            codexAgents.append(codexDraft);
            geminiMd.append(geminiDraft);
            copilot.append(copilotDraft);
            qwenMd.append(qwenDraft);
        }

        if (!privacyElements.isEmpty()) {
            cursorRules.append(cursorPrivacy);
            claudePrivacy.append("  </pii_guardrails>\n");
            claudeMd.append(claudePrivacy);
            claudeMd.append("\n<rule>\n  Never include runtime values of elements listed in <pii_guardrails> in logs, console output, external API calls, test fixtures, mock data, or code suggestions. Treat their values as strictly confidential.\n</rule>\n");
            codexAgents.append(codexPrivacy);
            geminiMd.append(geminiPrivacy);
            copilot.append(copilotPrivacy);
            qwenMd.append(qwenPrivacy);
        }

        if (!coreElements.isEmpty()) {
            cursorRules.append(cursorCore);
            claudeCore.append("  </core_elements>\n");
            claudeMd.append(claudeCore);
            claudeMd.append("\n<rule>Elements listed in <core_elements> are well-tested core components. Make changes with extreme caution and verify comprehensive test coverage before proposing modifications.</rule>\n");
            codexAgents.append(codexCore);
            copilot.append(copilotCore);
            qwenMd.append(qwenCore);
            geminiMd.append("\n## CORE FUNCTIONALITY (EXTREME CAUTION)\n")
                    .append("The following elements are well-tested core components. Make changes with extreme caution:\n\n")
                    .append(geminiCore);
        }

        if (!performanceElements.isEmpty()) {
            cursorRules.append(cursorPerf);
            claudePerf.append("  </performance_constraints>\n");
            claudeMd.append(claudePerf);
            claudeMd.append("\n<rule>Elements listed in <performance_constraints> are on a hot path. Never introduce O(n\u00B2) or worse complexity. Always reason about time and space complexity before suggesting changes.</rule>\n");
            codexAgents.append(codexPerf);
            copilot.append(copilotPerf);
            qwenMd.append(qwenPerf);
            geminiMd.append("\n## PERFORMANCE CONSTRAINTS (HOT PATH)\n")
                    .append("Never introduce O(n\u00B2) complexity into these elements. Always reason about complexity before proposing changes:\n\n")
                    .append(geminiPerf);
        }

        claudeMd.append("</project_guardrails>\n");
        claudeMd.append("\n<rule>Never propose edits to files listed in <locked_files>.</rule>\n");

        // Assemble llms.txt and llms-full.txt
        llmsTxt.append(llmsTxtContext);
        llmsFullTxt.append(llmsFullTxtContext);
        if (!auditElements.isEmpty()) { llmsTxt.append(llmsTxtAudit); llmsFullTxt.append(llmsFullTxtAudit); }
        if (!ignoreElements.isEmpty()) { llmsTxt.append(llmsTxtIgnore); llmsFullTxt.append(llmsFullTxtIgnore); }
        if (!draftElements.isEmpty()) { llmsTxt.append(llmsTxtDraft); llmsFullTxt.append(llmsFullTxtDraft); }
        if (!privacyElements.isEmpty()) { llmsTxt.append(llmsTxtPrivacy); llmsFullTxt.append(llmsFullTxtPrivacy); }
        if (!coreElements.isEmpty()) { llmsTxt.append(llmsTxtCore); llmsFullTxt.append(llmsFullTxtCore); }
        if (!performanceElements.isEmpty()) { llmsTxt.append(llmsTxtPerformance); llmsFullTxt.append(llmsFullTxtPerformance); }

        if (log != null) {
            log.info("Active services ({}): {}", activeServices.size(),
                activeServices.stream().sorted().collect(Collectors.joining(", ")));
            if (!lockedNames.isEmpty())  log.info("@AILocked:  {} — {}", lockedNames.size(),  String.join(", ", lockedNames));
            if (!contextNames.isEmpty()) log.info("@AIContext: {} — {}", contextNames.size(), String.join(", ", contextNames));
            if (!ignoreNames.isEmpty())  log.info("@AIIgnore:  {} — {}", ignoreNames.size(),  String.join(", ", ignoreNames));
            if (!auditNames.isEmpty())   log.info("@AIAudit:   {} — {}", auditNames.size(),   String.join(", ", auditNames));
            if (!draftNames.isEmpty())   log.info("@AIDraft:   {} — {}", draftNames.size(),   String.join(", ", draftNames));
            if (!privacyElements.isEmpty()) log.info("@AIPrivacy: {} — {}", privacyNames.size(), String.join(", ", privacyNames));
            if (!coreNames.isEmpty())    log.info("@AICore:    {} — {}", coreNames.size(),    String.join(", ", coreNames));
            if (!performanceNames.isEmpty()) log.info("@AIPerformance: {} — {}", performanceNames.size(), String.join(", ", performanceNames));
        }

        Map<String, String> contentByService = new LinkedHashMap<>();
        if (activeServices.contains("cursor"))    contentByService.put("cursor",    cursorRules.toString());
        if (activeServices.contains("qwen"))      contentByService.put("qwen",      qwenMd.toString());
        if (activeServices.contains("claude"))    contentByService.put("claude",    claudeMd.toString());
        if (activeServices.contains("gemini"))    contentByService.put("gemini",    geminiMd.toString());
        if (activeServices.contains("codex"))     contentByService.put("codex",     codexAgents.toString());
        if (activeServices.contains("copilot"))   contentByService.put("copilot",   copilot.toString());
        if (activeServices.contains("llms"))      contentByService.put("llms",      llmsTxt.toString());
        if (activeServices.contains("llms_full")) contentByService.put("llms_full", llmsFullTxt.toString());

        if (activeServices.contains("aiexclude") && (activeServices.contains("gemini") || activeServices.contains("codex"))) {
            contentByService.put("aiexclude", aiExclude.toString());
        }

        if (activeServices.contains("cursor_ignore"))  contentByService.put("cursor_ignore",  cursorIgnoreFile.toString());
        if (activeServices.contains("claude_ignore"))  contentByService.put("claude_ignore",  claudeIgnoreFile.toString());
        if (activeServices.contains("copilot_ignore")) contentByService.put("copilot_ignore", copilotIgnoreFile.toString());
        if (activeServices.contains("qwen_ignore"))    contentByService.put("qwen_ignore",    qwenIgnoreFile.toString());

        if (activeServices.contains("codex")) {
            contentByService.put("codex_config", "# " + GENERATED_HEADER.trim() + "\n[project]\nmodel = \"o3-mini\"\napproval_policy = \"on-request\"\n");
            contentByService.put("codex_rules", 
                "# " + GENERATED_HEADER.trim() + "\n# VibeTags: Starlark Command Permissions\n\n" +
                "prefix_rule(\"ls\", \"allow\")\n" +
                "prefix_rule(\"cat\", \"allow\")\n" +
                "prefix_rule(\"grep\", \"allow\")\n" +
                "prefix_rule(\"mvn\", \"prompt\")\n" +
                "prefix_rule(\"npm\", \"prompt\")\n" +
                "prefix_rule(\"git\", \"prompt\")\n" +
                "prefix_rule(\"rm\", \"prompt\")\n");
        }
        if (activeServices.contains("qwen")) {
            contentByService.put("qwen_settings", "{\n  \"project\": {\n    \"model\": \"qwen3-coder-plus\",\n    \"mcp\": {\n      \"enabled\": true\n    }\n  }\n}\n");
            contentByService.put("qwen_refactor", "# /refactor command\n# AUTO-GENERATED BY VIBETAGS\n\nRefactor the current selection to improve maintainability and performance while strictly following the project's contextual rules in QWEN.md.\n");
        }

        if (activeServices.contains("aider_conventions")) contentByService.put("aider_conventions", aiderConventions.toString());
        if (activeServices.contains("aider_ignore"))      contentByService.put("aider_ignore",      aiderIgnore.toString());

        Messager messager = getSafeMessager();
        String genMsg = "VibeTags: Generating files (v" + VERSION + ") for " + contentByService.size() + " active services: " + String.join(", ", contentByService.keySet());
        messager.printMessage(Diagnostic.Kind.NOTE, genMsg);

        contentByService.forEach((service, content) -> {
            Path filePath = serviceFiles.get(service);
            boolean isIgnoreFile = service.endsWith("_ignore") || service.equals("aider_ignore") || service.equals("aiexclude");
            boolean changed = writeFileIfChanged(filePath.toString(), content, anyAnnotationsFound || isIgnoreFile);
            String relPath = root.relativize(filePath).toString().replace('\\', '/');
            String status = changed ? "updated" : "no changes";
            String fileMsg = "VibeTags: " + status + " - " + relPath;
            getSafeMessager().printMessage(Diagnostic.Kind.NOTE, fileMsg);
            if (log != null) {
                if (changed) log.info("{} — updated", relPath);
                else         log.info("{} — no changes", relPath);
            }
        });

        // Granular Rules Writing — track written qNames so cleanup only removes true orphans
        Set<String> writtenQNames = new java.util.HashSet<>();
        elementRules.forEach((element, builder) -> {
            String qName = element.toString().replace('.', '-').replaceAll("[^a-zA-Z0-9-]", "-");
            writtenQNames.add(qName);
            String simpleName = element.getSimpleName().toString();
            String rulesContent = builder.toString().trim();
            String glob = javax.lang.model.element.ElementKind.PACKAGE.equals(element.getKind())
                ? "**/"+ simpleName + "/**/*.java"
                : "**/"+ simpleName + ".java";

            if (activeServices.contains("cursor_granular")) {
                String mdc = "---\n" +
                    "description: \"AI rules for " + element + "\"\n" +
                    "globs: [\"" + glob + "\"]\n" +
                    "alwaysApply: false\n" +
                    "---\n\n" +
                    "# Rules for " + simpleName + "\n\n" +
                    rulesContent;
                Path path = serviceFiles.get("cursor_granular").resolve(qName + ".mdc");
                writeFileIfChanged(path.toString(), mdc, true);
            }

            if (activeServices.contains("trae_granular")) {
                String md = "---\n" +
                    "alwaysApply: false\n" +
                    "globs: [\"" + glob + "\"]\n" +
                    "description: \"AI rules for " + element + "\"\n" +
                    "---\n\n" +
                    "# Rules for " + simpleName + "\n\n" +
                    rulesContent;
                Path path = serviceFiles.get("trae_granular").resolve(qName + ".md");
                writeFileIfChanged(path.toString(), md, true);
            }

            if (activeServices.contains("roo_granular")) {
                String md = "# Rules for " + simpleName + "\n\n" + rulesContent;
                Path path = serviceFiles.get("roo_granular").resolve(qName + ".md");
                writeFileIfChanged(path.toString(), md, true);
            }
        });

        // Cleanup orphaned granular files (classes that lost their annotations),
        // skipping files we just wrote to avoid a delete-then-recreate cycle.
        if (activeServices.contains("cursor_granular")) cleanupGranularDirectory(serviceFiles.get("cursor_granular"), ".mdc", writtenQNames);
        if (activeServices.contains("trae_granular"))   cleanupGranularDirectory(serviceFiles.get("trae_granular"), ".md", writtenQNames);
        if (activeServices.contains("roo_granular"))    cleanupGranularDirectory(serviceFiles.get("roo_granular"), ".md", writtenQNames);

        checkOrphanedAnnotations(messager, activeServices, 
            !lockedElements.isEmpty(),
            !ignoreElements.isEmpty(), 
            !auditElements.isEmpty());
    }

    void validateAnnotations(Messager messager, RoundEnvironment roundEnv) {
        // Contradiction Check: AIDraft + AILocked
        for (Element element : roundEnv.getElementsAnnotatedWith(AILocked.class)) {
            if (element.getAnnotation(AIDraft.class) != null) {
                messager.printMessage(Diagnostic.Kind.WARNING,
                    "VibeTags: " + element.toString() + " is annotated with both @AIDraft and @AILocked. This is contradictory.", element);
            }
        }

        // Empty Audit Check
        for (Element element : roundEnv.getElementsAnnotatedWith(AIAudit.class)) {
            AIAudit audit = element.getAnnotation(AIAudit.class);
            if (audit.checkFor().length == 0) {
                messager.printMessage(Diagnostic.Kind.WARNING,
                    "VibeTags: @AIAudit on " + element.toString() + " has no 'checkFor' items list. It will be ignored.", element);
            }
        }

        // Redundancy Check: AIPrivacy + AIIgnore
        for (Element element : roundEnv.getElementsAnnotatedWith(AIPrivacy.class)) {
            if (element.getAnnotation(AIIgnore.class) != null) {
                messager.printMessage(Diagnostic.Kind.WARNING,
                    "VibeTags: " + element.toString() + " is annotated with both @AIPrivacy and @AIIgnore. "
                    + "@AIIgnore already excludes the element from AI context; @AIPrivacy is redundant.", element);
            }
        }
    }

    void checkOrphanedAnnotations(Messager messager, Set<String> active, boolean hasLocked, boolean hasIgnore, boolean hasAudit) {
        if (hasIgnore) {
            warn(messager, active.contains("cursor") && !active.contains("cursor_ignore"),
                "VibeTags: @AIIgnore used but .cursorignore is missing for Cursor support. Consider creating it.");
            warn(messager, active.contains("claude") && !active.contains("claude_ignore"),
                "VibeTags: @AIIgnore used but .claudeignore is missing for Claude support. Consider creating it.");
            warn(messager, active.contains("copilot") && !active.contains("copilot_ignore"),
                "VibeTags: @AIIgnore used but .copilotignore is missing for Copilot support. Consider creating it.");
            warn(messager, active.contains("qwen") && !active.contains("qwen_ignore"),
                "VibeTags: @AIIgnore used but .qwenignore is missing for Qwen support. Consider creating it.");
            warn(messager, (active.contains("gemini") || active.contains("codex")) && !active.contains("aiexclude"),
                "VibeTags: @AIIgnore used but .aiexclude is missing for Gemini/Codex support. Consider creating it.");
        }

        if (hasLocked) {
            warn(messager, (active.contains("gemini") || active.contains("codex")) && !active.contains("aiexclude"),
                "VibeTags: @AILocked used but .aiexclude (hard guardrail) is missing for Gemini/Codex support. Consider creating it.");
        }
    }

    /** Emits a compiler WARNING via {@code messager} and mirrors it to the log file when the condition is true. */
    private void warn(Messager messager, boolean condition, String message) {
        if (!condition) return;
        messager.printMessage(Diagnostic.Kind.WARNING, message);
        if (log != null) log.warn(message);
    }

    void cleanupGranularDirectory(Path dir, String extension) {
        cleanupGranularDirectory(dir, extension, java.util.Collections.emptySet());
    }

    void cleanupGranularDirectory(Path dir, String extension, Set<String> excludeQNames) {
        if (dir == null || !Files.exists(dir) || !Files.isDirectory(dir)) return;
        try (java.util.stream.Stream<Path> stream = Files.list(dir)) {
            stream.filter(Files::isRegularFile)
                  .filter(p -> p.toString().endsWith(extension))
                  .filter(p -> {
                      String name = p.getFileName().toString();
                      int dot = name.lastIndexOf('.');
                      return !excludeQNames.contains(dot >= 0 ? name.substring(0, dot) : name);
                  })
                  .forEach(p -> {
                      try {
                          String content = Files.readString(p, java.nio.charset.StandardCharsets.UTF_8);
                          boolean updated = false;

                          int mdStart = content.indexOf(MARKER_START_MD);
                          if (mdStart >= 0) {
                              int end = content.indexOf(MARKER_END_MD);
                              if (end != -1) {
                                  String before = content.substring(0, mdStart).stripTrailing();
                                  String after = content.substring(end + MARKER_END_MD.length()).stripLeading();
                                  content = (!before.isEmpty() ? before + "\n\n" : "") + after;
                                  updated = true;
                              }
                          } else {
                              int hashStart = content.indexOf(MARKER_START_HASH);
                              if (hashStart >= 0) {
                                  int end = content.indexOf(MARKER_END_HASH);
                                  if (end != -1) {
                                      String before = content.substring(0, hashStart).stripTrailing();
                                      String after = content.substring(end + MARKER_END_HASH.length()).stripLeading();
                                      content = (!before.isEmpty() ? before + "\n\n" : "") + after;
                                      updated = true;
                                  }
                              }
                          }

                          if (updated) {
                              content = content.trim();
                              boolean isEmptyOrBoilerplate = content.isEmpty();
                              if (!isEmptyOrBoilerplate && content.startsWith("---")) {
                                  int secondTriple = content.indexOf("---", 3);
                                  if (secondTriple != -1) {
                                      String afterFrontMatter = content.substring(secondTriple + 3).trim();
                                      isEmptyOrBoilerplate = afterFrontMatter.isEmpty();
                                  }
                              }

                              if (isEmptyOrBoilerplate) {
                                  Files.delete(p);
                              } else {
                                  // Retain the file with manual edits, but scrubbed of the orphaned VibeTags section
                                  Files.writeString(p, content + "\n", java.nio.charset.StandardCharsets.UTF_8);
                              }
                          }
                      } catch (IOException ignored) {}
                  });
        } catch (IOException e) {
            // Log if useful, but stay silent during compilation
        }
    }

    /**
     * Walks up the element hierarchy to find the nearest TypeElement (class/interface)
     * or PackageElement. This ensures granular rules are consolidated at the file or package level.
     */
    private Element getOwningElement(Element e) {
        Element current = e;
        while (current != null) {
            ElementKind kind = current.getKind();
            if (current instanceof TypeElement || (kind != null && kind.equals(javax.lang.model.element.ElementKind.PACKAGE))) {
                return current;
            }
            current = current.getEnclosingElement();
        }
        return e;
    }

    /**
     * Returns a fully-qualified path for an element.
     * For FIELD, METHOD, and CONSTRUCTOR elements, prepends the enclosing type's FQN.
     * Falls back to element.toString() if no enclosing element is present (e.g. in tests).
     */
    private String elementPath(Element element) {
        ElementKind kind = element.getKind();
        if (kind == ElementKind.FIELD || kind == ElementKind.METHOD || kind == ElementKind.CONSTRUCTOR) {
            Element enclosing = element.getEnclosingElement();
            if (enclosing != null) {
                return enclosing.toString() + "." + element.toString();
            }
        }
        return element.toString();
    }

    /**
     * Returns a short display name for llms.txt link text.
     * For FIELD/METHOD/CONSTRUCTOR: "EnclosingSimpleName.memberSimpleName(params)" format.
     * For TYPE elements: just the simple name.
     */
    private String elementDisplayName(Element element) {
        ElementKind kind = element.getKind();
        if (kind == ElementKind.FIELD || kind == ElementKind.METHOD || kind == ElementKind.CONSTRUCTOR) {
            Element enclosing = element.getEnclosingElement();
            if (enclosing != null) {
                return enclosing.getSimpleName() + "." + element.toString();
            }
        }
        return element.getSimpleName().toString();
    }

    private void appendToGranular(Element element, String title, String content) {
        Element owner = getOwningElement(element);
        StringBuilder sb = elementRules.computeIfAbsent(owner, k -> new StringBuilder());
        if (sb.length() > 0) sb.append("\n");
        
        // Add a sub-header if the annotation is on a member (method/field) of the owning class
        if (!owner.equals(element)) {
            ElementKind kind = element.getKind();
            String kindStr = (kind != null) ? kind.toString().toLowerCase() : "element";
            sb.append("### Rules for ").append(kindStr)
              .append(" ").append(element.getSimpleName()).append("\n");
        } else {
            sb.append("## ").append(title).append("\n");
        }
        sb.append(content).append("\n");
    }

    /**
     * Returns the canonical map of service key → output file path for a given project root.
     *
     * @param root the project root directory
     * @return a map of logical service names to their expected file paths
     */
    public static Map<String, Path> buildServiceFileMap(Path root) {
        Map<String, Path> map = new LinkedHashMap<>();
        map.put("cursor",    root.resolve(".cursorrules"));
        map.put("claude",    root.resolve("CLAUDE.md"));
        map.put("aiexclude", root.resolve(".aiexclude"));
        map.put("codex",     root.resolve("AGENTS.md"));
        map.put("gemini",    root.resolve("gemini_instructions.md"));
        map.put("copilot",   root.resolve(".github/copilot-instructions.md"));
        map.put("qwen",      root.resolve("QWEN.md"));
        map.put("cursor_ignore",  root.resolve(".cursorignore"));
        map.put("claude_ignore",  root.resolve(".claudeignore"));
        map.put("copilot_ignore", root.resolve(".copilotignore"));
        map.put("qwen_ignore",    root.resolve(".qwenignore"));
        map.put("codex_config",   root.resolve(".codex/config.toml"));
        map.put("codex_rules",    root.resolve(".codex/rules/vibetags.rules"));
        map.put("qwen_settings",  root.resolve(".qwen/settings.json"));
        map.put("qwen_refactor",  root.resolve(".qwen/commands/refactor.md"));
        map.put("llms",           root.resolve("llms.txt"));
        map.put("llms_full",      root.resolve("llms-full.txt"));
        map.put("aider_conventions", root.resolve("CONVENTIONS.md"));
        map.put("aider_ignore",      root.resolve(".aiderignore"));
        map.put("cursor_granular",   root.resolve(".cursor/rules"));
        map.put("roo_granular",      root.resolve(".roo/rules"));
        map.put("trae_granular",     root.resolve(".trae/rules"));
        return map;
    }

    /**
     * Resolves which primary services should have their files written.
     * Only "signal" files (like QWEN.md or .cursorrules) are checked — their presence acts as the opt-in.
     *
     * @param messager        the compiler messager for printing notes
     * @param allServiceFiles the map of all possible service files
     * @return the set of active service keys based on existing files
     */
    public static Set<String> resolveActiveServices(Messager messager, Map<String, Path> allServiceFiles) {
        // Only these primary files define an "active" service
        Set<String> optInKeys = Set.of(
            "cursor", "claude", "aiexclude", "codex", "gemini", "copilot", "qwen",
            "cursor_ignore", "claude_ignore", "copilot_ignore", "qwen_ignore",
            "llms", "llms_full", "aider_conventions", "aider_ignore",
            "cursor_granular", "roo_granular", "trae_granular"
        );

        Set<String> active = new java.util.HashSet<>();

        allServiceFiles.forEach((key, path) -> {
            if (!optInKeys.contains(key)) return;
            if (Files.exists(path)) {
                active.add(key);
            }
        });

        if (active.isEmpty()) {
            StringBuilder msg = new StringBuilder(
                "VibeTags: No AI config files found - nothing will be generated.\n" +
                "Create one or more of the following files in your project root to opt in:\n");
            allServiceFiles.entrySet().stream()
                .filter(e -> optInKeys.contains(e.getKey()))
                .forEach(e -> msg.append("  ").append(e.getValue().getFileName()).append("\n"));
            messager.printMessage(javax.tools.Diagnostic.Kind.NOTE, msg.toString());
        }

        return active;
    }

    /**
     * Determines the appropriate VibeTags markers for a given file.
     *
     * @param fileName the name of the file
     * @return an array containing [startMarker, endMarker], or {@code null} if markers are not supported
     */
    private String[] getMarkersFor(String fileName) {
        if (fileName.endsWith(".md") || fileName.endsWith(".mdc") || fileName.equals("llms.txt") || fileName.equals("llms-full.txt")) {
            return new String[]{MARKER_START_MD, MARKER_END_MD};
        }
        if (fileName.endsWith(".json") || fileName.endsWith(".toml")) {
            return null; // No markers for JSON/TOML, overwrite only
        }
        // Default to hash comments for rules/ignore files (.cursorrules, .aiexclude, etc.)
        return new String[]{MARKER_START_HASH, MARKER_END_HASH};
    }

    /** Returns the messager from processingEnv, or a no-op messager if processingEnv is null (common in unit tests). */
    private Messager getSafeMessager() {
        if (processingEnv != null) return processingEnv.getMessager();
        return new Messager() {
            @Override public void printMessage(Diagnostic.Kind kind, CharSequence msg) {}
            @Override public void printMessage(Diagnostic.Kind kind, CharSequence msg, Element e) {}
            @Override public void printMessage(Diagnostic.Kind kind, CharSequence msg, Element e, javax.lang.model.element.AnnotationMirror a) {}
            @Override public void printMessage(Diagnostic.Kind kind, CharSequence msg, Element e, javax.lang.model.element.AnnotationMirror a, javax.lang.model.element.AnnotationValue v) {}
        };
    }

    /**
     * Writes {@code content} to {@code path} only if the file's current content differs.
     *
     * @param path    the destination file path
     * @param content the content to write
     * @param hasNewRules true if the current run found annotations, false otherwise
     * @return {@code true} if the file was written (content changed or file was empty),
     *         {@code false} if the existing content was already up-to-date.
     */
    public boolean writeFileIfChanged(String path, String content, boolean hasNewRules) {
        Messager messager = getSafeMessager();
        try {
            Path filePath = Paths.get(path);
            Path parent = filePath.getParent();
            if (parent != null) {
                Files.createDirectories(parent);
            }

            String fileName = filePath.getFileName().toString();
            String[] markers = getMarkersFor(fileName);
            boolean supportsMarkers = (markers != null);

            // Cheap pre-check: if the on-disk size can't possibly match the new content
            // (allowing for trim-whitespace tolerance), the non-marker overwrite branch
            // can skip the full file read entirely.
            long existingSize;
            boolean fileExists;
            try {
                existingSize = Files.size(filePath);
                fileExists = true;
            } catch (java.nio.file.NoSuchFileException nsfe) {
                existingSize = 0L;
                fileExists = false;
            }
            int contentByteLen = content.getBytes(java.nio.charset.StandardCharsets.UTF_8).length;
            boolean nonMarkerSizeMismatch = !supportsMarkers && fileExists
                && Math.abs(existingSize - contentByteLen) > 64;

            String existing = (fileExists && !nonMarkerSizeMismatch)
                ? Files.readString(filePath, java.nio.charset.StandardCharsets.UTF_8)
                : "";

            if (supportsMarkers) {
                String markerStart = markers[0];
                String markerEnd = markers[1];
                
                // Special handling for YAML front-matter: markers MUST come after it
                String frontMatter = "";
                String body = content;
                if (content.startsWith("---")) {
                    int secondTriple = content.indexOf("---", 3);
                    if (secondTriple != -1) {
                        frontMatter = content.substring(0, secondTriple + 3).trim();
                        body = content.substring(secondTriple + 3).trim();
                    }
                }
                
                String wrappedBody = markerStart + "\n" + body.trim() + "\n" + markerEnd;

                int start = existing.indexOf(markerStart);
                if (start >= 0) {
                    // Update existing section
                    int end = existing.indexOf(markerEnd);
                    if (end == -1) {
                        messager.printMessage(Diagnostic.Kind.WARNING, "VibeTags: malformed markers in " + path + " (no end marker). Preserving content before start marker.");
                        String before = stripLegacyVibeTagsBlock(existing.substring(0, start).stripTrailing());
                        String finalContent = (!before.isEmpty() ? before + "\n\n" : "") + wrappedBody + "\n";
                        if (existing.strip().equals(finalContent.strip())) {
                            return false;
                        }
                        writeContentWithBackup(filePath, finalContent);
                        return true;
                    }
                    end += markerEnd.length();
                    // Strip legacy VibeTags block from 'before' (written without markers by older versions)
                    String before = stripLegacyVibeTagsBlock(existing.substring(0, start).stripTrailing());
                    String after = existing.substring(end).stripLeading();
                    
                    StringBuilder sb = new StringBuilder();
                    if (!before.isEmpty()) sb.append(before).append("\n\n");
                    sb.append(wrappedBody);
                    if (!after.isEmpty()) sb.append("\n\n").append(after);
                    String finalContent = sb.toString().trim() + "\n";

                    if (existing.strip().equals(finalContent.strip())) {
                        return false;
                    }

                    if (!hasNewRules && !existing.isEmpty()) {
                        skipUpdateMsg(fileName, messager);
                        return false;
                    }

                    writeContentWithBackup(filePath, finalContent);
                    getSafeMessager().printMessage(Diagnostic.Kind.NOTE, "VibeTags: Updated " + fileName);
                    return true;
                } else if (!existing.isEmpty() && existing.contains(GENERATED_HEADER.trim())) {
                    // Legacy VibeTags file found (no markers but has header): upgrade to markers
                    String finalContent = (frontMatter.isEmpty() ? "" : frontMatter + "\n\n") + wrappedBody + "\n";
                    if (existing.strip().equals(finalContent.strip())) {
                        return false;
                    }

                    if (!hasNewRules && !existing.isEmpty()) {
                        skipUpdateMsg(fileName, messager);
                        return false;
                    }

                    writeContentWithBackup(filePath, finalContent);
                    getSafeMessager().printMessage(Diagnostic.Kind.NOTE, "VibeTags: Updated legacy file " + fileName);
                    return true;
                } else {
                    // Section missing or file is not a VibeTags file: append to the end
                    String updated = existing.isEmpty()
                        ? (frontMatter.isEmpty() ? "" : frontMatter + "\n\n") + wrappedBody + "\n"
                        : existing.stripTrailing() + "\n\n" + wrappedBody + "\n";
                    if (existing.strip().equals(updated.strip())) {
                        return false;
                    }

                    if (!hasNewRules && !existing.isEmpty()) {
                        skipUpdateMsg(fileName, messager);
                        return false;
                    }

                    writeContentWithBackup(filePath, updated);
                    String action = existing.isEmpty() ? "wrote" : "appended";
                    getSafeMessager().printMessage(Diagnostic.Kind.NOTE, "VibeTags: " + action + " " + fileName);
                    return true;
                }
            } else {
                // Non-markdown file: complete overwrite if changed
                if (!nonMarkerSizeMismatch && existing.strip().equals(content.strip())) {
                    return false;
                }

                // Smart skip for multi-module preservation
                if (!hasNewRules && fileExists && existingSize > 0) {
                    skipUpdateMsg(fileName, messager);
                    return false;
                }

                writeContentWithBackup(filePath, content);
                getSafeMessager().printMessage(Diagnostic.Kind.NOTE, "VibeTags: Updated " + fileName);
                return true;
            }
        } catch (IOException e) {
            getSafeMessager().printMessage(Diagnostic.Kind.WARNING, "VibeTags: Failed to write AI rules file: " + path + " - " + e.getMessage());
            return false;
        }
    }

    private void skipUpdateMsg(String fileName, Messager messager) {
        String msg = "VibeTags: Skipping update of " + fileName + " (no annotations found in this module, preserving existing rules)";
        messager.printMessage(Diagnostic.Kind.NOTE, msg);
        if (log != null) log.info("Skipping update of {} — no annotations found", fileName);
    }

    private void writeContentWithBackup(Path filePath, String finalContent) throws IOException {
        Path tmp = Paths.get(filePath.toString() + ".vibetags-tmp");
        Files.writeString(tmp, finalContent, java.nio.charset.StandardCharsets.UTF_8);
        try {
            Files.move(tmp, filePath,
                java.nio.file.StandardCopyOption.REPLACE_EXISTING,
                java.nio.file.StandardCopyOption.ATOMIC_MOVE);
        } catch (java.nio.file.AtomicMoveNotSupportedException e) {
            Files.move(tmp, filePath, java.nio.file.StandardCopyOption.REPLACE_EXISTING);
        }
    }

    /**
     * Strips a legacy VibeTags block (written without markers by older versions) from the given
     * {@code before} string, preserving any genuine human content that follows it.
     *
     * <p>Detection: the block starts with the VibeTags generated header (commented or bare).
     * For XML-structured files (CLAUDE.md): the block ends at the last {@code </rule>} or
     * {@code </project_guardrails>} tag within the first 2 000 characters.
     * For all other files (cursor rules, ignore lists, etc.): the entire {@code rest} is treated
     * as legacy since those files are fully VibeTags-managed.
     */
    String stripLegacyVibeTagsBlock(String before) {
        if (before == null || before.isEmpty()) return before;

        String commentedHeader = "<!-- " + GENERATED_HEADER.trim() + " -->";
        int legacyStart = before.indexOf(commentedHeader);
        if (legacyStart == -1) legacyStart = before.indexOf(GENERATED_HEADER.trim());
        if (legacyStart == -1) return before;

        String rawPrefix = before.substring(0, legacyStart).stripTrailing();
        String rest = before.substring(legacyStart);

        // Determine whether the prefix contains genuine human content.
        // Lines that are only hash-comments, bullets, blank, or HTML-comments are boilerplate.
        boolean hasHumanPrefix = !rawPrefix.isEmpty()
            && rawPrefix.lines().anyMatch(l -> {
                String t = l.trim();
                return !t.isEmpty() && !t.startsWith("#") && !t.startsWith("*")
                    && !t.startsWith("-") && !t.startsWith("<!--");
            });
        String prefix = hasHumanPrefix ? rawPrefix : "";

        // For XML-structured files (.md), find the last VibeTags closing tag within 2 000 chars
        // to avoid false positives deep inside human content.
        String searchWindow = rest.length() > 2000 ? rest.substring(0, 2000) : rest;
        int blockEnd = -1;
        for (String closer : new String[]{"</rule>", "</project_guardrails>"}) {
            int idx = searchWindow.lastIndexOf(closer);
            if (idx >= 0) blockEnd = Math.max(blockEnd, idx + closer.length());
        }

        String humanContent;
        if (blockEnd > 0) {
            int nlAfter = rest.indexOf("\n", blockEnd);
            humanContent = nlAfter >= 0 ? rest.substring(nlAfter + 1).stripLeading() : "";
        } else {
            // No XML closers: for fully auto-generated files the rest is all legacy;
            // for mixed human-content files try a double-newline separation.
            humanContent = hasHumanPrefix
                ? (rest.contains("\n\n") ? rest.substring(rest.indexOf("\n\n") + 2).stripLeading() : "")
                : "";
        }

        if (prefix.isEmpty()) return humanContent;
        if (humanContent.isEmpty()) return prefix;
        return prefix + "\n\n" + humanContent;
    }
}
