package se.deversity.vibetags.processor.internal.content.platforms;

import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;
import se.deversity.vibetags.annotations.AILocked;
import se.deversity.vibetags.processor.internal.content.Platform;
import se.deversity.vibetags.processor.internal.content.RenderingContext;
import se.deversity.vibetags.processor.model.ElementTag;
import se.deversity.vibetags.processor.model.GuardrailModel;
import se.deversity.vibetags.processor.model.TaggedElement;

import java.util.Set;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNotEquals;
import static org.mockito.Mockito.mock;
import static org.mockito.Mockito.when;

/**
 * Pins the two PR-reviewer Markdown documents, {@code .gemini/styleguide.md} and
 * {@code .greptile/rules.md}, byte for byte, and pins the one fact that made them worth merging:
 * they differ in exactly two strings, the heading suffix and the product name.
 *
 * <p>Before this test the two renderers were independent copies of the same eleven lines. A fix
 * applied to one and not the other, the empty-model wording or the "Flag any change" lead-in,
 * would have left the two review platforms disagreeing with nothing failing to name the cause.
 * The substitution assertion below is what detects that; the literal assertions keep the
 * substitution honest by proving what the bytes actually are.
 */
class ReviewGuidanceRendererContractTest {

    private final RenderingContext ctx = new RenderingContext(
            "Test Project", "# Generated Header\n", Set.of());

    private static GuardrailModel oneLockedElement() {
        TaggedElement element = mock(TaggedElement.class);
        when(element.path()).thenReturn("com.example.Ledger");
        when(element.kind()).thenReturn(ElementTag.CLASS);
        AILocked locked = mock(AILocked.class);
        when(locked.reason()).thenReturn("settlement contract");
        when(element.annotation(AILocked.class)).thenReturn(locked);
        return GuardrailModel.builder().add(AILocked.class, element).build();
    }

    /** The heading suffix and product name that are allowed to differ, and nothing else. */
    private static String asGreptile(String geminiOutput) {
        return geminiOutput
                .replace(" review style guide\n", " review rules\n")
                .replace("Gemini Code Assist reads this file", "Greptile reads this file");
    }

    @Test
    @DisplayName("an empty model renders the no-guardrails document, byte for byte")
    void emptyModelRendersNoGuardrailsDocument() {
        String gemini = new GeminiStyleguideRenderer()
                .render(GuardrailModel.EMPTY, Platform.GEMINI_STYLEGUIDE, ctx);

        assertEquals("""
                # Test Project review style guide
                # Generated Header
                # AUTO-GENERATED BY VIBETAGS. Gemini Code Assist reads this file when reviewing a \
                pull request in this repository.

                ## VibeTags guardrails

                No VibeTags guardrails are currently declared.
                """, gemini);
    }

    @Test
    @DisplayName("a populated model renders the flag-any-change lead-in and the guardrail block")
    void populatedModelRendersTheGuardrailBlock() {
        String gemini = new GeminiStyleguideRenderer()
                .render(oneLockedElement(), Platform.GEMINI_STYLEGUIDE, ctx);
        int blockStart = gemini.indexOf("following:\n\n") + "following:\n\n".length();

        assertEquals("""
                # Test Project review style guide
                # Generated Header
                # AUTO-GENERATED BY VIBETAGS. Gemini Code Assist reads this file when reviewing a \
                pull request in this repository.

                ## VibeTags guardrails

                Flag any change in this pull request that violates one of the following:

                """, gemini.substring(0, blockStart));

        // The block itself belongs to GuardrailInstructionBlock; assert it arrived, stripped.
        assertEquals(GuardrailInstructionBlock.build(oneLockedElement()).strip() + "\n",
                gemini.substring(blockStart));
    }

    @Test
    @DisplayName("the two review documents differ in exactly the heading suffix and the product name")
    void theTwoReviewDocumentsDifferOnlyInTheirTwoLiterals() {
        for (GuardrailModel model : new GuardrailModel[]{GuardrailModel.EMPTY, oneLockedElement()}) {
            String gemini = new GeminiStyleguideRenderer()
                    .render(model, Platform.GEMINI_STYLEGUIDE, ctx);
            String greptile = new GreptileRulesRenderer()
                    .render(model, Platform.GREPTILE_RULES, ctx);

            assertNotEquals(gemini, greptile, "the two documents must still name their own product");
            assertEquals(asGreptile(gemini), greptile,
                    "the two review documents have drifted beyond their two intended literals");
        }
    }
}
