#!/usr/bin/env python3
"""Fail a PR when its diff touches code protected by @AILocked.

Reads every ``.vibetags-locks`` report under the working directory (JSON Lines
between ``# VIBETAGS`` hash markers, regenerated by the build step that runs
before this script), lists the changed files against the merge base with
``git diff --raw -z``, and reports a violation when:

  1. a changed line range intersects a locked element's line range (for a renamed file,
     also the base report's range on the old side),
  2. a removed line in a source file contains the ``@AILocked`` annotation itself
     (lock stripping; scoped to source files because generated guardrail files and
     docs merely *mention* the annotation and reflow on every regeneration),
  3. a deleted source file contained ``@AILocked`` at the base revision; a source renamed
     to another extension, or changed into another file type, counts as deleted,
  4. a submodule that holds a locked element changes.

Checks 2 and 3 read the base revision. A Java source is lexed there, so ``@AILocked`` text
inside a string literal, text block, char literal or comment is not an annotation (#708).
Kotlin and Groovy sources, and any Java source that does not lex, keep the plain substring
match, which errs toward failing. So does anything else the guard cannot read: an unknown
diff status, an unparseable record, or a file whose diff does not map to one section.

Environment:
  VIBETAGS_BASE_REF    ref/SHA to diff against (required)
  VIBETAGS_WARN_ONLY   'true' to emit warnings instead of failing (default 'false')

Exit code 1 on violations unless warn-only.
"""

import json
import os
import re
import subprocess
import sys
import unicodedata

HUNK_RE = re.compile(r"^@@ -(\d+)(?:,(\d+))? \+(\d+)(?:,(\d+))? @@")

# Files that can carry @AILocked as an annotation on code. The lock-stripping and
# deleted-file checks are scoped to these: generated guardrail files and docs legitimately
# *mention* @AILocked, and regenerating them reflows those lines on every unrelated change.
# The first PR this guard ever ran on was flagged for exactly that (its own dogfooding PR,
# which reflowed generated Markdown), while a real stripped lock lives in a source file --
# and must stay a check of the base side's source, because a stripped lock is absent from the
# regenerated report and so invisible to any report-based check. A base-side report would not
# do either: a consumer's committed report can be stale, and a source cannot.
SOURCE_EXTS = (".java", ".kt", ".kts", ".groovy")


def is_lock_carrying_source(path):
    return path is not None and path.endswith(SOURCE_EXTS)


class _Unlexable(Exception):
    """The source is not well-formed enough to say where its literals and comments are."""


def _translate_unicode_escapes(text):
    """``(char, line)`` pairs after javac's unicode-escape translation (JLS 3.3).

    javac translates ``\\uXXXX`` before it lexes anything, so ``"\\u0022`` is an empty string
    rather than a string still open. Skipping the step would let an escaped quote make a real
    annotation look quoted. ``line`` is 1-based and counts ``\\n`` only, as git does, so it
    lines up with diff hunk numbers even in a file with lone carriage returns.
    """
    out = []
    i, n, line, backslashes = 0, len(text), 1, 0
    while i < n:
        ch = text[i]
        if ch == "\\" and backslashes % 2 == 0 and text.startswith("u", i + 1):
            j = i + 1
            while j < n and text[j] == "u":
                j += 1
            digits = text[j:j + 4]
            if len(digits) != 4 or any(d not in "0123456789abcdefABCDEF" for d in digits):
                raise _Unlexable()  # javac rejects a malformed unicode escape
            out.append((chr(int(digits, 16)), line))
            i, backslashes = j + 4, 0  # a translated backslash starts no further escape
            continue
        backslashes = backslashes + 1 if ch == "\\" else 0
        out.append((ch, line))
        if ch == "\n":
            line += 1
        i += 1
    return out


def java_annotation_lines(text, name="AILocked"):
    """The lines (1-based, as git numbers them) holding a real ``@name`` annotation, or None.

    Text inside a string literal, text block, char literal or comment is not an annotation,
    however it reads: #708 was a test-only pull request failed for editing Java fixture source
    held in string literals. The name may be spaced from the ``@``, qualified, or split by
    comments, as javac allows; every line from the ``@`` to the simple name counts.

    None means the source did not lex (an unterminated literal or comment, a malformed unicode
    escape, a text block with no line break after its opening quotes), so code cannot be told
    from text. Callers then fall back to the plain substring match, which errs toward failing.
    """
    try:
        return _scan_java(_translate_unicode_escapes(text), name)
    except _Unlexable:
        return None


def _java_ignorable(ch):
    """``Character.isIdentifierIgnorable``: part of an identifier, but not of its name.

    javac compares identifiers with these removed, so ``AI<soft hyphen>Locked`` names the lock.
    """
    code = ord(ch)
    return (code <= 0x08 or 0x0E <= code <= 0x1B or 0x7F <= code <= 0x9F
            or unicodedata.category(ch) == "Cf")


def _java_identifier_part(ch):
    """``Character.isJavaIdentifierPart``, plus the other-number characters ``str.isalnum``
    accepts (superscripts, fractions). javac rejects those outright, so no source that
    compiles is read differently.
    """
    return (ch.isalnum() or ch in "_$" or _java_ignorable(ch)
            or unicodedata.category(ch) in ("Mn", "Mc", "Pc", "Sc", "Nl"))


def _scan_java(chars, name):
    n = len(chars)

    def at(k):
        return chars[k][0] if k < n else ""

    def is_ident(k):
        return k < n and _java_identifier_part(chars[k][0])

    def skip_comment(k):
        """The index after a comment starting at k, or k itself when none starts there."""
        if at(k) == "/" and at(k + 1) == "/":
            while k < n and chars[k][0] not in "\r\n":
                k += 1
            return k
        if at(k) == "/" and at(k + 1) == "*":
            k += 2
            while k < n and not (chars[k][0] == "*" and at(k + 1) == "/"):
                k += 1
            if k >= n:
                raise _Unlexable()
            return k + 2
        return k

    def skip_trivia(k):
        while True:
            while k < n and chars[k][0].isspace():
                k += 1
            after = skip_comment(k)
            if after == k:
                return k
            k = after

    def skip_quoted(k, quote):
        """The index after a string or char literal opening at k."""
        k += 1
        while k < n:
            ch = chars[k][0]
            if ch == "\\":
                if k + 1 >= n or chars[k + 1][0] in "\r\n":
                    raise _Unlexable()
                k += 2
            elif ch == quote:
                return k + 1
            elif ch in "\r\n":
                raise _Unlexable()
            else:
                k += 1
        raise _Unlexable()

    def skip_text_block(k):
        """The index after a text block whose opening quotes start at k."""
        k += 3
        while k < n and chars[k][0] in " \t\f":
            k += 1
        if k >= n or chars[k][0] not in "\r\n":
            raise _Unlexable()
        while k < n:
            if chars[k][0] == "\\":
                k += 2
            elif chars[k][0] == '"' and at(k + 1) == '"' and at(k + 2) == '"':
                return k + 3
            else:
                k += 1
        raise _Unlexable()

    lines = set()
    i = 0
    while i < n:
        ch = chars[i][0]
        after = skip_comment(i)
        if after != i:
            i = after
        elif ch == '"':
            text_block = at(i + 1) == '"' and at(i + 2) == '"'
            i = skip_text_block(i) if text_block else skip_quoted(i, '"')
        elif ch == "'":
            i = skip_quoted(i, "'")
        elif ch == "@":
            k, simple_name, name_end = skip_trivia(i + 1), "", i + 1
            while is_ident(k):
                start = k
                while is_ident(k):
                    k += 1
                simple_name = "".join(c for c, _ in chars[start:k] if not _java_ignorable(c))
                name_end = k
                dot = skip_trivia(k)
                if at(dot) != ".":
                    break
                k = skip_trivia(dot + 1)
            if simple_name == name:
                lines.update(range(chars[i][1], chars[name_end - 1][1] + 1))
            i += 1
        else:
            i += 1
    return lines


def lock_lines(path, text):
    """Lines of ``text`` that carry a lock, or None when only a substring match can tell.

    Java is lexed. Kotlin and Groovy are not: Kotlin string templates nest code, strings and
    comments inside a string, and a Groovy slashy string cannot be told from a division without
    parsing, so a lexer that guessed could read a real annotation as text and pass its removal.
    """
    if path.endswith(".java"):
        return java_annotation_lines(text)
    return None


def strips_a_lock(path, base_text, removed):
    """Whether the removed base lines, ``(line number, text)`` pairs, held a real ``@AILocked``.

    Falls back to the substring match on the removed text whenever the base cannot be read or
    lexed, so an unsure answer fails the guard rather than passing it.
    """
    annotated = lock_lines(path, base_text) if base_text is not None else None
    if annotated is None:
        return any("@AILocked" in body for _, body in removed)
    return any(number in annotated for number, _ in removed)


def holds_a_lock(path, base_text):
    """Whether a deleted file carried a real ``@AILocked``, with the same fallback."""
    annotated = lock_lines(path, base_text)
    if annotated is None:
        return "@AILocked" in base_text
    return bool(annotated)


def run_git(*args):
    result = subprocess.run(
        ["git", *args], capture_output=True, text=True, encoding="utf-8", errors="replace"
    )
    if result.returncode != 0:
        sys.stderr.write(result.stderr)
        raise SystemExit(f"git {' '.join(args)} failed with exit code {result.returncode}")
    return result.stdout


def run_git_bytes(*args):
    """git's stdout as bytes: no decoding and no newline translation."""
    result = subprocess.run(["git", *args], capture_output=True)
    if result.returncode != 0:
        sys.stderr.write(result.stderr.decode("utf-8", errors="replace"))
        raise SystemExit(f"git {' '.join(args)} failed with exit code {result.returncode}")
    return result.stdout


def run_git_exact(*args):
    """``run_git`` without newline translation, for output whose line numbers matter.

    ``text=True`` turns every lone carriage return into a line break, so a removed line from a
    file with CR-only endings would count as several and shift the base line numbers the
    lock-stripping check looks up.
    """
    return run_git_bytes(*args).decode("utf-8", errors="replace")


def git_show_text(ref, path):
    """A file's content at ``ref`` as committed, without newline translation, or None."""
    blob = subprocess.run(["git", "show", f"{ref}:{path}"], capture_output=True)
    if blob.returncode != 0:
        return None
    return blob.stdout.decode("utf-8", errors="replace")


def find_reports(root):
    reports = []
    for dirpath, dirnames, filenames in os.walk(root):
        dirnames[:] = [d for d in dirnames if d not in (".git", "node_modules", "target", "build")]
        if ".vibetags-locks" in filenames:
            reports.append(os.path.join(dirpath, ".vibetags-locks"))
    return reports


def resolve_lock_path(recorded, report_dir, repo_root):
    """A lock's repo-relative path, resolved against the report that declared it.

    A ``.vibetags-locks`` records paths relative to its own VibeTags root, not to the
    repository. Normalizing against the repository root alone therefore leaves two reactors
    that both have a module at, say, ``showcase/src/main/java/...`` recording the identical
    string, and nothing downstream can tell them apart. Measured before this was fixed: a
    Gradle example's new files drew nine violations from the *Maven* example's report.

    Absolute paths are made repo-relative directly; anything outside the repository is left
    as it is, so it simply matches nothing.
    """
    path = recorded.replace("\\", "/")
    if os.path.isabs(path):
        rel = os.path.relpath(path, repo_root).replace("\\", "/")
        return path if rel.startswith("..") else rel
    report_rel = os.path.relpath(report_dir, repo_root).replace("\\", "/")
    if report_rel in ("", "."):
        return os.path.normpath(path).replace("\\", "/")
    return os.path.normpath(report_rel + "/" + path).replace("\\", "/")


def parse_lock_entries(text, report_dir, repo_root):
    """The 'locked' entries in one report's text, each with a repo-relative 'file'."""
    locks = []
    for line in text.splitlines():
        line = line.strip()
        if not line or line.startswith("#"):
            continue  # markers, header comments, module sub-markers
        try:
            entry = json.loads(line)
        except json.JSONDecodeError:
            continue
        if entry.get("type") != "locked":
            continue
        path = entry.get("file")
        if path:
            entry["file"] = resolve_lock_path(path, report_dir, repo_root)
        locks.append(entry)
    return locks


def load_locks(report_paths, repo_root):
    """Returns a list of lock dicts with a repo-relative 'file' path."""
    locks = []
    for report in report_paths:
        report_dir = os.path.dirname(os.path.abspath(report))
        with open(report, encoding="utf-8") as fh:
            locks.extend(parse_lock_entries(fh.read(), report_dir, repo_root))
    return locks


def lock_key(lock):
    """Identity of a lock across two revisions: which file, which element."""
    return (lock.get("file"), lock.get("element"))


def lock_entries_at(ref, report_paths, repo_root):
    """The lock entries already declared at ``ref``, read from the same reports through git.

    A report that did not exist at the base revision contributes nothing rather than raising.
    """
    locks = []
    for report in report_paths:
        abs_report = os.path.abspath(report)
        rel = os.path.relpath(abs_report, repo_root).replace(chr(92), "/")
        text = git_show_text(ref, rel)
        if text is None:
            continue  # no such report at the base revision
        locks.extend(parse_lock_entries(text, os.path.dirname(abs_report), repo_root))
    return locks


def locks_at(ref, report_paths, repo_root):
    """The lock keys already declared at ``ref``.

    A lock absent here is one this diff introduces, and the author of a lock is not violating it.
    """
    return {lock_key(lock) for lock in lock_entries_at(ref, report_paths, repo_root)}


def locks_for(locks, diff_path):
    """Locks whose file is this diff path.

    Compared exactly. This used to fall back to matching either path as a suffix of the other,
    to paper over absolute-vs-relative prefixes; ``resolve_lock_path`` now makes both sides
    repo-relative, and the suffix fallback actively did harm: any two modules sharing a
    relative path aliased each other's locks.
    """
    diff_path = diff_path.replace(chr(92), "/")
    return [lock for lock in locks if lock.get("file") == diff_path]


def parse_raw_entries(data):
    """Changed files from ``git diff --raw -z``: (status, old_mode, new_mode, old, new).

    ``-z`` prints every path verbatim and NUL-terminated. The patch headers this guard used to
    read quote a path holding a non-ASCII byte or a control character, and end one holding a
    space with a tab, so the path no longer ended in ``.java`` and the file skipped every
    source check. ``old`` is None for an addition and ``new`` for a deletion. Raises
    ValueError on a record it cannot read; the caller fails the guard.
    """
    nul = bytes([0])
    fields = data.split(nul)
    if fields and fields[-1] == b"":
        fields.pop()
    entries, i = [], 0
    while i < len(fields):
        meta = fields[i]
        parts = meta.split(b" ")
        if not meta.startswith(b":") or len(parts) != 5:
            raise ValueError(f"unexpected raw diff record {meta[:80]!r}")
        old_mode, new_mode = parts[0][1:].decode("ascii"), parts[1].decode("ascii")
        status = parts[4].decode("ascii")[:1]
        count = 2 if status in ("R", "C") else 1
        if i + count >= len(fields):
            raise ValueError(f"truncated raw diff record {meta[:80]!r}")
        paths = [os.fsdecode(field) for field in fields[i + 1:i + 1 + count]]
        if not all(paths):
            raise ValueError(f"empty path in raw diff record {meta[:80]!r}")
        i += 1 + count
        if count == 2:
            old, new = paths
        elif status == "A":
            old, new = None, paths[0]
        elif status == "D":
            old, new = paths[0], None
        else:
            old = new = paths[0]
        entries.append((status, old_mode, new_mode, old, new))
    return entries


def parse_patch_sections(diff_text):
    """Yields (old_hunks, new_hunks, removed_lines) per ``diff --git`` section.

    Each hunk is (start, count) on its side of the diff. removed_lines is a list of (base line
    number, text), numbered from the hunk's old side so a removed line can be looked up in the
    base blob. Paths are not read here: they come from ``parse_raw_entries``.

    Lines are split on newline alone, as git counts them: ``str.splitlines`` also breaks on a
    carriage return or form feed inside a line, which would shift every later number. Nothing
    before a section's first hunk is content, so a removed line whose own text starts with
    "-- " is a removal rather than a "--- " header.
    """
    section, in_hunk, old_line = None, False, 0
    for line in diff_text.split("\n"):
        if line.startswith("diff --git "):
            if section is not None:
                yield section
            section, in_hunk = ([], [], []), False
        elif section is None:
            continue
        elif line.startswith("@@"):
            m = HUNK_RE.match(line)
            if not m:
                raise ValueError(f"unreadable hunk header {line[:80]!r}")
            in_hunk, old_line = True, int(m.group(1))
            section[0].append((old_line, int(m.group(2)) if m.group(2) is not None else 1))
            section[1].append((int(m.group(3)), int(m.group(4)) if m.group(4) is not None else 1))
        elif not in_hunk:
            continue
        elif line.startswith("-"):
            section[2].append((old_line, line[1:]))
            old_line += 1
        elif line.startswith(" "):
            old_line += 1  # context line; --unified=0 emits none, but count it if present
    if section is not None:
        yield section


def annotation_message(text):
    """A workflow-command message: a newline in a file name or a lock reason cannot start one."""
    return text.replace("%", "%25").replace(chr(13), "%0D").replace(chr(10), "%0A")


def annotation_property(text):
    """A workflow-command property value, which additionally may not hold ':' or ','."""
    return annotation_message(text).replace(":", "%3A").replace(",", "%2C")


def touches(start, end, hunk_start, hunk_count):
    """Whether a hunk (start, count) touches lines start..end on the same side of the diff."""
    if hunk_count == 0:
        return start - 1 <= hunk_start <= end  # pure deletion or insertion at this position
    return hunk_start <= end and (hunk_start + hunk_count - 1) >= start


def range_violations(lock, path, hunks, where=""):
    start, end = lock.get("startLine"), lock.get("endLine")
    element, reason = lock.get("element", "?"), lock.get("reason", "")
    if start is None or end is None:
        # No positions (non-javac compiler): file-level fallback.
        yield (path, None, f"Change touches a file containing locked element {element} "
                           f"(no line info available). Reason: {reason}")
        return
    for hunk_start, hunk_count in hunks:
        if touches(start, end, hunk_start, hunk_count):
            yield (path, max(hunk_start, 1), f"Change touches @AILocked element {element} "
                                              f"(lines {start}-{end}{where}). Reason: {reason}")
            return


GITLINK_MODE = "160000"
CHECKED_STATUSES = ("A", "C", "D", "M", "R", "T")


def entry_violations(entry, merge_base, head_locks, base_locks, established):
    """Violations for one changed file, as (path, line or None, message) triples."""
    status, old_mode, new_mode, old, new = entry
    paths = list(dict.fromkeys(p for p in (old, new) if p))
    if status not in CHECKED_STATUSES:
        yield (paths[0], None, f"Unrecognised diff status {status!r}; failing closed")
        return
    if all(p.endswith(".vibetags-locks") for p in paths):
        return  # report regeneration is expected, not a violation

    if GITLINK_MODE in (old_mode, new_mode):
        # A submodule's own files never appear in this diff, so a lock inside one cannot be
        # range-checked: moving the pointer is treated as touching every lock beneath it.
        for path in paths:
            inside = [lock for lock in head_locks + base_locks
                      if (lock.get("file") or "").startswith(path.rstrip("/") + "/")]
            if inside:
                yield (path, None, f"Submodule holding locked element "
                                   f"{inside[0].get('element', '?')} changed; its code cannot "
                                   "be checked here, so this needs human review")
                return
        return

    # A file this diff CREATES (or copies into place) is exempt: the lock did not exist at the
    # base, so nobody can have violated it, and flagging it means a PR may never introduce an
    # @AILocked element. That blocked adding guardrails to the very codebase that ships them. A
    # copy leaves its source in place, and any edit to that source is its own entry.
    if status in ("A", "C"):
        return

    base_here = locks_for(base_locks, old)
    extension_changed = new is not None and os.path.splitext(old)[1] != os.path.splitext(new)[1]
    if status in ("D", "T") or (status == "R" and extension_changed):
        # Deleted, or renamed or retyped away from what it was: whatever the file becomes, the
        # source that held the lock is gone, so its base content is checked as for a deletion.
        what = "Deleted file" if status == "D" else f"File moved away from {old}"
        held = None
        if is_lock_carrying_source(old):
            base_text = git_show_text(merge_base, old)
            if base_text is None:
                yield (old, None, "Cannot read the base revision of a removed source file; "
                                  "failing closed")
                return
            if holds_a_lock(old, base_text):
                held = f"{what} contained @AILocked code"
        if held is None and base_here:
            held = f"{what} held locked element {base_here[0].get('element', '?')}"
        if held is not None:
            yield (old, None, held)
            return
        if status != "R":
            return

    head_here = locks_for(head_locks, new)
    source = is_lock_carrying_source(old) or is_lock_carrying_source(new)
    if not (source or head_here or base_here):
        return
    # One file at a time, named by literal pathspecs, so no path is ever read back out of a
    # patch header. --text keeps a file git would call binary from hiding its hunks.
    patch = run_git_exact(
        "--literal-pathspecs", "diff", "--unified=0", "--no-color", "--text", "--no-ext-diff",
        "--no-textconv", "--find-renames", "--no-relative", merge_base, "HEAD", "--", *paths)
    try:
        sections = list(parse_patch_sections(patch))
    except ValueError as err:
        sections = [err]
    if len(sections) != 1 or isinstance(sections[0], ValueError):
        yield (new, None, f"Cannot map this file's diff ({len(sections)} sections); failing closed")
        return
    old_hunks, new_hunks, removed = sections[0]

    # 2. Lock stripping: the @AILocked annotation itself was removed from source. Read on the
    # base side, because a stripped lock is absent from the regenerated report.
    if source and removed:
        base_text = git_show_text(merge_base, old)
        if strips_a_lock(old, base_text, removed):
            yield (new, None, "A line containing @AILocked was removed -- "
                              "removing a lock requires explicit human review")

    # 1. Changed lines intersect a locked range at HEAD. A lock absent from the base report is
    # one this diff introduces and is exempt: adding @AILocked to existing code is itself a
    # change to the lines it now covers, so without this every PR that adopts a lock fails on
    # the commit that introduces it. Measured: the PR that locked GuardrailAnnotations.ALL and
    # TransitiveManifest.RESOURCE_PACKAGE drew one violation each for doing so. A lock that
    # moved with its file counts as established under its old path.
    for lock in head_here:
        element = lock.get("element")
        if lock_key(lock) in established or (old, element) in established:
            yield from range_violations(lock, new, new_hunks)

    # 1b. A renamed file is also checked against the base report's ranges on the old side,
    # which catch an edit however the element or its path was renamed alongside it.
    if old != new:
        for lock in base_here:
            yield from range_violations(lock, old, old_hunks, " at the base revision")


def main():
    base_ref = os.environ.get("VIBETAGS_BASE_REF", "").strip()
    warn_only = os.environ.get("VIBETAGS_WARN_ONLY", "false").strip().lower() == "true"
    if not base_ref:
        raise SystemExit("VIBETAGS_BASE_REF is not set -- pass the PR base ref/SHA")
    # Option-injection guard: refs/SHAs never start with '-'. Reject so an attacker-influenced
    # base ref cannot be reinterpreted as a git option by `git merge-base`.
    if base_ref.startswith("-"):
        raise SystemExit("VIBETAGS_BASE_REF must not start with '-'")

    repo_root = run_git("rev-parse", "--show-toplevel").strip()
    merge_base = run_git("merge-base", base_ref, "HEAD").strip()
    kind = "warning" if warn_only else "error"

    reports = find_reports(os.getcwd())
    if not reports:
        # A guard that found nothing to guard has not passed; it has not run. The report is
        # opted in by committing .vibetags-locks, so its absence here means the action runs in
        # the wrong working-directory or the project never opted in -- either way the check
        # would be green while guarding nothing.
        print(f"::{kind}::VibeTags locked-files guard: no .vibetags-locks report found under "
              f"{annotation_message(os.getcwd())} -- commit an empty .vibetags-locks at the "
              "project root to opt in, and point working-directory at that root")
        return 0 if warn_only else 1
    locks = load_locks(reports, repo_root)
    print(f"VibeTags locked-files guard: {len(locks)} locked element(s) "
          f"from {len(reports)} report(s); diffing against {merge_base[:12]}")

    # Trailing "--" terminates options/refs so no value can be reinterpreted as a pathspec/flag.
    try:
        entries = parse_raw_entries(run_git_bytes(
            "diff", "--raw", "-z", "--no-abbrev", "--find-renames", "--no-ext-diff",
            "--no-relative", merge_base, "HEAD", "--"))
    except ValueError as err:
        message = f"VibeTags locked-files guard: cannot read the diff ({err}); failing closed"
        print(f"::{kind}::{annotation_message(message)}")
        return 0 if warn_only else 1
    base_locks = lock_entries_at(merge_base, reports, repo_root)
    established = {lock_key(lock) for lock in base_locks}
    violations = 0

    for entry in entries:
        for path, line, message in entry_violations(entry, merge_base, locks, base_locks,
                                                    established):
            violations += 1
            where = f"file={annotation_property(path)}"
            if line is not None:
                where += f",line={line}"
            print(f"::{kind} {where}::{annotation_message(message)}")

    if violations:
        verdict = "warning(s)" if warn_only else "violation(s)"
        print(f"\nVibeTags locked-files guard: {violations} {verdict} found.")
        return 0 if warn_only else 1
    print("\nVibeTags locked-files guard: no locked code touched.")
    return 0

if __name__ == "__main__":
    sys.exit(main())
