#!/usr/bin/env python3
"""Fail a PR when its diff touches code protected by @AILocked.

Reads every ``.vibetags-locks`` report under the working directory (JSON Lines
between ``# VIBETAGS`` hash markers, regenerated by the build step that runs
before this script), parses ``git diff`` against the merge base, and reports a
violation when:

  1. a changed line range intersects a locked element's line range,
  2. a removed line in a source file contains the ``@AILocked`` annotation itself
     (lock stripping; scoped to source files because generated guardrail files and
     docs merely *mention* the annotation and reflow on every regeneration),
  3. a deleted source file contained ``@AILocked`` at the base revision.

Environment:
  VIBETAGS_BASE_REF    ref/SHA to diff against (required)
  VIBETAGS_WARN_ONLY   'true' to emit warnings instead of failing (default 'false')

Exit code 1 on violations unless warn-only.
"""

import json
import os
import re
import subprocess
import sys

HUNK_RE = re.compile(r"^@@ -(\d+)(?:,(\d+))? \+(\d+)(?:,(\d+))? @@")

# Files that can carry @AILocked as an annotation on code. The lock-stripping and
# deleted-file checks are scoped to these: generated guardrail files and docs legitimately
# *mention* @AILocked, and regenerating them reflows those lines on every unrelated change.
# The first PR this guard ever ran on was flagged for exactly that (its own dogfooding PR,
# which reflowed generated Markdown), while a real stripped lock lives in a source file --
# and must stay a string check on the base side, because a stripped lock is absent from the
# regenerated report and so invisible to any report-based check.
SOURCE_EXTS = (".java", ".kt", ".kts", ".groovy")


def is_lock_carrying_source(path):
    return path is not None and path.endswith(SOURCE_EXTS)


def run_git(*args):
    result = subprocess.run(
        ["git", *args], capture_output=True, text=True, encoding="utf-8", errors="replace"
    )
    if result.returncode != 0:
        sys.stderr.write(result.stderr)
        raise SystemExit(f"git {' '.join(args)} failed with exit code {result.returncode}")
    return result.stdout


def find_reports(root):
    reports = []
    for dirpath, dirnames, filenames in os.walk(root):
        dirnames[:] = [d for d in dirnames if d not in (".git", "node_modules", "target", "build")]
        if ".vibetags-locks" in filenames:
            reports.append(os.path.join(dirpath, ".vibetags-locks"))
    return reports


def resolve_lock_path(recorded, report_dir, repo_root):
    """A lock's repo-relative path, resolved against the report that declared it.

    A ``.vibetags-locks`` records paths relative to its own VibeTags root, not to the
    repository. Normalizing against the repository root alone therefore leaves two reactors
    that both have a module at, say, ``showcase/src/main/java/...`` recording the identical
    string, and nothing downstream can tell them apart. Measured before this was fixed: a
    Gradle example's new files drew nine violations from the *Maven* example's report.

    Absolute paths are made repo-relative directly; anything outside the repository is left
    as it is, so it simply matches nothing.
    """
    path = recorded.replace("\\", "/")
    if os.path.isabs(path):
        rel = os.path.relpath(path, repo_root).replace("\\", "/")
        return path if rel.startswith("..") else rel
    report_rel = os.path.relpath(report_dir, repo_root).replace("\\", "/")
    if report_rel in ("", "."):
        return os.path.normpath(path).replace("\\", "/")
    return os.path.normpath(report_rel + "/" + path).replace("\\", "/")


def parse_lock_entries(text, report_dir, repo_root):
    """The 'locked' entries in one report's text, each with a repo-relative 'file'."""
    locks = []
    for line in text.splitlines():
        line = line.strip()
        if not line or line.startswith("#"):
            continue  # markers, header comments, module sub-markers
        try:
            entry = json.loads(line)
        except json.JSONDecodeError:
            continue
        if entry.get("type") != "locked":
            continue
        path = entry.get("file")
        if path:
            entry["file"] = resolve_lock_path(path, report_dir, repo_root)
        locks.append(entry)
    return locks


def load_locks(report_paths, repo_root):
    """Returns a list of lock dicts with a repo-relative 'file' path."""
    locks = []
    for report in report_paths:
        report_dir = os.path.dirname(os.path.abspath(report))
        with open(report, encoding="utf-8") as fh:
            locks.extend(parse_lock_entries(fh.read(), report_dir, repo_root))
    return locks


def lock_key(lock):
    """Identity of a lock across two revisions: which file, which element."""
    return (lock.get("file"), lock.get("element"))


def locks_at(ref, report_paths, repo_root):
    """The lock keys already declared at ``ref``.

    Read from the same reports through ``git show``, so a report that did not exist at the
    base contributes nothing rather than raising. A lock absent here is one this diff
    introduces, and the author of a lock is not violating it.
    """
    keys = set()
    for report in report_paths:
        abs_report = os.path.abspath(report)
        rel = os.path.relpath(abs_report, repo_root).replace("\\", "/")
        blob = subprocess.run(
            ["git", "show", f"{ref}:{rel}"],
            capture_output=True, text=True, encoding="utf-8", errors="replace",
        )
        if blob.returncode != 0:
            continue  # no such report at the base revision
        for lock in parse_lock_entries(blob.stdout, os.path.dirname(abs_report), repo_root):
            keys.add(lock_key(lock))
    return keys


def added_paths(name_status_text):
    """Paths the diff CREATES, from ``git diff --name-status``.

    A file that did not exist at the base cannot have had its locked code touched: the author
    of the diff is the one declaring the lock. Renames are status R and stay in scope, so
    moving a locked file is still checked.
    """
    added = set()
    for line in name_status_text.splitlines():
        parts = line.split("\t")
        if len(parts) >= 2 and parts[0].strip() == "A":
            added.add(parts[1].strip().replace("\\", "/"))
    return added


def locks_for(locks, diff_path):
    """Locks whose file is this diff path.

    Compared exactly. This used to fall back to matching either path as a suffix of the other,
    to paper over absolute-vs-relative prefixes; ``resolve_lock_path`` now makes both sides
    repo-relative, and the suffix fallback actively did harm: any two modules sharing a
    relative path aliased each other's locks.
    """
    diff_path = diff_path.replace("\\", "/")
    return [lock for lock in locks if lock.get("file") == diff_path]


def parse_diff(diff_text):
    """Yields (path, old_path, hunks, removed_lines) per changed file.

    path is None for deleted files; each hunk is (new_start, new_count).
    removed_lines is the list of '-' line bodies across all hunks of the file.
    """
    path = old_path = None
    hunks, removed = [], []
    for line in diff_text.splitlines():
        if line.startswith("diff --git "):
            if old_path is not None or path is not None:
                yield path, old_path, hunks, removed
            path = old_path = None
            hunks, removed = [], []
        elif line.startswith("--- "):
            target = line[4:]
            old_path = None if target == "/dev/null" else target[2:]  # strip "a/"
        elif line.startswith("+++ "):
            target = line[4:]
            path = None if target == "/dev/null" else target[2:]  # strip "b/"
        elif line.startswith("@@"):
            m = HUNK_RE.match(line)
            if m:
                new_start = int(m.group(3))
                new_count = int(m.group(4)) if m.group(4) is not None else 1
                hunks.append((new_start, new_count))
        elif line.startswith("-") and not line.startswith("---"):
            removed.append(line[1:])
    if old_path is not None or path is not None:
        yield path, old_path, hunks, removed


def main():
    base_ref = os.environ.get("VIBETAGS_BASE_REF", "").strip()
    warn_only = os.environ.get("VIBETAGS_WARN_ONLY", "false").strip().lower() == "true"
    if not base_ref:
        raise SystemExit("VIBETAGS_BASE_REF is not set -- pass the PR base ref/SHA")
    # Option-injection guard: refs/SHAs never start with '-'. Reject so an attacker-influenced
    # base ref cannot be reinterpreted as a git option by `git merge-base`.
    if base_ref.startswith("-"):
        raise SystemExit("VIBETAGS_BASE_REF must not start with '-'")

    repo_root = run_git("rev-parse", "--show-toplevel").strip()
    merge_base = run_git("merge-base", base_ref, "HEAD").strip()

    reports = find_reports(os.getcwd())
    if not reports:
        print("::warning::VibeTags locked-files guard: no .vibetags-locks report found -- "
              "did the build step run with the file touched?")
        return 0
    locks = load_locks(reports, repo_root)
    print(f"VibeTags locked-files guard: {len(locks)} locked element(s) "
          f"from {len(reports)} report(s); diffing against {merge_base[:12]}")

    # Trailing "--" terminates options/refs so no value can be reinterpreted as a pathspec/flag.
    diff_text = run_git("diff", "--unified=0", "--no-color", merge_base, "HEAD", "--")
    created = added_paths(
        run_git("diff", "--name-status", "--no-color", merge_base, "HEAD", "--")
    )
    established = locks_at(merge_base, reports, repo_root)
    kind = "warning" if warn_only else "error"
    violations = 0

    for path, old_path, hunks, removed_lines in parse_diff(diff_text):
        display = path or old_path or "?"
        if display.endswith(".vibetags-locks"):
            continue  # report regeneration is expected, not a violation

        # 3. Deleted source file that contained @AILocked at base.
        if path is None and old_path is not None:
            if is_lock_carrying_source(old_path):
                base_blob = subprocess.run(
                    ["git", "show", f"{merge_base}:{old_path}"],
                    capture_output=True, text=True, encoding="utf-8", errors="replace",
                )
                if base_blob.returncode == 0 and "@AILocked" in base_blob.stdout:
                    violations += 1
                    print(f"::{kind} file={old_path}::Deleted file contained @AILocked code")
            continue

        # 2. Lock stripping: the @AILocked annotation itself was removed from source.
        if is_lock_carrying_source(display) and any(
            "@AILocked" in line for line in removed_lines
        ):
            violations += 1
            print(f"::{kind} file={display}::A line containing @AILocked was removed -- "
                  "removing a lock requires explicit human review")

        # 1. Changed lines intersect a locked range at HEAD. Files this diff CREATES are
        # exempt: the lock did not exist at the base, so nobody can have violated it, and
        # flagging it means a PR may never introduce an @AILocked element. That blocked adding
        # guardrails to the very codebase that ships them. A later PR editing the now-locked
        # file is a rename or a modification, not an addition, and is still checked.
        if display in created:
            continue
        for lock in locks_for(locks, display):
            # The same exemption as `created` above, at element granularity rather than file.
            # Adding @AILocked to existing code is itself a change to the lines it now covers,
            # so without this every PR that adopts a lock fails on the commit that introduces
            # it -- and the file-level exemption does not help, because the file already
            # existed. Measured: the PR that locked GuardrailAnnotations.ALL and
            # TransitiveManifest.RESOURCE_PACKAGE drew one violation each for doing so.
            # Stripping a lock stays a violation; that is check 2, which reads the base side.
            if lock_key(lock) not in established:
                continue
            start, end = lock.get("startLine"), lock.get("endLine")
            element = lock.get("element", "?")
            reason = lock.get("reason", "")
            if start is None or end is None:
                # No positions (non-javac compiler): file-level fallback.
                violations += 1
                print(f"::{kind} file={display}::Change touches a file containing locked "
                      f"element {element} (no line info available). Reason: {reason}")
                continue
            for new_start, new_count in hunks:
                if new_count == 0:
                    touched = start - 1 <= new_start <= end  # pure deletion at this position
                else:
                    touched = new_start <= end and (new_start + new_count - 1) >= start
                if touched:
                    violations += 1
                    print(f"::{kind} file={display},line={max(new_start, 1)}::Change touches "
                          f"@AILocked element {element} (lines {start}-{end}). Reason: {reason}")
                    break

    if violations:
        verdict = "warning(s)" if warn_only else "violation(s)"
        print(f"\nVibeTags locked-files guard: {violations} {verdict} found.")
        return 0 if warn_only else 1
    print("\nVibeTags locked-files guard: no locked code touched.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
