#!/usr/bin/env python3
"""Fail a PR when its diff touches code protected by @AILocked.

Reads every ``.vibetags-locks`` report under the working directory (JSON Lines
between ``# VIBETAGS`` hash markers, regenerated by the build step that runs
before this script), lists the changed files against the merge base with
``git diff --raw -z``, and reports a violation when:

  1. a changed line range intersects a locked element's line range (for a renamed file,
     also the base report's range on the old side),
  2. a removed line in a source file contains the ``@AILocked`` annotation itself
     (lock stripping; scoped to source files because generated guardrail files and
     docs merely *mention* the annotation and reflow on every regeneration),
  3. a deleted source file contained ``@AILocked`` at the base revision; a source renamed
     to another extension, or changed into another file type, counts as deleted,
  4. a submodule that holds a locked element changes.

Checks 2 and 3 read the base revision. A Java, Kotlin or Groovy source is lexed there, so
``@AILocked`` text inside a string literal, text block, char literal or comment is not an
annotation (#708, #709). A source that does not lex keeps the plain substring match, which errs
toward failing; a Groovy source does not lex wherever a slashy string could start. A Kotlin or
Groovy source also counts the aliases that sources elsewhere at the base declare for the lock, a
``typealias`` or an ``@AnnotationCollector`` (#716); while a source that may declare one does not
lex, every annotation in that language counts. So does
anything else the guard cannot read: an unknown diff status, an unparseable record, or a file
whose diff does not map to one section.

Environment:
  VIBETAGS_BASE_REF    ref/SHA to diff against (required)
  VIBETAGS_WARN_ONLY   'true' to emit warnings instead of failing (default 'false')

Exit code 1 on violations unless warn-only.
"""

import json
import os
import re
import subprocess
import sys
import unicodedata

HUNK_RE = re.compile(r"^@@ -(\d+)(?:,(\d+))? \+(\d+)(?:,(\d+))? @@")

# Files that can carry @AILocked as an annotation on code. The lock-stripping and
# deleted-file checks are scoped to these: generated guardrail files and docs legitimately
# *mention* @AILocked, and regenerating them reflows those lines on every unrelated change.
# The first PR this guard ever ran on was flagged for exactly that (its own dogfooding PR,
# which reflowed generated Markdown), while a real stripped lock lives in a source file --
# and must stay a check of the base side's source, because a stripped lock is absent from the
# regenerated report and so invisible to any report-based check. A base-side report would not
# do either: a consumer's committed report can be stale, and a source cannot.
SOURCE_EXTS = (".java", ".kt", ".kts", ".groovy")
LOCK_NAME = "AILocked"
COLLECTOR_NAME = "AnnotationCollector"


def is_lock_carrying_source(path):
    return path is not None and path.endswith(SOURCE_EXTS)


class _Unlexable(Exception):
    """The source is not well-formed enough to say where its literals and comments are."""


def _translate_unicode_escapes(text):
    """``(char, line)`` pairs after javac's unicode-escape translation (JLS 3.3).

    javac translates ``\\uXXXX`` before it lexes anything, so ``"\\u0022`` is an empty string
    rather than a string still open. Skipping the step would let an escaped quote make a real
    annotation look quoted. ``line`` is 1-based and counts ``\\n`` only, as git does, so it
    lines up with diff hunk numbers even in a file with lone carriage returns.
    """
    out = []
    i, n, line, backslashes = 0, len(text), 1, 0
    while i < n:
        ch = text[i]
        if ch == "\\" and backslashes % 2 == 0 and text.startswith("u", i + 1):
            j = i + 1
            while j < n and text[j] == "u":
                j += 1
            digits = text[j:j + 4]
            if len(digits) != 4 or any(d not in "0123456789abcdefABCDEF" for d in digits):
                raise _Unlexable()  # javac rejects a malformed unicode escape
            out.append((chr(int(digits, 16)), line))
            i, backslashes = j + 4, 0  # a translated backslash starts no further escape
            continue
        backslashes = backslashes + 1 if ch == "\\" else 0
        out.append((ch, line))
        if ch == "\n":
            line += 1
        i += 1
    return out


def java_annotation_lines(text, name="AILocked"):
    """The lines (1-based, as git numbers them) holding a real ``@name`` annotation, or None.

    Text inside a string literal, text block, char literal or comment is not an annotation,
    however it reads: #708 was a test-only pull request failed for editing Java fixture source
    held in string literals. The name may be spaced from the ``@``, qualified, or split by
    comments, as javac allows; every line from the ``@`` to the simple name counts.

    None means the source did not lex (an unterminated literal or comment, a malformed unicode
    escape, a text block with no line break after its opening quotes), so code cannot be told
    from text. Callers then fall back to the plain substring match, which errs toward failing.
    """
    try:
        return _scan_java(_translate_unicode_escapes(text), name)
    except _Unlexable:
        return None


def _java_ignorable(ch):
    """``Character.isIdentifierIgnorable``: part of an identifier, but not of its name.

    javac compares identifiers with these removed, so ``AI<soft hyphen>Locked`` names the lock.
    """
    code = ord(ch)
    return (code <= 0x08 or 0x0E <= code <= 0x1B or 0x7F <= code <= 0x9F
            or unicodedata.category(ch) == "Cf")


def _java_identifier_part(ch):
    """``Character.isJavaIdentifierPart``, plus the other-number characters ``str.isalnum``
    accepts (superscripts, fractions). javac rejects those outright, so no source that
    compiles is read differently.
    """
    return (ch.isalnum() or ch in "_$" or _java_ignorable(ch)
            or unicodedata.category(ch) in ("Mn", "Mc", "Pc", "Sc", "Nl"))


def _scan_java(chars, name):
    n = len(chars)

    def at(k):
        return chars[k][0] if k < n else ""

    def is_ident(k):
        return k < n and _java_identifier_part(chars[k][0])

    def skip_comment(k):
        """The index after a comment starting at k, or k itself when none starts there."""
        if at(k) == "/" and at(k + 1) == "/":
            while k < n and chars[k][0] not in "\r\n":
                k += 1
            return k
        if at(k) == "/" and at(k + 1) == "*":
            k += 2
            while k < n and not (chars[k][0] == "*" and at(k + 1) == "/"):
                k += 1
            if k >= n:
                raise _Unlexable()
            return k + 2
        return k

    def skip_trivia(k):
        while True:
            while k < n and chars[k][0].isspace():
                k += 1
            after = skip_comment(k)
            if after == k:
                return k
            k = after

    def skip_quoted(k, quote):
        """The index after a string or char literal opening at k."""
        k += 1
        while k < n:
            ch = chars[k][0]
            if ch == "\\":
                if k + 1 >= n or chars[k + 1][0] in "\r\n":
                    raise _Unlexable()
                k += 2
            elif ch == quote:
                return k + 1
            elif ch in "\r\n":
                raise _Unlexable()
            else:
                k += 1
        raise _Unlexable()

    def skip_text_block(k):
        """The index after a text block whose opening quotes start at k."""
        k += 3
        while k < n and chars[k][0] in " \t\f":
            k += 1
        if k >= n or chars[k][0] not in "\r\n":
            raise _Unlexable()
        while k < n:
            if chars[k][0] == "\\":
                k += 2
            elif chars[k][0] == '"' and at(k + 1) == '"' and at(k + 2) == '"':
                return k + 3
            else:
                k += 1
        raise _Unlexable()

    lines = set()
    i = 0
    while i < n:
        ch = chars[i][0]
        after = skip_comment(i)
        if after != i:
            i = after
        elif ch == '"':
            text_block = at(i + 1) == '"' and at(i + 2) == '"'
            i = skip_text_block(i) if text_block else skip_quoted(i, '"')
        elif ch == "'":
            i = skip_quoted(i, "'")
        elif ch == "@":
            k, simple_name, name_end = skip_trivia(i + 1), "", i + 1
            while is_ident(k):
                start = k
                while is_ident(k):
                    k += 1
                simple_name = "".join(c for c, _ in chars[start:k] if not _java_ignorable(c))
                name_end = k
                dot = skip_trivia(k)
                if at(dot) != ".":
                    break
                k = skip_trivia(dot + 1)
            if simple_name == name:
                lines.update(range(chars[i][1], chars[name_end - 1][1] + 1))
            i += 1
        else:
            i += 1
    return lines


def kotlin_annotation_lines(text, name=LOCK_NAME, aliases=(), any_annotation=False):
    """The lines holding a real ``@name`` annotation in a Kotlin source, or None when unsure.

    Kotlin nests code inside strings: ``"${ ... }"`` and ``\"\"\"${ ... }\"\"\"`` hold arbitrary
    expressions, including further strings, comments and annotated declarations, and block
    comments nest. A lexer that lost track of either could read a real annotation as text and
    pass its removal, so every construct it does not model makes it give up instead: an
    unterminated or unbalanced literal, comment, template or brace, a ``$`` in code (the
    multi-dollar ``$$"..."`` prefix changes what a template is), a ``$`` before a backtick in a
    string, a raw string closed by more than three quotes, a backslash in code, a lone carriage
    return. None sends the caller back to the substring match, which errs toward failing.

    ``aliases`` are further names for the lock, declared in other files (#716);
    ``any_annotation`` counts every annotation, for when such a declaration could not be read.
    """
    try:
        return _script_annotation_lines(_lex_script(text, kotlin=True), {name, *aliases},
                                        any_annotation)
    except _Unlexable:
        return None


def groovy_annotation_lines(text, name=LOCK_NAME, aliases=(), any_annotation=False):
    """The lines holding a real ``@name`` annotation in a Groovy source, or None when unsure.

    Groovy's quoted strings (``'``, ``"``, ``'''``, ``\"\"\"``) and comments are lexed, with
    ``${ ... }`` templates in the double-quoted forms. A slashy string (``/.../``, ``$/.../$``)
    cannot be told from a division without parsing expressions, and one holding a quote would
    make a real annotation look quoted, so a ``/`` in code that does not start a comment makes
    the whole file unsure. So does any unicode escape (Groovy may translate one before lexing,
    as javac does), a ``$`` in a template string that starts neither a name nor ``${``, and
    anything the Kotlin lexer also gives up on. ``aliases`` and ``any_annotation`` are as for
    ``kotlin_annotation_lines``.
    """
    try:
        return _script_annotation_lines(_lex_script(text, kotlin=False), {name, *aliases},
                                        any_annotation)
    except _Unlexable:
        return None


def _lex_script(text, kotlin):
    """Kotlin or Groovy code tokens, ``(kind, value, line)``, with strings and comments removed.

    ``kind`` is "ident" (``value`` is the name, identifier-ignorable characters removed),
    "punct" (one character) or "string" (one token per literal, so tokens on either side of a
    literal never look adjacent). Code inside a string template is tokenized as code. ``line``
    is 1-based and counts ``\\n`` only, as git does.
    """
    if "\r" in text.replace("\r\n", ""):
        raise _Unlexable()  # a lone CR: the languages disagree with git about where a line ends
    if not kotlin and "\\u" in text:
        raise _Unlexable()
    chars, line = [], 1
    for ch in text:
        chars.append((ch, line))
        if ch == "\n":
            line += 1
    n = len(chars)

    def at(k):
        return chars[k][0] if k < n else ""

    def name_part(ch):
        """A Java identifier character; Kotlin names hold no ``$``, Groovy names may."""
        return _java_identifier_part(ch) and not (kotlin and ch == "$")

    tokens = []
    # Each frame is [mode, braces, quote, triple]: mode "code" (braces counts the "{" still open
    # in it) or "string". The bottom frame is the file; a code frame above it is a ${ } template.
    stack = [["code", 0, None, False]]
    i = 0
    if at(0) == "#" and at(1) == "!":
        while i < n and chars[i][0] != "\n":
            i += 1
    while i < n:
        frame = stack[-1]
        ch, line = chars[i]
        if frame[0] == "string":
            quote, triple = frame[2], frame[3]
            templates = kotlin or quote == '"'
            if ch == "\\" and not (kotlin and triple):
                if i + 1 >= n or (chars[i + 1][0] == "\n" and not triple):
                    raise _Unlexable()
                i += 2
            elif ch == quote:
                if not triple:
                    stack.pop()
                    i += 1
                    continue
                run = 0
                while at(i + run) == quote:
                    run += 1
                if run > 3:
                    raise _Unlexable()  # which three quotes close the string differs by language
                if run == 3:
                    stack.pop()
                i += run
            elif ch == "\n" and not triple:
                raise _Unlexable()
            elif ch == "$" and templates:
                nxt = at(i + 1)
                if nxt == "{":
                    stack.append(["code", 0, None, False])
                    i += 2
                elif kotlin and nxt == "`":
                    raise _Unlexable()
                elif not kotlin and not (nxt.isalpha() or nxt in "_$"):
                    raise _Unlexable()
                else:
                    i += 1
            else:
                i += 1
            continue

        if ch == "/" and at(i + 1) == "/":
            while i < n and chars[i][0] != "\n":
                i += 1
        elif ch == "/" and at(i + 1) == "*":
            depth, i = 1, i + 2
            while depth:
                if i >= n:
                    raise _Unlexable()
                if chars[i][0] == "*" and at(i + 1) == "/":
                    depth, i = depth - 1, i + 2
                elif kotlin and chars[i][0] == "/" and at(i + 1) == "*":
                    depth, i = depth + 1, i + 2
                else:
                    i += 1
        elif ch == "/" and not kotlin:
            raise _Unlexable()  # a slashy string may start here
        elif ch == '"' or (ch == "'" and not kotlin):
            triple = at(i + 1) == ch and at(i + 2) == ch
            if triple and at(i + 3) == ch:
                raise _Unlexable()  # four quotes open differently in the two languages
            stack.append(["string", 0, ch, triple])
            tokens.append(("string", None, line))
            i += 3 if triple else 1
        elif ch == "'":
            i += 1
            while at(i) != "'":
                if i >= n or chars[i][0] == "\n":
                    raise _Unlexable()
                if chars[i][0] == "\\":
                    if i + 1 >= n or chars[i + 1][0] == "\n":
                        raise _Unlexable()
                    i += 1
                i += 1
            tokens.append(("string", None, line))
            i += 1
        elif ch == "`":
            if not kotlin:
                raise _Unlexable()
            end = i + 1
            while end < n and chars[end][0] not in "`\n":
                end += 1
            if at(end) != "`" or end == i + 1:
                raise _Unlexable()
            value = "".join(c for c, _ in chars[i + 1:end] if not _java_ignorable(c))
            tokens.append(("ident", value, line))
            i = end + 1
        elif ch == "$" and kotlin:
            raise _Unlexable()  # a multi-dollar string prefix, or nothing Kotlin allows
        elif ch == "\\":
            if kotlin or at(i + 1) != "\n":
                raise _Unlexable()
            i += 2
        elif ch == "{":
            frame[1] += 1
            tokens.append(("punct", ch, line))
            i += 1
        elif ch == "}":
            if frame[1] == 0:
                if len(stack) == 1:
                    raise _Unlexable()
                stack.pop()  # the template ends; back in its string
            else:
                frame[1] -= 1
                tokens.append(("punct", ch, line))
            i += 1
        elif name_part(ch):
            start = i
            while i < n and name_part(chars[i][0]):
                i += 1
            value = "".join(c for c, _ in chars[start:i] if not _java_ignorable(c))
            tokens.append(("ident", value, line))
        elif ch.isspace():
            i += 1
        else:
            tokens.append(("punct", ch, line))
            i += 1
    if len(stack) != 1 or stack[0][1] != 0:
        raise _Unlexable()
    return tokens


# A Groovy type that can be an @AnnotationCollector. Kotlin's only cross-file alias is a typealias.
TYPE_KEYWORDS = ("class", "interface", "trait", "enum", "record")


def _tok(tokens, k, kind, value=None):
    return k < len(tokens) and tokens[k][0] == kind and (value is None or tokens[k][1] == value)


def _chain_end(tokens, k):
    """The index of the last name in a dotted name starting at k."""
    while _tok(tokens, k + 1, "punct", ".") and _tok(tokens, k + 2, "ident"):
        k += 2
    return k


def _type_name_end(tokens, k):
    """The index of the last name of the type starting at k, past parentheses and type
    annotations, or None when no name starts there."""
    while True:
        if _tok(tokens, k, "punct", "("):
            k += 1
        elif _tok(tokens, k, "punct", "@") and _tok(tokens, k + 1, "ident"):
            k = _chain_end(tokens, k + 1) + 1
            if _tok(tokens, k, "punct", "("):
                depth = 0
                while k < len(tokens):
                    depth += _tok(tokens, k, "punct", "(") - _tok(tokens, k, "punct", ")")
                    k += 1
                    if depth == 0:
                        break
        elif _tok(tokens, k, "ident"):
            return _chain_end(tokens, k)
        else:
            return None


def _declared_type(tokens, t):
    """The index of the name a type declaration starting at t declares, or None."""
    if _tok(tokens, t, "punct", "@") and _tok(tokens, t + 1, "ident", "interface"):
        return t + 2 if _tok(tokens, t + 2, "ident") else None
    if (_tok(tokens, t, "ident") and tokens[t][1] in TYPE_KEYWORDS and _tok(tokens, t + 1, "ident")
            and tokens[t + 1][1] not in TYPE_KEYWORDS
            and not (_tok(tokens, t - 1, "punct", "@") or _tok(tokens, t - 1, "punct", "."))):
        return t + 1
    return None


def _header_names(tokens, t, in_import):
    """The names written before the declaration at t, back to the statement or block before it.

    That covers every annotation on the declaration, with its arguments, so a collector's
    ``@AILocked`` and an ``@AnnotationCollector([AILocked])`` list are both in it. It can also take
    in a script statement ahead of the declaration, which only widens what counts.
    """
    names, depth, k = set(), 0, t - 1
    while k >= 0:
        kind, value, _ = tokens[k]
        if kind == "punct" and value in ")]":
            depth += 1
        elif kind == "punct" and value in "([":
            if depth == 0:
                break
            depth -= 1
        elif kind == "punct" and value in ";{}" and depth == 0:
            break
        elif kind == "ident" and k not in in_import:
            names.add(value)
        k -= 1
    return names


def _script_names(tokens, names):
    """The lock names one Kotlin or Groovy file sees, and the ones it declares for other files.

    Returns ``(local, declared, in_import)``. ``local`` is ``names`` plus every name this file
    gives one of them: an ``import ... as``, a ``typealias`` (plain, qualified, nested, with type
    parameters, or naming another alias) and an ``@AnnotationCollector`` type whose annotations
    name one, followed through each other until nothing grows. ``declared`` is the part another
    file can use, the typealiases and collectors. ``in_import`` holds the token indexes inside
    import statements. Both languages get both rules: neither keyword means anything else in the
    other language, so a stray match can only widen what counts.
    """
    count = len(tokens)
    imports, typealiases, types, in_import = [], [], [], set()
    for t in range(count):
        if _tok(tokens, t, "ident", "import") and _tok(tokens, t + 1, "ident"):
            k = t + 2 if tokens[t + 1][1] == "static" and _tok(tokens, t + 2, "ident") else t + 1
            end = _chain_end(tokens, k)
            in_import.update(range(k, end + 1))
            if _tok(tokens, end + 1, "ident", "as") and _tok(tokens, end + 2, "ident"):
                imports.append((tokens[end][1], tokens[end + 2][1]))
                in_import.update((end + 1, end + 2))
        elif _tok(tokens, t, "ident", "typealias") and _tok(tokens, t + 1, "ident"):
            k = t + 2  # past any type parameters, which cannot hold an "="
            while k < count and not (_tok(tokens, k, "punct", "=")
                                     or _tok(tokens, k, "ident", "typealias")):
                k += 1
            end = _type_name_end(tokens, k + 1) if _tok(tokens, k, "punct", "=") else None
            if end is not None:
                typealiases.append((tokens[end][1], tokens[t + 1][1]))
        else:
            declared_at = _declared_type(tokens, t)
            if declared_at is not None:
                types.append((declared_at, t))
    types = [(tokens[at][1], _header_names(tokens, t, in_import)) for at, t in types]
    collectors = {COLLECTOR_NAME} | {alias for target, alias in imports if target == COLLECTOR_NAME}

    local, declared, grown = set(names), set(), True
    while grown:
        grown = False
        for target, alias in imports + typealiases:
            if target in local and alias not in local:
                local.add(alias)
                grown = True
        for target, alias in typealiases:
            if target in local:
                declared.add(alias)
        for name, header in types:
            if name not in declared and header & collectors and header & local:
                declared.add(name)
                local.add(name)
                grown = True
    return local, declared, in_import


def _script_annotation_lines(tokens, names, any_annotation=False):
    """Lines that carry a lock, from Kotlin or Groovy code tokens.

    Deliberately wider than an annotation: every line from an ``@`` to a lock name after it
    (a use-site target such as ``@field:``, a qualified name, or a ``@[...]`` group), and every
    other code token naming the lock, such as a ``typealias`` right-hand side or a class
    reference, counts. ``names`` holds the lock and the aliases other files declare for it, and the
    names this file gives any of them count as the lock too (see ``_script_names``). A name counts
    wherever it is declared, so a same-named local class never hides an alias. Only an import
    statement itself does not count, so removing an unused import passes. With
    ``any_annotation``, every annotation counts. A wider answer can only fail a pull request that
    would otherwise pass.
    """
    count = len(tokens)
    local, _, in_import = _script_names(tokens, names)

    def tok(k, kind, value=None):
        return _tok(tokens, k, kind, value)

    def counts(name):
        return any_annotation or name in local

    lines = set()
    for t in range(count):
        kind, value, line = tokens[t]
        if kind == "ident" and value in local and t not in in_import:
            lines.add(line)
        if not (kind == "punct" and value == "@"):
            continue
        k = t + 1
        if tok(k, "ident") and tok(k + 1, "punct", ":"):
            k += 2  # a use-site target: @field:, @get:, @file: and the rest
        if tok(k, "punct", "["):
            depth, j = 0, k
            while True:
                if j >= count:
                    raise _Unlexable()
                if tok(j, "punct", "["):
                    depth += 1
                elif tok(j, "punct", "]"):
                    depth -= 1
                    if depth == 0:
                        break
                elif tok(j, "ident") and counts(tokens[j][1]):
                    lines.update(range(line, tokens[j][2] + 1))
                j += 1
        elif tok(k, "ident"):
            end = _chain_end(tokens, k)
            if counts(tokens[end][1]):
                lines.update(range(line, tokens[end][2] + 1))
    return lines


def script_language(path):
    """"kotlin" or "groovy" for a source whose annotations those lexers read, else None."""
    if path is not None and path.endswith((".kt", ".kts")):
        return "kotlin"
    if path is not None and path.endswith(".groovy"):
        return "groovy"
    return None


LANGUAGE_LABELS = {"kotlin": "Kotlin", "groovy": "Groovy"}


class BaseAliases:
    """Lock aliases declared across the base revision's Kotlin and Groovy sources (#716).

    ``names[language]`` holds every alias another file can use. ``unsure[language]`` lists the
    sources that may declare one but do not lex; while one is listed, every annotation in that
    language counts, because the alias it declares cannot be named.
    """

    def __init__(self, names=None, unsure=None):
        self.names = {"kotlin": frozenset(), "groovy": frozenset(), **(names or {})}
        self.unsure = {"kotlin": (), "groovy": (), **(unsure or {})}

    def names_for(self, path):
        return self.names.get(script_language(path), frozenset())

    def unsure_for(self, path):
        return self.unsure.get(script_language(path), ())


NO_ALIASES = BaseAliases()


def lock_lines(path, text, aliases=NO_ALIASES, any_annotation=False):
    """Lines of ``text`` that carry a lock, or None when only a substring match can tell.

    Java, Kotlin and Groovy each have their own lexer, and each answers None whenever it cannot
    be sure where code ends and a literal or comment begins (#708, #709). A Kotlin or Groovy
    source also counts the aliases other files declare (#716).
    """
    if path.endswith(".java"):
        return java_annotation_lines(text)
    language = script_language(path)
    if language == "kotlin":
        return kotlin_annotation_lines(text, aliases=aliases.names_for(path),
                                       any_annotation=any_annotation)
    if language == "groovy":
        return groovy_annotation_lines(text, aliases=aliases.names_for(path),
                                       any_annotation=any_annotation)
    return None


def text_holds_a_lock(path, text, aliases=NO_ALIASES, any_annotation=False):
    """The substring match a source that does not lex falls back to, erring toward failing.

    Java keeps ``@AILocked``. A Kotlin or Groovy text matches when it holds an ``@`` and a lock
    name anywhere, which a use-site target (``@field:AILocked``), a qualified name and an alias
    declared in another file all do; with ``any_annotation`` an ``@`` alone matches.
    """
    if script_language(path) is None:
        return "@AILocked" in text
    if "@" not in text:
        return False
    return any_annotation or any(name in text for name in {LOCK_NAME, *aliases.names_for(path)})


def strips_a_lock(path, base_text, removed, aliases=NO_ALIASES, any_annotation=False):
    """Whether the removed base lines, ``(line number, text)`` pairs, held a real ``@AILocked``.

    Falls back to the substring match on the removed text whenever the base cannot be read or
    lexed, so an unsure answer fails the guard rather than passing it.
    """
    annotated = (lock_lines(path, base_text, aliases, any_annotation)
                 if base_text is not None else None)
    if annotated is None:
        return any(text_holds_a_lock(path, body, aliases, any_annotation) for _, body in removed)
    return any(number in annotated for number, _ in removed)


def holds_a_lock(path, base_text, aliases=NO_ALIASES, any_annotation=False):
    """Whether a deleted file carried a real ``@AILocked``, with the same fallback."""
    annotated = lock_lines(path, base_text, aliases, any_annotation)
    if annotated is None:
        return text_holds_a_lock(path, base_text, aliases, any_annotation)
    return bool(annotated)


# The word a source must hold to declare an alias another file can use: a Kotlin typealias, or a
# Groovy collector, which names AnnotationCollector through an import, an import alias, a star
# import's simple name or its qualified name.
ALIAS_KEYWORDS = {"kotlin": "typealias", "groovy": COLLECTOR_NAME}
_ASCII_IGNORABLE = re.compile("[\x00-\x08\x0e-\x1b\x7f]")
_UNICODE_ESCAPE = re.compile(r"\\u+([0-9a-fA-F]{4})")


def _may_name(text, word, language):
    """Whether ``word`` could be written in ``text``, read before lexing and erring toward yes.

    An identifier-ignorable character inside the word does not hide it, and neither does a Groovy
    unicode escape, which is translated first. Translating one that a preceding backslash escapes
    can only find more. Measured on 998 Groovy files: counting any escape as a possible spelling
    made three files unsure for an escaped emoji or line separator in a literal.
    """
    if word in text:
        return True
    if language == "groovy" and "\\u" in text:
        text = _UNICODE_ESCAPE.sub(lambda match: chr(int(match.group(1), 16)), text)
        if word in text:
            return True
    if text.isascii() and not _ASCII_IGNORABLE.search(text):
        return False
    return word in "".join(ch for ch in text if not _java_ignorable(ch))


def base_script_sources(ref):
    """Every Kotlin and Groovy blob at ``ref`` as ``(path, text)``, read by two git processes.

    ``git ls-tree -r -z`` lists them and a single ``git cat-file --batch`` reads them all, so a
    tree of thousands of sources does not start a process per file. Raises ValueError when git's
    output cannot be read; the caller fails the guard.
    """
    wanted = []
    for record in run_git_bytes("ls-tree", "-r", "-z", "--full-tree", ref).split(bytes([0])):
        if not record:
            continue
        meta, tab, raw_path = record.partition(b"\t")
        parts = meta.split(b" ")
        if not tab or len(parts) != 3:
            raise ValueError(f"unexpected ls-tree record {record[:80]!r}")
        path = os.fsdecode(raw_path)
        if parts[1] == b"blob" and script_language(path):
            wanted.append((path, parts[2]))
    if not wanted:
        return []
    batch = subprocess.run(["git", "cat-file", "--batch"], capture_output=True,
                           input=b"".join(sha + b"\n" for _, sha in wanted))
    if batch.returncode != 0:
        sys.stderr.write(batch.stderr.decode("utf-8", errors="replace"))
        raise SystemExit(f"git cat-file --batch failed with exit code {batch.returncode}")
    out, pos, sources = batch.stdout, 0, []
    for path, sha in wanted:
        end = out.find(b"\n", pos)
        header = out[pos:end].split(b" ") if end >= 0 else []
        if len(header) != 3 or header[0] != sha or header[1] != b"blob":
            raise ValueError(f"unexpected cat-file header for {path!r}")
        start, size = end + 1, int(header[2])
        if len(out) < start + size + 1:
            raise ValueError(f"truncated cat-file output for {path!r}")
        sources.append((path, out[start:start + size].decode("utf-8", errors="replace")))
        pos = start + size + 1
    return sources


def collect_base_aliases(sources):
    """The lock aliases declared across ``(path, text)`` sources at the base revision (#716).

    Only a source that holds ``typealias`` (Kotlin) or ``AnnotationCollector`` (Groovy) can
    declare one, so only those are lexed. Aliases of aliases are followed across files until
    nothing grows. A candidate that does not lex cannot have its alias named; it is recorded as
    unsure when it also holds the lock's name or a known alias, the only way it could alias the
    lock, and an unsure language counts every annotation (see ``BaseAliases``).
    """
    lexed = {"kotlin": [], "groovy": []}
    unlexable = {"kotlin": [], "groovy": []}
    for path, text in sources:
        language = script_language(path)
        if language is None or not _may_name(text, ALIAS_KEYWORDS[language], language):
            continue
        try:
            lexed[language].append(_lex_script(text, kotlin=language == "kotlin"))
        except _Unlexable:
            unlexable[language].append((path, text))
    names, unsure = {}, {}
    for language, token_lists in lexed.items():
        known, grown = {LOCK_NAME}, True
        while grown:
            grown = False
            for tokens in token_lists:
                declared = _script_names(tokens, known)[1]
                if not declared <= known:
                    known |= declared
                    grown = True
        names[language] = frozenset(known - {LOCK_NAME})
        unsure[language] = tuple(path for path, text in unlexable[language]
                                 if any(_may_name(text, name, language) for name in known))
    return BaseAliases(names, unsure)


def unsure_note(path, aliases):
    """Why every annotation counts in ``path``'s language, for a violation message."""
    paths = aliases.unsure_for(path)
    others = f" and {len(paths) - 1} other source(s)" if len(paths) > 1 else ""
    return (f"{paths[0]}{others} may declare an alias of @AILocked but could not be lexed at the "
            "base revision")


def run_git(*args):
    result = subprocess.run(
        ["git", *args], capture_output=True, text=True, encoding="utf-8", errors="replace"
    )
    if result.returncode != 0:
        sys.stderr.write(result.stderr)
        raise SystemExit(f"git {' '.join(args)} failed with exit code {result.returncode}")
    return result.stdout


def run_git_bytes(*args):
    """git's stdout as bytes: no decoding and no newline translation."""
    result = subprocess.run(["git", *args], capture_output=True)
    if result.returncode != 0:
        sys.stderr.write(result.stderr.decode("utf-8", errors="replace"))
        raise SystemExit(f"git {' '.join(args)} failed with exit code {result.returncode}")
    return result.stdout


def run_git_exact(*args):
    """``run_git`` without newline translation, for output whose line numbers matter.

    ``text=True`` turns every lone carriage return into a line break, so a removed line from a
    file with CR-only endings would count as several and shift the base line numbers the
    lock-stripping check looks up.
    """
    return run_git_bytes(*args).decode("utf-8", errors="replace")


def git_show_text(ref, path):
    """A file's content at ``ref`` as committed, without newline translation, or None."""
    blob = subprocess.run(["git", "show", f"{ref}:{path}"], capture_output=True)
    if blob.returncode != 0:
        return None
    return blob.stdout.decode("utf-8", errors="replace")


def find_reports(root):
    reports = []
    for dirpath, dirnames, filenames in os.walk(root):
        dirnames[:] = [d for d in dirnames if d not in (".git", "node_modules", "target", "build")]
        if ".vibetags-locks" in filenames:
            reports.append(os.path.join(dirpath, ".vibetags-locks"))
    return reports


def resolve_lock_path(recorded, report_dir, repo_root):
    """A lock's repo-relative path, resolved against the report that declared it.

    A ``.vibetags-locks`` records paths relative to its own VibeTags root, not to the
    repository. Normalizing against the repository root alone therefore leaves two reactors
    that both have a module at, say, ``showcase/src/main/java/...`` recording the identical
    string, and nothing downstream can tell them apart. Measured before this was fixed: a
    Gradle example's new files drew nine violations from the *Maven* example's report.

    Absolute paths are made repo-relative directly; anything outside the repository is left
    as it is, so it simply matches nothing.
    """
    path = recorded.replace("\\", "/")
    if os.path.isabs(path):
        rel = os.path.relpath(path, repo_root).replace("\\", "/")
        return path if rel.startswith("..") else rel
    report_rel = os.path.relpath(report_dir, repo_root).replace("\\", "/")
    if report_rel in ("", "."):
        return os.path.normpath(path).replace("\\", "/")
    return os.path.normpath(report_rel + "/" + path).replace("\\", "/")


def parse_lock_entries(text, report_dir, repo_root):
    """The 'locked' entries in one report's text, each with a repo-relative 'file'."""
    locks = []
    for line in text.splitlines():
        line = line.strip()
        if not line or line.startswith("#"):
            continue  # markers, header comments, module sub-markers
        try:
            entry = json.loads(line)
        except json.JSONDecodeError:
            continue
        if entry.get("type") != "locked":
            continue
        path = entry.get("file")
        if path:
            entry["file"] = resolve_lock_path(path, report_dir, repo_root)
        locks.append(entry)
    return locks


def load_locks(report_paths, repo_root):
    """Returns a list of lock dicts with a repo-relative 'file' path."""
    locks = []
    for report in report_paths:
        report_dir = os.path.dirname(os.path.abspath(report))
        with open(report, encoding="utf-8") as fh:
            locks.extend(parse_lock_entries(fh.read(), report_dir, repo_root))
    return locks


def lock_key(lock):
    """Identity of a lock across two revisions: which file, which element."""
    return (lock.get("file"), lock.get("element"))


def lock_entries_at(ref, report_paths, repo_root):
    """The lock entries already declared at ``ref``, read from the same reports through git.

    A report that did not exist at the base revision contributes nothing rather than raising.
    """
    locks = []
    for report in report_paths:
        abs_report = os.path.abspath(report)
        rel = os.path.relpath(abs_report, repo_root).replace(chr(92), "/")
        text = git_show_text(ref, rel)
        if text is None:
            continue  # no such report at the base revision
        locks.extend(parse_lock_entries(text, os.path.dirname(abs_report), repo_root))
    return locks


def locks_at(ref, report_paths, repo_root):
    """The lock keys already declared at ``ref``.

    A lock absent here is one this diff introduces, and the author of a lock is not violating it.
    """
    return {lock_key(lock) for lock in lock_entries_at(ref, report_paths, repo_root)}


def locks_for(locks, diff_path):
    """Locks whose file is this diff path.

    Compared exactly. This used to fall back to matching either path as a suffix of the other,
    to paper over absolute-vs-relative prefixes; ``resolve_lock_path`` now makes both sides
    repo-relative, and the suffix fallback actively did harm: any two modules sharing a
    relative path aliased each other's locks.
    """
    diff_path = diff_path.replace(chr(92), "/")
    return [lock for lock in locks if lock.get("file") == diff_path]


def parse_raw_entries(data):
    """Changed files from ``git diff --raw -z``: (status, old_mode, new_mode, old, new).

    ``-z`` prints every path verbatim and NUL-terminated. The patch headers this guard used to
    read quote a path holding a non-ASCII byte or a control character, and end one holding a
    space with a tab, so the path no longer ended in ``.java`` and the file skipped every
    source check. ``old`` is None for an addition and ``new`` for a deletion. Raises
    ValueError on a record it cannot read; the caller fails the guard.
    """
    nul = bytes([0])
    fields = data.split(nul)
    if fields and fields[-1] == b"":
        fields.pop()
    entries, i = [], 0
    while i < len(fields):
        meta = fields[i]
        parts = meta.split(b" ")
        if not meta.startswith(b":") or len(parts) != 5:
            raise ValueError(f"unexpected raw diff record {meta[:80]!r}")
        old_mode, new_mode = parts[0][1:].decode("ascii"), parts[1].decode("ascii")
        status = parts[4].decode("ascii")[:1]
        count = 2 if status in ("R", "C") else 1
        if i + count >= len(fields):
            raise ValueError(f"truncated raw diff record {meta[:80]!r}")
        paths = [os.fsdecode(field) for field in fields[i + 1:i + 1 + count]]
        if not all(paths):
            raise ValueError(f"empty path in raw diff record {meta[:80]!r}")
        i += 1 + count
        if count == 2:
            old, new = paths
        elif status == "A":
            old, new = None, paths[0]
        elif status == "D":
            old, new = paths[0], None
        else:
            old = new = paths[0]
        entries.append((status, old_mode, new_mode, old, new))
    return entries


def parse_patch_sections(diff_text):
    """Yields (old_hunks, new_hunks, removed_lines) per ``diff --git`` section.

    Each hunk is (start, count) on its side of the diff. removed_lines is a list of (base line
    number, text), numbered from the hunk's old side so a removed line can be looked up in the
    base blob. Paths are not read here: they come from ``parse_raw_entries``.

    Lines are split on newline alone, as git counts them: ``str.splitlines`` also breaks on a
    carriage return or form feed inside a line, which would shift every later number. Nothing
    before a section's first hunk is content, so a removed line whose own text starts with
    "-- " is a removal rather than a "--- " header.
    """
    section, in_hunk, old_line = None, False, 0
    for line in diff_text.split("\n"):
        if line.startswith("diff --git "):
            if section is not None:
                yield section
            section, in_hunk = ([], [], []), False
        elif section is None:
            continue
        elif line.startswith("@@"):
            m = HUNK_RE.match(line)
            if not m:
                raise ValueError(f"unreadable hunk header {line[:80]!r}")
            in_hunk, old_line = True, int(m.group(1))
            section[0].append((old_line, int(m.group(2)) if m.group(2) is not None else 1))
            section[1].append((int(m.group(3)), int(m.group(4)) if m.group(4) is not None else 1))
        elif not in_hunk:
            continue
        elif line.startswith("-"):
            section[2].append((old_line, line[1:]))
            old_line += 1
        elif line.startswith(" "):
            old_line += 1  # context line; --unified=0 emits none, but count it if present
    if section is not None:
        yield section


def annotation_message(text):
    """A workflow-command message: a newline in a file name or a lock reason cannot start one."""
    return text.replace("%", "%25").replace(chr(13), "%0D").replace(chr(10), "%0A")


def annotation_property(text):
    """A workflow-command property value, which additionally may not hold ':' or ','."""
    return annotation_message(text).replace(":", "%3A").replace(",", "%2C")


def touches(start, end, hunk_start, hunk_count):
    """Whether a hunk (start, count) touches lines start..end on the same side of the diff."""
    if hunk_count == 0:
        return start - 1 <= hunk_start <= end  # pure deletion or insertion at this position
    return hunk_start <= end and (hunk_start + hunk_count - 1) >= start


def range_violations(lock, path, hunks, where=""):
    start, end = lock.get("startLine"), lock.get("endLine")
    element, reason = lock.get("element", "?"), lock.get("reason", "")
    if start is None or end is None:
        # No positions (non-javac compiler): file-level fallback.
        yield (path, None, f"Change touches a file containing locked element {element} "
                           f"(no line info available). Reason: {reason}")
        return
    for hunk_start, hunk_count in hunks:
        if touches(start, end, hunk_start, hunk_count):
            yield (path, max(hunk_start, 1), f"Change touches @AILocked element {element} "
                                              f"(lines {start}-{end}{where}). Reason: {reason}")
            return


GITLINK_MODE = "160000"
CHECKED_STATUSES = ("A", "C", "D", "M", "R", "T")


def entry_violations(entry, merge_base, head_locks, base_locks, established,
                     aliases=NO_ALIASES):
    """Violations for one changed file, as (path, line or None, message) triples."""
    status, old_mode, new_mode, old, new = entry
    paths = list(dict.fromkeys(p for p in (old, new) if p))
    if status not in CHECKED_STATUSES:
        yield (paths[0], None, f"Unrecognised diff status {status!r}; failing closed")
        return
    if all(p.endswith(".vibetags-locks") for p in paths):
        return  # report regeneration is expected, not a violation

    if GITLINK_MODE in (old_mode, new_mode):
        # A submodule's own files never appear in this diff, so a lock inside one cannot be
        # range-checked: moving the pointer is treated as touching every lock beneath it.
        for path in paths:
            inside = [lock for lock in head_locks + base_locks
                      if (lock.get("file") or "").startswith(path.rstrip("/") + "/")]
            if inside:
                yield (path, None, f"Submodule holding locked element "
                                   f"{inside[0].get('element', '?')} changed; its code cannot "
                                   "be checked here, so this needs human review")
                return
        return

    # A file this diff CREATES (or copies into place) is exempt: the lock did not exist at the
    # base, so nobody can have violated it, and flagging it means a PR may never introduce an
    # @AILocked element. That blocked adding guardrails to the very codebase that ships them. A
    # copy leaves its source in place, and any edit to that source is its own entry.
    if status in ("A", "C"):
        return

    base_here = locks_for(base_locks, old)
    extension_changed = new is not None and os.path.splitext(old)[1] != os.path.splitext(new)[1]
    if status in ("D", "T") or (status == "R" and extension_changed):
        # Deleted, or renamed or retyped away from what it was: whatever the file becomes, the
        # source that held the lock is gone, so its base content is checked as for a deletion.
        what = "Deleted file" if status == "D" else f"File moved away from {old}"
        held = None
        if is_lock_carrying_source(old):
            base_text = git_show_text(merge_base, old)
            if base_text is None:
                yield (old, None, "Cannot read the base revision of a removed source file; "
                                  "failing closed")
                return
            if holds_a_lock(old, base_text, aliases):
                held = f"{what} contained @AILocked code"
            elif aliases.unsure_for(old) and holds_a_lock(old, base_text, aliases, True):
                held = (f"{what} held an annotation, and {unsure_note(old, aliases)}; "
                        "failing closed")
        if held is None and base_here:
            held = f"{what} held locked element {base_here[0].get('element', '?')}"
        if held is not None:
            yield (old, None, held)
            return
        if status != "R":
            return

    head_here = locks_for(head_locks, new)
    source = is_lock_carrying_source(old) or is_lock_carrying_source(new)
    if not (source or head_here or base_here):
        return
    # One file at a time, named by literal pathspecs, so no path is ever read back out of a
    # patch header. --text keeps a file git would call binary from hiding its hunks.
    patch = run_git_exact(
        "--literal-pathspecs", "diff", "--unified=0", "--no-color", "--text", "--no-ext-diff",
        "--no-textconv", "--find-renames", "--no-relative", merge_base, "HEAD", "--", *paths)
    try:
        sections = list(parse_patch_sections(patch))
    except ValueError as err:
        sections = [err]
    if len(sections) != 1 or isinstance(sections[0], ValueError):
        yield (new, None, f"Cannot map this file's diff ({len(sections)} sections); failing closed")
        return
    old_hunks, new_hunks, removed = sections[0]

    # 2. Lock stripping: the @AILocked annotation itself was removed from source. Read on the
    # base side, because a stripped lock is absent from the regenerated report.
    if source and removed:
        base_text = git_show_text(merge_base, old)
        if strips_a_lock(old, base_text, removed, aliases):
            yield (new, None, "A line containing @AILocked was removed -- "
                              "removing a lock requires explicit human review")
        elif aliases.unsure_for(old) and strips_a_lock(old, base_text, removed, aliases, True):
            yield (new, None, "A line holding an annotation was removed, and "
                              f"{unsure_note(old, aliases)}; failing closed")

    # 1. Changed lines intersect a locked range at HEAD. A lock absent from the base report is
    # one this diff introduces and is exempt: adding @AILocked to existing code is itself a
    # change to the lines it now covers, so without this every PR that adopts a lock fails on
    # the commit that introduces it. Measured: the PR that locked GuardrailAnnotations.ALL and
    # TransitiveManifest.RESOURCE_PACKAGE drew one violation each for doing so. A lock that
    # moved with its file counts as established under its old path.
    for lock in head_here:
        element = lock.get("element")
        if lock_key(lock) in established or (old, element) in established:
            yield from range_violations(lock, new, new_hunks)

    # 1b. A renamed file is also checked against the base report's ranges on the old side,
    # which catch an edit however the element or its path was renamed alongside it.
    if old != new:
        for lock in base_here:
            yield from range_violations(lock, old, old_hunks, " at the base revision")


def main():
    base_ref = os.environ.get("VIBETAGS_BASE_REF", "").strip()
    warn_only = os.environ.get("VIBETAGS_WARN_ONLY", "false").strip().lower() == "true"
    if not base_ref:
        raise SystemExit("VIBETAGS_BASE_REF is not set -- pass the PR base ref/SHA")
    # Option-injection guard: refs/SHAs never start with '-'. Reject so an attacker-influenced
    # base ref cannot be reinterpreted as a git option by `git merge-base`.
    if base_ref.startswith("-"):
        raise SystemExit("VIBETAGS_BASE_REF must not start with '-'")

    repo_root = run_git("rev-parse", "--show-toplevel").strip()
    merge_base = run_git("merge-base", base_ref, "HEAD").strip()
    kind = "warning" if warn_only else "error"

    reports = find_reports(os.getcwd())
    if not reports:
        # A guard that found nothing to guard has not passed; it has not run. The report is
        # opted in by committing .vibetags-locks, so its absence here means the action runs in
        # the wrong working-directory or the project never opted in -- either way the check
        # would be green while guarding nothing.
        print(f"::{kind}::VibeTags locked-files guard: no .vibetags-locks report found under "
              f"{annotation_message(os.getcwd())} -- commit an empty .vibetags-locks at the "
              "project root to opt in, and point working-directory at that root")
        return 0 if warn_only else 1
    locks = load_locks(reports, repo_root)
    print(f"VibeTags locked-files guard: {len(locks)} locked element(s) "
          f"from {len(reports)} report(s); diffing against {merge_base[:12]}")

    # Trailing "--" terminates options/refs so no value can be reinterpreted as a pathspec/flag.
    try:
        entries = parse_raw_entries(run_git_bytes(
            "diff", "--raw", "-z", "--no-abbrev", "--find-renames", "--no-ext-diff",
            "--no-relative", merge_base, "HEAD", "--"))
    except ValueError as err:
        message = f"VibeTags locked-files guard: cannot read the diff ({err}); failing closed"
        print(f"::{kind}::{annotation_message(message)}")
        return 0 if warn_only else 1
    # Aliases of the lock can be declared in any Kotlin or Groovy source, not only a changed one, so
    # a diff that removes one of those sources' lines reads them all at the base first (#716).
    aliases = NO_ALIASES
    if any(script_language(old) for _, _, _, old, _ in entries):
        try:
            aliases = collect_base_aliases(base_script_sources(merge_base))
        except ValueError as err:
            message = (f"VibeTags locked-files guard: cannot read the base sources ({err}); "
                       "failing closed")
            print(f"::{kind}::{annotation_message(message)}")
            return 0 if warn_only else 1
        for language, unsure in aliases.unsure.items():
            if unsure:
                print(f"VibeTags locked-files guard: {len(unsure)} {LANGUAGE_LABELS[language]} "
                      "source(s) at the base may declare an alias of @AILocked but do not lex, "
                      f"so every annotation in a {LANGUAGE_LABELS[language]} source counts "
                      f"(first: {annotation_message(unsure[0])})")
    base_locks = lock_entries_at(merge_base, reports, repo_root)
    established = {lock_key(lock) for lock in base_locks}
    violations = 0

    for entry in entries:
        for path, line, message in entry_violations(entry, merge_base, locks, base_locks,
                                                    established, aliases):
            violations += 1
            where = f"file={annotation_property(path)}"
            if line is not None:
                where += f",line={line}"
            print(f"::{kind} {where}::{annotation_message(message)}")

    if violations:
        verdict = "warning(s)" if warn_only else "violation(s)"
        print(f"\nVibeTags locked-files guard: {violations} {verdict} found.")
        return 0 if warn_only else 1
    print("\nVibeTags locked-files guard: no locked code touched.")
    return 0

if __name__ == "__main__":
    sys.exit(main())
