import React, { useState } from 'react';
import { Shield, Folder, FileCode2, FileJson, ChevronRight, ChevronDown, Download, Github } from 'lucide-react';
import { CodeBlock } from './components/CodeBlock';

const FILES = [
  {
    name: 'pom.xml',
    language: 'xml',
    content: `<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>com.vibetags</groupId>
    <artifactId>vibetags-processor</artifactId>
    <version>1.0.0-SNAPSHOT</version>

    <properties>
        <maven.compiler.source>11</maven.compiler.source>
        <maven.compiler.target>11</maven.compiler.target>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    </properties>

    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>3.11.0</version>
                <configuration>
                    <!-- Disable annotation processing for the processor itself -->
                    <compilerArgument>-proc:none</compilerArgument>
                </configuration>
            </plugin>
        </plugins>
    </build>
</project>`
  },
  {
    name: 'build.gradle',
    language: 'groovy',
    content: `plugins {
    id 'java-library'
}

group = 'com.vibetags'
version = '1.0.0-SNAPSHOT'

repositories {
    mavenCentral()
}

java {
    sourceCompatibility = JavaVersion.VERSION_11
    targetCompatibility = JavaVersion.VERSION_11
}

tasks.withType(JavaCompile) {
    // Disable annotation processing when compiling the processor itself
    options.compilerArgs += ['-proc:none']
}`
  },
  {
    name: 'AILocked.java',
    path: 'src/main/java/com/vibetags/annotations/',
    language: 'java',
    content: `package com.vibetags.annotations;

import java.lang.annotation.ElementType;
import java.lang.annotation.Retention;
import java.lang.annotation.RetentionPolicy;
import java.lang.annotation.Target;

@Retention(RetentionPolicy.SOURCE)
@Target({ElementType.TYPE, ElementType.METHOD, ElementType.FIELD})
public @interface AILocked {
    String reason() default "Do not modify this code under any circumstances.";
}`
  },
  {
    name: 'AIContext.java',
    path: 'src/main/java/com/vibetags/annotations/',
    language: 'java',
    content: `package com.vibetags.annotations;

import java.lang.annotation.ElementType;
import java.lang.annotation.Retention;
import java.lang.annotation.RetentionPolicy;
import java.lang.annotation.Target;

@Retention(RetentionPolicy.SOURCE)
@Target({ElementType.TYPE, ElementType.METHOD})
public @interface AIContext {
    String focus() default "";
    String avoids() default "";
}`
  },
  {
    name: 'AIDraft.java',
    path: 'src/main/java/com/vibetags/annotations/',
    language: 'java',
    content: `package com.vibetags.annotations;

import java.lang.annotation.ElementType;
import java.lang.annotation.Retention;
import java.lang.annotation.RetentionPolicy;
import java.lang.annotation.Target;

@Retention(RetentionPolicy.SOURCE)
@Target({ElementType.TYPE, ElementType.METHOD})
public @interface AIDraft {
    String instructions() default "Implement this method/class according to standard practices.";
}`
  },
  {
    name: 'AIGuardrailProcessor.java',
    path: 'src/main/java/com/vibetags/processor/',
    language: 'java',
    content: `package com.vibetags.processor;

import com.vibetags.annotations.AIContext;
import com.vibetags.annotations.AILocked;

import javax.annotation.processing.*;
import javax.lang.model.SourceVersion;
import javax.lang.model.element.Element;
import javax.lang.model.element.TypeElement;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import java.nio.file.Paths;
import java.util.Set;

@SupportedAnnotationTypes("com.vibetags.annotations.*")
@SupportedSourceVersion(SourceVersion.RELEASE_11)
public class AIGuardrailProcessor extends AbstractProcessor {

    @Override
    public boolean process(Set<? extends TypeElement> annotations, RoundEnvironment roundEnv) {
        if (annotations.isEmpty()) return false;

        String rootPath = Paths.get("").toAbsolutePath().toString();

        StringBuilder cursorRules = new StringBuilder("# AUTO-GENERATED AI RULES\\n# Do not edit manually. Generated by VibeTags.\\n\\n## LOCKED FILES (DO NOT EDIT)\\n");
        StringBuilder claudeMd = new StringBuilder("<project_guardrails>\\n  <locked_files>\\n");
        StringBuilder aiExclude = new StringBuilder("# AUTO-GENERATED BY VIBETAGS\\n# The following files are strictly excluded from AI context.\\n");
        StringBuilder chatGpt = new StringBuilder("# Project Knowledge\\n\\n## Locked Files\\n");

        // Process @AILocked
        for (Element element : roundEnv.getElementsAnnotatedWith(AILocked.class)) {
            AILocked locked = element.getAnnotation(AILocked.class);
            String className = element.toString();
            String reason = locked.reason();

            cursorRules.append("* \`").append(className).append("\` - Reason: ").append(reason).append("\\n");
            
            claudeMd.append("    <file path=\\\"").append(className).append("\\\">\\n")
                    .append("      <reason>").append(reason).append("</reason>\\n")
                    .append("    </file>\\n");
                    
            aiExclude.append("**/").append(element.getSimpleName()).append(".java\\n");
            
            chatGpt.append("- **").append(className).append("**: ").append(reason).append("\\n");
        }

        claudeMd.append("  </locked_files>\\n  <contextual_instructions>\\n");
        cursorRules.append("\\n## CONTEXTUAL RULES\\n");
        chatGpt.append("\\n## Contextual Rules\\n");

        // Process @AIContext
        for (Element element : roundEnv.getElementsAnnotatedWith(AIContext.class)) {
            AIContext context = element.getAnnotation(AIContext.class);
            String className = element.toString();
            
            cursorRules.append("* \`").append(className).append("\`\\n  * Focus: ").append(context.focus())
                       .append("\\n  * Avoid: ").append(context.avoids()).append("\\n");
                       
            claudeMd.append("    <file path=\\\"").append(className).append("\\\">\\n")
                    .append("      <focus>").append(context.focus()).append("</focus>\\n")
                    .append("      <avoids>").append(context.avoids()).append("</avoids>\\n")
                    .append("    </file>\\n");
                    
            chatGpt.append("- **").append(className).append("**: Focus on ").append(context.focus())
                   .append(". Avoid ").append(context.avoids()).append(".\\n");
        }

        claudeMd.append("  </contextual_instructions>\\n</project_guardrails>\\n");
        claudeMd.append("\\n<rule>Never propose edits to files listed in <locked_files>.</rule>\\n");

        // Write files to the project root
        writeFile(rootPath + "/.cursorrules", cursorRules.toString());
        writeFile(rootPath + "/CLAUDE.md", claudeMd.toString());
        writeFile(rootPath + "/.aiexclude", aiExclude.toString());
        writeFile(rootPath + "/chatgpt_instructions.md", chatGpt.toString());

        return true;
    }

    private void writeFile(String path, String content) {
        try (PrintWriter out = new PrintWriter(new FileWriter(path))) {
            out.println(content);
        } catch (IOException e) {
            processingEnv.getMessager().printMessage(
                javax.tools.Diagnostic.Kind.WARNING, "VibeTags: Failed to write AI rules file: " + path
            );
        }
    }
}`
  },
  {
    name: 'javax.annotation.processing.Processor',
    path: 'src/main/resources/META-INF/services/',
    language: 'text',
    content: `com.vibetags.processor.AIGuardrailProcessor`
  }
];

export default function App() {
  const [activeFile, setActiveFile] = useState(FILES[5]); // Default to processor

  return (
    <div className="min-h-screen bg-[#0a0a0a] text-white flex flex-col font-sans">
      {/* Header */}
      <header className="h-14 border-b border-white/10 bg-[#121212] flex items-center justify-between px-6 shrink-0">
        <div className="flex items-center gap-3">
          <Shield className="text-indigo-500" size={20} />
          <h1 className="font-semibold tracking-tight">VibeTags Java Library</h1>
          <span className="px-2 py-0.5 rounded bg-indigo-500/10 text-indigo-400 text-xs font-mono border border-indigo-500/20">
            v1.0.0
          </span>
        </div>
        <div className="flex items-center gap-4 text-sm text-white/60">
          <p>The files have been generated in the <code className="text-indigo-400">/vibetags</code> directory.</p>
          <button className="flex items-center gap-2 bg-white/10 hover:bg-white/20 px-3 py-1.5 rounded-md transition-colors text-white">
            <Download size={14} />
            Export Project
          </button>
        </div>
      </header>

      {/* Main IDE Layout */}
      <div className="flex flex-1 overflow-hidden">
        {/* Sidebar */}
        <aside className="w-72 border-r border-white/10 bg-[#0f0f0f] flex flex-col overflow-y-auto">
          <div className="p-4 text-xs font-semibold text-white/40 uppercase tracking-wider">
            Project Explorer
          </div>
          
          <div className="px-2 pb-4">
            <div className="flex items-center gap-2 px-2 py-1.5 text-white/80">
              <ChevronDown size={14} />
              <Folder size={14} className="text-indigo-400" />
              <span className="text-sm font-medium">vibetags</span>
            </div>
            
            <div className="pl-6 space-y-0.5">
              {FILES.map((file, idx) => (
                <button
                  key={idx}
                  onClick={() => setActiveFile(file)}
                  className={`w-full flex items-center gap-2 px-2 py-1.5 rounded text-sm transition-colors ${
                    activeFile.name === file.name 
                      ? 'bg-indigo-500/20 text-indigo-300' 
                      : 'text-white/60 hover:bg-white/5 hover:text-white/90'
                  }`}
                >
                  {file.name.endsWith('.java') ? (
                    <FileCode2 size={14} className={activeFile.name === file.name ? 'text-indigo-400' : 'text-blue-400'} />
                  ) : (
                    <FileJson size={14} className={activeFile.name === file.name ? 'text-indigo-400' : 'text-yellow-400'} />
                  )}
                  <span className="truncate">{file.name}</span>
                </button>
              ))}
            </div>
          </div>
        </aside>

        {/* Editor Area */}
        <main className="flex-1 flex flex-col bg-[#0a0a0a] overflow-hidden">
          {/* Tabs */}
          <div className="h-10 border-b border-white/10 bg-[#121212] flex items-center px-2">
            <div className="flex items-center gap-2 px-4 py-2 bg-[#0a0a0a] border-t-2 border-t-indigo-500 text-sm text-white/90">
              {activeFile.name.endsWith('.java') ? (
                <FileCode2 size={14} className="text-blue-400" />
              ) : (
                <FileJson size={14} className="text-yellow-400" />
              )}
              {activeFile.name}
            </div>
          </div>

          {/* Code Content */}
          <div className="flex-1 overflow-y-auto p-6">
            <div className="max-w-4xl mx-auto">
              <div className="mb-4">
                <h2 className="text-xl font-semibold mb-1">{activeFile.name}</h2>
                {activeFile.path && (
                  <p className="text-sm text-white/40 font-mono">
                    {activeFile.path}{activeFile.name}
                  </p>
                )}
              </div>
              <CodeBlock 
                code={activeFile.content} 
                language={activeFile.language} 
              />
            </div>
          </div>
        </main>
      </div>
    </div>
  );
}

