package se.deversity.vibetags.processor.internal.content;

import org.junit.jupiter.api.Test;

import java.util.List;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNull;

/**
 * {@link ClaudeSectionMerge}: one {@code <project_guardrails>} document from several source sets'
 * bodies (issue #839), and a decline wherever the bodies are not the shape it knows.
 */
class ClaudeSectionMergeTest {

    private static final String HEADER = "<!-- # Generated by VibeTags -->";
    private static final String LOCK_RULE = "<rule>Never propose edits to files listed in <locked_files>.</rule>";
    private static final String CORE_RULE = "<rule>Elements listed in <core_elements> are core.</rule>";

    private static String body(String sections, String tail) {
        return HEADER + "\n<project_guardrails>\n" + sections + "</project_guardrails>" + tail;
    }

    private static String locked(String path, String reason) {
        return "    <file path=\"" + path + "\">\n      <reason>" + reason + "</reason>\n    </file>\n";
    }

    @Test
    void sharedSectionHoldsBothSourceSetsEntriesInOrder() {
        String main = body("  <locked_files>\n" + locked("a.Main", "wire format") + "  </locked_files>\n",
            "\n\n" + LOCK_RULE);
        String test = body("  <locked_files>\n" + locked("a.MainTest", "wire format") + "  </locked_files>\n",
            "\n\n" + LOCK_RULE + "\n\nGuardrails for test code are in TESTING.md.");

        assertEquals(body("  <locked_files>\n" + locked("a.Main", "wire format") + locked("a.MainTest", "wire format")
                + "  </locked_files>\n", "\n\n" + LOCK_RULE + "\n\nGuardrails for test code are in TESTING.md."),
            ClaudeSectionMerge.merge(List.of(main, test)),
            "two entries sharing a <reason> line both survive: entries are whole blocks, not lines");
    }

    @Test
    void aSectionOnlyTheTestSourceSetHasLandsWhereTheRendererPutsIt() {
        String core = "  <core_elements>\n    <element path=\"a.Core\"/>\n  </core_elements>\n\n" + CORE_RULE + "\n";
        String scoped = "  <scoped_rules>\n    <note>rule files load by glob</note>\n    <element path=\"a.X\"/>\n  </scoped_rules>\n";
        String main = body("  <locked_files>\n" + locked("a.Main", "r") + "  </locked_files>\n" + scoped, "");
        String test = body(core + "  <scoped_rules>\n    <note>rule files load by glob</note>\n    <element path=\"a.XTest\"/>\n  </scoped_rules>\n", "");

        assertEquals(body("  <locked_files>\n" + locked("a.Main", "r") + "  </locked_files>\n" + core
                + "  <scoped_rules>\n    <note>rule files load by glob</note>\n    <element path=\"a.X\"/>\n"
                + "    <element path=\"a.XTest\"/>\n  </scoped_rules>\n", ""),
            ClaudeSectionMerge.merge(List.of(main, test)),
            "core_elements goes before the shared scoped_rules, and the index note is written once");
    }

    @Test
    void anIdenticalEntryInBothSourceSetsIsWrittenOnce() {
        String main = body("  <locked_files>\n" + locked("a.Moved", "r") + "  </locked_files>\n", "");
        assertEquals(main, ClaudeSectionMerge.merge(List.of(main, main)));
    }

    @Test
    void declinesWhenTheSameSectionCarriesADifferentRule() {
        String main = body("  <core_elements>\n    <element path=\"a\"/>\n  </core_elements>\n\n" + CORE_RULE + "\n", "");
        String older = body("  <core_elements>\n    <element path=\"b\"/>\n  </core_elements>\n\n<rule>older wording</rule>\n", "");
        assertNull(ClaudeSectionMerge.merge(List.of(main, older)),
            "a sidecar from another processor version keeps its own rule, so the caller concatenates");
    }

    @Test
    void declinesWhatItCannotParse() {
        String ok = body("  <locked_files>\n" + locked("a", "r") + "  </locked_files>\n", "");
        assertNull(ClaudeSectionMerge.merge(List.of(ok, "# not a claude body")), "no wrapper");
        assertNull(ClaudeSectionMerge.merge(List.of(ok, body("  <locked_files>\n" + locked("b", "r"), ""))),
            "unclosed section");
        assertNull(ClaudeSectionMerge.merge(List.of(ok, body("stray text\n", ""))), "a line outside any section");
        assertNull(ClaudeSectionMerge.merge(List.of(ok, body("  <locked_files>\n  shallow\n  </locked_files>\n", ""))),
            "an entry line shallower than four spaces");
        assertNull(ClaudeSectionMerge.merge(List.of(ok, ok.replace(HEADER, "<!-- other header -->"))),
            "a different header");
    }

    @Test
    void oneBodyIsReturnedAsIs() {
        assertEquals("anything", ClaudeSectionMerge.merge(List.of("anything")));
        assertNull(ClaudeSectionMerge.merge(List.of()));
    }
}
