package se.deversity.vibetags.processor.internal.content;

import org.junit.jupiter.api.Test;

import java.util.List;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNull;

/**
 * {@link LocksReportMerge}: one {@code .vibetags-locks} body from several source sets (issue #851).
 * The report is JSON Lines with {@code #} comments, so each line stands alone and a union of lines,
 * first body first, is the whole merge.
 */
class LocksReportMergeTest {

    private static final String HEADER = "# Generated by VibeTags | https://github.com/PIsberg/vibetags\n"
        + "# Machine-readable @AILocked report (JSON Lines; '#' lines are comments).\n"
        + "{\"type\":\"format\",\"version\":1}";

    private static String locked(String element) {
        return "{\"type\":\"locked\",\"element\":\"" + element + "\",\"kind\":\"CLASS\"}";
    }

    @Test
    void theHeaderAndFormatRecordAppearOnceAndEveryLockIsKeptInOrder() {
        String main = HEADER + "\n" + locked("a.Main");
        String test = HEADER + "\n" + locked("a.MainTest");

        assertEquals(HEADER + "\n" + locked("a.Main") + "\n" + locked("a.MainTest"),
            LocksReportMerge.merge(List.of(main, test)));
    }

    @Test
    void aTestRoundWithNoLocksAddsNothing() {
        // This repository's own report: the test round wrote a header and a format record and no
        // lock, and stacked, that was three repeated lines.
        String main = HEADER + "\n" + locked("a.Main");

        assertEquals(main, LocksReportMerge.merge(List.of(main, HEADER)));
    }

    @Test
    void declinesALineThatIsNeitherACommentNorARecord() {
        assertNull(LocksReportMerge.merge(List.of(HEADER, HEADER + "\nnot json")),
            "a shape this merge does not know goes back to concatenation, which loses nothing");
    }

    @Test
    void oneBodyIsReturnedAsIs() {
        assertEquals(HEADER, LocksReportMerge.merge(List.of(HEADER)));
        assertNull(LocksReportMerge.merge(List.of()));
    }
}
