package se.deversity.vibetags.processor.internal.content.platforms;

import se.deversity.vibetags.processor.model.GuardrailModel;
import se.deversity.vibetags.processor.internal.content.Platform;
import se.deversity.vibetags.processor.internal.content.PlatformRenderer;
import se.deversity.vibetags.processor.internal.content.RenderingContext;
import se.deversity.vibetags.processor.internal.content.YamlMergeShape;

/**
 * PlatformRenderer for aider's {@code .aider.conf.yml}.
 *
 * <p>Exists for one reason: aider does not load {@code CONVENTIONS.md} on its own. Its
 * <a href="https://aider.chat/docs/usage/conventions.html">conventions documentation</a> is
 * explicit that the file has to be named, with {@code /read CONVENTIONS.md}, {@code --read}, or a
 * {@code read:} key in this file. VibeTags has generated {@code CONVENTIONS.md} since v0.5.0 and
 * nothing was loading it, so the aider platform produced a file no aider session ever opened.
 *
 * <p>The output does not vary with the annotations — it is one {@code read:} entry pointing at the
 * file that does vary. It still declares a {@link YamlMergeShape} because the file is YAML and a
 * reactor would otherwise write {@code read:} once per module.
 */
public final class AiderConfRenderer implements PlatformRenderer {

    /** The single entry, at the indent the merge shape declares. */
    private static final String READ_CONVENTIONS = "  - CONVENTIONS.md\n";

    @Override
    public String render(GuardrailModel model, Platform platform, RenderingContext context) {
        return "# AUTO-GENERATED BY VIBETAGS\n"
            + context.getGeneratedHeader()
            + "# aider does not load CONVENTIONS.md unless it is named here.\n"
            + "# See https://aider.chat/docs/usage/conventions.html\n\n"
            + "read:\n"
            + READ_CONVENTIONS;
    }

    /**
     * Every module points aider at the same {@code CONVENTIONS.md} — the reactor root's, which is
     * where the merged conventions land — so the merge keeps one entry rather than repeating it per
     * module. Declaring the entry as the empty body is what makes that happen: contributions equal
     * to it are dropped and it is re-emitted once.
     */
    @Override
    public YamlMergeShape mergeShape() {
        // stripTrailing, not strip: the leading two spaces are the declared indent, and the
        // merge re-emits this verbatim when every module contributed the same entry. Stripping
        // them dedents the sequence to column 0 in a reactor build. That still parses, but it
        // makes the merged file disagree with the single-module one for no reason, and on a
        // block-scalar platform the same mistake would break the document outright.
        return YamlMergeShape.appended("read:", 2, READ_CONVENTIONS.stripTrailing());
    }
}
