package se.deversity.vibetags.processor.internal.content.platforms;

import se.deversity.vibetags.processor.model.TaggedElement;
import se.deversity.vibetags.processor.model.GuardrailModel;
import se.deversity.vibetags.processor.internal.content.FormatterRegistry;
import se.deversity.vibetags.processor.internal.content.Platform;
import se.deversity.vibetags.processor.internal.content.PlatformRenderer;
import se.deversity.vibetags.processor.internal.content.RenderingContext;

/**
 * PlatformRenderer for generating `.aiexclude`.
 */
public final class AiExcludeRenderer implements PlatformRenderer {
    @Override
    public String render(GuardrailModel model, Platform platform, RenderingContext context) {
        StringBuilder globs = new StringBuilder(256);
        for (TaggedElement e : model.locked()) {
            FormatterRegistry.locked().format(e, globs, Platform.AI_EXCLUDE);
        }
        for (TaggedElement e : model.ignore()) {
            FormatterRegistry.ignore().format(e, globs, Platform.AI_EXCLUDE);
        }
        // A module with nothing to exclude contributes nothing, not a header: the same rule
        // IgnoreFileRenderer follows, for the same reason (ModuleSidecar.mergeFor() wraps every
        // non-blank contribution, so each empty module and source set added a header with no globs
        // under it). Decided on the globs, not on the model: a locked member is real but emits no
        // line, because a glob cannot name a member.
        if (globs.isEmpty()) {
            return "";
        }
        return "# AUTO-GENERATED BY VIBETAGS\n"
            + context.getGeneratedHeader()
            + "# The following files are strictly excluded from AI context.\n"
            + globs;
    }
}
