package se.deversity.vibetags.processor.internal.content.platforms;

import se.deversity.vibetags.processor.internal.AnnotationCollector;
import se.deversity.vibetags.processor.internal.content.Platform;
import se.deversity.vibetags.processor.internal.content.PlatformRenderer;
import se.deversity.vibetags.processor.internal.content.RenderingContext;

/**
 * PlatformRenderer for generating `.claude/skills/vibetags-guardrails/SKILL.md`.
 * Reuses the CursorRenderer's Markdown body and prepends the YAML frontmatter
 * (`name` + `description`) that Claude Code Skills require to be discoverable.
 */
public final class ClaudeSkillRenderer implements PlatformRenderer {
    // CursorRenderer is stateless — one shared instance is sufficient.
    private static final CursorRenderer CURSOR_RENDERER = new CursorRenderer();

    private static final String FRONT_MATTER = "---\n"
        + "name: vibetags-guardrails\n"
        + "description: \"AI guardrails and coding rules generated by VibeTags from @AILocked, "
        + "@AIContext, and related annotations. Load this skill when writing, reviewing, or "
        + "modifying code in this project.\"\n"
        + "---\n\n";

    @Override
    public String render(AnnotationCollector collector, Platform platform, RenderingContext context) {
        String body = CURSOR_RENDERER.render(collector, platform, context);
        if (body == null) {
            return null;
        }
        return FRONT_MATTER + body;
    }
}
