package se.deversity.vibetags.processor.internal.content.platforms;

import se.deversity.vibetags.processor.model.TaggedElement;
import java.util.List;
import se.deversity.vibetags.processor.model.GuardrailModel;
import se.deversity.vibetags.processor.internal.content.FormatterRegistry;
import se.deversity.vibetags.processor.internal.content.Platform;
import se.deversity.vibetags.processor.internal.content.PlatformRenderer;
import se.deversity.vibetags.processor.internal.content.RenderingContext;
import se.deversity.vibetags.processor.internal.content.SectionCatalog;

import static se.deversity.vibetags.processor.internal.content.platforms.AnnotationSections.section;

/**
 * PlatformRenderer for generating `.github/copilot-instructions.md`.
 */
public final class CopilotRenderer implements PlatformRenderer {

    private static final List<AnnotationSections.Section> SECTIONS = List.of(
        section(Platform.COPILOT, SectionCatalog.Key.AUDIT, GuardrailModel::audit, FormatterRegistry.audit()),
        section(Platform.COPILOT, SectionCatalog.Key.IGNORE, GuardrailModel::ignore, FormatterRegistry.ignore()),
        section(Platform.COPILOT, SectionCatalog.Key.DRAFT, GuardrailModel::draft, FormatterRegistry.draft()),
        section(Platform.COPILOT, SectionCatalog.Key.PRIVACY, GuardrailModel::privacy, FormatterRegistry.privacy()),
        section(Platform.COPILOT, SectionCatalog.Key.CORE, GuardrailModel::core, FormatterRegistry.core()),
        section(Platform.COPILOT, SectionCatalog.Key.PERFORMANCE, GuardrailModel::performance, FormatterRegistry.performance()),
        section(Platform.COPILOT, SectionCatalog.Key.CONTRACT, GuardrailModel::contract, FormatterRegistry.contract()),
        section(Platform.COPILOT, SectionCatalog.Key.TEST_DRIVEN, GuardrailModel::testDriven, FormatterRegistry.testDriven()),
        section(Platform.COPILOT, SectionCatalog.Key.THREAD_SAFE, GuardrailModel::threadSafe, FormatterRegistry.threadSafe()),
        section(Platform.COPILOT, SectionCatalog.Key.IMMUTABLE, GuardrailModel::immutable, FormatterRegistry.immutable()),
        section(Platform.COPILOT, SectionCatalog.Key.DEPRECATED, GuardrailModel::deprecated, FormatterRegistry.deprecated()),
        section(Platform.COPILOT, SectionCatalog.Key.OBSERVABILITY, GuardrailModel::observability, FormatterRegistry.observability()),
        section(Platform.COPILOT, SectionCatalog.Key.REGULATION, GuardrailModel::regulation, FormatterRegistry.regulation()),
        section(Platform.COPILOT, SectionCatalog.Key.PARALLEL_TESTS, GuardrailModel::parallelTests, FormatterRegistry.parallelTests()),
        section(Platform.COPILOT, SectionCatalog.Key.LEGACY_BRIDGE, GuardrailModel::legacyBridge, FormatterRegistry.legacyBridge()),
        section(Platform.COPILOT, SectionCatalog.Key.ARCHITECTURE, GuardrailModel::architecture, FormatterRegistry.architecture()),
        section(Platform.COPILOT, SectionCatalog.Key.PUBLIC_API, GuardrailModel::publicApi, FormatterRegistry.publicApi()),
        section(Platform.COPILOT, SectionCatalog.Key.STRICT_EXCEPTIONS, GuardrailModel::strictExceptions, FormatterRegistry.strictExceptions()),
        section(Platform.COPILOT, SectionCatalog.Key.STRICT_TYPES, GuardrailModel::strictTypes, FormatterRegistry.strictTypes()),
        section(Platform.COPILOT, SectionCatalog.Key.INTERNATIONALIZED, GuardrailModel::internationalized, FormatterRegistry.internationalized()),
        section(Platform.COPILOT, SectionCatalog.Key.STRICT_CLASSPATH, GuardrailModel::strictClasspath, FormatterRegistry.strictClasspath()),
        section(Platform.COPILOT, SectionCatalog.Key.SCHEMA_SAFE, GuardrailModel::schemaSafe, FormatterRegistry.schemaSafe()),
        section(Platform.COPILOT, SectionCatalog.Key.IDEMPOTENT, GuardrailModel::idempotent, FormatterRegistry.idempotent()),
        section(Platform.COPILOT, SectionCatalog.Key.FEATURE_FLAG, GuardrailModel::featureFlag, FormatterRegistry.featureFlag()),
        section(Platform.COPILOT, SectionCatalog.Key.SECURE, GuardrailModel::secure, FormatterRegistry.secure())
    );

    /** The head above plus the shared tail, so a new annotation is listed once, in {@link AnnotationSections}. */
    private static final List<AnnotationSections.Section> ALL_SECTIONS = AnnotationSections.concat(
        SECTIONS, AnnotationSections.newestAnnotationSections(Platform.COPILOT));

    @Override
    public String render(GuardrailModel model, Platform platform, RenderingContext context) {
        StringBuilder sb = new StringBuilder(context.estimatedContentSize());
        boolean indexed = GranularIndexSection.indexActive(platform, context);
        sb.append("# GitHub Copilot Instructions\n")
          .append(context.getGeneratedHeader())
          .append("# AUTO-GENERATED BY VIBETAGS. Do not edit manually.\n");

        // The locked heading is dropped when nothing is locked: empty headings are what made a supposedly lean
        // copilot-instructions.md bulkier than the full merge it replaced (issue #319) and caused double blank lines.
        if (!model.locked().isEmpty()) {
            sb.append("\n## Locked Files — DO NOT MODIFY\nDo not suggest changes to the following files:\n\n");
            for (TaggedElement e : model.locked()) {
                FormatterRegistry.locked().format(e, sb, Platform.COPILOT);
            }
        }

        if (indexed) {
            // Granular sibling opted in: keep the always-loaded safety buckets inline and index the
            // rest to the scoped .github/instructions files (context detail moves there too).
            AnnotationSections.renderInlineSafetySections(sb, model, Platform.COPILOT);
            GranularIndexSection.appendMarkdownIndex(sb, platform, context);
        } else {
            sb.append("\n## Contextual Guidelines\n");
            for (TaggedElement e : model.context()) {
                FormatterRegistry.context().format(e, sb, Platform.COPILOT);
            }

            AnnotationSections.render(sb, model, Platform.COPILOT, ALL_SECTIONS);
        }

        return sb.toString();
    }
}
