package se.deversity.vibetags.processor.internal.content.platforms;

import java.util.List;
import se.deversity.vibetags.processor.internal.AnnotationCollector;
import se.deversity.vibetags.processor.internal.content.Escape;
import se.deversity.vibetags.processor.internal.content.Platform;
import se.deversity.vibetags.processor.internal.content.PlatformRenderer;
import se.deversity.vibetags.processor.internal.content.RenderingContext;

/**
 * PlatformRenderer for generating Ellipsis's {@code ellipsis.yaml} review configuration.
 * Each VibeTags guardrail becomes one entry in {@code pr_review.rules} so Ellipsis fails or
 * comments on pull requests that breach a guardrail.
 */
public final class EllipsisRenderer implements PlatformRenderer {
    @Override
    public String render(AnnotationCollector collector, Platform platform, RenderingContext context) {
        StringBuilder sb = new StringBuilder(1024);
        sb.append("# AUTO-GENERATED BY VIBETAGS\n")
          .append(context.getGeneratedHeader())
          .append("# Ellipsis AI review configuration. Do not edit manually.\n\n")
          .append("version: 1.3\n")
          .append("pr_review:\n")
          .append("  rules:\n");

        List<String> rules = GuardrailInstructionBlock.lines(collector);
        if (rules.isEmpty()) {
            sb.append("    []\n");
        } else {
            for (String rule : rules) {
                // YAML 1.2 double-quoted scalars accept the JSON escapes, so the shared escaper is
                // the right one here — as sweep.yaml and .plandex.yaml already do. The private copy
                // this replaces handled only \ and ", letting control characters through raw, which
                // a YAML double-quoted scalar forbids: the file then fails to parse and Ellipsis
                // silently reviews against nothing.
                sb.append("    - \"").append(Escape.json(rule)).append("\"\n");
            }
        }
        return sb.toString();
    }
}
