package se.deversity.vibetags.processor.internal.content.platforms;

import se.deversity.vibetags.processor.model.TaggedElement;
import java.util.ArrayList;
import java.util.List;
import se.deversity.vibetags.processor.model.GuardrailModel;
import se.deversity.vibetags.processor.internal.content.AnnotationDescriptor;
import se.deversity.vibetags.processor.internal.content.AnnotationDescriptors;
import se.deversity.vibetags.processor.internal.content.Platform;
import se.deversity.vibetags.processor.internal.content.RenderingContext;

/**
 * Builds a single, human-readable guardrail-instruction block covering every collected
 * annotation. Shared by the PR-reviewer renderers (CodeRabbit, Ellipsis, PR-Agent) and the
 * Roo custom-mode renderer, which all need the same prose summary embedded into their own
 * schema (YAML block scalars, TOML multiline strings, etc.).
 *
 * <p>{@link #reviewDocument} builds on {@link #build} for the two reviewers whose configuration
 * is a whole Markdown file rather than a field inside one: Gemini Code Assist's
 * {@code .gemini/styleguide.md} and Greptile's {@code .greptile/rules.md}. Those two documents
 * are identical apart from a heading suffix and a product name, so they share one
 * implementation; a change to the wording now reaches both or neither.
 *
 * <p>Formatting is delegated to the per-annotation formatters using {@link Platform#INTERPRETER}
 * (a free-text, single-line-per-element style already supported by every formatter), so the
 * block stays in lock-step with the rest of the generated guardrails without duplicating the
 * per-annotation prose here.
 */
final class GuardrailInstructionBlock {

    private GuardrailInstructionBlock() {}

    /**
     * Renders the guardrail summary as one bullet line per annotated element. Returns an empty
     * string when no annotations were collected.
     */
    static String build(GuardrailModel model) {
        StringBuilder sb = new StringBuilder(1024);
        Platform p = Platform.INTERPRETER;
        for (AnnotationDescriptor descriptor : AnnotationDescriptors.ALL) {
            for (TaggedElement e : model.of(descriptor.type())) {
                descriptor.formatter().format(e, sb, p);
            }
        }
        return sb.toString();
    }

    /** The guardrail summary split into non-blank lines (leading "- "/"* " bullet stripped). */
    static List<String> lines(GuardrailModel model) {
        List<String> out = new ArrayList<>();
        for (String line : build(model).split("\n", -1)) {
            String trimmed = line.strip();
            if (trimmed.isEmpty()) continue;
            if (trimmed.startsWith("- ") || trimmed.startsWith("* ")) {
                trimmed = trimmed.substring(2).strip();
            }
            out.add(trimmed);
        }
        return out;
    }

    /** Indents every line of {@code block} by {@code spaces}, preserving blank lines as empty. */
    static String indent(String block, int spaces) {
        String pad = " ".repeat(spaces);
        StringBuilder sb = new StringBuilder(block.length() + 32);
        for (String line : block.split("\n", -1)) {
            if (line.isEmpty()) {
                sb.append('\n');
            } else {
                sb.append(pad).append(line).append('\n');
            }
        }
        return sb.toString();
    }

    /**
     * Renders a complete Markdown review document for a PR reviewer whose per-repository
     * configuration is a whole file rather than a field inside one.
     *
     * <p>Markdown, so {@code GuardrailFileWriter} gives the file HTML-comment markers and anything
     * the user wrote around them survives regeneration.
     *
     * @param headingSuffix what follows the project name in the H1, e.g. {@code "review rules"}
     * @param productName   the reviewer as it should name itself, e.g. {@code "Greptile"}
     */
    static String reviewDocument(
            GuardrailModel model, RenderingContext context, String headingSuffix, String productName) {
        StringBuilder sb = new StringBuilder(context.estimatedContentSize());
        sb.append("# ").append(context.getProjectName()).append(' ').append(headingSuffix).append('\n')
          .append(context.getGeneratedHeader())
          .append("# AUTO-GENERATED BY VIBETAGS. ").append(productName)
          .append(" reads this file when reviewing a pull request in this repository.\n\n")
          .append("## VibeTags guardrails\n\n");

        String block = build(model);
        if (block.isBlank()) {
            sb.append("No VibeTags guardrails are currently declared.\n");
        } else {
            sb.append("Flag any change in this pull request that violates one of the following:\n\n")
              .append(block.strip()).append('\n');
        }
        return sb.toString();
    }
}
