package se.deversity.vibetags.processor.internal.content.platforms;

import se.deversity.vibetags.processor.model.TaggedElement;
import se.deversity.vibetags.processor.model.GuardrailModel;
import se.deversity.vibetags.processor.internal.content.FormatterRegistry;
import se.deversity.vibetags.processor.internal.content.Platform;
import se.deversity.vibetags.processor.internal.content.PlatformDescriptor;
import se.deversity.vibetags.processor.internal.content.PlatformDescriptors;
import se.deversity.vibetags.processor.internal.content.PlatformRenderer;
import se.deversity.vibetags.processor.internal.content.RenderingContext;

/**
 * A highly reusable PlatformRenderer for generating all standalone ignore/exclusion files.
 */
public final class IgnoreFileRenderer implements PlatformRenderer {
    @Override
    public String render(GuardrailModel model, Platform platform, RenderingContext context) {
        // A module with nothing to ignore contributes nothing, not a header.
        //
        // The header alone is non-blank, and ModuleSidecar.mergeFor() wraps every non-blank
        // contribution in its own module sub-markers. In a reactor, modules carrying no @AIIgnore
        // therefore each added a full "AUTO-GENERATED BY VIBETAGS / Generated by VibeTags /
        // <platform>-specific exclusion list" block to the merged file — three modules produced
        // three copies of the boilerplate around one real exclusion line. Returning empty lets the
        // merge skip them, which is what "this module has no opinion" should look like.
        if (model.ignore().isEmpty()) {
            return "";
        }
        StringBuilder sb = new StringBuilder(512);
        String name = getPlatformSpecificName(platform);
        sb.append("# AUTO-GENERATED BY VIBETAGS\n")
          .append(context.getGeneratedHeader())
          .append("# ").append(name).append("-specific exclusion list.\n");

        for (TaggedElement e : model.ignore()) {
            FormatterRegistry.ignore().format(e, sb, platform);
        }
        return sb.toString();
    }

    /**
     * The tool name in the header comment of an exclusion file.
     *
     * <p>Declared by the platform entry rather than by a switch here (<a
     * href="https://github.com/PIsberg/vibetags/issues/762">issue #762</a>). The switch had a
     * {@code default} arm, so a new exclusion file whose label nobody added shipped a header that
     * said "AI Platform" and no test could tell that from a deliberate one. The fallback stays for
     * a platform that is not an exclusion file at all and should never reach here.
     */
    private static String getPlatformSpecificName(Platform platform) {
        PlatformDescriptor descriptor = PlatformDescriptors.byPlatform(platform);
        String label = descriptor == null ? null : descriptor.ignoreLabel();
        return label == null ? "AI Platform" : label;
    }
}
