package se.deversity.vibetags.processor.internal.content.platforms;

import javax.lang.model.element.Element;
import se.deversity.vibetags.processor.internal.AnnotationCollector;
import se.deversity.vibetags.processor.internal.content.FormatterRegistry;
import se.deversity.vibetags.processor.internal.content.Platform;
import se.deversity.vibetags.processor.internal.content.PlatformRenderer;
import se.deversity.vibetags.processor.internal.content.RenderingContext;

/**
 * A highly reusable PlatformRenderer for generating all standalone ignore/exclusion files.
 */
public final class IgnoreFileRenderer implements PlatformRenderer {
    @Override
    public String render(AnnotationCollector collector, Platform platform, RenderingContext context) {
        StringBuilder sb = new StringBuilder(512);
        String name = getPlatformSpecificName(platform);
        sb.append("# AUTO-GENERATED BY VIBETAGS\n")
          .append(context.getGeneratedHeader())
          .append("# ").append(name).append("-specific exclusion list.\n");

        for (Element e : collector.ignore()) {
            FormatterRegistry.ignore().format(e, sb, platform);
        }
        return sb.toString();
    }

    private static String getPlatformSpecificName(Platform platform) {
        switch (platform) {
            case CURSOR_IGNORE:      return "Cursor";
            case CLAUDE_IGNORE:      return "Claude";
            case COPILOT_IGNORE:     return "Copilot";
            case QWEN_IGNORE:        return "Qwen";
            case CODY_IGNORE:        return "Cody";
            case SUPERMAVEN_IGNORE:  return "Supermaven";
            case DOUBLE_IGNORE:      return "Double.bot";
            case CODEIUM_IGNORE:     return "Codeium";
            case ANTIGRAVITY_IGNORE: return "Antigravity AI";
            case AIDER_IGNORE:       return "Aider";
            default:                 return "AI Platform";
        }
    }
}
