package se.deversity.vibetags.processor.internal.content.platforms;

import org.jspecify.annotations.Nullable;
import se.deversity.vibetags.processor.model.GuardrailModel;
import se.deversity.vibetags.processor.internal.content.Platform;
import se.deversity.vibetags.processor.internal.content.PlatformRenderer;
import se.deversity.vibetags.processor.internal.content.RenderingContext;

/**
 * PlatformRenderer for generating `.junie/guidelines.md`.
 * Reuses the CursorRenderer and replaces the header.
 */
public final class JunieRenderer implements PlatformRenderer {
    // CursorRenderer is stateless — one shared instance is sufficient.
    private static final CursorRenderer CURSOR_RENDERER = new CursorRenderer();

    @Override
    public @Nullable String render(GuardrailModel model, Platform platform, RenderingContext context) {
        String cursorContent = CURSOR_RENDERER.render(model, platform, context);
        if (cursorContent == null) {
            return null;
        }
        String cursorHeader = "# AUTO-GENERATED AI RULES\n" + context.getGeneratedHeader() + "# Do not edit manually.\n\n## LOCKED FILES (DO NOT EDIT)\n";
        String junieHeader = "# JetBrains Junie Guidelines\n" + context.getGeneratedHeader() + "# AUTO-GENERATED BY VIBETAGS. Do not edit manually.\n\n## Locked Files (Do Not Modify)\nThe following files must not be modified:\n\n";
        return cursorContent.replace(cursorHeader, junieHeader);
    }
}
