package se.deversity.vibetags.processor.internal.content.platforms;

import org.jspecify.annotations.Nullable;
import se.deversity.vibetags.processor.model.GuardrailModel;
import se.deversity.vibetags.processor.internal.content.Platform;
import se.deversity.vibetags.processor.internal.content.PlatformRenderer;
import se.deversity.vibetags.processor.internal.content.RenderingContext;

/**
 * PlatformRenderer for Junie's two guidelines files: {@code .junie/AGENTS.md}, which Junie checks
 * first, and the legacy {@code .junie/guidelines.md} (#673). Both get the same rendering.
 * Reuses the CursorRenderer and replaces the header.
 *
 * <p>{@code .junie/AGENTS.md} is not the root {@code AGENTS.md}: that one is the Codex service,
 * written only as the sole AI config file or with a marker pair (invariant 4), and this renderer
 * never produces its content.
 */
public final class JunieRenderer implements PlatformRenderer {
    // CursorRenderer is stateless — one shared instance is sufficient.
    private static final CursorRenderer CURSOR_RENDERER = new CursorRenderer();

    @Override
    public @Nullable String render(GuardrailModel model, Platform platform, RenderingContext context) {
        String cursorContent = CURSOR_RENDERER.render(model, platform, context);
        if (cursorContent == null) {
            return null;
        }
        String cursorHeader = AnnotationSections.lockedPreambleOpening(context.getGeneratedHeader());
        if (model.locked().isEmpty()) {
            String junieHeader = "# JetBrains Junie Guidelines\n" + context.getGeneratedHeader() + "# AUTO-GENERATED BY VIBETAGS. Do not edit manually.\n";
            return cursorContent.replace(cursorHeader, junieHeader);
        }
        String junieHeader = "# JetBrains Junie Guidelines\n" + context.getGeneratedHeader() + "# AUTO-GENERATED BY VIBETAGS. Do not edit manually.\n\n## Locked Files (Do Not Modify)\nThe following files must not be modified:\n\n";
        return cursorContent.replace(cursorHeader, junieHeader);
    }
}
