package se.deversity.vibetags.processor.internal.content.platforms;

import se.deversity.vibetags.processor.internal.AnnotationCollector;
import se.deversity.vibetags.processor.internal.content.Escape;
import se.deversity.vibetags.processor.internal.content.Platform;
import se.deversity.vibetags.processor.internal.content.PlatformRenderer;
import se.deversity.vibetags.processor.internal.content.RenderingContext;

/**
 * PlatformRenderer for generating Qodo/Codium PR-Agent's {@code .pr_agent.toml} configuration.
 * The VibeTags guardrails are injected as {@code extra_instructions} for the reviewer and
 * code-suggestion tools. The {@code .toml} file is overwritten wholesale (no markers).
 */
public final class PrAgentRenderer implements PlatformRenderer {
    @Override
    public String render(AnnotationCollector collector, Platform platform, RenderingContext context) {
        String block = GuardrailInstructionBlock.build(collector).strip();
        String instructions = block.isBlank()
            ? "No VibeTags guardrails are currently declared."
            : "Enforce the following VibeTags guardrails. Flag any change that violates them:\n" + block;

        String body = Escape.tomlMultiline(instructions);

        StringBuilder sb = new StringBuilder(1024);
        sb.append("# AUTO-GENERATED BY VIBETAGS\n")
          .append(context.getGeneratedHeader())
          .append("# Qodo/Codium PR-Agent configuration. Do not edit manually.\n\n")
          .append("[pr_reviewer]\n")
          .append("extra_instructions = \"\"\"\n")
          .append(body).append("\n")
          .append("\"\"\"\n\n")
          .append("[pr_code_suggestions]\n")
          .append("extra_instructions = \"\"\"\n")
          .append(body).append("\n")
          .append("\"\"\"\n");
        return sb.toString();
    }
}
