package se.deversity.vibetags.processor.internal;

import ch.qos.logback.classic.Level;
import ch.qos.logback.classic.LoggerContext;
import ch.qos.logback.classic.spi.ILoggingEvent;
import ch.qos.logback.core.read.ListAppender;
import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.io.TempDir;
import org.slf4j.LoggerFactory;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.List;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNull;
import static org.junit.jupiter.api.Assertions.assertNotNull;
import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertTrue;
import se.deversity.vibetags.annotations.AIContext;

/**
 * The writer's DEBUG events are a contract, not commentary.
 *
 * <p>A test can assert that a file was not rewritten. It cannot, from the return value alone,
 * assert <em>why</em>: an unchanged file and a file skipped because no annotations were found
 * both return {@code false}. The {@code reason=} on each {@code write.skip} is the only place
 * that distinction is observable, which is what makes these events worth pinning.
 *
 * <p>Renaming an event asserted here is a breaking change. See CLAUDE.md, "Logging".
 */
@DisplayName("GuardrailFileWriter DEBUG events")
@AIContext(
    focus = "The event names and reason= values asserted here are the writer's published "
        + "contract, not test scaffolding: people grep build logs for write.skip and "
        + "reason=cache-unchanged. Add a case when you add an event",
    avoids = "Renaming or merging an asserted event to tidy the assertions; that is a "
        + "breaking change for every consumer parsing a build log, and nothing else catches it"
)
class GuardrailFileWriterLogContractTest {

    private static final String HEADER =
        "# Generated by VibeTags | https://github.com/PIsberg/vibetags\n";

    private ch.qos.logback.classic.Logger logger;
    private ListAppender<ILoggingEvent> appender;

    /**
     * The suite runs tests in parallel, so a logger shared by name would mix one test's events
     * into another's assertions. Each test captures its own logger instead.
     */
    @BeforeEach
    void captureDebugLog(org.junit.jupiter.api.TestInfo testInfo) {
        LoggerContext context = (LoggerContext) LoggerFactory.getILoggerFactory();
        logger = context.getLogger(
            GuardrailFileWriterLogContractTest.class.getName() + "." + testInfo.getDisplayName());
        logger.setLevel(Level.DEBUG);
        appender = new ListAppender<>();
        appender.setContext(context);
        appender.start();
        logger.addAppender(appender);
    }

    @AfterEach
    void detach() {
        logger.detachAppender(appender);
        appender.stop();
    }

    private List<String> events() {
        return appender.list.stream().map(ILoggingEvent::getFormattedMessage).toList();
    }

    private boolean logged(String fragment) {
        return events().stream().anyMatch(m -> m.contains(fragment));
    }

    @Test
    @DisplayName("a byte-identical rewrite says why it was skipped")
    void identicalContentSkipsWithAReason(@TempDir Path dir) throws IOException {
        Path file = dir.resolve("AGENTS.md");
        String body = HEADER + "\nrule one\n";
        GuardrailFileWriter writer = new GuardrailFileWriter(HEADER, null, logger);

        assertTrue(writer.writeFileIfChanged(file.toString(), body, true),
            "first write creates the file");
        assertTrue(logged("write.commit"), "the commit is recorded: " + events());

        appender.list.clear();
        assertFalse(writer.writeFileIfChanged(file.toString(), body, true),
            "identical content is not rewritten");
        assertTrue(logged("write.skip"), "a skip is recorded: " + events());
        assertTrue(logged("reason=identical-bytes"),
            "the skip carries the reason that distinguishes it from every other skip: " + events());
        assertTrue(logged("file=AGENTS.md"), "events name the file, not the absolute path");
    }

    @Test
    @DisplayName("a rule file whose generated block could not be removed logs reason=io-error")
    void failedScrubLogsIoError(@TempDir Path dir) throws Exception {
        Path rule = dir.resolve("com-example-Gone.md");
        Files.writeString(rule, GuardrailFileWriter.MARKER_START_MD + "\n" + HEADER + "rule\n"
            + GuardrailFileWriter.MARKER_END_MD + "\n\nThe developer's note.\n");
        GuardrailFileWriter writer = new GuardrailFileWriter(HEADER, null, logger);

        try (AutoCloseable held = blockRewrite(rule)) {
            assertEquals(List.of(), writer.cleanupGranularDirectory(dir, ".md", java.util.Set.of()),
                "a removal that failed is not reported as one");
        }
        assertTrue(logged("write.skip file=com-example-Gone.md reason=io-error"),
            "the failed rewrite names its reason: " + events());
    }

    /**
     * Makes replacing {@code file} fail until closed: an open handle on Windows, which does not
     * share delete access with a rename over the file, and a read-only directory elsewhere.
     */
    private static AutoCloseable blockRewrite(Path file) throws IOException {
        if (System.getProperty("os.name").toLowerCase(java.util.Locale.ROOT).contains("win")) {
            return new java.io.FileInputStream(file.toFile());
        }
        Path parent = file.getParent();
        java.util.Set<java.nio.file.attribute.PosixFilePermission> before = Files.getPosixFilePermissions(parent);
        Files.setPosixFilePermissions(parent, java.nio.file.attribute.PosixFilePermissions.fromString("r-xr-xr-x"));
        AutoCloseable restore = () -> Files.setPosixFilePermissions(parent, before);
        if (Files.isWritable(parent)) {
            try {
                restore.close();
            } catch (Exception e) {
                throw new IOException(e);
            }
            org.junit.jupiter.api.Assumptions.abort("a read-only directory does not block a rewrite here");
        }
        return restore;
    }

    @Test
    @DisplayName("a hand-written whole-file output is skipped with reason=hand-written-whole-file")
    void handWrittenWholeFileSkipsWithItsReason(@TempDir Path dir) throws IOException {
        Path file = dir.resolve("config.toml");
        String handWritten = "[pr_reviewer]\nnum_code_suggestions = 3\n";
        Files.writeString(file, handWritten);
        GuardrailFileWriter writer = new GuardrailFileWriter(HEADER, null, logger);

        assertFalse(writer.writeFileIfChanged(file.toString(), HEADER + "[pr_reviewer]\n", true),
            "a configuration VibeTags did not write is not replaced");
        assertEquals(handWritten, Files.readString(file));
        assertTrue(logged("write.skip file=config.toml reason=hand-written-whole-file"),
            "the skip names its own reason: " + events());
    }

    @Test
    @DisplayName("a .pr_agent.toml the span merge cannot read is skipped with the merge's reason")
    void unmergeablePrAgentConfigSkipsWithTheMergesReason(@TempDir Path dir) throws IOException {
        Path file = dir.resolve(".pr_agent.toml");
        String handWritten = "[pr_reviewer]\nextra_instructions = \"one line\"\n";
        Files.writeString(file, handWritten);
        GuardrailFileWriter writer = new GuardrailFileWriter(HEADER, null, logger);

        assertFalse(writer.writeFileIfChanged(file.toString(),
            HEADER + "[pr_reviewer]\nextra_instructions = \"\"\"\nrule\n\"\"\"\n", true));
        assertEquals(handWritten, Files.readString(file));
        assertTrue(logged("write.skip file=.pr_agent.toml reason=not-multiline-string"),
            "the skip names why the merge refused: " + events());
    }

    @Test
    @DisplayName("a non-marker file with matching size but differing bytes logs reason=bytes-differ")
    void exactSizeMismatchLogsBytesDiffer(@TempDir Path dir) throws IOException {
        Path file = dir.resolve("settings.toml");
        // Behind the writer's header: a whole-file output without it is hand-written and left alone.
        String initial = HEADER + "key = \"value1\"\n";
        String updated = HEADER + "key = \"value2\"\n";
        Files.writeString(file, initial);
        GuardrailFileWriter writer = new GuardrailFileWriter(HEADER, null, logger);

        assertTrue(writer.writeFileIfChanged(file.toString(), updated, true),
            "content differs with same size, so file is updated");
        assertTrue(logged("write.update"), "an update is recorded: " + events());
        assertTrue(logged("reason=bytes-differ"),
            "exact-size mismatch logs reason=bytes-differ, not size-differs: " + events());
    }

    @Test
    @DisplayName("an empty round skips for a different, distinguishable reason")
    void noNewRulesSkipsWithItsOwnReason(@TempDir Path dir) throws IOException {
        Path file = dir.resolve("AGENTS.md");
        Files.writeString(file, HEADER + "\nrule one\n");
        GuardrailFileWriter writer = new GuardrailFileWriter(HEADER, null, logger);

        assertFalse(writer.writeFileIfChanged(file.toString(), HEADER + "\nrule two\n", false),
            "content differs but the round contributed nothing, so nothing is written");
        assertTrue(logged("reason=no-new-rules"),
            "this skip is not the same as an unchanged file, and the log says so: " + events());
    }

    @Test
    @DisplayName("a file that is not UTF-8 skips with reason=not-utf8 and names the encoding")
    void unreadableEncodingSkipsWithItsOwnReason(@TempDir Path dir) throws IOException {
        Path file = dir.resolve("CLAUDE.md");
        Files.write(file, "\uFEFFnotes\n".getBytes(java.nio.charset.StandardCharsets.UTF_16LE));
        GuardrailFileWriter writer = new GuardrailFileWriter(HEADER, null, logger);

        assertFalse(writer.writeFileIfChanged(file.toString(), HEADER + "\nrule one\n", true),
            "a file that cannot be decoded is not written");
        assertTrue(logged("write.skip file=CLAUDE.md reason=not-utf8 encoding=UTF-16LE"),
            "an encoding skip is distinguishable from a failed write: " + events());
    }

    @Test
    @DisplayName("nothing is logged at INFO or above during ordinary writes")
    void theNarrativeStaysAtDebug(@TempDir Path dir) throws IOException {
        Path file = dir.resolve("CLAUDE.md");
        GuardrailFileWriter writer = new GuardrailFileWriter(HEADER, null, logger);
        writer.writeFileIfChanged(file.toString(), HEADER + "\nrule\n", true);
        writer.writeFileIfChanged(file.toString(), HEADER + "\nrule\n", true);

        assertEquals(List.of(),
            appender.list.stream()
                .filter(e -> e.getLevel().isGreaterOrEqual(Level.INFO))
                .map(ILoggingEvent::getFormattedMessage)
                .toList(),
            "INFO is the operator's budget: a routine write must not spend it");
    }

    /**
     * A removal is a decision like any other. The rule files of a departed module are deleted by
     * name, and that deletion is what invalidates their cache entries; without the event there is
     * no way to tell from the log whether a missing file was removed by VibeTags or by hand.
     */
    @Test
    @DisplayName("a deletion is logged as a commit, and a dry-run deletion as a skip with its reason")
    void deletionsAreLoggedLikeWrites(@TempDir Path dir) throws IOException {
        Path file = dir.resolve("com-example-Gone.md");
        Files.writeString(file, HEADER + "\nrule\n");

        GuardrailFileWriter dryRun = new GuardrailFileWriter(HEADER, null, logger, null, true);
        assertTrue(dryRun.deleteIfExists(file), "dry-run reports the file it would have removed");
        assertTrue(Files.exists(file), "and leaves it in place");
        assertTrue(logged("delete.skip file=com-example-Gone.md reason=dry-run"),
            "the dry-run must say why nothing was deleted: " + events());
        assertEquals(List.of(file.toString()), dryRun.dryRunChanges(),
            "check mode reads the removal off the same ledger as the writes");

        GuardrailFileWriter writer = new GuardrailFileWriter(HEADER, null, logger);
        assertTrue(writer.deleteIfExists(file));
        assertFalse(Files.exists(file));
        assertTrue(logged("delete.commit file=com-example-Gone.md"),
            "a real deletion is a commit event: " + events());
        assertFalse(writer.deleteIfExists(file), "a second delete of a missing file is a quiet no-op");
    }

    /**
     * Placeholder integrity, asserted at runtime because nothing can assert it statically.
     *
     * <p>Every event this writer emits goes through {@code debug(String event, Object... args)},
     * whose format string is a <em>parameter</em>, not a literal. Checkers that count {@code {}}
     * against arguments — codekoll's CK-SLF4J-PLACEHOLDER, SpotBugs' SLF4J detectors — only ever
     * see that forwarding call and skip it, because they require a constant format. So a mismatch
     * in any caller reaches the log with no tool objecting: a surplus {@code {}} prints literally,
     * and a surplus argument is dropped without a word. The wrapper is worth keeping (it is what
     * makes the level guard and the null-logger check single-sited), so the check moves here.
     */
    @Test
    @DisplayName("every DEBUG event balances its {} placeholders against its arguments")
    void placeholdersMatchArguments(@TempDir Path dir) throws IOException {
        Path file = dir.resolve("AGENTS.md");
        String body = HEADER + "\nrule one\n";
        GuardrailFileWriter writer = new GuardrailFileWriter(HEADER, null, logger);

        // Exercise each distinct event shape: a commit, an identical-bytes skip, an empty round.
        writer.writeFileIfChanged(file.toString(), body, true);
        writer.writeFileIfChanged(file.toString(), body, true);
        writer.writeFileIfChanged(file.toString(), HEADER + "\nrule two\n", false);

        assertFalse(appender.list.isEmpty(), "the narrative must actually have run");

        for (ILoggingEvent event : appender.list) {
            Object[] args = event.getArgumentArray();
            int supplied = args == null ? 0 : args.length;
            // SLF4J convention: a trailing Throwable is the stack trace, not a substitution.
            if (supplied > 0 && args[supplied - 1] instanceof Throwable) {
                supplied--;
            }
            int placeholders = countPlaceholders(event.getMessage());
            assertEquals(placeholders, supplied,
                "'" + event.getMessage() + "' has " + placeholders + " {} but " + supplied
                    + " argument(s); SLF4J drops the difference silently");
            assertFalse(event.getFormattedMessage().contains("{}"),
                "an unsubstituted {} reached the log: " + event.getFormattedMessage());
        }
    }

    private static int countPlaceholders(String format) {
        int count = 0;
        for (int i = format.indexOf("{}"); i >= 0; i = format.indexOf("{}", i + 2)) {
            count++;
        }
        return count;
    }

    @Test
    @DisplayName("fileName extracts simple name from path or falls back to path string")
    void fileNameExtractsNameOrFallsBack() {
        assertEquals("test.md", GuardrailFileWriter.fileName(Path.of("a/b/test.md")));
        // Path.of("") has an empty-but-present file name, so it does not reach the fallback.
        assertEquals("", GuardrailFileWriter.fileName(Path.of("")));
        // getFileName() is null only for a root, which is the one input the fallback exists for.
        Path root = Path.of("x").toAbsolutePath().getRoot();
        assertNotNull(root, "an absolute path always has a root");
        assertNull(root.getFileName(), "a root is the case the fallback is written for");
        assertEquals(root.toString(), GuardrailFileWriter.fileName(root));
    }
}
