package se.deversity.vibetags.processor.internal;

import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.io.TempDir;
import org.junit.jupiter.params.ParameterizedTest;
import org.junit.jupiter.params.provider.ValueSource;

import javax.annotation.processing.Messager;
import javax.lang.model.element.AnnotationMirror;
import javax.lang.model.element.AnnotationValue;
import javax.lang.model.element.Element;
import javax.tools.Diagnostic;
import java.io.IOException;
import java.nio.charset.Charset;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.List;

import static org.junit.jupiter.api.Assertions.assertArrayEquals;
import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertTrue;

/**
 * A guardrail file VibeTags cannot read as UTF-8 is left alone, and the warning says what to do.
 *
 * <p>Windows PowerShell 5.1's {@code echo "" > CLAUDE.md}, the obvious way to opt a platform in on
 * that shell, writes UTF-16 LE with a byte order mark. VibeTags reads and writes UTF-8, so the
 * read failed and the build printed {@code Failed to write AI rules file: ... Input length = 1}
 * on every compile (#878). Nothing was lost, but the file never got its guardrails and nothing in
 * the message said why. Writing the file back in UTF-8 would change its encoding under the user,
 * so the fix is the message: name the encoding and the remedy, and leave the bytes untouched.
 */
class GuardrailFileWriterEncodingTest {

    private static final String HEADER =
        "# Generated by VibeTags | https://github.com/PIsberg/vibetags\n";
    private static final String GENERATED = HEADER + "\n## Locked Files\n\n- `com.example.Ledger`\n";

    @ParameterizedTest(name = "{0}")
    @ValueSource(strings = {"UTF-16LE", "UTF-16BE"})
    @DisplayName("a UTF-16 file is left unchanged and the warning says to re-save it as UTF-8")
    void utf16FileGetsAnActionableWarning(String encoding, @TempDir Path dir) throws IOException {
        Path file = dir.resolve("CLAUDE.md");
        byte[] original = ("\uFEFFHand-written project notes.\n").getBytes(Charset.forName(encoding));
        Files.write(file, original);

        List<String> warnings = new ArrayList<>();
        GuardrailFileWriter writer = new GuardrailFileWriter(HEADER, capturing(warnings), null);

        assertFalse(writer.writeFileIfChanged(file.toString(), GENERATED, true),
            "a file that cannot be read cannot be merged into, so nothing is written");
        assertArrayEquals(original, Files.readAllBytes(file),
            "the user's file keeps its bytes, encoding included");
        assertEquals(1, warnings.size(), "one warning per file: " + warnings);
        String warning = warnings.get(0);
        assertTrue(warning.contains("CLAUDE.md"), "the warning names the file: " + warning);
        assertTrue(warning.contains("UTF-16"), "the warning names the encoding found: " + warning);
        assertTrue(warning.contains("Re-save it as UTF-8"), "the warning says what to do: " + warning);
        assertFalse(warning.contains("Input length"),
            "the decoder's byte count tells the user nothing: " + warning);
    }

    @Test
    @DisplayName("a file in another single-byte encoding is called not UTF-8, not UTF-16")
    void latin1FileIsReportedAsNotUtf8(@TempDir Path dir) throws IOException {
        Path file = dir.resolve("CLAUDE.md");
        byte[] original = "Caf\u00e9 notes.\n".getBytes(StandardCharsets.ISO_8859_1);
        Files.write(file, original);

        List<String> warnings = new ArrayList<>();
        GuardrailFileWriter writer = new GuardrailFileWriter(HEADER, capturing(warnings), null);

        assertFalse(writer.writeFileIfChanged(file.toString(), GENERATED, true));
        assertArrayEquals(original, Files.readAllBytes(file));
        assertEquals(1, warnings.size(), "one warning per file: " + warnings);
        String warning = warnings.get(0);
        assertTrue(warning.contains("not valid UTF-8"), "the warning names the problem: " + warning);
        assertFalse(warning.contains("UTF-16"), "there is no byte order mark to call it UTF-16: " + warning);
        assertTrue(warning.contains("Re-save it as UTF-8"), "the warning says what to do: " + warning);
    }

    @Test
    @DisplayName("re-saving the file as UTF-8 is enough: the next build writes it")
    void resavedFileIsWritten(@TempDir Path dir) throws IOException {
        Path file = dir.resolve("CLAUDE.md");
        Files.write(file, "\uFEFFHand-written project notes.\n".getBytes(StandardCharsets.UTF_16LE));
        List<String> warnings = new ArrayList<>();
        GuardrailFileWriter writer = new GuardrailFileWriter(HEADER, capturing(warnings), null);
        assertFalse(writer.writeFileIfChanged(file.toString(), GENERATED, true));

        // What the warning tells the user to do.
        Files.writeString(file, "Hand-written project notes.\n", StandardCharsets.UTF_8);

        assertTrue(writer.writeFileIfChanged(file.toString(), GENERATED, true),
            "the remedy the warning names has to work");
        String after = Files.readString(file, StandardCharsets.UTF_8);
        assertTrue(after.contains("Hand-written project notes."), after);
        assertTrue(after.contains("com.example.Ledger"), after);
    }

    @Test
    @DisplayName("a coding failure that is not the file's keeps the plain message")
    void unencodableContentIsNotBlamedOnTheFile(@TempDir Path dir) throws IOException {
        Path file = dir.resolve("CLAUDE.md");
        Files.writeString(file, "Hand-written project notes.\n", StandardCharsets.UTF_8);
        List<String> warnings = new ArrayList<>();
        GuardrailFileWriter writer = new GuardrailFileWriter(HEADER, capturing(warnings), null);

        // A lone surrogate cannot be encoded, so the write fails with the same exception type a
        // UTF-16 file raises on read. The file is valid UTF-8 and must not be called otherwise.
        assertFalse(writer.writeFileIfChanged(file.toString(), GENERATED + "- `\uD800`\n", true));
        assertEquals(1, warnings.size(), "one warning per file: " + warnings);
        assertTrue(warnings.get(0).contains("Failed to write AI rules file"), warnings.get(0));
        assertFalse(warnings.get(0).contains("Re-save it as UTF-8"),
            "telling the user to re-save a valid UTF-8 file sends them after the wrong problem: "
                + warnings.get(0));
    }

    private static Messager capturing(List<String> sink) {
        return new Messager() {
            @Override
            public void printMessage(Diagnostic.Kind k, CharSequence msg) {
                if (k == Diagnostic.Kind.WARNING) {
                    sink.add(msg.toString());
                }
            }

            @Override
            public void printMessage(Diagnostic.Kind k, CharSequence msg, Element e) {
                printMessage(k, msg);
            }

            @Override
            public void printMessage(Diagnostic.Kind k, CharSequence msg, Element e, AnnotationMirror a) {
                printMessage(k, msg);
            }

            @Override
            public void printMessage(Diagnostic.Kind k, CharSequence msg, Element e, AnnotationMirror a,
                                     AnnotationValue v) {
                printMessage(k, msg);
            }
        };
    }
}
