package se.deversity.vibetags.processor.internal;

import ch.qos.logback.classic.Level;
import ch.qos.logback.classic.LoggerContext;
import ch.qos.logback.classic.spi.ILoggingEvent;
import ch.qos.logback.core.read.ListAppender;
import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.io.TempDir;
import org.slf4j.LoggerFactory;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.List;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertTrue;

/**
 * The writer's DEBUG events are a contract, not commentary.
 *
 * <p>A test can assert that a file was not rewritten. It cannot, from the return value alone,
 * assert <em>why</em>: an unchanged file and a file skipped because no annotations were found
 * both return {@code false}. The {@code reason=} on each {@code write.skip} is the only place
 * that distinction is observable, which is what makes these events worth pinning.
 *
 * <p>Renaming an event asserted here is a breaking change. See CLAUDE.md, "Logging".
 */
@DisplayName("GuardrailFileWriter DEBUG events")
class GuardrailFileWriterLogContractTest {

    private static final String HEADER =
        "# Generated by VibeTags | https://github.com/PIsberg/vibetags\n";

    private ch.qos.logback.classic.Logger logger;
    private ListAppender<ILoggingEvent> appender;

    /**
     * The suite runs tests in parallel, so a logger shared by name would mix one test's events
     * into another's assertions. Each test captures its own logger instead.
     */
    @BeforeEach
    void captureDebugLog(org.junit.jupiter.api.TestInfo testInfo) {
        LoggerContext context = (LoggerContext) LoggerFactory.getILoggerFactory();
        logger = context.getLogger(
            GuardrailFileWriterLogContractTest.class.getName() + "." + testInfo.getDisplayName());
        logger.setLevel(Level.DEBUG);
        appender = new ListAppender<>();
        appender.setContext(context);
        appender.start();
        logger.addAppender(appender);
    }

    @AfterEach
    void detach() {
        logger.detachAppender(appender);
        appender.stop();
    }

    private List<String> events() {
        return appender.list.stream().map(ILoggingEvent::getFormattedMessage).toList();
    }

    private boolean logged(String fragment) {
        return events().stream().anyMatch(m -> m.contains(fragment));
    }

    @Test
    @DisplayName("a byte-identical rewrite says why it was skipped")
    void identicalContentSkipsWithAReason(@TempDir Path dir) throws IOException {
        Path file = dir.resolve("AGENTS.md");
        String body = HEADER + "\nrule one\n";
        GuardrailFileWriter writer = new GuardrailFileWriter(HEADER, null, logger);

        assertTrue(writer.writeFileIfChanged(file.toString(), body, true),
            "first write creates the file");
        assertTrue(logged("write.commit"), "the commit is recorded: " + events());

        appender.list.clear();
        assertFalse(writer.writeFileIfChanged(file.toString(), body, true),
            "identical content is not rewritten");
        assertTrue(logged("write.skip"), "a skip is recorded: " + events());
        assertTrue(logged("reason=identical-bytes"),
            "the skip carries the reason that distinguishes it from every other skip: " + events());
        assertTrue(logged("file=AGENTS.md"), "events name the file, not the absolute path");
    }

    @Test
    @DisplayName("an empty round skips for a different, distinguishable reason")
    void noNewRulesSkipsWithItsOwnReason(@TempDir Path dir) throws IOException {
        Path file = dir.resolve("AGENTS.md");
        Files.writeString(file, HEADER + "\nrule one\n");
        GuardrailFileWriter writer = new GuardrailFileWriter(HEADER, null, logger);

        assertFalse(writer.writeFileIfChanged(file.toString(), HEADER + "\nrule two\n", false),
            "content differs but the round contributed nothing, so nothing is written");
        assertTrue(logged("reason=no-new-rules"),
            "this skip is not the same as an unchanged file, and the log says so: " + events());
    }

    @Test
    @DisplayName("nothing is logged at INFO or above during ordinary writes")
    void theNarrativeStaysAtDebug(@TempDir Path dir) throws IOException {
        Path file = dir.resolve("CLAUDE.md");
        GuardrailFileWriter writer = new GuardrailFileWriter(HEADER, null, logger);
        writer.writeFileIfChanged(file.toString(), HEADER + "\nrule\n", true);
        writer.writeFileIfChanged(file.toString(), HEADER + "\nrule\n", true);

        assertEquals(List.of(),
            appender.list.stream()
                .filter(e -> e.getLevel().isGreaterOrEqual(Level.INFO))
                .map(ILoggingEvent::getFormattedMessage)
                .toList(),
            "INFO is the operator's budget: a routine write must not spend it");
    }
}
