package se.deversity.vibetags.processor.internal;

import org.junit.jupiter.api.Test;
import org.junit.jupiter.params.ParameterizedTest;
import org.junit.jupiter.params.provider.ValueSource;

import java.util.Map;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertThrows;
import static org.junit.jupiter.api.Assertions.assertTrue;

/**
 * What the manifest reader does with a document that stops in the middle.
 *
 * <p>{@link JsonTest} covers input that is malformed in a structural way. This covers input that is
 * simply cut short, which is the shape a real failure takes: a JAR entry read through a stream that
 * ended early, a file half-written by a build that was killed, an entry truncated by a packaging
 * step. The parser is reading a manifest from a JAR the consuming build did not produce, so every
 * one of these has to end in a {@code JsonException} carrying an offset — not an
 * {@link StringIndexOutOfBoundsException}, not a silently half-read document, and not a hang.
 *
 * <p>The cases are generated by truncating one valid document at every length, so a new parser
 * branch that forgets its end-of-input guard is caught wherever it sits rather than only at the
 * handful of offsets someone thought to write down.
 */
class JsonTruncationTest {

    /**
     * One document exercising every value kind the grammar has, so truncating it walks the parser
     * through object, array, string, escape, unicode escape, number and literal states.
     */
    private static final String COMPLETE =
        "{\"pkg\":\"a.b\",\"rules\":[{\"annotation\":\"@AISecure\",\"n\":-12.5e+3,"
            + "\"ok\":true,\"no\":false,\"nil\":null,\"esc\":\"a\\u0041b\\n\\\"c\"}]}";

    @Test
    void theCompleteDocumentParses() {
        // The control: without this, a truncation test passes just as well against a parser that
        // rejects everything.
        Map<String, Object> parsed = Json.parseObject(COMPLETE);
        assertEquals("a.b", parsed.get("pkg"));
        assertTrue(parsed.get("rules") instanceof java.util.List, "rules should parse as a list");
    }

    @Test
    void everyTruncationOfAValidDocumentIsRejectedCleanly() {
        for (int len = 1; len < COMPLETE.length(); len++) {
            String truncated = COMPLETE.substring(0, len);
            Throwable thrown = assertThrows(Throwable.class, () -> Json.parseObject(truncated),
                "a document cut at " + len + " chars parsed as if it were complete: " + truncated);
            assertTrue(thrown instanceof Json.JsonException,
                "cutting at " + len + " chars threw " + thrown.getClass().getName()
                    + " instead of JsonException; the manifest reader turns JsonException into a "
                    + "skipped manifest and lets anything else out: " + truncated);
        }
    }

    @Test
    void anEmptyDocumentIsRejected() {
        assertThrows(Json.JsonException.class, () -> Json.parseObject(""));
        assertThrows(Json.JsonException.class, () -> Json.parseObject("   "));
    }

    @ParameterizedTest
    @ValueSource(strings = {
        "{\"a\":\"x\\",          // ends on the backslash: the escape has no character after it
        "{\"a\":\"x\\u12\"}",    // fewer than four hex digits before the closing quote
        "{\"a\":\"x\\u\"}",      // no hex digits at all
        "{\"a\":\"x\\q\"}",      // an escape the grammar does not define
    })
    void aBrokenEscapeIsRejected(String document) {
        assertThrows(Json.JsonException.class, () -> Json.parseObject(document));
    }

    @ParameterizedTest
    @ValueSource(strings = {
        "{\"a\":}",              // a value position holding no value
        "{\"a\":@}",             // a character that starts no value at all
        "{\"a\" \"b\"}",         // the name/value separator missing
        "{\"a\":\"b\",}",        // a trailing comma where a name must follow
        "{\"a\":tru}",           // a literal cut short
        "[1,2",                  // an array that never closes
    })
    void structurallyImpossibleInputIsRejected(String document) {
        assertThrows(Json.JsonException.class, () -> Json.parse(document));
    }

    @Test
    void theExceptionCarriesTheOffsetItFailedAt() {
        // The manifest reader logs this message; without an offset a rejected manifest is a report
        // that something, somewhere in a JAR, is wrong.
        Json.JsonException e = assertThrows(Json.JsonException.class,
            () -> Json.parse("{\"a\":@}"));
        assertTrue(e.getMessage().contains("offset"),
            "message should say where it gave up, was: " + e.getMessage());
    }

    @Test
    void quoteEscapesTheWhitespaceControlsTheParserReadsBack() {
        // quote() and the string reader are a pair; every escape one writes the other has to read.
        String awkward = "tab\there\r\ncarriage\bback\fform\"quote\\slash";
        String document = "{\"k\":" + Json.quote(awkward) + "}";
        assertEquals(awkward, Json.parseObject(document).get("k"),
            "a value containing every control escape must survive the round trip intact");
    }

    @Test
    void quoteEmitsTheShortEscapeNotTheUnicodeOneForKnownControls() {
        // \b and \f are below 0x20, so a quote() that lost its explicit cases would still produce
        // readable output via the \\u fallback and this pair would be the only way to notice.
        assertEquals("\"\\b\\f\\r\"", Json.quote("\b\f\r"));
    }
}
